### ISSUE TITLE
文档中说的消息本地存储功能貌似并未实现

### ISSUE THREAD

**Issue by dai-xun** [wildfirechat/android-chat#1]
如题

**Comment by imndx** [comment]
是自定义消息吗？
自定义消息的话。
1. 消息的存储标识要设置为：```flag = PersistFlag.Persist_And_Count``` 或者```flag = PersistFlag.Persist```
2. 需要调用```ChatManager#registerMessageContent```进行消息类型注册，最终会调用```                    ProtoLogic#registerMessageFlag(type, flag);```

@dai-xun 请问你是怎么使用的？

**Comment by imndx** [comment]
另外，数据存储功能是在协议栈层实现的，请参考[proto](https://github.com/wildfirechat/proto)

**Comment by monsterLin** [comment]
我按照这个操作，但是自定义消息确实本地没有存储.. @imndx
