### ISSUE TITLE
一个群中发过多图片消息（大于500张）时,app卡死或者半死

### ISSUE THREAD

**Issue by wangsanpiao** [wildfirechat/android-chat#102]
复现步骤：
1.加入一个有很多条图片消息的群（如野火官方测试群1）或者自己建立一个群然后发500条以上的图片消息
2.重新安装app或者清空app所有数据重新登陆

现象：首页显示连接中。。。直到离线消息拉取完毕,app卡住，很难操作

**Comment by imndx** [comment]
请用最新代码测试

**Comment by wangsanpiao** [comment]
测试了，好多了，虽然不是特别流畅，但是不会卡死了。不过如果一个用户如果有多个群，每个群都有不少离线图片消息，还是会很卡

**Comment by imndx** [comment]
你加imndx为好友，然后拉他进群，测试下

**Comment by wangsanpiao** [comment]
好的

**Comment by imndx** [comment]
最新代码已解决。

**Comment by yuzhongrong** [comment]
能把提交的log提供下吗 解决的方案
