### ISSUE TITLE
不同手机型号发送表情乱码问题解决方式探讨

### ISSUE THREAD

**Issue by pullwindyuan** [wildfirechat/android-chat#103]
#93 bug我通过使用base64传输初步确定能够解决这个问题：
1、在TextMessageContent的public TextMessageContent(String content)中进行base64编码（编码要添加特殊字符组成的一个头部，比如"₠∉∂ζ"，便于区分是否是经过base64编码的）；
2、在会话列表初始化的时候对lastMessage的TextMessageContent进行base64解码；
3、在TextMessageContent的public String getContent()进行base64解码；

但是这种打补丁的方式很low，以目前我了解的情况，在mars里面解决了为啥5版本发送给9版本的表情信息乱码问题是最好的。我跟踪了后台和前端，消息出方向没问题，问题出在用户端接收到消息后由于编码问题导致最终存储在本地的消息被转换成了一段固定乱码。但是我们目前没能力跟踪mars里的数据处理流程。

**Comment by pullwindyuan** [comment]
还需要在CharManager的public void sendMessage(final Message msg, final int expireDuration, final SendMessageCallback callback)方法中针对TextMessageContent消息通过调用改造后的TextMessageContent构造方法来进行内容base64编码后发出，这样转发消息才不会乱码

**Comment by imndx** [comment]
#93

**Comment by imndx** [comment]
#93 下面讨论，这个先关了。
