### ISSUE TITLE
群列表总是为空

### ISSUE THREAD

**Issue by wangsanpiao** [wildfirechat/android-chat#107]
登陆用户实际已加入了他人的群，并且自己也创建了群，但是群列表依然为空

**Comment by wangsanpiao** [comment]
登陆用户实际已加入了他人的群，并且自己也创建了群，但是群列表依然为空

![2019-07-29-16-01-33](https://user-images.githubusercontent.com/17610744/62032163-9084e380-b21b-11e9-8b11-1358804db5b6.png)

**Comment by imndx** [comment]
和微信逻辑一致，保存到通讯录，这个地方才显示
