### ISSUE TITLE
聊天记录过多，应用卡顿

### ISSUE THREAD

**Issue by Anlycal** [wildfirechat/android-chat#108]
单个群或者个人聊天记录累计过多，应用就变的卡顿。

**Comment by imndx** [comment]
是最新代码吗？
如何复现？

**Comment by Anlycal** [comment]
是的，复现：一个群在线聊天记录两千条以上，应用就非常卡，必须得清掉聊天记录。可以有清除部分聊天记录的方法不？，自动清除。

**Comment by imndx** [comment]
我们发现一个bug：
第一次从低版本升级到最新版本，会比较卡；杀进程，然后在进，就好了。

请你确认下，杀进程，重新进入应用之后，还卡吗？

**Comment by Anlycal** [comment]
杀掉进程也卡，必须得清空聊天记录，单个会话的聊天记录不能太多。还有个问题，Ios发的视频在android上点击转发的时候崩溃，而且看不到错误日志。

**Comment by imndx** [comment]
iOS卡吗？

**Comment by Anlycal** [comment]
IOS不卡

**Comment by imndx** [comment]
请更新到最新代码测试，一定注意更新：mars-core-release.aar 文件哈。
2ffeceb

**Comment by Anlycal** [comment]
已更新，卡顿已解决。有一个新问题，聊天记录过多，发送信息的发送回调就会有延迟（达到600ms）,正常的延迟只有10多毫秒

在ChatManager中

public void onPrepared(final long messageId, final long savedTime) throws RemoteException {
                    msg.messageId = messageId;
                    msg.serverTime = savedTime;
                    mainHandler.post(() -> {
                        if (callback != null) {
                            callback.onPrepare(messageId, savedTime);
                        }
                        int index = 0;
                        for (OnSendMessageListener listener : sendMessageListeners) {//聊天记录过多，此处延迟严重
                            listener.onSendPrepare(msg, savedTime);
                        }

                    });
                }

**Comment by Anlycal** [comment]
已更新，卡顿已解决。有一个新问题，聊天记录过多，发送信息的发送回调就会有延迟（达到600ms）,正常的延迟只有10多毫秒,另外通过ProtoLogic.sendMessage(···)发送延迟了200多ms

在ChatManager中

public void onPrepared(final long messageId, final long savedTime) throws RemoteException {
msg.messageId = messageId;
msg.serverTime = savedTime;
mainHandler.post(() -> {
if (callback != null) {
callback.onPrepare(messageId, savedTime);
}
for (OnSendMessageListener listener : sendMessageListeners) {//聊天记录过多，此处延迟严重
listener.onSendPrepare(msg, savedTime);
}

                });
            }

**Comment by Anlycal** [comment]
已更新，卡顿已解决。有一个新问题，聊天记录过多，发送信息的发送回调就会有延迟（达到600ms）,正常的延迟只有10多毫秒,另外通过ProtoLogic.sendMessage(···)发送延迟了300多ms

在ChatManager中

public void onPrepared(final long messageId, final long savedTime) throws RemoteException {
msg.messageId = messageId;
msg.serverTime = savedTime;
mainHandler.post(() -> {
if (callback != null) {
callback.onPrepare(messageId, savedTime);
}
for (OnSendMessageListener listener : sendMessageListeners) {//聊天记录过多，此处延迟严重
listener.onSendPrepare(msg, savedTime);
}

            });
        }

**Comment by zombiu** [comment]
学习了！
