### ISSUE TITLE
视频通话，对方没接听，我方点击切换到语音通话，对方界面没变化，对方点击接听后是视频通话，我方是语音通话

### ISSUE THREAD

**Issue by oldpan1310** [wildfirechat/android-chat#109]
视频通话，对方没接听，我方点击切换到语音通话，对方界面没变化，对方点击接听后是视频通话，我方是语音通话

**Comment by oldpan1310** [comment]
看代码是只处理了AVEngineKit.CallState.Connected状态，而没有处理AVEngineKit.CallState.Outgoing状态
![Uploading image.png…]()

**Comment by imndx** [comment]
已规避。
534523c
