### ISSUE TITLE
iphone7 11.4.1版本闪退

### ISSUE THREAD

**Issue by self-transcendence** [wildfirechat/android-chat#11]
可以正常打开app，但是使用键盘打字，或者发表情，立刻闪退回到桌面

**Comment by heavyrain2012** [comment]
你好，请问您是自己下载代码编译的，还是从appstore上下载的？
我们手上没有11.4的手机，使用最新的代码在11.4的模拟器上测试，在会话界面输入文字和表情，没有出现crash现象。请用最新代码再测试一遍，如果还有问题，请详细描述操作步骤。如果您是iOS开发请帮我们debug一下
