### ISSUE TITLE
消息体Message中没有扩展字段能用

### ISSUE THREAD

**Issue by cricketshen** [wildfirechat/android-chat#110]
消息体Message中没有扩展字段能用，有时候需要在消息体中加一点自己的信息，但是目前协议不支持消息体加扩展字段

**Comment by ChenTsuei** [comment]
我现在也面临这个问题，我想要在每个Message中加入GPS信息，但现在的做法很dirty，在searchableContent里加一些东西然后在服务端再解析出来。
在此之前我也试图在Message里添加一些东西，但是奇怪的是从chat到client的过程中这些信息不见了，我觉得可能是序列化的时候出了问题。
我不太清楚，想要在Message中添加一个新的字段，需要修改哪些部分呢？
谢谢您的项目，这个开源项目真是太良心了。

**Comment by imndx** [comment]
这个需求，我们会近期加上。

**Comment by imndx** [comment]
已添加，请用最新代码验证。

手机端和服务端都需要升级。
