### ISSUE TITLE
管理员移除群成员异常

### ISSUE THREAD

**Issue by wangsanpiao** [wildfirechat/android-chat#115]
![gifhome_320x746_10s](https://user-images.githubusercontent.com/17610744/62345329-89fcb180-b524-11e9-8041-e243b2cd1474.gif)
管理员移除群成员会失败，并且还有权限移除群主，gif中“王三棍是群主”。IOS也有这个问题

**Comment by imndx** [comment]
请升级server端代码，并测试。
