### ISSUE TITLE
群主移除管理员的功能还是没有

### ISSUE THREAD

**Issue by wangsanpiao** [wildfirechat/android-chat#116]
只有添加群管理的功能，没有移除群管理的功能

**Comment by wangsanpiao** [comment]
说错了，只有添加管理员的功能，没有移除管理员的功能

**Comment by imndx** [comment]
我测试了最新代码没问题。

**Comment by wangsanpiao** [comment]
我怀疑我们说的不是一个东西，我的意思是群主把管理员降级成为普通成员

**Comment by imndx** [comment]
有的。
群管理，管理员，点击某个管理员，会提示移出管理员

**Comment by wangsanpiao** [comment]
![gifhome_320x746_14s](https://user-images.githubusercontent.com/17610744/62369896-a79d3b80-b563-11e9-8481-b15b55635f98.gif)
最新的代码没有这个功能啊，你是不是有本地的代码没有提交上来

**Comment by imndx** [comment]
确认，已经带上这个功能了，[代码在这](https://github.com/wildfirechat/android-chat/blob/78f5e9f6fe651452563b1080391969a1e5dcd7a8/chat/src/main/java/cn/wildfire/chat/kit/group/manage/GroupManagerListFragment.java#L78)

**Comment by wangsanpiao** [comment]
我不知道你怎么测试出来功能正常的
`    @Override
    public void onUserClick(UIUserInfo userInfo) {
        if (userInfo.getUserInfo().uid.equalsIgnoreCase(groupInfo.owner)) {
            return;
        }
        GroupMember groupMember = groupViewModel.getGroupMember(groupInfo.target, userInfo.getUserInfo().uid);
        if (groupMember.type == GroupMember.GroupMemberType.Owner) {
            new MaterialDialog.Builder(getActivity())
                    .items(Collections.singleton("移除群管理"))
                    .itemsCallback((dialog, itemView, position, text) -> {
                        groupViewModel.setGroupManager(groupInfo.target, false, Collections.singletonList(userInfo.getUserInfo().uid), Collections.singletonList(0), null);
                    })
                    .cancelable(true)
                    .build()
                    .show();
        }
    }`
groupMember.type == GroupMember.GroupMemberType.Owner在这里面不一直是false吗，点的就是管理员啊，groupMember.type就是Manager啊

**Comment by imndx** [comment]
群主才能添加移除管理员，Owner是群主

**Comment by wangsanpiao** [comment]
对啊，群主才能移除管理员，但是你这里这个userInfo是点击的那个管理员对象，而不是登陆用户，所以这个判断有问题，即使登陆用户是群主也没用

**Comment by imndx** [comment]
哦哦，明白了，谢谢

**Comment by wangsanpiao** [comment]
您可长点心吧，这个测一下很明显就能发现问题，也费不了什么时间

**Comment by imndx** [comment]
你们都看出问题了，可以顺手就改了，然后给我们提个pull request，一起把这个项目完善了

^..^

**Comment by wangsanpiao** [comment]
OK,我看得懂的我就改了提Pull request
