### ISSUE TITLE
【必现】断网发送消息 1.消息tab没有显示正在发送小箭头，2 聊天页面发送失败的消息跑到最上去了

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#118]
![image](https://user-images.githubusercontent.com/7382234/62416499-7cebd980-b66e-11e9-9a89-46e6a08d1cab.png)

![image](https://user-images.githubusercontent.com/7382234/62416525-fc79a880-b66e-11e9-81be-0f81924e8e38.png)

**Comment by yuzhongrong** [comment]
初步定位应该是这里出问题了
![image](https://user-images.githubusercontent.com/7382234/62416615-8d9d4f00-b670-11e9-8abb-eb0acdd4a403.png)

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/62416629-d94ff880-b670-11e9-9afb-e087f1e92e1b.png)

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/62416862-38177100-b675-11e9-9076-a759599c01a2.png)

**Comment by imndx** [comment]
我用我们代码测试了下，复现不了呀。
你用我们最新代码，编个demo出来试下。

**Comment by yuzhongrong** [comment]
好的

**Comment by yuzhongrong** [comment]
目前服务器架设在国外 所以你的数据表中的时间 发送成功 消息是 服务器返回时间 ，发送不成功 消息是本地时间  ，由于我服务器在洛杉矶  多了一个夏令时间1个小时， 所以。。。
