### ISSUE TITLE
安卓端刚注册的用户后台能接收到消息，但界面没显示不出来

### ISSUE THREAD

**Issue by my-soul** [wildfirechat/android-chat#119]
安卓端刚注册的用户后台能接收到消息，我打日志能看到收到消息，但界面没显示不出来，IOS端没发现这样的问题。

**Comment by imndx** [comment]
我们的demo上，能复现这问题吗？如何复现？

**Comment by my-soul** [comment]
你们的demo就没这样的问题，奇怪哎

**Comment by imndx** [comment]
那请确认代码是不是最新的，或者是不是有什么改动。

**Comment by my-soul** [comment]
项目如果使用最新的gradle编译的话就会出现这个问题 ：）
