### ISSUE TITLE
聊天页面有新消息时，向上滚动查看历史聊天信息卡屏

### ISSUE THREAD

**Issue by Anlycal** [wildfirechat/android-chat#127]
群聊天页面及时信息过多，向上滚动查看历史聊天信息卡屏。

**Comment by imndx** [comment]
#121 
#120

**Comment by imndx** [comment]
我理解的向下滚动才加载历史消息呀？

有多少消息？
是处于会话界面，收到很多消息吗？

**Comment by Anlycal** [comment]
处于会话页面，实时收到的消息过多，再往上拉历史聊天记录，滑动卡屏严重。

**Comment by imndx** [comment]
好的，我们测试一下。消息都是普通消息，还是图片消息？

**Comment by Anlycal** [comment]
我这测试的是普通文本信息，用多台手机模拟发送群聊消息（1s/条），在另一台手机上测试接收数据，向上滑动有点卡，另外累计数据量过多时，数据显示跳屏，不连贯。

**Comment by Anlycal** [comment]
如果聊天记录少的话，不卡，累计聊天记录过多，滑动卡屏现象明显。

**Comment by Anlycal** [comment]
可以从本地的聊天记录存储入手解决不？历史聊天记录不多的情况下，实时接收消息量多运行显示还是流畅。

**Comment by imndx** [comment]
出问题的时候，历史消息大概有多少？

是最新代码吗？历史消息过多导致卡顿的问题，之前解决过一个。

**Comment by Anlycal** [comment]
是最新代码，之前历史信息过多导致的卡顿，退出应用再进来同样卡顿，目前这个问题没有了。现有的问题就是历史记录量达到四五千条以上，接收消息显示不连贯，跳来跳去，且向上滑动卡屏，清空聊天记录又可以恢复正常。

**Comment by imndx** [comment]
请测试一下最新代码

**Comment by Anlycal** [comment]
好的，只要更新协议栈吗？

**Comment by imndx** [comment]
都需要更新
