### ISSUE TITLE
ChatManager getUserInfo 缓存问题

### ISSUE THREAD

**Issue by zhaozeyx** [wildfirechat/android-chat#129]
![image](https://user-images.githubusercontent.com/4213414/63068483-dba23480-bf45-11e9-9d6c-c74ca945399d.png)
ChatManager getUserInfo方法中，如果是通过mClient获取用户信息，用户信息会被添加到缓存中，但是，如果通过userSource获取用户信息，就不会添加到缓存。

这里是不是应该不区分何种获取方式，都添加到缓存比较合适？

**Comment by imndx** [comment]
是的，应当都添加，或者都不添加

**Comment by yuzhongrong** [comment]
第一次获取用户信息问题到现在还没有解决 不仅仅是这一个地方第一次无法拿到

**Comment by imndx** [comment]
> 第一次获取用户信息问题到现在还没有解决 不仅仅是这一个地方第一次无法拿到

你的说的，和这个不是一个问题。
第一次拿不到，会有通知的。
