### ISSUE TITLE
Android语音

### ISSUE THREAD

**Issue by zhaozeyx** [wildfirechat/android-chat#130]

**Comment by zhaozeyx** [comment]
Android语音消息点击播放之后，home按键退到后台，语音会继续播放

**Comment by yuzhongrong** [comment]
这个我解决了 给你看下代码
![image](https://user-images.githubusercontent.com/7382234/63103935-9b2bd080-bfb0-11e9-9f64-f84b026489f6.png)

**Comment by imndx** [comment]
已解决

**Comment by zhaozeyx** [comment]
谢谢了，这个我自己解决了

**Comment by yuzhongrong** [comment]
这个很好解决的





------------------ 原始邮件 ------------------
发件人: "Demon"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 中午11:29
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "荣"<956942189@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] Android语音 (#130)




谢谢了，这个我自己解决了

**Comment by zhaozeyx** [comment]
啊，我也只是给官方提个issue
