### ISSUE TITLE
安卓端搜索好友不能模糊匹配吗？

### ISSUE THREAD

**Issue by dilenzhu** [wildfirechat/android-chat#134]
安卓端目前搜索好友只会列出一条记录，不能同ios 一样进行模糊匹配吗？谢谢！

**Comment by imndx** [comment]
你好，是什么地方？我没找到你说的地方。
请截个图说明下

**Comment by dilenzhu** [comment]
![QQ图片20190820112239](https://user-images.githubusercontent.com/10102755/63315233-fc4efd80-c33c-11e9-9e10-54708ac0a4c8.jpg)
位置：联系人-顶部有一个搜索的图标，点击进去。
目前这里张的联系人有多个，但是安卓端，只能列出一笔记录。苹果端搜索可以列出多个。
谢谢！
