### ISSUE TITLE
图片和视频收不到通知的问题

### ISSUE THREAD

**Issue by zhaozeyx** [wildfirechat/android-chat#135]
现在发现Android应用退到后台，对方发过来图片和视频收不到推送通知，定位了一下原因是收到通知的时候发生了空指针异常，
拿ImageMessageContent 举例
![image](https://user-images.githubusercontent.com/4213414/63237489-da8a4380-c274-11e9-94ae-89a91c1e9ed6.png)

![image](https://user-images.githubusercontent.com/4213414/63237481-ce9e8180-c274-11e9-93b1-e1c877c740a5.png)

这里thumbnail会为空

**Comment by zhaozeyx** [comment]
![image](https://user-images.githubusercontent.com/4213414/63237590-305eeb80-c275-11e9-8ccf-54b0afd3409a.png)
by the way 这里通知栏不处理视频消息的显示吗？

**Comment by imndx** [comment]
已解决，请测试最新代码
