### ISSUE TITLE
关于聊天界面获取群组信息不正确的问题

### ISSUE THREAD

**Issue by zhaozeyx** [wildfirechat/android-chat#137]
我们这边进行压测，创建了很多的群组。
![image](https://user-images.githubusercontent.com/4213414/63250207-abd49300-c29d-11e9-9ffd-c74a45b64eb5.png)
我第一次通过群组进聊天界面的时候，蓝框里面获取的群组为null，但是第二次点击进入聊天界面的时候返回了正确的群组信息，我现在不确定是因为什么原因导致的。群组少的时候没遇见这个情况。

数据库中群组个数为598个

**Comment by imndx** [comment]
当群信息未同步到本地的时候，会返回null，这是会从服务端拉取群信息，拉取成功之后，会有群信息更新回调。
