### ISSUE TITLE
自定义消息存在问题

### ISSUE THREAD

**Issue by xiefangzhenz** [wildfirechat/android-chat#139]
Android自定义消息，消息类型为2000，发送成功之后，对方是Android手机，接受之后，显示unknowmessage ，如果对方是iOS手机，则没问题

**Comment by imndx** [comment]
应当是你自定义消息处理的不对，请检查下。

可以看看这个文档

http://docs.wildfirechat.cn/android/chatuikit.html

**Comment by xiefangzhenz** [comment]
@imndx 在群友的帮助下解决了  谢谢  没有进行注册，要在chatmanager里面注册
