### ISSUE TITLE
#138 修正之后，APP移除重新安装，第一次登陆会崩溃

### ISSUE THREAD

**Issue by yichenlo01** [wildfirechat/android-chat#140]
[#138](https://github.com/wildfirechat/android-chat/issues/138) 修正之后。
現在APP移除重新安装，第一次登陆会崩溃。

**Comment by imndx** [comment]
请提供一份日志，我本地无法无限。

**Comment by yichenlo01** [comment]
![image](https://user-images.githubusercontent.com/36438807/63341087-0859b000-c37b-11e9-8825-55e0e9049694.png)

**Comment by yichenlo01** [comment]
我尝试用手动的方式 把#138 的code 加回去一样会报错，
用昨天的代码是没有问题的。
还是是因为手机不够力。 MI 3W老手机了

**Comment by imndx** [comment]
你好，请试下最新代码

**Comment by yichenlo01** [comment]
用干净的帐号没问题
试过用干净的帐号加进千人群组跟百人群组，也没问题。

但用之前的几个帐号，里面包含不少的群组跟私聊，首次登录的时候tool bar下面会显示连接中，接着就崩溃。
再一次执行app就显示初始化，等久一点，信息资讯会慢慢回来。

**Comment by imndx** [comment]
> 用干净的帐号没问题
> 试过用干净的帐号加进千人群组跟百人群组，也没问题。
> 
> 但用之前的几个帐号，里面包含不少的群组跟私聊，首次登录的时候tool bar下面会显示连接中，接着就崩溃。
> 再一次执行app就显示初始化，等久一点，信息资讯会慢慢回来。

用现在最新的代码，还有这问题？

是否包含了，这个commit fa064189cfee263ef8c160c44e84098357c85279

**Comment by yichenlo01** [comment]
有的
