### ISSUE TITLE
时间显示问题

### ISSUE THREAD

**Issue by zhaozeyx** [wildfirechat/android-chat#142]
![image](https://user-images.githubusercontent.com/4213414/63476015-ea429b80-c4b1-11e9-9b10-bcc683eda405.png)
16：54的消息其实是前一天发的，但是按照TimeUtil里面的算法，
![image](https://user-images.githubusercontent.com/4213414/63476046-047c7980-c4b2-11e9-93ac-e18f84b53d93.png)
这里会返回0 ，并不会拼接上昨天。

如果这算法不正确的话，那么后面的其它的计算应该也都有些问题。

**Comment by zhaozeyx** [comment]
我看了下微信的逻辑
首先判断是不是昨天，然后判断是不是同一周，同一周显示 星期几，其它的显示年月日

**Comment by imndx** [comment]
请测试最新代码
