### ISSUE TITLE
关于整合client等module的问题

### ISSUE THREAD

**Issue by 8608140hao** [wildfirechat/android-chat#144]
在自有项目中，引入push、client作为module开发。自有项目是android开发的。但push、client好像是androidx，引入后会报Support包冲突。
在不互相转换的前提下，如何解决冲突？
如果把client等包转换成android，会和仓库不比配，以后的升级是问题。
如果把自有项目转换成android，代码量很大。

**Comment by imndx** [comment]
Android Studio 提供一个Migrate to AndroidX功能，你可以尝试一下

**Comment by 8608140hao** [comment]
就是不太想把自由项目转换成androidx的，因为是线上的项目，所以轻易不敢动。

**Comment by imndx** [comment]
那你尝试把我们的项目9*

**Comment by imndx** [comment]
那可以尝试把client改了用support包
