### ISSUE TITLE
1群聊输入@ 进入选择联系人页面 第一次无法拿到群成员

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#146]
![image](https://user-images.githubusercontent.com/7382234/63650009-02e3d780-c778-11e9-8a48-dcaa84bc774a.png)

**Comment by imndx** [comment]
正常应当能拿到的，如果拿不到，那会有通知的

```
onGroupMembersUpdate

```

**Comment by imndx** [comment]
请测试最新代码
