### ISSUE TITLE
发送稍大视频或文件时一直失败

### ISSUE THREAD

**Issue by modernstar** [wildfirechat/android-chat#147]
当发送稍大视频（小视频录满）或文件时，客户端无法发送成功，返回码为413

**Comment by imndx** [comment]
413是七牛云存储返回的错误码，表示文件太大。

**Comment by modernstar** [comment]
感谢您的回复，但是我服务器端的配置并未使用七牛云，相关配置如下：
#*********************************************************************
# Media server configuration
#*********************************************************************
##是否使用七牛云存储。1使用七牛；0使用内存文件服务器。
media.server.use_qiniu 0

**Comment by imndx** [comment]
文件太大，内置的也会报这个错误码

**Comment by modernstar** [comment]
那文件大小的限制是否有地方配置？或者是否可以不用Client，自己处理媒体的上传？

**Comment by imndx** [comment]
可以自己处理媒体的上传，上传完之后，设置媒体消息的remoteUrl，并将localPath置空

**Comment by modernstar** [comment]
好的，明白了，非常感谢！！
