### ISSUE TITLE
创建群 会话列表群头像显示为群成员头像 不是几个人宫格头像

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#149]
![image](https://user-images.githubusercontent.com/7382234/63789563-36fefa00-c92a-11e9-977f-9efb65d5baa0.png)

**Comment by imndx** [comment]
群二维码中间的那个小图，显示的是什么呢？

**Comment by yuzhongrong** [comment]
是单人头像

**Comment by yuzhongrong** [comment]
群二维码

**Comment by yuzhongrong** [comment]
我觉得这个只要控制每个人 设置头像的大小  即可  我看你处理了 头像上传3个地方 群，频道，和个人
