### ISSUE TITLE
getGroupMember返回的Member updateDT为0导致无法排序

### ISSUE THREAD

**Issue by qiu198022** [wildfirechat/android-chat#150]
Android getGroupMember返回的Member updateDT为0导致无法按照加入群组的时间排序。

修改Proto的MessageDB.cc的代码添加排序_update_dt ASC， ios编译proto后替换可以正常实现排序功能。但是android修改之后发现Java上层获取的groupmember的排序不对。但是底层db数据库向Java上层提供的member list打印出来的log的顺序是对的，但是上层Java层获取的list里面缺少updateDT值，顺序不对！
<img width="1515" alt="屏幕快照 2019-08-28 下午6 22 39" src="https://user-images.githubusercontent.com/51344/63847667-d8388f80-c9c0-11e9-9e7a-6f83b2bec73f.png">

        std::list<TGroupMember> MessageDB::GetGroupMembers(const std::string &groupId, bool refresh) {
            DB2 *db = DB2::Instance();
            if (!db->isOpened()) {
                return std::list<TGroupMember>();
            }

#ifdef __ANDROID__
            std::list<std::string> columns;
            columns.push_back("_gid");
            columns.push_back( "_mid");
            columns.push_back("_alias");
            columns.push_back("_type");
            columns.push_back("_update_dt");

            std::string sql = db->GetSelectSql(GROUP_MEMBER_TABLE_NAME, columns, "_gid=?","_update_dt ASC");
#else
            std::string sql = db->GetSelectSql(GROUP_MEMBER_TABLE_NAME, {"_gid",  "_mid", "_alias", "_type", "_update_dt"}, "_gid=?","_update_dt ASC");
#endif

<img width="908" alt="屏幕快照 2019-08-28 下午6 14 13" src="https://user-images.githubusercontent.com/51344/63847120-b5f24200-c9bf-11e9-8886-d95ad6ecfd61.png">

**Comment by qiu198022** [comment]
<img width="973" alt="屏幕快照 2019-08-28 下午7 08 19" src="https://user-images.githubusercontent.com/51344/63850691-3ec0ac00-c9c7-11e9-9d17-0dd6a5003d44.png">
ClientServer.java里面获取groupmemembers的member.updateDt = protoMember.getUpdateDt();是0，但是里面获取的groupid，memberid和alias是有值的

**Comment by imndx** [comment]
fix
