### ISSUE TITLE
阅读源码时的一点疑问

### ISSUE THREAD

**Issue by 512DIDIDI** [wildfirechat/android-chat#157]
在ChatManager类中，有两个Handler变量，我查看了用到mainHandler的地方，发现全都是调用post(Runnable r)方法，但是post方法本质上和sendMessage几乎无异，Runnable里run方法体本质上还是在主线程跑，能否请问一下这样设计的意义？谢谢。

**Comment by imndx** [comment]
mainHandler.post的调用方，并不在主线程
