### ISSUE TITLE
好友删除问题；

### ISSUE THREAD

**Issue by MaTengFei1990** [wildfirechat/android-chat#159]
1、 删除好友及添加好友消息问题：
a、b角色：a 添加b为好友，b能收到添加好友提醒；添加完好友b ,a再把b删除，a的好友列表里面没有b,在a 的好友推荐列表里面可以再添加b 。（此路径正确）
反过来：当a把b 删除后再有b添加a好友会出现以下问题：在b的好友推荐列表里面找不到a，反而在已添加好友列表里面；如再添加a为好友必须通过输入手机号添加，这样可以添加成功但在 a那边没有添加用户消息提醒。

请尽快解决一下，谢谢啦；么么哒

**Comment by imndx** [comment]
我试了下我们最新的demo，复现不了你说的这个问题。

**Comment by imndx** [comment]
经确认是客户token错误错误导致的
