### ISSUE TITLE
app头像更换，聊天界面重复问题；

### ISSUE THREAD

**Issue by MaTengFei1990** [wildfirechat/android-chat#160]
在用户信息页面，修改用户头像后，返回到聊天的界面 之前的头像和现在的头像都存在；
![7b095a8a5f6e4ba76226fe2cd70668b](https://user-images.githubusercontent.com/19420333/64471514-4598ad00-d185-11e9-9854-16d7cc55e432.jpg)
。

**Comment by imndx** [comment]
最新代码已解决。
