### ISSUE TITLE
Android：查看聊天图片，希望增加点击缩小功能；

### ISSUE THREAD

**Issue by MaTengFei1990** [wildfirechat/android-chat#163]
1、聊天时发送图片，点开后不能进行点击缩小，只能用手机返回键缩小。

**Comment by imndx** [comment]
Pull request welcome.

**Comment by LeonShannon** [comment]
https://github.com/SherlockGougou/BigImageViewPager 
我用这个库来图片查看

**Comment by imndx** [comment]
> https://github.com/SherlockGougou/BigImageViewPager 我用这个库来图片查看

你好，可否提个 PR :smile: ?
