### ISSUE TITLE
添加语音播放小红点后现在主页未读小红点总数是可以统计到也可以显示出来，但是会话列表上没有统计包含包括语言的小红点个数

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#172]
1 对方发给我语音消息

2 主页消息显示小红点，但消息列表会话没有显示

3。点击会话 进去一看 来了4条语言

需求：会话也显示未读包括这4条，而不是仅仅在主页消息显示这4条

**Comment by imndx** [comment]
请用我们最新的代码测试，我们没有复现。

**Comment by imndx** [comment]
no response.
