### ISSUE TITLE
聊天输入面板报错

### ISSUE THREAD

**Issue by xiongxiangdong** [wildfirechat/android-chat#177]
第一次启动,点击聊天面板的加号,然后在点击表情符号,其实你会发现聊天面板的高度比实际会低.然后把聊天面板回收.在点表情就会这样.

**Comment by imndx** [comment]
这是一个体验问题，只有第一安装，第一次进入会话界面，并且直接点加号，或者表情按钮，会出现了。
如果仔细测试，你会发现微信也有类似问题。

**Comment by xiongxiangdong** [comment]
关键会崩溃.高度不一致没有问题.但是点一会加号点一会表情,然后回收聊天面板,有时候表情那个emotionLayout会崩溃....

**Comment by xiongxiangdong** [comment]
问题的完整复现.如果是第一次点edittext是没有问题.如果是点加号或者表情就有问题.因为弹出的输入法高度导致面板高度与表情的高度不一致要重新计算.所以会出问题.
