### ISSUE TITLE
Android有个闪退的问题

### ISSUE THREAD

**Issue by ChasenTsai** [wildfirechat/android-chat#180]
好友聊天发送文件，选择QQ浏览器的文件管理里面的文件，如果是图片会闪退，其他文件会发不出去。

**Comment by imndx** [comment]
你好，能否提供一份错误日志？

**Comment by ChasenTsai** [comment]
抱歉，这个 Issue 不是我本人发出，应该是被盗号，我没有了解过这个项目。
