### ISSUE TITLE
最新版本的android-chat成功登录后无法连接后台IM服务器

### ISSUE THREAD

**Issue by GerJeffrey** [wildfirechat/android-chat#186]
最新版本的android-chat和0.28版server登录成功后一直显示连接失败。我的开发环境是MacOS AndroidStudio，服务器在MacOS下启动，相关ip和port都按照要求设置，登录成功也说明android-chat、app server和im-server之间的http通信是没有问题的，那么有问题的应该是android-chat与im-server之间的通信，我在前面用尝试过0.25版本，ip和por设置一模一样，但是android-chat与im-server之间的连接是正常的，也就是说0.25版本没有这个连接问题。所以，比较困惑，请教一下可能的原因？谢谢！

**Comment by imndx** [comment]
你是直接用我们Android-chat的代码测试吗？还是集成到你们项目里面去了? 集成到项目去的话，需要注意更新mars-release.aar这个文件

**Comment by GerJeffrey** [comment]
> 你是直接用我们android-chat的代码测试吗？还是集成到你们项目里面去了? 集成到项目去的话，需要注意更新mars-core-release.aar这个文件

没有集成，直接用android-chat的代码测试的。

**Comment by imndx** [comment]
我们没有复现出这问题，请问可否提供一份日志？
包括客户端和服务端？

另外，请问iOS工作正常吗？

**Comment by GerJeffrey** [comment]
抱歉，问题已经解决，是设置端口没有使用默认的80端口，修改后可以了。此问题可以关闭了。
