### ISSUE TITLE
替换了IM和应用服务器 发送媒体文件出现404

### ISSUE THREAD

**Issue by 512DIDIDI** [wildfirechat/android-chat#187]
替换了im和应用服务器地址后，
发送媒体文件端点走了 onPrepare - onFailure  ，
Msg.content里的remoteUrl为空，错误码为404，服务器配置了
 `media.server.use_qiniu 0
local.media.storage.root ../fs`
使用了内置媒体服务器，生成了相应的fs文件夹，但fs文件夹里没有上传的文件，请问是还有哪里需要配置吗？

**Comment by imndx** [comment]
请给我们提供一下服务端的日志。

**Comment by 512DIDIDI** [comment]
你好，请问可以将媒体服务器改为自己搭建的吗？文档里没有相关的说明，如果可以，请问应该改什么配置呢？

**Comment by heavyrain2012** [comment]
您需要自己配置媒体服务，请参考文档 docs.wildfirechat.cn

**Comment by 512DIDIDI** [comment]
文档中没有具体说明修改地方，仅有七牛云的较为详细，请问自己搭建的媒体服务器应该替换哪些部分呢？

**Comment by imndx** [comment]
媒体服务器并没有标准的API，也就没有标准的配置方法了。可参考七牛或者内置媒体服务的处理，自行对接。

另外，专业版server包含专业的文件存储

**Comment by 512DIDIDI** [comment]
好的 谢谢回答
