### ISSUE TITLE
能否加一些控制智能家居硬件的功能啊，比如小米插座、球泡这些

### ISSUE THREAD

**Issue by SmartArduino** [wildfirechat/android-chat#188]
能否加一些控制智能家居硬件的功能啊，比如小米插座、球泡这些

**Comment by imndx** [comment]
你这个想法有意思，我们是有做一些物联网相关的打算。

**Comment by heavyrain2012** [comment]
我们对智能家居方面不太了解，你能给我们提供一些相关的资料吗

**Comment by SmartArduino** [comment]
网上很多

发自邮洽 (http://mailchat.cn/)

发件人: heavyrain.lee (mailto:notifications@github.com)
收件人: wildfirechat/android-chat (mailto:android-chat@noreply.github.com)
抄送人: 易 称福 (mailto:yichoneyi@163.com)、Author (mailto:author@noreply.github.com)
2019-11-02 11:09
主 题: Re: [wildfirechat/android-chat] 能否加一些控制智能家居硬件的功能啊，比如小米插座、球泡这些 (#188)

我们对智能家居方面不太了解，你能给我们提供一些相关的资料吗

**Comment by SmartArduino** [comment]
我们这儿有一些wifi灯和球泡，
https://www.v2ex.com/t/590509#reply235
https://www.v2ex.com/t/598641#reply1
需要的话，可以把协议提供给你，局域网控制很方便，象苹果的homekit一样，先发现设备，然后控制。

**Comment by BaLaLaLs** [comment]
做智能家居只是用到了mqtt，我觉得im就应该纯粹一点
