### ISSUE TITLE
IOS发视频给Android，Android接收下载后播放视频提示播放错误。

### ISSUE THREAD

**Issue by hihxh** [wildfirechat/android-chat#190]
如标题所示

**Comment by heavyrain2012** [comment]
1，每次都是这样吗，还是偶尔？
2，跟android手机型号有关吗？换不同品牌和不同版本手机情况怎么样？
3，是在demo上测试的吗？

请确认上述问题

**Comment by hihxh** [comment]
每次都这样，跟手机型号和品牌无关，是在demo上测试的

**Comment by heavyrain2012** [comment]
我们手上只有一些小米手机和模拟器，测试都没有问题，请提供出问题的型号和版本，另外请验证小米手机是否有问题，还有使用最新代码编译测试
