### ISSUE TITLE
android-chat，登录后发送好友请求，对端用户登录后无法找到此请求

### ISSUE THREAD

**Issue by GerJeffrey** [wildfirechat/android-chat#191]
使用最新的android-chat，有两个用户user1，user2，user1和user2登录流程都正常，登录user1后通过searchUser搜索到user2，并添加user2，在数据库中可以查看到有user1给user2发送的friend-request数据，但是user2登录后，没有发现此好友请求，通过调试后发现，ChatManager.Instance().getUnreadFriendRequestStatus()总是返回为0，也就是说没有找到此请求，通过打印分服务器日志，发现DatabaseStore.getPersistFriendRequests函数返回的好友请求数量为1，也就是说服务器端已经找到此条好友请求数据，并且返回给移动端，但是为何移动端却没有接收到？
抱歉，第一次涉及到IM技术，这一块的业务流程还没有搞清楚，不知道我是否说的清楚，不知道您能否帮忙提示一下？谢谢！！

**Comment by GerJeffrey** [comment]
添加服务器端日志
INFO  MemoryMessagesStore 1714  - 进入getFriendRequestList,获取朋友请求数量:1,[{"unknownFields":{"fields":{}},"bitField0_":127,"fromUid_":"6f58d19c0a3347e7b533ba8d56a28a57","toUid_":"8714bb9b200346d1b9e93f29a25df420","reason_":"我是 移动用户13585779367","status_":0,"updateDt_":1572438883035,"fromReadStatus_":false,"toReadStatus_":false,"memoizedIsInitialized":-1,"memoizedSerializedSize":-1,"memoizedSize":-1}]
30/10/2019 20:45:09,955 [pool-2-thread-11] INFO  MemoryMessagesStore 1726  - 进入getFriendRequestList,获取朋友请求数量:1
30/10/2019 20:45:09,955 [pool-2-thread-11] INFO  FriendRequestPullHandler 29  - 进入朋友请求FriendRequestPullHandler处理,获取好友请求数量:1
30/10/2019 20:45:09,956 [pool-2-thread-11] INFO  FriendRequestPullHandler 34  - 进入朋友请求FriendRequestPullHandler处理,获取好友请求数据:[{"unknownFields":{"fields":{}},"bitField0_":127,"fromUid_":"6f58d19c0a3347e7b533ba8d56a28a57","toUid_":"8714bb9b200346d1b9e93f29a25df420","reason_":"我是 移动用户13585779367","status_":0,"updateDt_":1572438883035,"fromReadStatus_":false,"toReadStatus_":false,"memoizedIsInitialized":-1,"memoizedSerializedSize":-1,"memoizedSize":-1}]
30/10/2019 20:45:09,957 [pool-2-thread-11] INFO  FriendRequestPullHandler 42  - 进入朋友请求FriendRequestPullHandler处理,构建数据:[10,113,10,32,54,102,53,56,100,49,57,99,48,97,51,51,52,55,101,55,98,53,51,51,98,97,56,100,53,54,97,50,56,97,53,55,18,32,56,55,49,52,98,98,57,98,50,48,48,51,52,54,100,49,98,57,101,57,51,102,50,57,97,50,53,100,102,52,50,48,26,30,-26,-120,-111,-26,-104,-81,32,-25,-89,-69,-27,-118,-88,-25,-108,-88,-26,-120,-73,49,51,53,56,53,55,55,57,51,54,55,32,0,40,-37,-11,-92,-27,-31,45,48,0,56,0]
30/10/2019 20:45:09,957 [pool-2-thread-11] INFO  FriendRequestPullHandler 44  - 进入朋友请求FriendRequestPullHandler处理,返回数据！

**Comment by GerJeffrey** [comment]
拉取好友请求数据时，除了friend-request表外，还涉及到其他表吗？另外，friend-request中的status在好友请求这个业务流程中具体表示哪些状态？

**Comment by yuzhongrong** [comment]
我也有这样的问题
