### ISSUE TITLE
音视频拨打接听后无反应，是什么原因？

### ISSUE THREAD

**Issue by guoxb2016** [wildfirechat/android-chat#192]
报错信息
#1804 java.lang.NoSuchMethodError
No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.phy.ccms-AYM41oYfJ_uexB43MameBg==/base.apk!classes3.dex)

com.phy.ccms.kit.voip.SingleVoipCallActivity.init(SingleVoipCallActivity.java:184)

**Comment by heavyrain2012** [comment]
请参考demo的实现

**Comment by imndx** [comment]
gradle版本的问题，请看下readme
