### ISSUE TITLE
群主转让信息本地消息无法正常刷新

### ISSUE THREAD

**Issue by lovejhf** [wildfirechat/android-chat#194]
写法参考了群增、删管理员代码,发现一个问题,调用设置管理员的方法的时候    mClient.setOnGroupMembersUpdateListener(new IOnGroupMembersUpdateListener.Stub() {
                    @Override
                    public void onGroupMembersUpdated(String groupId, List<GroupMember> members) throws RemoteException {
                        ChatManager.this.onGroupMembersUpdate(groupId, members);
                    }
                });能执行.调用transferGroup()群主转让的时候上面该方法不能执行不知是何原因。解决过的朋友望不吝赐教

**Comment by imndx** [comment]
已解决，请测试最新代码。
