### ISSUE TITLE
大文件发送失败

### ISSUE THREAD

**Issue by ShaoPengHu** [wildfirechat/android-chat#195]
大文件发送一半会重新重百分之一开始发送，不知道重何查起，不知道是什么原因，这个是跟服务器有关吗

**Comment by imndx** [comment]
文件有大小有限制，默认100M
另外，你们使用的是内置文件服务吗？建议使用七牛等云存储

**Comment by ShaoPengHu** [comment]
默认100M这个有看到  是使用内置的 但是有时候网络好的时候就发送成功了 我应该从哪着手

**Comment by imndx** [comment]
1.看下服务端有无报错。
2. 可使用wireshark等抓包看下，是谁断关闭了连接。

另外，内置文件服务，性能等有问题，仅作测试，不推荐商用

**Comment by imndx** [comment]
no response.
