### ISSUE TITLE
Mobile number change only contry

### ISSUE THREAD

**Issue by sadsouler** [wildfirechat/android-chat#196]
Hello, I just love that you made, but just I want to ask that how to change only china to any only any country

**Comment by imndx** [comment]
目前，手机号之前，我们没有添加国家代码。
1. 需要在手机号添加国家代码(SMSLoginActivity
2. app server目前对接的是腾讯短信服务，我不太确认是否支持全球短信验证码服务。如果不支持的话，需要自行对接。

**Comment by sadsouler** [comment]
do I have to connect it with a firebase account, if I have to then what component do I have to enable it?

Thanks in advance.

**Comment by imndx** [comment]
connect it with a firebase account?

抱歉，我不明白。

**Comment by sadsouler** [comment]
See you have set in login page as only china number can register in your app so can I change it to my country only login

**Comment by imndx** [comment]
是的，可以，但你需要修改代码，添加相应的实现。

**Comment by sadsouler** [comment]
Okay, see I'm new to android and I don't know much about android coding so if you help me out then i can show your app as a project in my organization which is related to automation this is the site[Mechatronics Forum](https://mechatronicsforum.tk/) so if you can help me out then it would be nice for me

**Comment by imndx** [comment]
抱歉，我们有很多需要交付的项目，目前没有人力能帮你。

如果你只是测试的话，可以用super code登录的，不需要真的短信验证码。
super code在app server配置。

**Comment by HuuNguyen312** [comment]
@imndx I want to test your app. Please provide "super code". Thanks
