### ISSUE TITLE
mars-core-release 有开源吗？

### ISSUE THREAD

**Issue by dulcan1988** [wildfirechat/android-chat#198]
mars-core-release 有开源吗？用了腾讯的mars框架吗，有没二次开发？

**Comment by imndx** [comment]
你好。
目前不开源，是基于腾讯mars二次开发的。

**Comment by dulcan1988** [comment]
腾讯mars更新的话，会跟着更新吗？

**Comment by imndx** [comment]
会的，但我们不是实时追踪上游，相当于我们维护了一个自己的分支，有自己的演进计划
