### ISSUE TITLE
请问 ProtoMessage 这个实体类,他的jar包是没有开源吗

### ISSUE THREAD

**Issue by moyokoo** [wildfirechat/android-chat#2]
cn.wildfirechat.model.ProtoMessage

**Comment by imndx** [comment]
请参考[协议栈](https://github.com/wildfirechat/proto)代码。
这个类的具体路径是[ProtoMessage.java](https://github.com/wildfirechat/proto/blob/firechat/mars/libraries/mars_android_sdk/src/main/java/cn/wildfirechat/model/ProtoMessage.java)

**Comment by moyokoo** [comment]
好的 谢谢

**Comment by imndx** [comment]
不客气。
哦，请给个⭐^~^
