### ISSUE TITLE
會話中傳送圖片。傳完後，「原本的圖片」的 size 變小了！

### ISSUE THREAD

**Issue by ieyoieyo** [wildfirechat/android-chat#211]
實測，會話中傳送圖片。傳完後，「原本的圖片」的 size 變小了！！
原本的圖：8.98 MB, 4000x2667
傳送後變：8.15 MB, 4000x2667
推測是在下圖紅框的`new FileOutputStream(imageFileSource)`覆寫了原本的圖。因為 imageFileSource 是「已存在的檔案」，所以原本的檔案內容會被清除，然後下一行的`bmpSource.compress(Bitmap.CompressFormat.JPEG, 100, fosSource);` 把前面做 InputStream時的 bmpSource 拿來壓縮 JPEG-100 存回原本的檔案，到此原本的檔案就已經被覆寫了，是嗎？

![Snipaste_2019-11-20_15-51-18](https://user-images.githubusercontent.com/3890826/69219567-156e8100-0bae-11ea-8185-272298464db3.png)

代碼是 11/19 的。

**Comment by imndx** [comment]
你分析的是对的，不应该更新原图，已修正，谢谢。
b691454

**Comment by ieyoieyo** [comment]
> 你分析的是对的，不应该更新原图，已修正，谢谢。
> [b691454](https://github.com/wildfirechat/android-chat/commit/b69145477191389cf1f210b3149e2446f9a232f1)

修正後，在「設定頭像」時，在下圖第 40行 new FileOutputStream(thumbImgName) 的時候會有 Exception 如下圖

![Snipaste_2019-11-21_14-06-11](https://user-images.githubusercontent.com/3890826/69311902-735f9f00-0c68-11ea-8853-4a2e9f06bfba.png)

**Comment by ieyoieyo** [comment]
推測要把第 40行的這個
new FileOutputStream(thumbImgName)
換成：
new FileOutputStream(imageFileThumb)
是嗎？我測過這樣子是 OK的。
