### ISSUE TITLE
请问一下，如果一个手机号，在两台设备上面进行登陆，如何能踢掉之前登陆的人信息？

### ISSUE THREAD

**Issue by dilenzhu** [wildfirechat/android-chat#217]
请问一下，如果一个手机号，在两台设备上面进行登陆，如何能踢掉之前登陆的人信息(是需要在客户端踢出下线，还是服务端有接口呢)？谢谢！

**Comment by imndx** [comment]
已解决，请将
Android、iOS、app server、im server都更新至最新

**Comment by dilenzhu** [comment]
好的，谢谢！
