### ISSUE TITLE
视频通话的清晰度问题，希望可以提供给外部修改分辨率

### ISSUE THREAD

**Issue by unengchan** [wildfirechat/android-chat#22]
测试过程中，响应速度、流畅度都没有问题，但是视频通话清晰度比较一般，如果可以提供方法设置视频通话的清晰度就更好了，或者定义几个合适的分辨率供外部选择调用。

**Comment by imndx** [comment]
请更新代码，并参考下面
``` gEngineKit.setVideoProfile(VideoProfile.VP120P_3, false);```
