### ISSUE TITLE
特定 mp4 檔案傳送失敗，影片 size = 55MB

### ISSUE THREAD

**Issue by ieyoieyo** [wildfirechat/android-chat#221]
我有一個 mp4 影片無論如何就是傳送失敗(100MB以下)！
狀況：
- 影片資訊：55MB，1280 x 720, MimeType: video/mp4。是用手機錄製的。
- 與它在同一路徑下的其他影片都可以傳送成功！
- 改至內部路徑再傳，一樣失敗 ( /storage/emulated/0/Pictures/Telegram/ttyyuui.mp4 )

追蹤到 ChatManager.sendMessage() 裡面的 mClient.send() 裡的回調 onFailure(final int errorCode), 這裡的「errorCode」是「400」。(ChatManager.java:1309, 最新的 commit)
這個「400」是 HTTP 狀態碼「400 Bad Request」嗎？

該 mp4 檔案在：
https://mega.nz/#!aksEHKyJ!n4Z8BICP91lRQ_SZtP0QmPCmBvuMxW9oka5EFHA6QEU
或
https://drive.google.com/file/d/139ukjW1yJZr-kFMHah9rh6MG9ybckWyF/view?usp=sharing

**Comment by anlei586** [comment]
服务器默认是小于等于50MB的限制

**Comment by ieyoieyo** [comment]
瞭解，close it
