### ISSUE TITLE
允許私聊的 ON-OFF 狀態 與實際可私聊的狀態不一致

### ISSUE THREAD

**Issue by ieyoieyo** [wildfirechat/android-chat#223]
請問 群組 成員權限的「允許普通成員發起臨時會話」(以下簡稱"允許私聊) 的 ON-OFF 狀態，是否有已知 issue？
PS：我知道 群主可以與成員私聊不論「允許私聊」是 ON 或 OFF
發現有以下問題：
- 「允許私聊」的狀態不會記憶。調成 ON，背景拉掉(關閉APP)，再進入 群組 > 成員權限 > 允許私聊 有時是 ON 有時是 OFF。
- 隨著這樣的測試做了多次，群組會話界面上，會發生「您關閉了成員私聊」出現連續三次的情況，而不是「一次"開啟"、一次"關閉"」。

**Comment by totemtec** [comment]
代码在这里，客户端程序员理解错了状态

ModifyGroupInfoType.Modify_Group_PrivateChat, preventPrivateChat ? "1" : "0", notifyLines, notifyMsg, 

应该改为：

ModifyGroupInfoType.Modify_Group_PrivateChat, privateChat ? "0" : "1", notifyLines, notifyMsg,

**Comment by imndx** [comment]
> 代码在这里，客户端程序员理解错了状态
> 
> ModifyGroupInfoType.Modify_Group_PrivateChat, preventPrivateChat ? "1" : "0", notifyLines, notifyMsg,
> 
> 应该改为：
> 
> ModifyGroupInfoType.Modify_Group_PrivateChat, privateChat ? "0" : "1", notifyLines, notifyMsg,

谢谢指正
