### ISSUE TITLE
安卓搜索聊天记录接口问题

### ISSUE THREAD

**Issue by Zyhant** [wildfirechat/android-chat#227]
searchConversation搜索所有记录keyword传值h搜出2条记录，在进入到searchMessage搜索时keyword传值h只搜出1条，聊天记录为kuh、hul，只会搜出第二条记录，没有模糊匹配，这样和searchConversation搜出来的结果匹配不上，在IOS没有问题，searchMessage能模糊匹配

**Comment by imndx** [comment]
请更新下代码，再次测试。
