### ISSUE TITLE
关于IM服务连接问题

### ISSUE THREAD

**Issue by jp5201314** [wildfirechat/android-chat#232]
测试贵方的官方版本在用户登录后，重新启动app连接IM服务时出现首次连接不成功返回false
![image](https://user-images.githubusercontent.com/25917917/69936328-7123fd00-1512-11ea-9555-f3914862271d.png)
![image](https://user-images.githubusercontent.com/25917917/69936349-7f721900-1512-11ea-9d79-8bb3c0d51840.png)
dao导致首次连接启动ClientService的成功连接回调中连接   mClient.connect(userId, token);这个方法返回false，在这里面注册的收消息监听及其他监听都未收到数据（猜测时连接未成功），有没有什么办法解决程序在登录状态启动IM服务（启动ClientService）后成功连接到服务，亟待解决，望回复!!!

**Comment by imndx** [comment]
```ChatManager#connect```的返回值，表示的并不是IM 的连接状态，连接状态请通过```OnConnectionStatusChangeListener```监听。

**Comment by jp5201314** [comment]
mClient.setOnReceiveMessageListener(new IOnReceiveMessageListener.Stub() {
                    @Override
                    public void onReceive(List<Message> messages, boolean hasMore) throws RemoteException {
                      // Log.d("dsadsadsa",messages.toString());
                        onReceiveMessage(messages, hasMore);
                    }
                    @Override
                    public void onRecall(long messageUid) throws RemoteException {
                        onRecallMessage(messageUid);
                    }
                });
这个方法在程序启动后监听不到应该接收到的信息呢，就是对方发送了消息，我这边启动app时一进入应该就能监听到消息接收是吧，但是都是没有，你们官方的也是没有的

**Comment by imndx** [comment]
应用启动之后，状态变化是：
connecting -> receiving -> connected
处理receiving状态时，收到的消息，不通知到```ChatManager```，等状态变为connected之后，调用相关方法能获取到。

具体可参考```ClientService.java```里面的```onReceiveMessage```

**Comment by imndx** [comment]
no response.
