### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by ShaoPengHu** [wildfirechat/android-chat#233]
选择图片发送后，按住图片转发，选择好友弹窗时闪退 
contentImageView.getLayoutParams().width 为空

**Comment by imndx** [comment]
你好，请提供一份日志。从代码看的话，感觉不太可能为空呢。

**Comment by ShaoPengHu** [comment]
我以为是我这边写的问题 然后就测了下你们的demo也是会这样

**Comment by ShaoPengHu** [comment]
是这一步 Bitmap bitmap = ((ImageMessageContent) message.content).getThumbnail();

**Comment by imndx** [comment]
fix. 45ff8d7
