### ISSUE TITLE
1、手机端发送的文件看不到文件名(必须点开)，2、聊天中图片是否考虑支持像微信一样，添加一个按钮，能看到全部往来图片呢

### ISSUE THREAD

**Issue by dilenzhu** [wildfirechat/android-chat#234]
1、手机端发送的文件看不到文件名(必须点开)，
2、聊天中图片是否考虑支持像微信一样，添加一个按钮，能看到全部往来图片呢

谢谢！

**Comment by liangzai448** [comment]
![Screenshot_20200109_021906_cn wanyichangz chat](https://user-images.githubusercontent.com/57494210/72004468-72b9b100-3286-11ea-987d-1c016219e32d.jpg)
很简单实现啊

**Comment by dilenzhu** [comment]
> ![Screenshot_20200109_021906_cn wanyichangz chat](https://user-images.githubusercontent.com/57494210/72004468-72b9b100-3286-11ea-987d-1c016219e32d.jpg)
> 很简单实现啊

我已经实现了(比如重要消息循环提醒，重写音视频通话(因为有的设备视频通话有问题)，还有比如图片预览仿微信支持查看分组等等)，只是给官方提的需求。

**Comment by dilenzhu** [comment]
不过基本我只是借鉴了一下官方的思路，协议、UI和后台，我都自己重写了(基本是仿钉钉的)，增加了小程序的功能在上面。

**Comment by liangzai448** [comment]
> 不过基本我只是借鉴了一下官方的思路，协议、UI和后台，我都自己重写了(基本是仿钉钉的)，增加了小程序的功能在上面。

大哥加个好友一起交流一下吧

**Comment by imndx** [comment]
文件名的问题已解决。
另外一个问题，尚未规划，这个issue先关了，可以重提一个issue，进行feature追踪
