### ISSUE TITLE
android 设备；先卸载在重新安装App  ，会话页面中的最后一条消息没有获取到；

### ISSUE THREAD

**Issue by MaTengFei1990** [wildfirechat/android-chat#237]
android 设备；先卸载在重新安装App  ，会话页面中的最后一条消息没有获取到；会话列表的中的每个的lasetMessage为null;
![image](https://user-images.githubusercontent.com/19420333/70703890-ee6a2180-1d0b-11ea-8fc6-dde1aa8d58b0.png)

**Comment by imndx** [comment]
已解决，请更新最新代码测试。
