### ISSUE TITLE
紧急：当消息过多会导致android页面及其卡顿

### ISSUE THREAD

**Issue by yzdying** [wildfirechat/android-chat#238]
现在有 getMessageCount接口，需要多一个 clearMessageToCount(int count)   清除回话至指定的缓存数量即可。 这样才能在消息过多的情况下即使清理一些消息

**Comment by heavyrain2012** [comment]
我们在最新版的ios和android工程中添加了一个新的清除消息接口，可以删除会话指定时间之前的消息，请使用此方法来应急。我们稍后会重构会话列表的生成方法，保证在100W条消息时也有足够好的响应速度。

**Comment by heavyrain2012** [comment]
我们最近版本已经对数据库性能进行了大量的优化，请使用最新版本测试不清除消息是否性能可以接受

**Comment by imndx** [comment]
no response.
