### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by davidzhang12138** [wildfirechat/android-chat#240]
用户使用时发生了闪退 可以帮忙看下吗 谢谢
下面是信息

日志:

1 java.lang.RuntimeException:Unable to destroy activity {cn.ttlt.chat/cn.wildfire.chat.kit.conversation.ConversationActivity}: java.lang.NullPointerException: Attempt to read from field 'cn.wildfirechat.model.Conversation$ConversationType cn.wildfirechat.model.Conversation.type' on a null object reference
--
2 android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4604)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to read from field 'cn.wildfirechat.model.Conversation$ConversationType cn.wildfirechat.model.Conversation.type' on a null object reference
6 cn.wildfire.chat.kit.conversation.ConversationFragment.onDestroy(ConversationFragment.java:583)
7 androidx.fragment.app.Fragment.performDestroy(Fragment.java:2922)
8 androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1504)
9 androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1668)
10 androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1748)
11 androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1812)
12 androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3118)
13 androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3103)
14 androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:330)
15 androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:365)
16 androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
17 android.app.Activity.performDestroy(Activity.java:7417)
18 android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1323)
19 android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4589)
20 android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4622)
21 android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
22 android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
23 android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
24 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
25 android.os.Handler.dispatchMessage(Handler.java:106)
26 android.os.Looper.loop(Looper.java:193)
27 android.app.ActivityThread.main(ActivityThread.java:6898)
28 java.lang.reflect.Method.invoke(Native Method)
29 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
30 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

设备机型
    一加 A6010
系统版本
    Android 9,level 28
ROM
    OnePlus/OnePlus6T
CPU架构
    arm64-v8a

**Comment by imndx** [comment]
你好，这个问题已修复了，请升级到最新代码测试。
