### ISSUE TITLE
更新用户信息失败 返回1

### ISSUE THREAD

**Issue by liuwenzhi1** [wildfirechat/android-chat#243]
请问这个状态码 对应的具体原因是什么？有错误的状态码列表吗

**Comment by imndx** [comment]
我们不会返回这个错误码的，错误码可参考[错误码](http://docs.wildfirechat.cn/server/admin_api/error_code.html?h=%E9%94%99%E8%AF%AF%E7%A0%81)

**Comment by liuwenzhi1** [comment]
@imndx  你好，我发现出现这个现象的原因是我登录成功之后 马上更新用户信息，我这边已经做出了相应的处理，谢谢
