### ISSUE TITLE
3个人的群聊可以撤回别人发的消息

### ISSUE THREAD

**Issue by minorlai** [wildfirechat/android-chat#250]

**Comment by minorlai** [comment]
@LeonDevLifeLog @imndx @heavyrain2012 @siqiii

**Comment by imndx** [comment]
管理员可以撤回别人发的消息

**Comment by minorlai** [comment]
> 管理员可以撤回别人发的消息

怎么取消这个权限呢

**Comment by imndx** [comment]
目前，这个可以在端上控制一下，可以参考下面的地方，修改一下撤回控制逻辑。

```NormalMessageContentViewHolder#contextMenuItemFilter```
