### ISSUE TITLE
群聊人数没有限制人员个数？

### ISSUE THREAD

**Issue by minorlai** [wildfirechat/android-chat#252]
经测试可以一直添加群人员

**Comment by imndx** [comment]
你好，架构上支持无上限。

具体可以参考[群组](http://docs.wildfirechat.cn/base_knowledge/group.html)

**Comment by minorlai** [comment]
> 你好，架构上支持无上限。
> 
> 具体可以参考[群组](http://docs.wildfirechat.cn/base_knowledge/group.html)

你好，人数过多这个问题会造成卡顿，甚至崩溃
针对这问题，有解决的方案吗？
