### ISSUE TITLE
历史消息信息无法获取的问题

### ISSUE THREAD

**Issue by KunCho** [wildfirechat/android-chat#255]
集成完后，重新进入后，会出现无法获取历史聊天消息的问题，聊天记录丢失，无法获取，这种情况应该如何解决？

**Comment by imndx** [comment]
你好。
请测试一下我们的demo有无相同问题，如果有，请在我们demo上复现问题，并提供一下日志。

**Comment by KunCho** [comment]
APP杀死后，再次进入APP后要重新调接口获取token再次重连吧？这种时候重新连接后之前的聊天记录就没有了。

**Comment by imndx** [comment]
是的，需要获取token，然后连接。

1. 确认是同一个用户吗？
2. 这问题是必现的吗？

请提供日志，方便分析？最好是用我们的demo去复现问题，然后提供日志。

**Comment by imndx** [comment]
no response.
