### ISSUE TITLE
如何过滤会话线路

### ISSUE THREAD

**Issue by LeeUsun** [wildfirechat/android-chat#258]
你好，我之前创了一个issue-256，被关了。是什么原因的。。。
问题：因为业务需要，想问下如何过滤会话线路的

**Comment by imndx** [comment]
你好。
上一个issue，因为有commit修复了那个issue，所以自动关闭了。
请用最新代码测试，确认问题是否已修复，如果未修复，请描述详细复现步骤。

**Comment by LeeUsun** [comment]
这样啊。我好像用的是064的这个版本，而且已经嵌入到自己的项目里面去，并且已作了大量的修改，好像不太好解决 0.0

**Comment by imndx** [comment]
你可以参考下我们最近几个commit都修改了什么内容，并同步过去

**Comment by LeeUsun** [comment]
好的，感谢你

**Comment by LeeUsun** [comment]
你好，我已经按照issue-256中的commit修复了，不会崩溃。
不过又出现另外一个问题，在MainActivity中init()方法中改变Arrays.asList(1)线路为1，这时候之前创建的会话为1的群组并没有显示出来，然后再重新创建，这时候依旧没有显示。
然后我在ConversationViewHolder中的构造方法中发现，Arrays.asList(0)竟然是固定了0，这，就有点尴尬了。
然后两处地方都改成1之后，运行app，之前创建的线路为1的群组，依旧没有显示，这时候我再创建群组，群组竟然成功地显示出来了。
我把这两处地方都改成0或者都改成1或者都改成2，反复测试，发现以下几个问题，
1. 创建线路1的会话（此时已创建成功，但是还没发第一句话），线路0的手机在会话列表已经能看到群组已经创建成功，线路1、线路2的手机看不到群创建（线路2看不到可以理解，线路1看不到或许是因为尚未有人发言？）
2.线路1的手机在线路1的群组中，修改群名，正常情况应该有xxx修改群名为xxx的提示，但是线路1的手机上（包括自己和其它线路1的手机）看不到，反而线路0的手机中能看到这个提示。
3.线路1的手机在线路1的群组中发言，其它线路1的手机能正常收到，但是线路0的手机却收不到信息，这就奇怪了，线路0的手机会话列表中都能看到线路1的群组，也能收到群改名的信息，但是在线路1的手机上发言，线路0的手机收不到；经测试，同样地在线路1的会话中，线路0手机，发信息，线路1在此群组中同样收不到
4.继续收集问题，线路这方面bug会比较多

**Comment by imndx** [comment]
提交了一个新的commit，上面的大部分问题，应当都修复了，请你测试一下。

**Comment by imndx** [comment]
no response.
