### ISSUE TITLE
i can't modify my information and notify my friend 

### ISSUE THREAD

**Issue by lianchengtong** [wildfirechat/android-chat#26]
when i want to modify my information ,for example nickname ,or avatar and so on,but then i have modify my information ,but in the page of my friend's contract , it do not work. then i kill the app it is the same.

**Comment by imndx** [comment]
这个地方的更新逻辑和微信一致：
进入到用户详情页才会去更新。

**Comment by lianchengtong** [comment]
thanks, i don't know it is a bug, or is there anything wrong with the code ?the client id is null ?
java.lang.Exception: mars service not connected
![QQ图片20190531140341](https://user-images.githubusercontent.com/10555518/58685038-f33d3880-83ac-11e9-96d0-2c4d106773a1.png)

**Comment by imndx** [comment]
请确认```Application#onCreate````里面是否调用过```ChatManager#init```

**Comment by lianchengtong** [comment]
yes, i have call function init, because i just clone from github, it is work before use bufferknife 8.6, but when i upgrade the latest version of  bufferknife 10.1.0，it doesn't work,

**Comment by imndx** [comment]
我没有测试过```bufferknife 8.10```，但感觉不应当导致bind failure。

请你给我们提供一份更详细的日志：

``` adb logcat > wfc.log ```

**Comment by lianchengtong** [comment]
05-31 19:25:19.976  3729  3729 W Looper  : Slow Frame: doFrame is 12624ms late
05-31 19:25:19.996   389  1000 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=0.45 dur=13264.47 max=12648.33 min=7.54
05-31 19:25:20.002  3729  3729 D ViewRootImpl[Toast]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
05-31 19:25:20.009  3729  3729 E libc    : Access denied finding property "ro.sf.lcd_density"
05-31 19:25:19.998  3729  3729 W ldfirechat.chat: type=1400 audit(0.0:121238): avc: denied { read } for name="u:object_r:graphics_config_prop:s0" dev="tmpfs" ino=10303 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:graphics_config_prop:s0 tclass=file permissive=0
05-31 19:25:20.009  3729  3729 E InputTransport: ro.sf.lcd_density must be defined as a build property
05-31 19:25:20.015  3729  3729 I Toast   : Show toast from OpPackageName:cn.wildfirechat.chat, PackageName:cn.wildfirechat.chat
05-31 19:25:20.017   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.287107,dur:1748.93,max:750.56,min:13.69
05-31 19:25:20.068   389   389 W GuiExt  : Cannot find GuiExtService
05-31 19:25:20.068   389   389 I BufferQueueConsumer: [unnamed-389-3029](this:0xa560d000,id:3029,api:0,p:-1,c:389) connect(C): consumer=(389:/system/bin/surfaceflinger) controlledByApp=false
05-31 19:25:20.068   389   389 I BufferQueueConsumer: [unnamed-389-3029](this:0xa560d000,id:3029,api:0,p:-1,c:389) setConsumerName: unnamed-389-3029
05-31 19:25:20.068   389   389 I BufferQueueConsumer: [Toast#0](this:0xa560d000,id:3029,api:0,p:-1,c:389) setConsumerName: Toast#0
05-31 19:25:20.068   389   389 I BufferQueueConsumer: [Toast#0](this:0xa560d000,id:3029,api:0,p:-1,c:389) setDefaultBufferSize: width=417 height=90
05-31 19:25:20.093  3729  3729 D Surface : Surface::allocateBuffers(this=0x91591800)
05-31 19:25:20.093  3729  3900 D Surface : Surface::connect(this=0x91591800,api=1)
05-31 19:25:20.093   389   466 I BufferQueueProducer: [Toast#0](this:0xa560d000,id:3029,api:1,p:3729,c:389) connect(P): api=1 producer=(3729:cn.wildfirechat.chat) producerControlledByApp=true
05-31 19:25:20.117  3729  3900 D GraphicBuffer: register, handle(0xa3daeb80) (w:417 h:90 s:448 f:0x1 u:b00)
05-31 19:25:20.194  1737 28724 W MiuiPerfServiceClient: interceptAndQueuing:3729|cn.wildfirechat.chat|12648|12648|unknown|null|cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity|419256040866603|Slow main thread|1
05-31 19:25:20.213   378   378 W IMGMemtrackHAL: hal_get_memory: memtrack cache rebuild was required
05-31 19:25:20.340  1737  1755 I zygote  : Background concurrent copying GC freed 160512(9MB) AllocSpace objects, 132(2MB) LOS objects, 78% free, 3MB/15MB, paused 222us total 143.385ms
05-31 19:25:20.543   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:20.564   963   972 I zygote  : Background concurrent copying GC freed 383776(13MB) AllocSpace objects, 38(1512KB) LOS objects, 42% free, 21MB/38MB, paused 310us total 429.978ms
05-31 19:25:20.744   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:21.019   389   426 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=43.01 dur=1022.99 max=232.04 min=8.38
05-31 19:25:21.033   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:44.283710,dur:1016.17,max:218.80,min:14.52
05-31 19:25:21.402   531   531 I thermal_repeater: [recvMdThermalInfo] ret=36, strLen=127,  0, 32767, -127, 11313, 32767, 25441
05-31 19:25:21.744   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:21.968  3729  3900 D Surface : Surface::disconnect(this=0x91591800,api=1)
05-31 19:25:21.968  3729  3900 D GraphicBuffer: unregister, handle(0xa3dac780) (w:417 h:90 s:448 f:0x1 u:b00)
05-31 19:25:21.969   389   426 I BufferQueueProducer: [Toast#0](this:0xa560d000,id:3029,api:1,p:3729,c:389) disconnect(P): api 1
05-31 19:25:21.971  3729  3729 D View    : [Warning] assignParent to null: this = android.widget.LinearLayout{dbbf1ab V.E...... ......ID 0,0-417,90}
05-31 19:25:22.020   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=2.00 dur=1001.20 max=503.41 min=497.79
05-31 19:25:22.047   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:4.931497,dur:1013.89,max:498.57,min:15.50
05-31 19:25:22.325   389   389 I BufferQueueConsumer: [Toast#0](this:0xa560d000,id:3029,api:1,p:-1,c:-1) disconnect(C)
05-31 19:25:22.326   389   389 I BufferQueue: [Toast#0](this:0xa560d000,id:3029,api:1,p:-1,c:-1) ~BufferQueueCore
05-31 19:25:22.376   963  1063 D WifiStateMachine:  MtkL2ConnectedState 131155 764 0, mShouldDeferDisableWifi = false, mState = MONITORING
05-31 19:25:22.543   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:22.598   389  1416 I BufferQueueProducer: [StatusBar#0](this:0xa5648000,id:3,api:1,p:1136,c:389) queueBuffer: fps=0.92 dur=4343.22 max=3345.30 min=8.75
05-31 19:25:22.745   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:23.519   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=2.00 dur=1498.69 max=500.97 min=498.09
05-31 19:25:23.528   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:14.847767,dur:1481.70,max:498.54,min:14.34
05-31 19:25:23.745   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:24.532   389   426 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=1.97 dur=1013.31 max=514.76 min=498.55
05-31 19:25:24.543   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.955819,dur:1014.95,max:500.86,min:14.88
05-31 19:25:24.544   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:24.746   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:25.386   963  1063 D WifiStateMachine:  MtkL2ConnectedState 131155 764 0, mShouldDeferDisableWifi = false, mState = MONITORING
05-31 19:25:25.746   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:26.030   389   466 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=2.00 dur=1497.96 max=500.13 min=498.64
05-31 19:25:26.041   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.003319,dur:1497.52,max:499.25,min:499.09
05-31 19:25:26.544   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:26.546   528   612 E connsyslogger: Bootup Log: 8 log files! 
05-31 19:25:26.641   389   426 I BufferQueueProducer: [StatusBar#0](this:0xa5648000,id:3,api:1,p:1136,c:389) queueBuffer: fps=0.25 dur=4043.00 max=4043.00 min=4043.00
05-31 19:25:26.746   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:27.045   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=1.97 dur=1015.20 max=515.85 min=499.35
05-31 19:25:27.056   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.954890,dur:1015.27,max:515.79,min:99.85
05-31 19:25:27.747   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:28.405   963  1063 D WifiStateMachine:  MtkL2ConnectedState 131155 764 0, mShouldDeferDisableWifi = false, mState = MONITORING
05-31 19:25:28.542   389   426 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=2.00 dur=1497.05 max=499.62 min=498.36
05-31 19:25:28.545   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:28.553   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.003823,dur:1497.14,max:499.44,min:498.62
05-31 19:25:28.747   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:29.238  1671  1671 I ADB_SERVICES: service_to_fd shell,v2:export ANDROID_LOG_TAGS="''"; exec logcat
05-31 19:25:29.556   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=1.97 dur=1014.30 max=515.66 min=498.63
05-31 19:25:29.568   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:1.970756,dur:1014.84,max:515.97,min:498.87
05-31 19:25:29.747   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:30.545   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:30.685   389   466 I BufferQueueProducer: [StatusBar#0](this:0xa5648000,id:3,api:1,p:1136,c:389) queueBuffer: fps=0.25 dur=4043.59 max=4043.59 min=4043.59
05-31 19:25:30.700   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.650477,dur:1131.87,max:499.95,min:132.70
05-31 19:25:30.748   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:31.056   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=2.00 dur=1500.03 max=500.73 min=499.59
05-31 19:25:31.058  1671  1671 I ADB_SERVICES: g_pending_list length=1
05-31 19:25:31.058  1671  1671 I ADB_SERVICES: +read_data=486283 local_socket_list_len=7
05-31 19:25:31.421   963  1063 D WifiStateMachine:  MtkL2ConnectedState 131155 764 0, mShouldDeferDisableWifi = false, mState = MONITORING
05-31 19:25:31.422   531   531 I thermal_repeater: [recvMdThermalInfo] ret=36, strLen=127,  0, 32767, -127, 11313, 32767, 25441
05-31 19:25:31.748   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:32.069   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=1.98 dur=1012.30 max=513.62 min=498.68
05-31 19:25:32.081   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.171995,dur:1381.22,max:515.86,min:366.05
05-31 19:25:32.546   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:32.749   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:33.070   389  1416 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=2.00 dur=1000.85 max=501.27 min=499.59
05-31 19:25:33.271   389  1416 I BufferQueueProducer: [StatusBar#0](this:0xa5648000,id:3,api:1,p:1136,c:389) queueBuffer: fps=0.39 dur=2586.10 max=2586.10 min=2586.10
05-31 19:25:33.279   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.503750,dur:1198.20,max:499.05,min:200.39
05-31 19:25:33.749   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:34.280   389   466 I BufferQueueProducer: [StatusBar#0](this:0xa5648000,id:3,api:1,p:1136,c:389) queueBuffer: fps=2.97 dur=1008.45 max=988.83 min=9.34
05-31 19:25:34.292   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:4.937384,dur:1012.68,max:498.80,min:14.34
05-31 19:25:34.433   963  1063 D WifiStateMachine:  MtkL2ConnectedState 131155 764 0, mShouldDeferDisableWifi = false, mState = MONITORING
05-31 19:25:34.546   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:34.582   389  1416 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=1.98 dur=1512.55 max=515.16 min=496.85
05-31 19:25:34.750   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:35.592   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:3.076988,dur:1299.97,max:498.89,min:116.77
05-31 19:25:35.750   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:36.080   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=2.00 dur=1497.56 max=500.45 min=498.39
05-31 19:25:36.547   528   612 E connsyslogger: Bootup Log: 8 log files! 
05-31 19:25:36.547   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:36.751   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:37.090   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.003329,dur:1497.51,max:499.24,min:499.12
05-31 19:25:37.451   963  1063 D WifiStateMachine:  MtkL2ConnectedState 131155 764 0, mShouldDeferDisableWifi = false, mState = MONITORING
05-31 19:25:37.593   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=1.98 dur=1513.66 max=514.34 min=499.63
05-31 19:25:37.751   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:38.105   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:1.970253,dur:1015.10,max:515.65,min:499.45
05-31 19:25:38.547   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:38.739   389   466 I BufferQueueProducer: [StatusBar#0](this:0xa5648000,id:3,api:1,p:1136,c:389) queueBuffer: fps=0.45 dur=4459.64 max=4043.29 min=416.35
05-31 19:25:38.751   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:39.090   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=2.00 dur=1496.98 max=500.27 min=498.09
05-31 19:25:39.602   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.670799,dur:1497.68,max:499.22,min:149.99
05-31 19:25:39.752   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:40.107   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=1.97 dur=1016.33 max=516.39 min=499.94
05-31 19:25:40.460   963  1063 D WifiStateMachine:  MtkL2ConnectedState 131155 764 0, mShouldDeferDisableWifi = false, mState = MONITORING
05-31 19:25:40.548   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:40.617   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:1.970287,dur:1015.08,max:515.84,min:499.24
05-31 19:25:40.752   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:41.444   531   531 I thermal_repeater: [recvMdThermalInfo] ret=36, strLen=127,  0, 32767, -127, 11313, 32767, 25441
05-31 19:25:41.603   389   466 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=2.00 dur=1496.83 max=500.35 min=498.21
05-31 19:25:41.753   365   365 W /vendor/bin/mtd: Waited one second for vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default. Waiting another...
05-31 19:25:42.115   389   389 I DisplayDevice: [Built-in Screen (type:0)] fps:2.003080,dur:1497.69,max:499.52,min:498.66
05-31 19:25:42.548   528   609 D connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
05-31 19:25:42.619   389   427 I BufferQueueProducer: [cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity#0](this:0xa440b000,id:3026,api:1,p:3729,c:389) queueBuffer: fps=1.97 dur=1015.54 max=516.02 min=499.53

**Comment by lianchengtong** [comment]
i don't know what is the trouble,but now it is ok, thanks .

**Comment by imndx** [comment]
fix
新问题，请提新的issue
