### ISSUE TITLE
开启（关闭）私聊 / 开启（关闭）禁言

### ISSUE THREAD

**Issue by minorlai** [wildfirechat/android-chat#260]
如何不接收开启或关闭的通知？

**Comment by imndx** [comment]
你好。
请详细描述一下问题，不是很明白。

**Comment by minorlai** [comment]
> 你好。
> 请详细描述一下问题，不是很明白。

你好，比如我是管理员，我反复打开或关闭私聊，然后返回群里会显示很多“您已打开私聊”、“您已关闭私聊”。
我的问题是：如果只让这类通知显示一次或者不显示呢？（或者说这种通知是哪种类型呢？）

**Comment by imndx** [comment]
你好，这种消息是：GroupMuteNotificationContent

**Comment by minorlai** [comment]
你好，我想禁止从服务器接收该类消息




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "imndx"<notifications@github.com&gt;; 
发送时间: 2020年1月15日(星期三) 晚上6:48
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com&gt;; 
抄送: "Allen"<1150142387@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wildfirechat/android-chat] 开启（关闭）私聊 / 开启（关闭）禁言 (#260)




你好，这种消息是：GroupMuteNotificationContent

**Comment by minorlai** [comment]
> 你好，这种消息是：GroupMuteNotificationContent

这种消息从服务器拉取下来怎么区分的呢？它是什么type的？

**Comment by imndx** [comment]
你看下代码吧，如果是想全部都不显示出来，那直接改下这个消息的persistFlag就可以了
