### ISSUE TITLE
三星 SM G955F  Android 5.1.1 闪退

### ISSUE THREAD

**Issue by minorlai** [wildfirechat/android-chat#261]
![TIM截图20200117135741](https://user-images.githubusercontent.com/18749313/72656260-f5ecac80-39d4-11ea-883c-da8339d7f9d5.png)

![1121](https://user-images.githubusercontent.com/18749313/72656392-e15ce400-39d5-11ea-9faa-4039860518b6.png)

步骤：注册两个账号成功之后，登录第一个保存登录状态，隔天打开app，点击退出登录，登第二个账号的时候MainActivity 判断中 --> ConnectionStatusLogout=-2 ，会出现一直登不上去的情况，status=-2 状态比较频繁。

**Comment by imndx** [comment]
已解决，请升级到最新测试
