### ISSUE TITLE
华为推送问题

### ISSUE THREAD

**Issue by LeeUsun** [wildfirechat/android-chat#262]
你好，华为推送收不到。
我在华为开发者联盟注册了app，也取得了appId的参数。我在push/build.gradle文件中，更换HMS_APP_ID为自己注册的参数，但是app互相发消息并没有收到推送通知。
于是我从HuaweiPushRevicer.java类的onToken()方法中获取了token，然后在华为控制台那里输入单个token测试推送消息，这样子操作的话是可以推送到我的手机上。

**Comment by LeeUsun** [comment]
因为开发的app只在华为的手机上运行，所以暂时没做其他厂商的推送测试

**Comment by imndx** [comment]
1. 目前华为推送才有透传方式，需要开启自启动、通知栏等权限才会显示。

可参考这个PR: [华为推送通知栏](https://github.com/wildfirechat/push_server/pull/11)

**Comment by imndx** [comment]
no response.

**Comment by Tgakes** [comment]
请问你这个后面如何解决的呢？
