### ISSUE TITLE
对话消息中如何更新消息

### ISSUE THREAD

**Issue by LeeUsun** [wildfirechat/android-chat#263]
messageViewModel.onMessageUpdate()这方法能更新消息，但只能在自己那端看到更新后的消息，我想做到别人那端也更新。
业务场景：类似于微信转账的，对方发过来的转账，自己领取后，（自己那端）先onMessageUpdate一下别人发红包的那条消息，从待领取---已被领取，然后自己再发一条 “已领取” 的信息；然后对方那端，虽然看到领取转账的那方发了一条 “已领取” 的信息，但是刚才发起转账的那条消息没被update，还是显示 “待领取”的状态。

**Comment by LeeUsun** [comment]
而且messageViewModel.onMessageUpdate()更新完消息之后，确实能看到消息更新了，但是重新进来之后还是恢复没更新之前的数据。
例如
((TextMessageContent) message.message.content).setContent(“修改数据”);
messageViewModel.onMessageUpdate(message);
执行完之后能看到消息的内容变为“修改数据”，退出对话activity，重新进，又变回原来的内容，而不是“修改数据”

**Comment by imndx** [comment]
如果需要更新消息，并存库，需要调用```ChatManager.updateMessageContent```

**Comment by imndx** [comment]
no response.
