### ISSUE TITLE
APP杀掉进程后无法收到推送消息

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#265]
你好，APP杀掉进程后无法收到推送消息。
我是先用你们最新的代码，用项目里的证书打的包，在华为、oppo、小米三个手机上，杀掉进程后都收不到推送消息；然后在自己项目里，正确替换各个推送平台KEY后，杀掉进程也是无法收到推送消息。这两种情况下，APP不杀进程，退到后台，都是可以正常收到消息提醒，而且确定消息通知等所需权限都已打开。

**Comment by imndx** [comment]
我刚用小米手机测试了一下，能正常收到推送。

可以从以下两个思路去查这个问题：
1. 确认端上```ChatManager.setDeviceToken```是否调用。
2. 确认是否有调用push server。

**Comment by imndx** [comment]
另外，打开自启动和通知栏消息权限了吗？

**Comment by imndx** [comment]
no response.
