### ISSUE TITLE
切换成自己的服务器后IM不通

### ISSUE THREAD

**Issue by CheriseQiu** [wildfirechat/android-chat#266]
切换成了自己的服务器，验证码后台写死的，登录成功之后IM模块不通，修改昵称返回-1，请问是什么原因呢

**Comment by CheriseQiu** [comment]
Android端只修改了 IM_SERVER_HOST  和  APP_SERVER_ADDRESS

**Comment by imndx** [comment]
能正常发送文本消息吗？

**Comment by CheriseQiu** [comment]
也不能------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>
发送时间: 2020年2月12日(星期三) 下午3:39
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "CheriseQiu"<315748441@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 切换成自己的服务器后IM不通 (#266)



能正常发送文本消息吗？
 
&mdash;

**Comment by imndx** [comment]
可能是连接就没有成功，请看下连接状态。

我不是很明白你们修改的逻辑，但需要注意下面的地方：
1. 获取token所使用的clientId，一定要通过```ChatManager#getClient```获取

**Comment by CheriseQiu** [comment]
会话列表一直显示连着中，应该是没通，客户端是只需要修改IM服务地址和service服务地址就行了吧



---原始邮件---
发件人: "imndx"<notifications@github.com&gt;
发送时间: 2020年2月12日(周三) 晚上6:18
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com&gt;;
抄送: "CheriseQiu"<315748441@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wildfirechat/android-chat] 切换成自己的服务器后IM不通 (#266)



可能是连接就没有成功，请看下连接状态。
 
我不是很明白你们修改的逻辑，但需要注意下面的地方：
  
获取token所使用的clientId，一定要通过ChatManager#getClient获取

**Comment by imndx** [comment]
是的，如果你们什么也没改动的话，只需修改```Config.java```文件即可。

请提供安卓端的全量日志吧，没有日志不能分析。

**Comment by imndx** [comment]
no response.
