### ISSUE TITLE
android第二次进入没有数据

### ISSUE THREAD

**Issue by wanshijie3** [wildfirechat/android-chat#267]
![手机数据库截图](https://user-images.githubusercontent.com/19466443/74533981-c9916500-4f6d-11ea-9a1b-c0a2dc340409.jpg)
android
在将android-chat集成进我的工程后第一次进入正常,第二次没有数据,显示连接失败,个人信息显示一串字符
因为在包名下找不到数据库,所以无法确认问题,
但是在fils路径下找到了一个和用户名字符相同的路径,
实际调试发现,在第一次进入时会生成一个data文件,二次进入时又会生成一个较小的文件,之后再次进入也都无数据,删除后生成的data文件也 无效,后续仍然会继续生成
无法确认具体问题,望提供解决方法

**Comment by imndx** [comment]
是否有修改过生成clientId相关的方法？

**Comment by wanshijie3** [comment]
> 是否有修改过生成clientId相关的方法？

并没有修改过,做过最大的改动就是把工程中的androidx转成了support,不清楚clientid的生成逻辑,这个clientid是在java层获取的还是在协议层获取的呢?为什么会出现两次登录clientid不相同的情况呢?
这个问题不是必现,但是在合成后发生频率很高

**Comment by imndx** [comment]
这个clientId是在java层生成的，```ChatManager#getClientId```。
看起来像存到```SharedPreference```里面的```clientId```丢了，然后重新生成了一个新的。

**Comment by wanshijie3** [comment]
原来是这样,,但是我看了下`ChatManager#getClientId`,直接跳转到了 `IRemoteClient`,接着具体实现就看不到了
![chatmanager_fun](https://user-images.githubusercontent.com/19466443/74585835-411dcd80-501c-11ea-97b6-68ccdda060ec.jpg)
接着我搜了下刚才你说的`clientid`,在`ClientService#getDeviceType`找到了`clientid`的相关操作,`clientid`的生成是否就在这里呢,如果是的话是否可以在这里简化或者避免这种问题产生呢

![client_fun](https://user-images.githubusercontent.com/19466443/74585847-67436d80-501c-11ea-86db-c7b489d6731f.jpg)

**Comment by imndx** [comment]
最新代码已经更新了getClientId方法，请你们更新测试

**Comment by wanshijie3** [comment]
不好意思,还是再问一下,最新代码在1月4日做的一次修改,看到新的clienId获取方式仍然是在SharedPreference存取的一套逻辑,没有什么明显变化,只是地方变了,换成了在ChatManager获取并传入,但是增加了StnLogic.clientId()的相关方法,请问cliendId新的的生成方式和这个有关吗,是否和协议层相关?
![最新版代码](https://user-images.githubusercontent.com/19466443/74598102-3740ac80-50a6-11ea-91c5-1391ac516ad8.jpg)

**Comment by imndx** [comment]
你好，```getEncodedClientId```返回的是加密后的clientId，并且需要在ClientService绑定成功之后，才能正常返回。
```getEncodedClientId```，目前仅限内部使用，如开发中的朋友圈。

更新后的```getClientId```并不依赖于clientService，这样任何时候，都可以正常获取使用。

**Comment by wanshijie3** [comment]
好的,了解,另外我之前集成后再次进入获取不到id的问题是个多进程问题,需要在使用`SharedPreferences`时添设置MODE `MODE_MULTI_PROCESS`,开启多进程访问才可以,暂时解决我的问题,这个问题可能在涉及到集成多进程工程中普遍存在,不确认是否会造成其他影响

**Comment by imndx** [comment]
你好。
根据官方文档，```SharedPreferences``` 是有多进程访问问题，推荐使用```ContentProvider```，这个地方我们再次看下。

你说的多进程集成是：把```WfcUIKit(ChatManager)```运行在单独的进程？

**Comment by wanshijie3** [comment]
不是这个意思,我是指工程本身开启了多条进程,我测试了多次,发现生成并存储`clientId`部分的代码没有运行进程限制,所以打印结果看到并没有肯定运行于主进程,,也会运行于`marsservice`进程,这就造成了之前我遇到的情况

**Comment by imndx** [comment]
您好，我更新了下```getClientId```的逻辑，采用文件互斥锁的方式，请你测试一下。

**Comment by imndx** [comment]
您好，我更新了下```getClientId```的逻辑，采用文件互斥锁的方式，请你测试一下。

**Comment by wanshijie3** [comment]
新的存取方法更安全,很好的解决了这个问题,十分感谢回复

**Comment by imndx** [comment]
@wanshijie3 
你好，昨天的代码有个bug，请你重新更新一下代码。

**Comment by wanshijie3** [comment]
好的
