### ISSUE TITLE
使用你们demo登陆时，程序崩溃如图

### ISSUE THREAD

**Issue by yndjl** [wildfirechat/android-chat#268]
![1581926871](https://user-images.githubusercontent.com/18571223/74635021-1b213600-51a0-11ea-99bd-c49557c37bc0.png)
`02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err: android.os.DeadObjectException
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at android.os.BinderProxy.transact(Binder.java:496)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at cn.wildfirechat.client.IRemoteClient$Stub$Proxy.connect(IRemoteClient.java:1403)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at cn.wildfirechat.remote.ChatManager.connect(ChatManager.java:1232)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at cn.wildfire.chat.app.login.SMSLoginActivity$1.onUiSuccess(SMSLoginActivity.java:86)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at cn.wildfire.chat.app.AppService$2.onUiSuccess(AppService.java:96)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at cn.wildfire.chat.app.AppService$2.onUiSuccess(AppService.java:93)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at cn.wildfire.chat.kit.net.SimpleCallback$1.run(SimpleCallback.java:19)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-17 15:57:52.220 2668-2668/cn.wildfirechat.chat W/System.err:     at android.os.Looper.loop(Looper.java:135)`

**Comment by yndjl** [comment]
还有个问题，就是第一次登陆的时，登陆成功，会弹出应用停止运行的弹窗提示。点掉弹框之后，进入主页面，然后再退出来，杀掉进程之后，再进应用就是登陆界面。随后再次进行手机号码登陆，最后都会跳转到登陆界面。我用的是模拟器测试的。

**Comment by imndx** [comment]
请你更新下代码，重新测试一下

**Comment by yndjl** [comment]
> 请你更新下代码，重新测试一下

更了你们那个修复cliendId的方法。模拟器上新装上应用demo，第一次登陆时，调用ChatManager的connect方法还是报错。但是退出登陆之后，第二次登陆就没有问题。错误日志如下：

**Comment by imndx** [comment]
你好，请你提供一下marsservice进程的日志。

可以通过adb logcat > log.txt 抓取全部日志。

**Comment by imndx** [comment]
no response.
