### ISSUE TITLE
使用开源版本的客户端

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/android-chat#269]
1.无法获取到我加入的群列表
比如A创建群C，B加入这个群，B的群列表接口返回的是空，同时A也只有先收藏了C这个群才能看到
2.总是出现消息发出去，但是总要很久才接收到的问题
3.用的系统自己的媒体服务大图片基本就显示不出来，或者很慢

**Comment by heavyrain2012** [comment]
1，群列表跟微信逻辑一致，只有收藏了才存在
2，需要判断接收端到服务器的网络状况（ping值和丢包率）和连接情况，请给我们提供日志
3，请确认手机与服务器的网络（ping值和丢包率），请抓取pcap日志。另外系统内的媒体服务属于测试性质的，建议使用七牛

**Comment by dotcool** [comment]
1.但是收藏也不稳定

**Comment by dotcool** [comment]
我看官方的demo也没法获取到群聊列表

**Comment by heavyrain2012** [comment]
没有，我们也没有提供获取所有群聊的接口。因为建群是非常容易的事，每个人都会有大量的群，可能说完事后就再也不关心了，特别关注的群可以收藏，这也是微信的逻辑。

**Comment by dotcool** [comment]
好的
