### ISSUE TITLE
Git上最新的代码，在Android上，发送音视频通话，对方无法接收到

### ISSUE THREAD

**Issue by sihan100** [wildfirechat/android-chat#273]
![Uploading QQ截图20200223183606.png…]()
您好，经过本人反复测试，库上最新的Android代码编译后无法进行音视频通话，但是0.6.9的版本代码，编译后可以正常通话，我们自己的服务器设置也没有问题，看看是不是你们的相关代码没有合并提交到master上？谢谢了！

**Comment by heavyrain2012** [comment]
通话双方都是最新版吗，还是说一个旧的一个新的？

**Comment by sihan100** [comment]
通话双方的版本都是一样的，我的意思是昨天库上最新的代码下载下来后，编译出的版本，在通话双方音视频都不行。但是你们页面上提供的0.6.9的版本源码编译出的apk在通话双方就都是正常的！我经过反复测试，猜想问题可能还是库上最新代码与之前你们提供的版本有差异导致的！所以还麻烦你们确认一下！再次表示感谢！图中所示为正常的版本！
![image](https://user-images.githubusercontent.com/6994955/75127619-0c380780-56fb-11ea-84fb-f1e23d946763.png)

**Comment by imndx** [comment]
你好，我用GitHub上最新的代码测试了，一切正常的，请你更新下代码测试一下，如果还是有问题，请给我们提供一下全量日志。

**Comment by xfjxfj** [comment]
我这边现在也会出现这样的问题，请问在demo中，除了一开始在server初始化外，还有其他地方启动服务然后去监听来电吗？
