### ISSUE TITLE
部分7.0手机机型，建立链接不成功

### ISSUE THREAD

**Issue by zhanshen1373** [wildfirechat/android-chat#275]
移动端日志：
2016-03-15 13:52:48.677 2297-2314/com.hayden.hap.zct:marsservice E/mars::proto: [DB2.cc, getDBPath, 310]:open db /data/user/0/com.hayden.hap.zct/files/3/6bcf5d4bac5c6f041458015328503/data
2016-03-15 13:52:48.680 2297-2314/com.hayden.hap.zct:marsservice E/mars::proto: [DB2.cc, Open, 375]:open db done
2016-03-15 13:52:51.240 2297-2313/com.hayden.hap.zct:marsservice E/mars::proto: [MessageDB.cc, getUserInfo, 3473]:get user info refresh 3, 0,ver:1
2016-03-15 13:52:51.358 2297-2384/com.hayden.hap.zct:marsservice E/mars::proto: [MessageDB.cc, getUserInfo, 3473]:get user info refresh 3, 1,ver:1

**Comment by imndx** [comment]
你好，请提供完整的日志。

**Comment by zhanshen1373** [comment]
移动端就这些log，而且是在marsservice进程中，你是不是需要服务端日志

**Comment by zhanshen1373** [comment]
> 你好，请提供完整的日志

移动端就这些log，而且是在marsservice进程中，你是不是需要服务端日志

**Comment by imndx** [comment]
你命令行下用adb logcat 来抓日志，应当还有其他日志。

**Comment by yeshengwu** [comment]
官方demo使用的是 0.7.0版本，下载地址是github扫码的 http://static.wildfirechat.cn/download-demo.htm

日志文件请见附件。http://bbs.wildfirechat.cn/attach-download-58.htm

**Comment by zhanshen1373** [comment]
> 你命令行下用adb logcat 来抓日志，应当还有其他日志。

adb 不是上古的玩意吧，好不容弄出来了，这个回复不能上截图。我回家再看看吧。

**Comment by zhanshen1373** [comment]
> > 你命令行下用adb logcat 来抓日志，应当还有其他日志。
> 
> adb 不是上古的玩意吧，好不容弄出来了，这个回复不能上截图。我回家再看看吧。

03-18 06:20:10.253 E/mars::proto( 1677): [DB2.cc, getDBPath, 310]:open db /data/user/0/com.hayden.hap.zct/files/3/6bcf5d4bac5c6f041458015328503/data
03-18 06:20:10.256 E/mars::proto( 1677): [DB2.cc, Open, 375]:open db done
03-18 06:20:10.262 E/NativeCrypto( 1716): ssl=0xebc282c0 cert_verify_callback x509_store_ctx=0xd854ceac arg=0x0
03-18 06:20:10.262 E/NativeCrypto( 1716): ssl=0xebc282c0 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
03-18 06:20:10.954 E/st480   (  331): IOCTL_SENSOR_GET_DATA_MAG error!
03-18 06:20:11.954 E/st480   (  331): IOCTL_SENSOR_GET_DATA_MAG error!
03-18 06:20:12.076 E/WifiStateMachine( 1021): mIsFullScanOngoing: false, mSendScanResultsBroadcast: false
03-18 06:20:12.088 E/WifiScanningService( 1021): WifiSingleScanStateMachine IdleState enter
03-18 06:20:12.695 E/        (  346): Audio_PerfServiceNative_userDisable == NULL
03-18 06:20:12.809 E/mars::stn( 1677): [net_source.cc, GetLongLinkItems, 192]:longlink host empty.
03-18 06:20:12.847 E/mars::stn( 1677): [longlink.cc, __RunConnect, 469]:task socket close sock:-1 vecaddr empty
03-18 06:20:12.929 E/mars::stn( 1677): [net_source.cc, GetLongLinkItems, 192]:longlink host empty.
03-18 06:20:12.955 E/st480   (  331): IOCTL_SENSOR_GET_DATA_MAG error!
03-18 06:20:12.993 E/mars::stn( 1677): [longlink.cc, __RunConnect, 469]:task socket close sock:-1 vecaddr empty
03-18 06:20:13.074 E/mars::stn( 1677): [net_source.cc, GetLongLinkItems, 192]:longlink host empty.
03-18 06:20:13.099 E/mars::proto( 1677): [MessageDB.cc, getUserInfo, 3473]:get user info refresh 3, 0,ver:1
03-18 06:20:13.124 E/mars::stn( 1677): [longlink.cc, __RunConnect, 469]:task socket close sock:-1 vecaddr empty
03-18 06:20:13.179 E/mars::stn( 1677): [net_source.cc, GetLongLinkItems, 192]:longlink host empty.
03-18 06:20:13.215 E/mars::stn( 1677): [longlink.cc, __RunConnect, 469]:task socket close sock:-1 vecaddr empty
一部分日志，看一下吧

**Comment by imndx** [comment]
你好，你手机时间不对，请校准时间。
为了防止重放攻击等，协议栈会对时间进行校验。

**Comment by zhanshen1373** [comment]
> 你好，你手机时间不对，请校准时间。
> 为了防止重放攻击等，协议栈会对时间进行校验。

厉害了
