### ISSUE TITLE
官方demo登陆成功后无法连接im

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/android-chat#276]
官方demo使用的是 0.7.0版本，下载地址是github扫码的 http://static.wildfirechat.cn/download-demo.htm

日志文件请见附件。[http://bbs.wildfirechat.cn/attach-download-58.htm](url)

**Comment by yeshengwu** [comment]
同样demo在小米8上是成功登陆并获取到消息的。所以很困惑。[https://github.com/wildfirechat/android-chat/issues/275](url)

**Comment by imndx** [comment]
你好，我看了日志，但感觉日志不全，没有发现问题。请你重新测试，并抓取完整的日志。

**Comment by yeshengwu** [comment]
> 你好，我看了日志，但感觉日志不全，没有发现问题。请你重新测试，并抓取完整的日志。

我主要测试的是登陆页获取验证码到首页tab选中 会话列表页 头部一直显示 “正在连接...” 超过2分钟多次试验都是同样问题所以就退出app把日志在 as中拷贝出来，没有过滤所有包括libc等日志都可以看的。我感觉是兼容性问题，小米8没问题的。
所以你想说的完整日志要包含什么关键字，这样我重新测试看能否搜索到你给我的关键字，这样我也好提供更完整日志，

**Comment by imndx** [comment]
完整日志会包含大量的：```mars::proto```。

在命令行下```adb logcat > log.txt```， 然后复现问题，就能抓取到完整日志。

**Comment by yeshengwu** [comment]
我在命令行下adb logcat > mate10.log上传的日志，帮忙看看。
[http://bbs.wildfirechat.cn/attach-download-59.htm](url)

**Comment by yeshengwu** [comment]
我在命令行下adb logcat >mate10-newapp.log上传的日志，帮忙看看。这个不是demo,是我们自己修改了包名的，里面有很多 mars::proto
http://bbs.wildfirechat.cn/attach-download-60.htm

**Comment by yeshengwu** [comment]
我的mate10系统版本是：android 9 api: 28.   是否定位到相关问题了？
最新日志有mars::proto。 里面有很多 topic ROUTE 的日志，难道是在mate10上面dns出问题了？

**Comment by imndx** [comment]
日志显示，你们服务端(im.ylyapps.com/39.106.144.201)80端口被nginx占用，是否将
```/route```等请求转到了 ```im server```，可以参考[nginx配置](https://github.com/wildfirechat/server/tree/wildfirechat/broker/nginx)

**Comment by yeshengwu** [comment]
> 日志显示，你们服务端(im.ylyapps.com/39.106.144.201)80端口被nginx占用，是否将
> `/route`等请求转到了 `im server`，可以参考[nginx配置](https://github.com/wildfirechat/server/tree/wildfirechat/broker/nginx)

那我们同样app为何小米8没有问题？

**Comment by imndx** [comment]
确认服务器地址是(im.ylyapps.com/39.106.144.201) ？

```curl -v 39.106.144.201/api/version```返回```404```

**Comment by yeshengwu** [comment]
curl -v im.ylyapps.com/api/version 返回是对的。

**Comment by yeshengwu** [comment]
我的qq  635061682 欢迎骚扰。等我们解决好我把问题答案再放上来，是否愿意来跟我玩？哈哈

**Comment by imndx** [comment]
你好，日志显示访问```im.ylyapps.com/route``` 返回数据不对，请你用```WireShark```抓一个pcap包，我们分析一下，请求数据是不是有什么不对。

**Comment by yeshengwu** [comment]
pcap包已经抓了，帮忙分析 [http://bbs.wildfirechat.cn/attach-download-61.htm](url)

**Comment by imndx** [comment]
你好，你手机日期不对。

**Comment by yeshengwu** [comment]
手机时间调正确后测试正常了，但我还想问具体原因：为何手机时间不对会导致im无法连接呢？

**Comment by heavyrain2012** [comment]
因为协议栈重要数据都会带有时间检查功能，防止被人抓包进行重放攻击。正常情况下手机都会带有自动校时功能，不会出这个问题。我们后续也会对这点进行优化，解决一些没有校时功能的设备的问题
