### ISSUE TITLE
消息引用

### ISSUE THREAD

**Issue by liangzai448** [wildfirechat/android-chat#279]
如题

**Comment by imndx** [comment]
你好，不明白问题，请重新描述一下具体需求

**Comment by liangzai448** [comment]
![Screenshot_20200302_213506](https://user-images.githubusercontent.com/57494210/75681042-c4eae180-5ccd-11ea-8825-c3299625bb4d.jpg)
![Uploading Screenshot_20200302_213449.jpg…]()

**Comment by imndx** [comment]
明白了，你指的是是消息引用吧？这个正在计划中。

**Comment by liangzai448** [comment]
![Screenshot_20200302_213449](https://user-images.githubusercontent.com/57494210/75681150-f663ad00-5ccd-11ea-8047-6e3902993a53.jpg)
就是这种效果，回复某条信息，点击被回复的信息可以跳转到原信息的位置

**Comment by imndx** [comment]
已解决，请更新到最新代码。
