### ISSUE TITLE
what is the trouble ?is it the push bug 

### ISSUE THREAD

**Issue by lianchengtong** [wildfirechat/android-chat#28]
![image](https://user-images.githubusercontent.com/10555518/58928405-f35e7f00-8784-11e9-9277-a5c0e161ecfc.png)

**Comment by heavyrain2012** [comment]
Push服务需要知道当前手机型号和版本，需要读取/system/build.prop。从日志上看是没有访问权限，请确认应用需要的权限都已经开通

**Comment by lianchengtong** [comment]
![image](https://user-images.githubusercontent.com/10555518/59079984-fa1dfb00-8918-11e9-9402-ca1b77cc8d17.png)
can you tell what is the trouble ?when i use voice function ?
