### ISSUE TITLE
手动更新消息状态不成功

### ISSUE THREAD

**Issue by hyl87** [wildfirechat/android-chat#280]
updateMessage(long messageId, MessageStatus status)
1.手动更新成发送失败,重新拉取消息列表的时候会变成sent的状态
2.ios的消息状态更新是成功的

**Comment by hyl87** [comment]
@imndx  android 的这个bug什么时候能修复啊,最近在做已读回执 和已到达的状态修改啊

**Comment by imndx** [comment]
请参考 d0fd5ad
