### ISSUE TITLE
A拉黑B，A发起视屏通话，B多次点接受后，B会崩溃

### ISSUE THREAD

**Issue by zhanshen1373** [wildfirechat/android-chat#283]
03-03 10:44:38.443 F/libc    (22558): /usr/local/google/buildbot/src/android/ndk-release-r16/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "Pure virtual function called!" failed
03-03 10:44:38.475 E/aao_buf_mgr(  555): [updateInfo]  pAEResult is NULL 
03-03 10:44:38.475 E/aao_buf_mgr(  555):  (updateInfo){#600:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/mt6765/buf_mgr/AAOBufMgr.cpp}
03-03 10:44:38.516 E/aao_buf_mgr(  555): [updateInfo]  pAEResult is NULL 
03-03 10:44:38.516 E/aao_buf_mgr(  555):  (updateInfo){#600:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/mt6765/buf_mgr/AAOBufMgr.cpp}

**Comment by imndx** [comment]
你好，这个问题可能修复了，请问你使用的是最新的代码吗？
请用最新代码(avenginekit.aar)测试一下。

**Comment by zhanshen1373** [comment]
1月13更新的代码，移动端更新的话，是不是服务端也要更新

**Comment by imndx** [comment]
针对这个问题，应当可以只更新移动端。

**Comment by zhanshen1373** [comment]
> 针对这个问题，应当可以只更新移动端。

了解了，谢谢
