### ISSUE TITLE
如题。demo中的项目是否有已读回执功能呢

### ISSUE THREAD

**Issue by yndjl** [wildfirechat/android-chat#284]

**Comment by imndx** [comment]
你好，目前没有已读回执功能，如果想自行开发的话，可以参考

#88

**Comment by yndjl** [comment]
看了#88中想法。咨询下在前两天ChatManager中添加的更新本地消息状态方法中，以下代码中关于status的判断，是什么理解？
` if ((   message.direction == MessageDirection.Send 
          && status.value() >= MessageStatus.Mentioned.value())
       ||
          message.direction == MessageDirection.Receive 
          && status.value() < MessageStatus.Mentioned.value())
    {
           return false;
     }`

**Comment by hyl87** [comment]
android 的 updatemessage 有bug 等修复 @yndjl

**Comment by imndx** [comment]
请参考 d0fd5ad

**Comment by yndjl** [comment]
关于群消息的已读回执，有什么好的思路吗

**Comment by imndx** [comment]
群里有个定向消息的概念，发送消息时，通过```toUsers```指定消息发给群里那些人。

将回执信息，通过定向消息，发送给原消息的发送者。

**Comment by imndx** [comment]
补充一下，专业版IM Server已支持消息回执功能。
