### ISSUE TITLE
安卓端获取到的用户信息的type不准确，永远是0，跟服务端的不一致

### ISSUE THREAD

**Issue by huqch** [wildfirechat/android-chat#285]
如题，在安卓端用如下代码
UserInfo user = ChatManager.Instance().getUserInfo(userId,true);
获取到的UserInfo没有解析type字段吧？就算服务端改成3了，安卓端一直是0

**Comment by imndx** [comment]
你服务端是怎么改的？直接修改数据库了？

**Comment by huqch** [comment]
我在本地网络调试，改了数据库重启了的，而且服务器我也打印日志了 ，服务器的type不是0

**Comment by imndx** [comment]
你好，不能直接改数据库。

或者你可以把```_dt```那个字段的值改大一点测试一下。

**Comment by huqch** [comment]
我知道服务端数据都是缓存在Hazelcast里面的，但是我通过api接口修改的用户信息，客户端的type也是0哦

**Comment by imndx** [comment]
你好，端上调用```getUserInfo```的时候，有个```refresh```的参数，需要传```true```才会触发去服务端拉取新的用户信息，然后又回调通知。

**Comment by huqch** [comment]
String userId = ChatManager.Instance().getUserId();
    UserInfo user = ChatManager.Instance().getUserInfo(userId,true);
    System.out.println(user.name+"---"+user.displayName +"----"+user.type+"---"+user.uid);
  客户端我是这么去获取的哦，点了好几次 都是0，我都把服务端日志打出来了，服务端明明是3
算了 没关系啦 我在服务端控制吧

**Comment by imndx** [comment]
```ChatManager.Instance().getUserInfo(userId,true);```返回的是本地的用户信息，更新后的用户信息，会通过```onUserInfoUpdate```回调通知。

**Comment by imndx** [comment]
no response
