### ISSUE TITLE
多人音视频的几个问题

### ISSUE THREAD

**Issue by heavyrain2012** [wildfirechat/android-chat#288]
1、语音通话时静音功能不稳定，暂不清楚是底层问题还是我们的处理有问题
2、发起群聊通话后，对方未接通的几个状态：对方正忙（对方拒绝接听），对方忙线中（对方正在通话中），对方无应答（对方在收到提醒的时间内未接听）
3、群聊通话时，在讲话的成员，其对应图标内有“正在说话”的状态显示

**Comment by imndx** [comment]
3. 已添加
