### ISSUE TITLE
聊天记录清空不掉

### ISSUE THREAD

**Issue by ShaoPengHu** [wildfirechat/android-chat#29]
清空聊天记录 再点进去聊天下拉又有聊天数据 并且可以无限下拉一直添加之前的聊天数据

**Comment by imndx** [comment]
这是个问题。

清空聊天记录，再次进入了，触发了加载远程聊天记录，所以看起来清不掉。

**Comment by lianchengtong** [comment]
@ShaoPengHu I don't know how you review the issue ,but i can't find it ,is there anything trouble with you.
@imndx why do i can't delete my friend ,single chat in the contract ,

**Comment by imndx** [comment]
@lianchengtong 说中文吧

**Comment by yuzhongrong** [comment]
这个问题如何解决的
