### ISSUE TITLE
一个用户向正在音频/视频通话中的几个用户发起新的呼叫时，，导致通话中的用户断开通话。

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/android-chat#290]
1、A、B正在通话中，用户C 使用android或ios设备，发起仅包含A、B、C三人的的群聊通话，导致A、B的通话断开，且收不到来自C的群聊通话邀请，C自己一直处于等待接听的状态。
2、A、B正在通话中，用户C 使用android或ios设备，发起包含A、B、C、D的群聊，导致A、B的通话断开，且收不到来自C的群聊邀请，用户D可以收到多人通话邀请，并可成功加入多人通话。
请WF的朋友修复
来自TFD 产品 Charlie

**Comment by imndx** [comment]
fix

**Comment by Charlie191011** [comment]
已修复，关闭
