### ISSUE TITLE
新的proto Android 的 getConversation 返回空

### ISSUE THREAD

**Issue by hihxh** [wildfirechat/android-chat#292]
只有聊过天的getConversation才能正常返回ConversationInfo，从通讯录进去发消息没有聊过天的ConversationInfo都是null

**Comment by imndx** [comment]
现在是的。参考```NullUserInfo```，返回一个```NullConversationInfo```是否能满足需求呢？

**Comment by hihxh** [comment]
这个不太合理吧，用户如果只是单纯的想看对方详情，但是本地没有聊天记录就无法查看。还是希望能向以前一样正常返回ConversationInfo

**Comment by imndx** [comment]
看对方详情，和会话没关系，详情是在UserInfo里面。

可能我不太理解你的问题

**Comment by hihxh** [comment]
就是会话详情，操作消息免打扰和置顶聊天的界面。如果双方没有聊天记录，就获取不到。
