### ISSUE TITLE
多人音频通话，语音连接显示正常状态下，可能会出现没有声音的情况

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/android-chat#293]
人多语音群聊中（有安卓也有ios加入），某个手机没有声音，听不见别人，别人也听不见他。但是连接页面显示正常，计时正常。（出现问题的设备不是固定某个设备）
该问题安卓和iOS都出现过（非必现）

**Comment by Charlie191011** [comment]
@imndx @heavyrain2012 请问你们是否能复现，并定位修复？

**Comment by imndx** [comment]
这个问题目前应当解决了，请用最新版测试。
