### ISSUE TITLE
已读，未读状态更新不及时问题

### ISSUE THREAD

**Issue by 343661629** [wildfirechat/android-chat#298]
在调用ChatManager中的updateMessage方法来修改message的status，通过调用boolean result = mClient.updateMessageStatus(messageId, status.ordinal()); 方法发现，最后一条消息的状态更新不及时，比如，有两条消息，第一条状态更改过来了，第二天没改过来。依次类推，最后一条消息，更新不及时

**Comment by imndx** [comment]
已解决，请将代码更新到最新测试。
