### ISSUE TITLE
A对B发起视频通话，A黑屏卡死。A对B发起语音通话，B点接听没反应

### ISSUE THREAD

**Issue by zhanshen1373** [wildfirechat/android-chat#300]
视频通话 感觉是这段代码的问题
gEngineKit.getCurrentSession().startPreview()
移动端是最新的代码

**Comment by imndx** [comment]
你好，请用我们最新代码（什么也不改）测试，确认一下，我本地无法复现。

如果问题依然存在的话，请给我们提供完整日志。

```adb logcat > log.txt```抓取全部日志。

**Comment by zhanshen1373** [comment]
> 你好，请用我们最新代码（什么也不改）测试，确认一下，我本地无法复现。
> 
> 如果问题依然存在的话，请给我们提供完整日志。
> 
> `adb logcat > log.txt`抓取全部日志。

03-17 10:40:25.097 E/AndroidRuntime(19895): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/webrtc/audio/JavaAudioDeviceModule$AudioRecordErrorCallback;
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at cn.wildfirechat.avenginekit.AVEngineKit.b()
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at cn.wildfirechat.avenginekit.AVEngineKit.g()
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at cn.wildfirechat.avenginekit.AVEngineKit$CallSession.startPreview()
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at cn.wildfire.chat.kit.voip.SingleVideoFragment.init(SingleVideoFragment.java:327)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at cn.wildfire.chat.kit.voip.SingleVideoFragment.onCreateView(SingleVideoFragment.java:85)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2693)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1361)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1668)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1748)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1812)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:446)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2598)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2386)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2341)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2244)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3122)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at cn.wildfire.chat.kit.voip.SingleCallActivity.onStart(SingleCallActivity.java:86)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at android.app.Activity.performStart(Activity.java:6683)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at android.os.Handler.dispatchMessage(Handler.java:110)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at android.os.Looper.loop(Looper.java:203)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at android.app.ActivityThread.main(ActivityThread.java:6247)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at java.lang.reflect.Method.invoke(Native Method)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
03-17 10:40:25.097 E/AndroidRuntime(19895): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
03-17 10:40:25.097 E/AndroidRuntime(19895): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.webrtc.audio.JavaAudioDeviceModule$AudioRecordErrorCallback" on path: DexPathList[[zip file

**Comment by imndx** [comment]
你好，你们项目里面```webrtc```版本太低了。
请更新到：```    implementation 'org.webrtc:google-webrtc:1.0.30039' ```

**Comment by DoNotLookAtMe** [comment]
小米4LTE 在没有给允许悬浮窗权限的时候会黑屏卡死。

**Comment by android-xiao-jun** [comment]
![image](https://user-images.githubusercontent.com/39174748/93552347-d9a97100-f9a2-11ea-8b9f-5f156d2faf07.png)
@DoNotLookAtMe 我这个是这么解决的，悬浮窗获取失败，黑屏卡死了
