### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by yndjl** [wildfirechat/android-chat#301]
突然就出现了以上这个错误。日志如下。请帮忙分析下。谢谢啦
[main.log](https://github.com/wildfirechat/android-chat/files/4341098/main.log)
[marsserviver.log](https://github.com/wildfirechat/android-chat/files/4341099/marsserviver.log)

**Comment by imndx** [comment]
你好，这看起来是域名解析的问题，和我们可能没什么关系。
