### ISSUE TITLE
无力吐槽。你们都不用写注释的吗？

### ISSUE THREAD

**Issue by lianyagang** [wildfirechat/android-chat#306]
DEMO级别也好歹注释下吧？这样怎么二次开发~~大兄弟

**Comment by wrz123456** [comment]
想拿UI进行二次开发，当时进去代码一坨一坨 我就懵了

**Comment by imndx** [comment]
```ChatManager```那个类，会添加一些注释。

**Comment by lianyagang** [comment]
> `ChatManager`那个类，会添加一些注释。

我觉得，你们是不是出一个api的文档。讲真的。要二次开发，直接拿你们demo。太难了。ChatManager这类的注释，完全也不够啊。。。

**Comment by imndx** [comment]
嗯嗯，我们会不断完善文档、注释等，让大家二次开发的体验更好。

**Comment by wrz123456** [comment]
哈哈哈，我是想拆UI过来的..
主要是Kit注释比较少 看代码有点痛苦..

**Comment by imndx** [comment]
> 哈哈哈，我是想拆UI过来的..
> 主要是Kit注释比较少 看代码有点痛苦..

我们代码的命名等，一般都挺通俗易懂，看到函数名，大体能猜到这个函数是干什么的。当然了，我们会不断完善注释、文档的。
