### ISSUE TITLE
在小米手机上，将app退到后台，一段时间后，其他手机给该小米手机发消息，小米手机收不到消息；

### ISSUE THREAD

**Issue by MaTengFei1990** [wildfirechat/android-chat#307]
在小米手机上，将app退到后台，一段时间后，其他手机给该小米手机发消息，小米手机收不到消息；

**Comment by imndx** [comment]
你好，我们已经对接了小米推送，如果采用第三方推送的话，需要自行对接。请参考```PushService```类和```ChatManager.setDeviceToken```
