### ISSUE TITLE
第一次拿userinfo 无法获取

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#31]
只能获取到 如下{"displayName":"","gender":0,"name":"\u003cBqCLBLuu\u003e","type":0,"uid":"BqCLBLuu","updateDt":0}

**Comment by yuzhongrong** [comment]
我要的数据结果是  {"company":"","displayName":"余撒时候回来","email":"","extra":"","friendAlias":"","gender":0,"groupAlias":"","mobile":"1EFdLFDPSW29VKDYspzwVrYyFWeyJ6pnBZ","name":"1EFdLFDPSW29VKDYspzwVrYyFWeyJ6pnBZ","portrait":"","social":"","type":0,"uid":"N5OHNHhh","updateDt":1560015928016}

**Comment by yuzhongrong** [comment]
为什么需要获取2次  第二次进入新的朋友 就可以获取

**Comment by imndx** [comment]
第一次获取的时候，如果本地没有对应的用户信息，会返回```NullUserInfo```，然后从服务器拉取，拉取成功之后，会有通知。

**Comment by yuzhongrong** [comment]
好的谢谢 我知道了
