### ISSUE TITLE
关于聊天记录的清空与拉取的问题

### ISSUE THREAD

**Issue by yndjl** [wildfirechat/android-chat#310]
在demo上发现，清空了聊天记录。重新打开回话，聊天记录又会被重新拉取。是因为在打开回话时，执行了下面的拉取操作：
`ChatManager.Instance().getRemoteMessages(conversation, fromMessageUid, count, new GetRemoteMessageCallback() {
//                    @Override
//                    public void onSuccess(List<Message> messages) {
//                        if (messages != null && !messages.isEmpty()) {
//                            List<UiMessage> msgs = new ArrayList<>();
//                            for (Message msg : messages) {
//                                msgs.add(new UiMessage(msg));
//                            }
//                            result.postValue(msgs);
//                        } else {
//                            result.postValue(new ArrayList<UiMessage>());
//                        }
//                    }
//
//                    @Override
//                    public void onFail(int errorCode) {
//                        result.postValue(new ArrayList<UiMessage>());
//                    }
//                });`

我看到在[#287](https://github.com/wildfirechat/android-chat/issues/287#issue-575110111)中给出以下建议。

> 是否开启拉取远程历史消息

> message.remote_history_message 0

这个开关设置，是在server端进行的配置吗？
如果在服务端将这个关闭了的话，会影响在客户端增加手动拉取聊天记录的功能吗？
如果会产生影响的话，那么感觉只需要将进行远程历史消息的请求注释就OK了吧

**Comment by imndx** [comment]
你好，关闭了远程历史消息，就不能手动拉取远程的历史消息了。

你可以修改一下界面拉取历史消息的逻辑，首次进入的时候，不拉取历史消息；仅当，用户手动触发的时候，才拉取。
