### ISSUE TITLE
群聊语音通话时，静音按钮无效。

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/android-chat#313]
群聊语音通话时，用户第一次点击静音按钮后，静音按钮界面高亮（正常），但是没有静音生效，对方依然可以听见。
用户再次点击静音按钮，按钮UI恢复初始状态（正常），但此时静音依然没有生效。
多次点击静音按钮，没有生效

**Comment by heavyrain2012** [comment]
这个问题是因为muteAudio接口的含义发生了变化，请你们研发同事看一下demo上是怎么使用的，具体好像是设置完后再获取一下状态

**Comment by imndx** [comment]
已解决，请更新到最新代码测试。

**Comment by heavyrain2012** [comment]
客户反应，问题还存在

**Comment by imndx** [comment]
目前，demo上无法复现，先把issue关了，如果还有问题的话，请先在demo上测试一下，然后新提一个issue。
