### ISSUE TITLE
语音通话，关闭扬声器时触发防误触模式，防误触模式释放后，系统自动打开了扬声器

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/android-chat#315]
安卓客户端默认语音打通时是扬声器打开的，手动关闭后，通过手机距离传感器触发通话的防误触模式（接电话时贴脸防误触），然后释放防误触模式，此时扬声器的状态依然是关闭的，但是实际效果却是扬声器外放。

**Comment by imndx** [comment]
已解决，请更新到最新代码测试。
