### ISSUE TITLE
发送自定义消息 errorCode = -100001

### ISSUE THREAD

**Issue by geguol** [wildfirechat/android-chat#317]
这个错误码是什么意思，这个不是服务端返回的

**Comment by imndx** [comment]
这个问题需要日志分析一下，请提供完整日志。

**Comment by geguol** [comment]
> 这个问题需要日志分析一下，请提供完整日志。

https://gist.github.com/bd50468af42ac715c0201985f55d2314

**Comment by geguol** [comment]
> 这个问题需要日志分析一下，请提供完整日志。
https://gist.github.com/bd50468af42ac715c0201985f55d2314
请问这个日志可以看是什么问题吗

**Comment by imndx** [comment]
没有这个错误码呀，是-1001 吗？

另外，日志只有协议栈的，需要全部的。
[日志抓取](http://docs.wildfirechat.cn/faq/android/q3.html)

**Comment by imndx** [comment]
no response
