### ISSUE TITLE
如果获取，当前用户的所有聊天记录

### ISSUE THREAD

**Issue by lianyagang** [wildfirechat/android-chat#318]
ChatManager.Instance()
                    .getMessagesEx2(listOf(Conversation.ConversationType.Single), listOf(0),
                            MessageStatus.All, key, true, 10, null) 
这个API。获取的是本地的所有聊天数据。如果获取远程的所有会话的聊天记录

**Comment by imndx** [comment]
```  public List<Message> getMessages(Conversation conversation, long fromIndex, boolean before, int count, String withUser) {```

用上面这个接口可以获取某一个用户/会话的消息。

由于Android IPC限制，不能一次全部获取，可以分批获取

**Comment by lianyagang** [comment]
> ` public List<Message> getMessages(Conversation conversation, long fromIndex, boolean before, int count, String withUser) {`
> 
> 用上面这个接口可以获取某一个用户/会话的消息。
> 
> 由于Android IPC限制，不能一次全部获取，可以分批获取

可是如果分批获取，怎么保证顺序？

**Comment by imndx** [comment]
> > ` public List<Message> getMessages(Conversation conversation, long fromIndex, boolean before, int count, String withUser) {`
> > 用上面这个接口可以获取某一个用户/会话的消息。
> > 由于Android IPC限制，不能一次全部获取，可以分批获取
> 
> 可是如果分批获取，怎么保证顺序？

通过fromIndex保证，每次fromIndex都传当前已有消息的中，最旧的一条的```messageId```

**Comment by lianyagang** [comment]
我的意思是，我想分页获取，当前用户，跟所有人对话的在线聊天记录。根据先后，进行排序。
例如客服聊天的模式，有ABC 三个客服，用户每次进入聊天页面，可以在页面看到ABC三个客户跟自己的会话记录

**Comment by imndx** [comment]
```   
 public List<Message> getMessagesEx(List<Conversation.ConversationType> conversationTypes, List<Integer> lines, List<Integer> contentTypes, long fromIndex, boolean before, int count, String withUser) 
```
或者
```
 public List<Message> getMessagesEx2(List<Conversation.ConversationType> conversationTypes, List<Integer> lines, MessageStatus messageStatus, long fromIndex, boolean before, int count, String withUser) 

```


你好，这两个个方法应当能部分满足需求，但只能获取本地的，远程历史历史消息没法获取。
