### ISSUE TITLE
发送消息时返回错误码247，一直被禁言，代码中并未调用禁言代码。

### ISSUE THREAD

**Issue by 568571931** [wildfirechat/android-chat#319]

**Comment by 568571931** [comment]
单对单发消息

**Comment by 568571931** [comment]
![image](https://user-images.githubusercontent.com/16234520/78144108-c1c84a00-7461-11ea-8002-6eb61201cb35.png)
![image](https://user-images.githubusercontent.com/16234520/78144164-d4428380-7461-11ea-8193-65587e6bdcbf.png)
能收到别人发送对消息，自己却发不出去

**Comment by imndx** [comment]
是不是后台操作把该用用禁言了？可以看下数据库里面，用户状态是不是1或者2？

**Comment by 568571931** [comment]
收到，很感谢您的回答



---原始邮件---
发件人: "imndx"<notifications@github.com&gt;
发送时间: 2020年4月2日(周四) 下午3:12
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com&gt;;
抄送: "BlueKevin"<568571931@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wildfirechat/android-chat] 发送消息时返回错误码247，一直被禁言，代码中并未调用禁言代码。 (#319)




 
是不是后台操作把该用用禁言了？可以看下数据库里面，用户状态是不是1或者2？
