### ISSUE TITLE
大概十分钟左右没有在聊天室发送消息，会出现发送消息显示感叹号的情况，重进聊天室才行。请问这个该怎么解决？

### ISSUE THREAD

**Issue by aibfive** [wildfirechat/android-chat#32]

**Comment by imndx** [comment]
目前，长时间不活动，会自动退出聊天室。
稍后，会加入相关配置项，让可设置多久不活跃，自动退出

**Comment by aibfive** [comment]
谢谢了!!!

**Comment by aibfive** [comment]
> 目前，长时间不活动，会自动退出聊天室。
> 稍后，会加入相关配置项，让可设置多久不活跃，自动退出

谢谢！！！

**Comment by aibfive** [comment]
谢谢!!!


------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 中午1:08
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "小五"<1456574276@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 大概十分钟左右没有在聊天室发送消息，会出现发送消息显示感叹号的情况，重进聊天室才行。请问这个该怎么解决？ (#32)




目前，长时间不活动，会自动退出聊天室。
 稍后，会加入相关配置项，让可设置多久不活跃，自动退出
