### ISSUE TITLE
同个账号无法支持多把android手机登录！！！

### ISSUE THREAD

**Issue by gnmmdk** [wildfirechat/android-chat#323]
公司的项目接入了im的代碼，单设备可以正常发送，但是同个账号在两把android手机登录，会有一方一直断开连接的情况。 我在下方打印了日志
![image](https://user-images.githubusercontent.com/18391426/78231444-6354a780-7505-11ea-9071-6d330cab98b0.png)

一台可以正常连接，打印的日志如下：
2020-04-02 16:56:03.398 31286-31349/com.xxx.xxxx: Im connectionStatus=2
2020-04-02 16:56:03.436 31286-31349/com.xxx.xxxx: Im connectionStatus=1

一台无法连接，打印的日志如下：
...
2020-04-02 17:02:31.508 8983-8998/com.xxx.xxxx: Im connectionStatus=-1
2020-04-02 17:02:31.509 8983-8998/com.xxx.xxxx: Im connectionStatus=-6
2020-04-02 17:02:46.489 8983-8998/ com.xxx.xxxx：Im connectionStatus=0
2020-04-02 17:02:46.593 8983-8998/com.xxx.xxxx: Im connectionStatus=-1
2020-04-02 17:02:46.666 8983-8998/com.xxx.xxxx: Im connectionStatus=-6
2020-04-02 17:02:46.691 8983-8998/com.xxx.xxxx: Im connectionStatus=0
2020-04-02 17:02:46.812 8983-8998/com.xxx.xxxx: Im connectionStatus=-1

android的demo是只能登录一个账号，公司的ios同事可以进行多端操作。android这里需要做什么配置吗？

**Comment by imndx** [comment]
看下server的配置，有个多端支持的，需要打开，才能同一个账号，多个设备登录

**Comment by gnmmdk** [comment]
> 看下server的配置，有个多端支持的，需要打开，才能同一个账号，多个设备登录

多端是指多台android设备？还是一端android手机，一端ios，一端web?

**Comment by imndx** [comment]
> > 看下server的配置，有个多端支持的，需要打开，才能同一个账号，多个设备登录
> 
> 多端是指多台android设备？还是一端android手机，一端ios，一端web?

多台手机

**Comment by gnmmdk** [comment]
> > > 看下server的配置，有个多端支持的，需要打开，才能同一个账号，多个设备登录
> > 
> > 
> > 多端是指多台android设备？还是一端android手机，一端ios，一端web?
> 
> 多台手机

服務器是由配置你說的這個，ios可以多台，android就不行。

**Comment by imndx** [comment]
你好，获取token的时候，需要一个clientId，这个clientId，你们怎么来的？

**Comment by lianyagang** [comment]
> 你好，获取token的时候，需要一个clientId，这个clientId，你们怎么来的？
> 
> clientId用来标识设备，每个设备都不应当相同，我们提供了`ChatManager.getClientId`。

两台android设备，使用同一个账号登录，可以确定ChatManager.getClientId是不同的，但是，就是无法多设备同时在线，一台在线，另外一台啥消息都收不到了。服务端也配置了server.multi_endpoint true。完全搞不懂你们SDK了

**Comment by lianyagang** [comment]
另外，提个建议。能不能把client这个封装包里面的文档补全下？好歹出个Doc，开发者可以参考使用api吧。

**Comment by imndx** [comment]
你好，请提供Android端的全日志(```adb logcat > log```)，和对应的服务端日志(wildfirechat.log)，我们分析一下。

**Comment by imndx** [comment]
> 另外，提个建议。能不能把client这个封装包里面的文档补全下？好歹出个Doc，开发者可以参考使用api吧。

谢谢，我们正在完善文档和注释。

**Comment by imndx** [comment]
no response.

**Comment by gnmmdk** [comment]
> no response.

能否提供下邮箱

**Comment by imndx** [comment]
这儿你可以就直接付上文件的。

![image](https://user-images.githubusercontent.com/34434072/78620981-044fb380-78b4-11ea-9253-163bfccfc87c.png)

**Comment by gnmmdk** [comment]
服务端的问题，已经可以双端了，还是感谢您的解答。
