### ISSUE TITLE
消息漫游getRemoteMessages获取到的消息列表一直是空的。

### ISSUE THREAD

**Issue by KookCaptain** [wildfirechat/android-chat#324]
使用自己的服务器，使用getRemoteMessages方法获取远程漫游消息返回列表一直是空的，下载的野火demo一样是卸载重装之后历史消息就没了，但是使用demo原服务器域名，就可以获取到历史消息。可能会是什么问题呢？

**Comment by imndx** [comment]
请确认服务端打开了相关开关。
```
##首次登录，是否接收之前的历史消息。0 不接收；1接收。
message.roaming 0

##是否开启拉取远程历史消息
message.remote_history_message 0

```

**Comment by KookCaptain** [comment]
非常感谢，就是这个原因，问题解决了，再次感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"imndx"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 上午9:44
收件人:&nbsp;"wildfirechat/android-chat"<android-chat@noreply.github.com&gt;;
抄送:&nbsp;"张瑶"<zy1020399904@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wildfirechat/android-chat] 消息漫游getRemoteMessages获取到的消息列表一直是空的。 (#324)





 
请确认服务端打开了相关开关。
 ##首次登录，是否接收之前的历史消息。0 不接收；1接收。 message.roaming 0 ##是否开启拉取远程历史消息 message.remote_history_message 0
