### ISSUE TITLE
我用安卓手机发送消息的时候，返回  发送消息失败 -500

### ISSUE THREAD

**Issue by w3336713** [wildfirechat/android-chat#325]
你好，我们这边使用Demo部署了以后，这边安卓机发送消息会出现个问题，频率非常高。

发送消息失败  500

并且你们文档上也没有说明这个错误代码，还请帮忙看一下。

**Comment by imndx** [comment]
你好，我们没有遇到过这个错误，请提供一下手机端的全量日志。

```adb logcat > wfc.log```

**Comment by w3336713** [comment]
不好意思，我打错了，发送消息的时候，一直转圈，然后就提示 发送消息失败 -500.
![QQ图片20200404115330](https://user-images.githubusercontent.com/13687058/78418035-03781100-766b-11ea-88c1-aeb0bfc97d77.jpg)

**Comment by w3336713** [comment]
并且这个出现的频率还是蛮高的。特别是在安卓端。

**Comment by imndx** [comment]
你好，我们没有见过这个错误，需要日志才能分析。

**Comment by w3336713** [comment]
你好，我们在12:26:23的时候又复现了这个情况，下面是全部的log日志，请帮忙解决。
[new 5.txt](https://github.com/wildfirechat/android-chat/files/4430741/new.5.txt)

**Comment by imndx** [comment]
你好，服务端返了500，请把im server下面的日志也给我们一下.
```logs/wildfirechat.log```

**Comment by w3336713** [comment]
[12.26.24_log.txt](https://github.com/wildfirechat/android-chat/files/4430826/12.26.24_log.txt)

**Comment by imndx** [comment]
> [12.26.24_log.txt](https://github.com/wildfirechat/android-chat/files/4430826/12.26.24_log.txt)

这个日志不完整，请你把: wildfirechat.log 和 http.log都附上吧。

**Comment by w3336713** [comment]
[http.log](https://github.com/wildfirechat/android-chat/files/4430846/http.log)
[wildfirechat.log](https://github.com/wildfirechat/android-chat/files/4430847/wildfirechat.log)

**Comment by imndx** [comment]
你好 ，你们服务器是部署到香港的？
大陆到香港的网络不通畅 。

**Comment by w3336713** [comment]
我们在排查的时候，发现这个-500不是来自于服务器，而是这个CallBack里面，请问一下，这里的 -500 是什么意思，代表什么地方有问题。？

![QQ图片20200404171651](https://user-images.githubusercontent.com/13687058/78423330-2967da80-7698-11ea-8734-87f998b0582d.png)

**Comment by imndx** [comment]
是网络超时，报的-500。

**Comment by imndx** [comment]
可参考这边[文章](https://mp.weixin.qq.com/s/6PSOwmsDMvZPGcVLfpyY4g)

**Comment by w3336713** [comment]
我们在排查日志的时候，发现，每次客户端报-500错误的时候，服务器日志 会有 xxx  no active的日志，xxx 是我们这边发送的目标人。也就是说，当我发送给a消息的时候，如果会出现-500的错误，那么a在日志上必然是 no active。

**Comment by imndx** [comment]
no response.
