### ISSUE TITLE
第三方拍照视频修改视频质量上传失败

### ISSUE THREAD

**Issue by zhanshen1373** [wildfirechat/android-chat#326]
第三方拍照视频把 mJCameraView.setMediaQuality(JCameraView.MEDIA_QUALITY_HIGH);
设置成这样后，上传不成功。返回errorCode是-1

**Comment by imndx** [comment]
-1，一般是 密钥错误，修改是视频质量一般不会导致这个问题。

请提供一下相关日志。

**Comment by zhanshen1373** [comment]
> -1，一般是 密钥错误，修改是视频质量一般不会导致这个问题。
> 
> 请提供一下相关日志。

公司的网有毒，没事了。关了吧
