### ISSUE TITLE
用户退出群组后,群内有消息时,又出现该会话

### ISSUE THREAD

**Issue by 11bq** [wildfirechat/android-chat#328]
如图,群成员1退出群聊后,,群成员1的会话列表无此会话,群内其他成员也收到该成员退群的通知,但是在群组信息内,群成员还是有该成员,当群内发消息时,群成员1的会话列表又出现该会话,同时也可以发信息,退群使用的GroupViewModel内的quitGroup方法,MessageContent传与不传效果一致

![device-2020-04-07-195420](https://user-images.githubusercontent.com/18617152/78666831-87035d80-790a-11ea-9e77-ffe87126fe05.png)
![device-2020-04-07-195808](https://user-images.githubusercontent.com/18617152/78666848-8d91d500-790a-11ea-8c87-5821829c5aae.png)
![device-2020-04-07-195622](https://user-images.githubusercontent.com/18617152/78666860-9387b600-790a-11ea-9414-dc3300462de8.png)
![QQ截图20200407200225](https://user-images.githubusercontent.com/18617152/78667003-c8940880-790a-11ea-83ca-47eb52c2b637.png)

**Comment by 11bq** [comment]
代码使用的是3月6日拉取得代码,只更换了服务器ip,其他代码未更改

**Comment by imndx** [comment]
你好，我用demo测试了，没有复现该问题。建议见移动端和服务端代码都升级到最新进行测试。
