### ISSUE TITLE
媒体服务的/fs请求是有做封装吗

### ISSUE THREAD

**Issue by 512DIDIDI** [wildfirechat/android-chat#329]
请问android端到server端的api是有做了封装吗，可以增加server api或者修改吗？谢谢

**Comment by imndx** [comment]
你好，内置文件存储不支持server api。

第三方存储的话，都有api的，可以参考具体的。
我们的[专业存储](https://github.com/wildfirechat/WF-minio)，也是支持的

**Comment by 512DIDIDI** [comment]
> 你好，内置文件存储不支持server api。
> 
> 第三方存储的话，都有api的，可以参考具体的。
> 我们的[专业存储](https://github.com/wildfirechat/WF-minio)，也是支持的

不好意思没有描述清楚，我的意思是我现在想把文件存储改成minio(我知道专业版有直接走minio服务器不走im服务的库，但现在需求想要文件上传依然通过im服务)，所以改成了依然走server端的GetQiniuUploadTokenHandler方法，但服务端上传文件默认走/fs的UploadFileAction，请问这个Action可以拓展吗，或者可以自定义server api吗，例如我想把/fs改成/media的请求。谢谢

**Comment by 512DIDIDI** [comment]
现在我的实现方式是暴力修改了UploadFileAction类里的方法，把文件在这里上传到minio服务器中，然后修改了GetQiniuUploadTokenHandler里的domain地址，但这样代码完整度被破坏，希望可以拓展Action，增加例如/media的请求

**Comment by imndx** [comment]
媒体上传，可以完全是应用层控制的，不用走IM Server，移动端应用层直接往存储服务传。

**Comment by 512DIDIDI** [comment]
请问现在七牛上传文件也是直接通过移动端上传吗？server端只是保留了七牛的token吗？

**Comment by imndx** [comment]
> 请问现在七牛上传文件也是直接通过移动端上传吗？server端只是保留了七牛的token吗？

嗯嗯，是的，是在协议栈里面，不经过im server的。

你们可以不同协议栈，直接在上层处理上传逻辑。

**Comment by 512DIDIDI** [comment]
好的 谢谢解答 打扰您了！
