### ISSUE TITLE
断网模式下，在聊天页面发送图片或者语音的bug

### ISSUE THREAD

**Issue by gnmmdk** [wildfirechat/android-chat#331]
断网模式下，在聊天页面发送图片/语音/视频，收到失败的的状态。
   @Override
                public void onFailure(final int errorCode) throws RemoteException {
                    msg.status = MessageStatus.Send_Failure;
                    ...省略的代码...
                }

重新进入后，获取该条消息的状态还是Sending状态。
文本消息正常，消息的状态是Send_Failure状态。

**Comment by heavyrain2012** [comment]
问题已经确认，我们会尽快修复，谢谢反馈

**Comment by heavyrain2012** [comment]
已修复，请用最新版本验证

**Comment by gnmmdk** [comment]
> 已修复，请用最新版本验证

master拉取的代码最新是

> 已修复，请用最新版本验证

在最新版本验证，飞行模式下发送了图片/文字/语音/，发送失败后，退出页面再进来，发送失败的消息会丢失。
