### ISSUE TITLE
消息收发延时高[bug]

### ISSUE THREAD

**Issue by hyl87** [wildfirechat/android-chat#332]
server version 0.39
android sdk 最新版本
在消息收发延时高时,发送方只发了一条消息,收消息方会收到两条内容一样的消息

**Comment by heavyrain2012** [comment]
请确认当时的服务器状况1，cpu利用率。2，带宽利用率。
另外请确认两条消息的UID是不是一样的

**Comment by imndx** [comment]
no response.
