### ISSUE TITLE
删除未读信息有bug

### ISSUE THREAD

**Issue by lianyagang** [wildfirechat/android-chat#333]
删除未读信息，回调两个地方onConversationUnreadStatusClear、onConversationRemove
之后，会触发重新获取聊天列表数据的api。发现IM还是会返回之前删除的那条数据，只是lastMessage是空。但是如果强制第三次刷新。就不会返回之前删除的那条数据

**Comment by lianyagang** [comment]
急！！！

**Comment by imndx** [comment]
是删除会话，还是删除消息？

**Comment by lianyagang** [comment]
长按会话列表的item--》弹窗、删除会话

**Comment by lianyagang** [comment]
> 是删除会话，还是删除消息？

长按会话列表的item---》弹窗----》删除会话

**Comment by imndx** [comment]
你好 ，最新代码已经修复，请更新到最新代码测试
