### ISSUE TITLE
有没有混淆规则啊

### ISSUE THREAD

**Issue by hyl87** [wildfirechat/android-chat#335]
混淆了报异常
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mars.proto.ProtoLogic.registerMessageFlag(int, int) (tried Java_com_tencent_mars_proto_ProtoLogic_registerMessageFlag and Java_com_tencent_mars_proto_ProtoLogic_registerMessageFlag__II)

但是并没有混淆native的方法

**Comment by imndx** [comment]
```com.tencent.mars```下面的不能混淆。
```cn.wildfirechat.client```下面的也不能混淆。

**Comment by hyl87** [comment]
好的

**Comment by winniexuwen** [comment]
添加了不能混淆，还是报同一个错误

**Comment by wanshijie3** [comment]
此问题仍然存在,和混淆无关,在我手中的一款红米机型中是概率出现,非必现,是否和进程有关?

**Comment by imndx** [comment]
#545
