### ISSUE TITLE
聊天页面发送多张图片，发送成功后，退出重进，发送的图片只剩最后一张

### ISSUE THREAD

**Issue by gnmmdk** [wildfirechat/android-chat#336]
如题

**Comment by imndx** [comment]
最新的demo上，无法复现。
请问你们代码是最新的吗？

**Comment by gnmmdk** [comment]
> 最新的demo上，无法复现。
> 请问你们代码是最新的吗？

master上只能拉取到4月9号的代码。
但是我看你们提交的是三天前，也就是14号左右。
![image](https://user-images.githubusercontent.com/18391426/79535754-f0286500-80b0-11ea-831b-3cd8a9c707c1.png)
为啥拉取不到最新的代码？

**Comment by gnmmdk** [comment]
> 最新的demo上，无法复现。
> 请问你们代码是最新的吗？

拉取了最新的代码，还是"发送的图片只剩最后一张"

**Comment by imndx** [comment]
你好，请问下，demo上如何复现？

另外，最新代码，我加了些日志，请你更新，然后这样试一下：
1. 发送一条文本消息
2. 发送多张图片
3. 发送成功之后，退出重进。
4. 确认下现在看到的是什么？就最后一张图片，还是什么？

**Comment by gnmmdk** [comment]
> 你好，请问下，demo上如何复现？
> 
> 另外，最新代码，我加了些日志，请你更新，然后这样试一下：
> 
> 1. 发送一条文本消息
> 2. 发送多张图片
> 3. 发送成功之后，退出重进。
> 4. 确认下现在看到的是什么？就最后一张图片，还是什么？

好的，下午在忙，晚点忙忘了我试下，并回复你哈。

**Comment by gnmmdk** [comment]
> > 你好，请问下，demo上如何复现？
> > 另外，最新代码，我加了些日志，请你更新，然后这样试一下：
> > 
> > 1. 发送一条文本消息
> > 2. 发送多张图片
> > 3. 发送成功之后，退出重进。
> > 4. 确认下现在看到的是什么？就最后一张图片，还是什么？
拉取最新代码按照你上面说的流程，发送成功后退出重新，还是剩下最后一张照片,

**Comment by gnmmdk** [comment]
> 你好，请问下，demo上如何复现？
> 
> 另外，最新代码，我加了些日志，请你更新，然后这样试一下：
> 
> 1. 发送一条文本消息
> 2. 发送多张图片
> 3. 发送成功之后，退出重进。
> 4. 确认下现在看到的是什么？就最后一张图片，还是什么？

用最新的代码，按照你说的上面的步骤，还是只能最后一张照片，应该是mars-core-release库的问题，我将mars-core库回滚到4月2号之前，没有出现丢照片的情况。但是4月2号之前mars-core再无网络的情况下发送图片，等待图片发送失败（出现红色感叹号），退出重进应该图片出现了继续上传的图标，应该是发送失败的图标才对。

**Comment by gnmmdk** [comment]
> 你好，请问下，demo上如何复现？
> 
> 另外，最新代码，我加了些日志，请你更新，然后这样试一下：
> 
> 1. 发送一条文本消息
> 2. 发送多张图片
> 3. 发送成功之后，退出重进。
> 4. 确认下现在看到的是什么？就最后一张图片，还是什么？

用最新的代码，按照你说的上面的步骤，还是只能最后一张照片，应该是mars-core-release库的问题，我将mars-core库回滚到4月2号之前，没有出现丢照片的情况。但是4月2号之前mars-core再无网络的情况下发送图片，等待图片发送失败（出现红色感叹号），退出重进图片出现了继续上传的图标，应该是发送失败的图标才对。

**Comment by imndx** [comment]
请你在我们demo上测试一下，告诉我们复现路径。

**Comment by gnmmdk** [comment]
> 请你在我们demo上测试一下，告诉我们复现路径。

“用最新的代码，按照你说的上面的步骤，还是只能最后一张照片”，这个就是在野火的demo上运行的。复现路径？聊天界面一发送多张图片就会有丢照片的情况。你是什么手机测试的？

**Comment by imndx** [comment]
> > 请你在我们demo上测试一下，告诉我们复现路径。
> 
> “用最新的代码，按照你说的上面的步骤，还是只能最后一张照片”，这个就是在野火的demo上运行的。复现路径？聊天界面一发送多张图片就会有丢照片的情况。你是什么手机测试的？

我在小米8、模拟器上测试，都没有出现

**Comment by gnmmdk** [comment]
> > > 请你在我们demo上测试一下，告诉我们复现路径。
> > 
> > 
> > “用最新的代码，按照你说的上面的步骤，还是只能最后一张照片”，这个就是在野火的demo上运行的。复现路径？聊天界面一发送多张图片就会有丢照片的情况。你是什么手机测试的？
> 
> 我在小米8、模拟器上测试，都没有出现

345498912 加下我qq聊一聊?

**Comment by gnmmdk** [comment]
> > > 请你在我们demo上测试一下，告诉我们复现路径。
> > 
> > 
> > “用最新的代码，按照你说的上面的步骤，还是只能最后一张照片”，这个就是在野火的demo上运行的。复现路径？聊天界面一发送多张图片就会有丢照片的情况。你是什么手机测试的？
> 
> 我在小米8、模拟器上测试，都没有出现


> > > 请你在我们demo上测试一下，告诉我们复现路径。
> > 
> > 
> > “用最新的代码，按照你说的上面的步骤，还是只能最后一张照片”，这个就是在野火的demo上运行的。复现路径？聊天界面一发送多张图片就会有丢照片的情况。你是什么手机测试的？
> 
> 我在小米8、模拟器上测试，都没有出现

我这边用华为p30pro，和三星的G9600手机，可以发下你的安装包给我吗？我这边安装测试下？

**Comment by imndx** [comment]
> 345498912

你微信加:wfchat吧,加不了你QQ
