### ISSUE TITLE
userinfo中的 type属性 始终等于0

### ISSUE THREAD

**Issue by hyl87** [wildfirechat/android-chat#337]
userinfo中的 type属性 始终等于0

**Comment by heavyrain2012** [comment]
不明白您遇到的问题，请补充操作步骤，现象和期望结果

**Comment by hyl87** [comment]
大概就是 后台创建了一个系统账号，对userinfo 的type设值100，但是 android 这边 获取到的type 一直是0， ios 是正确的

**Comment by imndx** [comment]
Android端，卸载重装，type会变为100吗？

**Comment by hyl87** [comment]
@imndx  卸载重装 也是0
