### ISSUE TITLE
bugly 收集到了如下的异常；

### ISSUE THREAD

**Issue by MaTengFei1990** [wildfirechat/android-chat#339]
#00 pc 000f6734 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
--
2 #01 pc 000f6723 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
3 #02 pc 000dce99 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
4 #03 pc 000d864d /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
5 #04 pc 0010da53 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
6 #05 pc 00109f13 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
7 #06 pc 0010d4fb /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
8 #07 pc 000ff1d1 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
9 #08 pc 000fa0df /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
10 #09 pc 000da5e9 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
11 #10 pc 000d9b99 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
12 #11 pc 000d9507 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
13 #12 pc 000b3d2b /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
14 #13 pc 000b583f /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
15 #14 pc 000a0c09 /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so [armeabi-v7a]
16 #15 pc 000ad13d /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/lib/arm/libmarsstn.so (Java_com_tencent_mars_proto_ProtoLogic_setAuthInfo+264) [armeabi-v7a]
17 #16 pc 0244bd1d /data/app/com.hollysmart.smart_beijinggovernmentaffairsplatform-1/oat/arm/base.odex (oatexec+14093597) [armeabi]
18 java:
19 cn.wildfirechat.client.ClientService.initProto(ClientService.java:1945)
20 cn.wildfirechat.client.ClientService.access$400(ClientService.java:125)
21 cn.wildfirechat.client.ClientService$ClientServiceStub.connect(ClientService.java:184)
22 cn.wildfirechat.client.IRemoteClient$Stub.onTransact(IRemoteClient.java:63)
23 android.os.Binder.execTransact(Binder.java:453)

**Comment by heavyrain2012** [comment]
检查是不是token为空，或者切换用户的时候没有退出
