### ISSUE TITLE
关于群组下拉加载历史记录的问题

### ISSUE THREAD

**Issue by YangYaXing** [wildfirechat/android-chat#34]
首先拉几个用户新建一个群，然后发几十条群消息，发送完毕后，再新增用户。新进来的用户下拉加载历史记录时，历史记录会不停的重复加载，并且有数据不全，排序还会有问题。

**Comment by imndx** [comment]
你好，请你看下有我们的demo测试一下，有无类似的问题。

**Comment by YangYaXing** [comment]
你好，我刚刚下载了最新的安卓demo测试了下，还是有这个问题，具体表现是我先创建个群，发几十条消息，然后在新拉入一个用户。新拉入的用户下拉加载历史记录，会出现历史消息排序错乱问题以及消息重复问题。ios上周也有测过，ios本身代码有进行重复消息过滤，但是历史记录也存在排序问题以及历史记录展示不全。




------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 上午10:01
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于群组下拉加载历史记录的问题 (#34)




你好，请你看下有我们的demo测试一下，有无类似的问题。

**Comment by imndx** [comment]
OK，谢谢，我们分析下。

**Comment by YangYaXing** [comment]
Inconsistency detected. Invalid view holder adapter positionViewHolder{1b26e6f2 position=21 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}



------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上7:05
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于群组下拉加载历史记录的问题 (#34)




Closed #34 via 17f6559.

**Comment by YangYaXing** [comment]
修改后下拉历史记录报错：Inconsistency detected. Invalid view holder adapter positionViewHolder{36e05ccf position=25 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{8e0ca3a VFED.... .F....ID 0,0-1080,1538 #7f080158 app:id/msgRecyclerView}



------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上7:05
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于群组下拉加载历史记录的问题 (#34)




Closed #34 via 17f6559.

**Comment by YangYaXing** [comment]
新拉进来的群员下拉查看历史记录显示正确了，但是创建群时的群员下拉加载历史记录，每加载一次历史记录都是倒序排列




------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上7:05
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于群组下拉加载历史记录的问题 (#34)




Closed #34 via 17f6559.

**Comment by YangYaXing** [comment]
你好，我刚刚更改了您变更的代码，新拉进来的用户下拉历史记录代码重复的问题已经修改好了，但是新拉进来的用户每返回一次的数据都是倒序排列，原始用户显示正常。




------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上7:05
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于群组下拉加载历史记录的问题 (#34)




Closed #34 via 17f6559.

**Comment by YangYaXing** [comment]
你好，我刚刚更改了您变更的代码，新拉进来的用户下拉历史记录代码重复的问题已经修改好了，但是新拉进来的用户点开聊天界面的第一次每返回一次的数据都是倒序排列，再次进入则乱序排列。原始用户显示正常。


------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上7:05
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于群组下拉加载历史记录的问题 (#34)




Closed #34 via 17f6559.

**Comment by imndx** [comment]
好的，谢谢，我先重新打开这问题，再分析下。

但是新拉进来的用户点开聊天界面的第一次每返回一次的数据都是倒序排列

这是什么意思？

**Comment by YangYaXing** [comment]
我的意思是：比如我是群主，我按招1到10，a到z分别发送出去消息，比如，发送完后，我拉个新成员b，新成员下拉加载历史消息，预期得到的是从上到下1，2，3，4，5显示出来，结果返回的是相反的顺序5，4，3，2，1。比如，然后该成员返回上一级，再次点击进入该群聊天界面，返回的历史消息排序则出现错乱，如图：




------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 上午7:56
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于群组下拉加载历史记录的问题 (#34)




好的，谢谢，我先重新打开这问题，再分析下。
 
但是新拉进来的用户点开聊天界面的第一次每返回一次的数据都是倒序排列
 
这是什么意思？

**Comment by YangYaXing** [comment]
你好，按照您的方法，我把                                                mars-core-release.aar文件替换掉了，历史记录变成跟以前一样会重复出现加载。                                                mars-core-release.aar文件是今天早上刚更新的那个





------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 晚上11:20
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于群组下拉加载历史记录的问题 (#34)




Closed #34 via dab1895.

**Comment by YangYaXing** [comment]
看了下你们又更新了conversationActivity文件，改了运行后，后面拉进来的用户头一次下拉历史记录显示正常，退出再次进入，排序错乱。
