### ISSUE TITLE
问一下 如何修改启动延迟的

### ISSUE THREAD

**Issue by cell3389** [wildfirechat/android-chat#345]
如何修改启动延迟的

**Comment by imndx** [comment]
指的是闪屏页的时间吗？
请看下SplashActivity

**Comment by cell3389** [comment]
![1](https://user-images.githubusercontent.com/55130931/82048860-f594c180-96e7-11ea-9e9d-b8c951e5ed7d.jpg)
这个页面

**Comment by cell3389** [comment]
修改时间长些

**Comment by imndx** [comment]
请看下SplashActivity，修改里面的delay。
