### ISSUE TITLE
[dismissGroup]解散群组失败，但会群发"退出了群组"消息。这是一个交互上的小bug。

### ISSUE THREAD

**Issue by AlexFeng-007** [wildfirechat/android-chat#347]
我们修改了群组规则：“非普通群”的群主是不可解散群组的。
但现在出现一个小Bug:当群主在群详情页点击“解散并删除”时，会提示“解散群组失败”.但返回群会话页面时却收到“您退出了群组”消息,同时其他群成员也会收到此错误消息。 ----请教大佬，这里就是一个交互上的错误，安卓端应该怎么改正呢？

**Comment by imndx** [comment]
你们修改了im server吗？

> “非普通群”的群主是不可解散群组的

那当是 “非普通群”的群主时，详情页是不是就不应该显示解散按钮？

**Comment by AlexFeng-007** [comment]
好的，非常感谢！
这里采用了您的建议：当 “非普通群”的群主时，就不显示解散按钮。
跳过了“复杂”的交互流程，简单处理好了。。
