### ISSUE TITLE
修改群组名称偶尔会收到两次消息

### ISSUE THREAD

**Issue by DoNotLookAtMe** [wildfirechat/android-chat#355]
1.群主修改群名称后，会收到两次消息提醒，一次reciver 一次sender 很诡异，偶发。
2.如果网络不好的情况下，发送消息，接收方会出现接收到多次消息的情况

**Comment by imndx** [comment]
1.  一次reciver 一次sender 是什么意思？
2. 请参考[通用问题](https://docs.wildfirechat.cn/faq/general.html) 25
