### ISSUE TITLE
Android端会话列表有没有被好友删除的监听

### ISSUE THREAD

**Issue by wuditwj** [wildfirechat/android-chat#356]

**Comment by imndx** [comment]
你好，目前没有这个监听。
请问你下，你们是什么场景下，需要这个监听？

**Comment by wuditwj** [comment]
一个账号被好友删除之后,在会话列表页面不会自动删除与那个好友的对话

**Comment by imndx** [comment]
你好，可以通过 ```OnFriendUpdateListener.onFriendListUpdate``` 来实现。

**Comment by wuditwj** [comment]
我试过了,好像被删除了之后并不会触发这个方法
