### ISSUE TITLE
消息体过大导致发送失败

### ISSUE THREAD

**Issue by AFAP** [wildfirechat/android-chat#359]
自定义了一个消息体，里面包含了图片的链接及图片的Base64缩略图，由于base64字符串较长，导致消息发布出去。测试过了，如果不传这个字段就可以，初步怀疑是不是消息大小有限制？

**Comment by imndx** [comment]
是的，对消息体大小有限制，建议消息大小别超过5K。

**Comment by AFAP** [comment]
> 是的，对消息体大小有限制，建议消息大小别超过5K。

明白了
