### ISSUE TITLE
自定义群组通知接收失败

### ISSUE THREAD

**Issue by AFAP** [wildfirechat/android-chat#360]
继承自GroupNotificationMessageContent，在修改群extra时发送，结果PC和iOS收到都是null，自定义的id是1003，大于1000，在修改extra时，如果new一个修改群名的通知，是能正确显示的，但是自定义的就不行，所有构造都是参考群名修改做的。

**Comment by AFAP** [comment]
![image](https://user-images.githubusercontent.com/11977837/84587267-34857680-ae50-11ea-861e-0f9578b7e42b.png)


package cn.wildfirechat.message.notification;

import android.os.Parcel;

import org.json.JSONException;
import org.json.JSONObject;

import cn.wildfirechat.message.Message;
import cn.wildfirechat.message.core.ContentTag;
import cn.wildfirechat.message.core.MessagePayload;
import cn.wildfirechat.message.core.PersistFlag;
import cn.wildfirechat.remote.ChatManager;

import static cn.wildfirechat.message.core.MessageContentType.ContentType_GROUP_TIP;

/**
 * 通用群组提示信息
 */
@ContentTag(type = ContentType_GROUP_TIP, flag = PersistFlag.Persist)
public class GroupTipNotificationContent extends GroupNotificationMessageContent {
    public String operateUser;
    public String text;

    public GroupTipNotificationContent() {
    }

    @Override
    public String formatNotification(Message message) {
        StringBuilder sb = new StringBuilder();
        if (fromSelf) {
            sb.append("您");
        } else {
            sb.append("\"");
            sb.append(ChatManager.Instance().getUserDisplayName(operateUser));
            sb.append("\"");
        }
        sb.append(text);

        return sb.toString();
    }

    @Override
    public MessagePayload encode() {
        MessagePayload payload = new MessagePayload();

        try {
            JSONObject objWrite = new JSONObject();
            objWrite.put("g", groupId);
            objWrite.put("o", operateUser);
            objWrite.put("t", text);

            payload.binaryContent = objWrite.toString().getBytes();
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return payload;
    }

    @Override
    public void decode(MessagePayload payload) {
        try {
            if (payload.binaryContent != null) {
                JSONObject jsonObject = new JSONObject(new String(payload.binaryContent));
                groupId = jsonObject.optString("g");
                operateUser = jsonObject.optString("o");
                text = jsonObject.optString("t");
            }
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        super.writeToParcel(dest, flags);
        dest.writeString(this.operateUser);
        dest.writeString(this.text);
    }

    protected GroupTipNotificationContent(Parcel in) {
        super(in);
        this.operateUser = in.readString();
        this.text = in.readString();
    }

    public static final Creator<GroupTipNotificationContent> CREATOR = new Creator<GroupTipNotificationContent>() {
        @Override
        public GroupTipNotificationContent createFromParcel(Parcel source) {
            return new GroupTipNotificationContent(source);
        }

        @Override
        public GroupTipNotificationContent[] newArray(int size) {
            return new GroupTipNotificationContent[size];
        }
    };
}

**Comment by imndx** [comment]
```encode```, ```decode```时，需要处理新增的字段 。

**Comment by AFAP** [comment]
> `encode`, `decode`时，需要处理新增的字段 。

处理了，你可以从我的代码看到，字段就是text，缩写t

**Comment by AFAP** [comment]
> `encode`, `decode`时，需要处理新增的字段 。

经查，PC出问题的，这里要注意content和binaryContent，这里用的是binaryContent
