### ISSUE TITLE
多人视频性能问题：耗电快，设备发热较厉害

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/android-chat#369]
电量95%，系统只开一个应用，只测试单人，多人视频2小时，电量只剩下10%，且设备发热较厉害。

**Comment by heavyrain2012** [comment]
多人音视频架构问题，所以性能消耗比较大。另外多人视频本身消耗也比较大，可以用微信对比测试看看

https://github.com/wildfirechat/server/issues/217
