### ISSUE TITLE
发46M的文件apk文件发不出去 显示失败

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#37]
![image](https://user-images.githubusercontent.com/7382234/59658281-be671900-91d5-11e9-9dda-69a9ae281732.png)

**Comment by heavyrain2012** [comment]
用的是七牛文件服务器，还是内置文件服务器

**Comment by yuzhongrong** [comment]
自己的没用第三方的云

**Comment by LeonDevLifeLog** [comment]
后台配置最大上传文件尺寸为50mb,修改一下限制就好了

**Comment by yuzhongrong** [comment]
好的

**Comment by yuzhongrong** [comment]
已经解决

**Comment by imndx** [comment]
> 已经解决

请分享一下解决方案，谢谢。

**Comment by yuzhongrong** [comment]
文件过大 我再app端限制了下大小
原来app是100M的
