### ISSUE TITLE
关于conversation line一些疑问?

### ISSUE THREAD

**Issue by hyl87** [wildfirechat/android-chat#371]

**Comment by hyl87** [comment]
Conversation(Conversation.ConversationType.Single, toUid, 1) 设置line 之后, 1 line 获取消息列表时,里面只有send方向的消息,没有接收方向的

**Comment by imndx** [comment]
接受方向，对方也是发送到1这个 会话线路吗？

**Comment by hyl87** [comment]
@imndx  是的 收发都是1这个line

**Comment by imndx** [comment]
你好，无法复现问题，请用最新代码测试。
