### ISSUE TITLE
设置聊天类型位群组聊天类型，但是，显示的是全部的会话类型，如果将群聊单独抽离出来，消息的未读数接口完全不够用，只有单聊，群@，还有群的@

### ISSUE THREAD

**Issue by RookieBro** [wildfirechat/android-chat#372]
这里图片没法上传，我把遇到的问题大概描述一下，聊天列表如果将他的类型修改成Group的时候，会展示所有的会话类型，消息未读数接口的问题在于，关于其他聊天类型的未读，比如我要获取群组的未读数，获取频道的未读数等。
还有一个问题是来自于聊天窗口的拍照录像功能，这个功能突然间就不行了，提示拍照错误，请向我们反馈

**Comment by imndx** [comment]
你好：

1. ```getUnreadCountEx```可获取指定会话类型和会话线路的未读数。
2. 这个问题，对应代码都是开源的，你们可以自行调试一下，然后给我们提个PR。
