### ISSUE TITLE
多人视频时，安卓等待接听页面中，成员列表中缺少自己的头像

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/android-chat#376]
多人视频时，安卓等待接听页面中，成员列表中缺少自己。
场景：安卓1 call 安卓2和iOS1
iOS1的等待接听页面中，成员列表为自己和安卓2
安卓2的等待接听页面中，成员列表只有iOS1

**Comment by heavyrain2012** [comment]
客户验证demo中存在这个问题

**Comment by heavyrain2012** [comment]
UI的问题，已经修改UI，请更新验证

**Comment by Charlie191011** [comment]
最新版本SDK测试中，多人通话场景，iOS接停方的接听等待页面中，底部成员列表显示所有成员，包括自己和发起方。
安卓对应的页面中，底部成员列表中，没有显示自己和发起方的头像
