### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by DoNotLookAtMe** [wildfirechat/android-chat#378]
java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.gwssi.g-2/base.apk:classes3.dex)

麻烦看下打包后，点击音视频崩溃，并且报这个错怎么解决？或者提供一个思路也行

**Comment by DoNotLookAtMe** [comment]
初步判断是在dex分包的时候导致的，但是不知道怎么解决

**Comment by imndx** [comment]
升级gradle版本

**Comment by DoNotLookAtMe** [comment]
gradle 已经升级到3.6.3还是报之前的错

**Comment by imndx** [comment]
你好，可以参考[这儿](https://github.com/twilio/video-quickstart-android/issues/430)

**Comment by DoNotLookAtMe** [comment]
我在 gradle.properties 中添加了android.enableDexingArtifactTransform.desugaring=false 就可以了。🙏🙏
