### ISSUE TITLE
@功能

### ISSUE THREAD

**Issue by ShaoPengHu** [wildfirechat/android-chat#38]
@功能是不是未完善的，为啥@完@的消息数是0 类型也是普通消息

**Comment by imndx** [comment]
请测试最新代码，刚提交的

**Comment by imndx** [comment]
再次确认了，@数正常。

问题出在协议栈，需要更新```mars-core-release.aar```

**Comment by ShaoPengHu** [comment]
后端需要更新吗 我前端是更新了这个文件的

**Comment by ShaoPengHu** [comment]
promptTextView.setText("[有人@我]");
                promptTextView.setVisibility(View.VISIBLE); 大哥你少写了后面这个

**Comment by imndx** [comment]
哦哦，失误了，已解决，谢谢。
