### ISSUE TITLE
socket服务是否可以配置端口

### ISSUE THREAD

**Issue by DoNotLookAtMe** [wildfirechat/android-chat#381]
因为我们公司服务没办法修改端口，所以想问下是否可以在项目中配置

**Comment by heavyrain2012** [comment]
强制用80端口是因为使用80端口在国内是需要备案的，是被监管的，这样能够避免一些非法行为使用我们的SDK。一般情况下是不可以更换端口的，除非有充足的理解说明为什么不能用80端口

**Comment by LiuChiDong** [comment]
> 强制用80端口是因为使用80端口在国内是需要备案的，是被监管的，这样能够避免一些非法行为使用我们的SDK。一般情况下是不可以更换端口的，除非有充足的理解说明为什么不能用80端口

你好，如果我们正式服务器的80已经被占用了要怎么修改客户端这边连接时用的端口呢，其他项目在用了

**Comment by zhanshen1373** [comment]
> 因为我们公司服务没办法修改端口，所以想问下是否可以在项目中配置

除了用80端口，还有别的办法解决吗，项目中80被占用了
