### ISSUE TITLE
为什么要保证lifecycle在2.2.0以上，是因为AndroidX兼容吗？

### ISSUE THREAD

**Issue by Tobecomebest** [wildfirechat/android-chat#383]

**Comment by imndx** [comment]
由于所依赖的各个组件，他们版本升级的时候，可能会有不能向下兼容的情况，这时候，就需要一个选择：兼容最新的版本，还是兼容特定版本。在此，我们选择了尽量兼容最新的版本；对于旧版本等，我们不能保证兼容性，可以自行测试。
