### ISSUE TITLE
Wildfirechat contact sync

### ISSUE THREAD

**Issue by zloyFrost** [wildfirechat/android-chat#384]
Good day. Is it possible to support synchronization of telephone contacts with wildfirechat to automatically add to the application ??? thank

**Comment by heavyrain2012** [comment]
抱歉，英语不好，只能中文回复你，你可以 google translate 来翻译回复，如果有疑问可以在此讨论。

请检查文档 https://docs.wildfirechat.cn/blogs/手机通讯录用户关系和好友推荐.html

**Comment by zloyFrost** [comment]
> 抱歉，英语不好，只能中文回复你，你可以 google translate 来翻译回复，如果有疑问可以在此讨论。
> 
> 请检查文档 [https://docs.wildfirechat.cn/blogs/手机通讯录用户关系和好友推荐.html](https://docs.wildfirechat.cn/blogs/%E6%89%8B%E6%9C%BA%E9%80%9A%E8%AE%AF%E5%BD%95%E7%94%A8%E6%88%B7%E5%85%B3%E7%B3%BB%E5%92%8C%E5%A5%BD%E5%8F%8B%E6%8E%A8%E8%8D%90.html)

我想问一下将来是否会引入用户与电话帐户的同步，以便快速找到朋友

**Comment by imndx** [comment]
你好，这涉及到用户隐私等相关问题，我们目前没有相关计划。
