### ISSUE TITLE
安卓IM连接失败.IOS正常,求请教!

### ISSUE THREAD

**Issue by shanggquan** [wildfirechat/android-chat#385]
服务器已经部署好了. ios 链接正常 也可以正常聊天.
安卓的可以登录上,安卓 IM连接好像有问题 不能连接上. 安卓app端和后台都没有看到明显的bug Log信息
安卓把地址改成 野火的测试地址可以正常聊天.
请问大概问题出在哪里,我们好有一个调查方向.

**Comment by imndx** [comment]
请给我们提供一下Android客户端的日志，抓取日志，请参考[日志](https://docs.wildfirechat.cn/faq/android/q3.html)

**Comment by heavyrain2012** [comment]
文档常见问题有排查步骤，请按照步骤排查
