### ISSUE TITLE
@LayoutRes这个注解在library中使用会报“错误: 元素值必须为常量表达式”

### ISSUE THREAD

**Issue by changeforyou** [wildfirechat/android-chat#386]
我们是组件化开发的，@LayoutRes这个注解在library中使用会报“错误: 元素值必须为常量表达式”，在主工程里没问题，我们是想在library中使用，想要咨询下这个问题你们有好的解决办法吗？

**Comment by imndx** [comment]
目前不支持以library的方式引入，只能已源码的方式引入，集成方式，请参考[集成](https://docs.wildfirechat.cn/faq/android/q2.html)

**Comment by imndx** [comment]
已支持library方式集成，请使用最新代码，遇到library方式集成相关问题，请到这个issue下讨论: #390 

其他问题，请新提issue。
