### ISSUE TITLE
没有朋友圈的功能代码吗

### ISSUE THREAD

**Issue by qiebixuefu12345** [wildfirechat/android-chat#391]

**Comment by imndx** [comment]
你好，朋友圈功能代码分为两部分：UI 和 SDK。
UI部分代码在这儿[朋友圈UI](https://github.com/wildfirechat/android-momentkit)
SDK部分是闭源，且收费的，如果需要，可参考这儿，[申请试用](https://docs.wildfirechat.cn/trial/)
