### ISSUE TITLE
demo语音通话在小米上不响铃，接听按钮点击无反应

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/android-chat#395]
#### 操作说明
两个小米进行测试：小米5x和小米6x
相互拨打语音电话

#### 表现现象
两台手机都有弹出界面但都不响铃
小米5x点击接听按钮可以正常接听
小米6x点击接听按钮无反应
挂断按钮都正常
只有语音通话有这个问题 视频通话无问题

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
必现 
#### demo对比结果
demo0.7进行的测试

**Comment by xhun2015** [comment]
补充下，以上测试小米5x用的0.8的debug版本 小米6x是用的demo0.7 release版本。小米5x发起的语音小米6x接听无反应，小米5x发起的视频小米6x点击接听有60%几率不成功，点击接听后两边都不响铃了，但是不出画面。小米6x发起的所有音视频小米5x都能成功接听。如果两个手机都使用demo0.7则没有以上所有问题。

**Comment by imndx** [comment]
你好，两部手机都使用0.8.0版本测试的话，有上述问题吗？

**Comment by xhun2015** [comment]
0.8打包后登录失败，错误 0 null ,没法测试，是做了限制吗？私有部署还没搭建

**Comment by xhun2015** [comment]
对了，不响铃这个无论从哪台手机发起都不响铃

**Comment by imndx** [comment]
> 0.8打包后登录失败，错误 0 null ,没法测试，是做了限制吗？私有部署还没搭建

没有做限制，如果连接官方服务器，不不需做任何改动，直接打包即可。

请将相关日志，给我们贴一下
