### ISSUE TITLE
在另外一个进程调用uikit，怎么能用主进程的ChatManager

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/android-chat#396]
目前我只能两个进程都初始化ChatManager，否则子进程调用UIkit 会因为ChatManager为初始化获取不到实例崩溃。两个进程都初始化，问题也不大，就是音视频消息，有两个，主进程的接听了，子进程的还在响铃。我做了个判断，如果是子进程不初始化AV.问题也算解决了。还有更好的解决办法吗。我不是原生开发人员，可能问题有点弱智

**Comment by imndx** [comment]
进程之间是隔离的，没法直接调用。什么场景下需要在多个进程调用uikit？

针对你的具体问题，目前我们也没有更好的办法。

**Comment by xhun2015** [comment]
项目集成的uniapp 小程序sdk,野火做为宿主APP,其他项目作为小程序嵌入野火，小程序调用uikit的界面。项目就类似于微信小程序，微信和微信小程序是不同进程，但是微信小程序可以调用微信的原生功能和UI
