### ISSUE TITLE
小米手机demo包没有来电提示音

### ISSUE THREAD

**Issue by woyaozuoai** [wildfirechat/android-chat#398]
v0.7.0版
小米手机 demo包 语音连麦 本机和通话方 弹出来电画面没有提示音 , 多人语音连麦通话有来电音, 视频来电 转语音图标图片看不清

**Comment by imndx** [comment]
你好，语音通话时，是有提示音的，只是比较小，不是通过外放出来的。后续我们会修复这个问题，也欢迎给我们提PR。

**Comment by imndx** [comment]
已解决，请更新到最新代码。
