### ISSUE TITLE
关于新的朋友页面

### ISSUE THREAD

**Issue by YangYaXing** [wildfirechat/android-chat#40]
收到加好友信息，第一次点开新的朋友，接收不到userinfo信息，再次进入才能收到，请问该怎么解决呢？

**Comment by imndx** [comment]
第一次本地没有，会返回一个只有uid的userinfo，同时去服务器拉用户信息，来到之后会有回调通知的

**Comment by YangYaXing** [comment]
这个有办法优化吗


------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 中午11:31
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于新的朋友页面 (#40)




第一次本地没有，会返回一个只有uid的userinfo，同时去服务器拉用户信息，来到之后会有回调通知的

**Comment by YangYaXing** [comment]
这个有办法优化吗？我是写了一个Intent跳转到该页面1毫秒后销毁再次进入，，，感觉卡卡的


------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 中午11:31
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于新的朋友页面 (#40)




第一次本地没有，会返回一个只有uid的userinfo，同时去服务器拉用户信息，来到之后会有回调通知的

**Comment by imndx** [comment]
加一下监听就行了。
我们会在好友请求列表界面加上

**Comment by YangYaXing** [comment]
你好，方便把监听的代码贴上吗，




------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>; 
发送时间: 2019年6月20日(星期四) 中午11:34
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>; 
抄送: "Yang雅兴"<850992232@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wildfirechat/android-chat] 关于新的朋友页面 (#40)




加一下监听就行了。
 我们会在好友请求列表界面加上

**Comment by YangYaXing** [comment]
可以了！谢谢




------------------ 原始邮件 ------------------
发件人: "imndx"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午4:46
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com>;
抄送: "Yang雅兴"<850992232@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wildfirechat/android-chat] 关于新的朋友页面 (#40)




Closed #40 via c15f082.
