### ISSUE TITLE
getconversationread始终犯规null

### ISSUE THREAD

**Issue by AFAP** [wildfirechat/android-chat#401]
getconversationread这个方法一直返回null

**Comment by imndx** [comment]
请用最新的测试，如果问题依旧，请提供一些日志。

**Comment by AFAP** [comment]
> 请用最新的测试，如果问题依旧，请提供一些日志。

就是用的最新的，也没日志，debug得到的就是null...

**Comment by imndx** [comment]
你好，我们在最新的demo上无法复现。

**Comment by AFAP** [comment]
> 你好，我们在最新的demo上无法复现。

直接替换成最新的mars-core-release.arr就行吧，替换后还是null

**Comment by imndx** [comment]
> > 你好，我们在最新的demo上无法复现。
> 
> 直接替换成最新的mars-core-release.arr就行吧，替换后还是null

你好，你先别集成到你们项目，直接下载我们demo的代码，看下能否复现。

另外，connect成功之前，这个函数是可能返回null的，这种情况，你可以在```ChatManager```里面对应的地方打个断点确认一下。

**Comment by imndx** [comment]
no response.
