### ISSUE TITLE
关于离线消息拉取小问题

### ISSUE THREAD

**Issue by onesand** [wildfirechat/android-chat#406]
#### 表现现象

再次进来APP时候，是怎么拉取离线消息的？我debug时候发现没走 ChatManager 的 onReceiveMessage 方法，麻烦可以说一下离线消息到达通过哪个地方可以监听吗？

**Comment by imndx** [comment]
connect 成功之后，会自动去拉取离线消息，如果有离线消息的话，会走```ChatManager#onReceiveMessage```的.

**Comment by onesand** [comment]
我打了 log ，也 debug 了，发现重新打开app进来，接到历史消息没有走到 ChatManager#onReceiveMessage 里面来，方便的话您试试？

**Comment by onesand** [comment]
已解决。应该是APP关闭后，后台的服务把消息拉取到了，然后ChatManager的消息监听对象被回收了，所以导致监听不到。

**Comment by ManBali** [comment]
> 已解决。应该是APP关闭后，后台的服务把消息拉取到了，然后ChatManager的消息监听对象被回收了，所以导致监听不到。

哪有什么应该是的啊。
