### ISSUE TITLE
视频聊天镜像左右颠倒问题

### ISSUE THREAD

**Issue by oldpan1310** [wildfirechat/android-chat#41]
视频聊天中镜像反了，人向左移动，画面向右移动。能否暴露API那开发者自由修改

**Comment by Derek-Zh** [comment]
同求，前置摄像头应做镜像处理

**Comment by imndx** [comment]
目前现象和微信一致，我们暂时不修改。

可通过下面api进行镜像设置：

```((SurfaceViewRenderer) surfaceView).setMirror(true);```
