### ISSUE TITLE
语音

### ISSUE THREAD

**Issue by ShaoPengHu** [wildfirechat/android-chat#416]
请问下我发起了语音通话后它先显示发送了一条对方未接听的自定义类型消息，然后又掉起了语音通话，对方也能收到，但是并不能接听，请问下是什么原因  语音的aar包我也更新了 voip中的资源也更新了

**Comment by ShaoPengHu** [comment]
![QQ图片20200818161442](https://user-images.githubusercontent.com/37129212/90488109-fa956100-e16d-11ea-9583-730d487af533.png)
一开始这个状态是Incoming的，我点击之后就是Connecting，都界面状态没变化 ，是不是我遗漏了什么？

**Comment by ShaoPengHu** [comment]
是不是这个 session.answerCall(false); 方法执行后 在哪个地方我遗漏了？ voip这一部分全是拷贝demo的  之前还是可以的 更最新的就出问题了

**Comment by ShaoPengHu** [comment]
点击接听后就一直 Connecting

**Comment by ShaoPengHu** [comment]
![QQ图片20200819141609](https://user-images.githubusercontent.com/37129212/90598966-98e4fd80-e226-11ea-94c8-3e4b00701d9b.png)
只是少了什么吗

**Comment by ShaoPengHu** [comment]
更新下org.webrtc:google-webrtc解决

**Comment by imndx** [comment]
> 更新下org.webrtc:google-webrtc解决

更新到什么版本？用我们配置的版本不行？

**Comment by ShaoPengHu** [comment]
我用的是旧demo上的1.0.2，更新就可以了
