### ISSUE TITLE
创建群，成员乱序

### ISSUE THREAD

**Issue by gnmmdk** [wildfirechat/android-chat#418]
如题，创建群的选择四个人（例如 小一，小二，小三，小四）
创建完到设置群页面，获取到的人员顺序变了，可能变成（小四，小二，小一，小三)

**Comment by gnmmdk** [comment]
> 如题，创建群的选择四个人（例如 小一，小二，小三，小四）
> 创建完到设置群页面，获取到的人员顺序变了，可能变成（小四，小二，小一，小三)

demo也是如此

**Comment by heavyrain2012** [comment]
已解决，请下载最新的server代码编译运行验证

**Comment by heavyrain2012** [comment]
还有些问题，我们会尽快解决
