### ISSUE TITLE
Android 消息撤回重新编辑没生效

### ISSUE THREAD

**Issue by ShaoPengHu** [wildfirechat/android-chat#419]
Android 的消息撤回没生效

**Comment by ShaoPengHu** [comment]
说错了 是重新编辑没生效，

**Comment by imndx** [comment]
请详细描述 如何复现

**Comment by ShaoPengHu** [comment]
就是撤回的时候没有显示重新编辑，我看RecallMessageContentViewHolder.class这个没有用到，估计是SimpleNotificationMessageContentViewHolder.class注册了RecallMessageContent.class

**Comment by imndx** [comment]
> 就是撤回的时候没有显示重新编辑，我看RecallMessageContentViewHolder.class这个没有用到，估计是SimpleNotificationMessageContentViewHolder.class注册了RecallMessageContent.class

是的，你说的是对的。之前忘了已经开发了这功能，就没去调试。
