### ISSUE TITLE
发起语音通话的时候接收方没有响声

### ISSUE THREAD

**Issue by ShaoPengHu** [wildfirechat/android-chat#420]
发起语音通话的时候接收方没有响声

**Comment by imndx** [comment]
请按照issue模板，提供更详细的信息。

**Comment by android-xiao-jun** [comment]
![image](https://user-images.githubusercontent.com/39174748/92294224-d4890280-ef5c-11ea-9a3b-dfc48360c6da.png)
![image](https://user-images.githubusercontent.com/39174748/92294231-e2d71e80-ef5c-11ea-80ef-57dc121f7ae8.png)
兄弟，这个问题，我是这么解决没有提示声的
@ShaoPengHu

**Comment by android-xiao-jun** [comment]
![image](https://user-images.githubusercontent.com/39174748/92294268-46f9e280-ef5d-11ea-9ee5-187d85f64224.png)
提示声，还得加个这个。


你最好用耳机（蓝牙，有线）试一试，，我这边耳机接听没有声音，还得修改其他地方 @ShaoPengHu

**Comment by imndx** [comment]
谢谢，我们测试一下
