### ISSUE TITLE
服务端接口更新用户昵称或头像后，其他用户看到的还是原来的昵称和头像

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/android-chat#423]
服务端接口更新用户昵称或头像后，其他用户看到的还是原来的昵称和头像，删除本地数据，或重新安装才能更新，或者去点击查看每个用户的用户信息后，才会更新。有办法同步吗

**Comment by imndx** [comment]
你好，目前设计如此。

其实，微信也是一样的，对方换了头像，你需要点击查看其详情才更新的。

**Comment by heavyrain2012** [comment]
文档常见问题对这个问题有说明的，只有主动刷新才能更新
