### ISSUE TITLE
FriendRequest 类下的timestamp 转换时间的问题；

### ISSUE THREAD

**Issue by MaTengFei1990** [wildfirechat/android-chat#424]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
FriendRequest 类下的timestamp 转换时间有问题啊；能帮忙看一下吗；

#### 表现现象

![image](https://user-images.githubusercontent.com/19420333/91412795-dbd54f80-e87c-11ea-9722-f8118aec4350.png)

#### 预期结果
timestamp 可以转化成时间戳；

**Comment by heavyrain2012** [comment]
已接近，请把client更新到最新验证
