### ISSUE TITLE
AVEngineKit.AVEngineCallback can't listen after app is killed

### ISSUE THREAD

**Issue by ThazinSoe-tzs** [wildfirechat/android-chat#428]
## 提issue小提示
If app is **killed** in person A, **NO** incoming floating window is shown even person B make VIOP call.

#### 操作说明
**onReceiveCall()** override method of **AVEngineKit.AVEngineCallback** can't call after app is killed.

#### 表现现象
In WfcUIKit.java class, **onReceiveCall()** override method can't listen after app is killed.
```
 @Override
    public void onReceiveCall(AVEngineKit.CallSession session) {
        List<String> participants = session.getParticipantIds();
        if (participants == null || participants.isEmpty()) {
            return;
        }
        ......
    }
```

#### 预期结果
Even app is killed, incoming floating window should show.

#### 补充条件
By using latest version on github master branch.
https://github.com/wildfirechat/android-chat

#### demo对比结果
![no-incoming-call](https://user-images.githubusercontent.com/27953823/91828192-ce95d780-ec65-11ea-9b3e-f90b39938424.jpg)

**Comment by heavyrain2012** [comment]
需要对接推送服务， https://github.com/wildfirechat/push_server
