### ISSUE TITLE
git能不能搜下身啊 1个多G了

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/android-chat#429]

**Comment by xhun2015** [comment]
按照这篇文章对fork项目进行测试 改写历史后，项目大小变成了90M左右,感觉瘦身把，1个G 翻墙都要下载老半天。
下面是我执行的命令：
git filter-branch --tree-filter 'rm -f mars-core-release/mars-core-release.aar' --tag-name-filter cat -- --all
主要删除历史中的mars-core-release.aar这个二进制文件

**Comment by imndx** [comment]
#435

**Comment by imndx** [comment]
可通过下面，只拉取最新的代码。
```
git clone --depth=1 https://github.com/wildfirechat/android-chat.git
```
