### ISSUE TITLE
多人视频接听后，自己的视角有时会变成头像而不是画面。切换摄像头时，视角有时也会变成头像，切换摄像头失败

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/android-chat#432]
接听后，自己的视角有时会变成头像而不是画面。切换摄像头时，视角有时也会变成头像，切换摄像头失败

 demo对比结果
demo上安卓切换不了摄像头，点击切换按钮无响应

**Comment by imndx** [comment]
你好，出现自己头像的时候，可能没有真正接通，请提供一下日志。
