### ISSUE TITLE
接通后，翻转摄像头，多切换几次，视角不对，有时候显示为自己的头像，有时候自己的视角没有显示翻转成功，停留在当前视角，但在其他方显示的视角是对的

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/android-chat#433]
表现现象
多人视频时，多次点击切换摄像头按钮，切换多次摄像头时，有时切换失败，没有切换成功；有时直接切换成了自己头像。但是其他视频用户看到该用户的切换效果是正常的，可以正常切换前后摄像头的视角。

demo对比结果
demo切换摄像头按钮点击无响应

**Comment by imndx** [comment]
你好，切换摄像头是 旋转摄像头 的意思吗？

我在demo上测试了下，正常接通之后，是可以切换的。
