### ISSUE TITLE
仓库超过1个G的问题能不能解决下啊，fork的项目超过1G没法push了

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/android-chat#435]
现在的问题是，我fork的项目，超过1G后，我修改一些文件后想push到gitee仓库，没办法push了，会提示如下错误：
remote: Powered by GITEE.COM [GNK-5.0]
remote: This repository(including wiki) size 1143.71 MB, exceeds 1024.00 MB.
remote: Push rejected for repository size exceeds limit.
remote: HelpLink:           https://gitee.com/help/articles/4232
remote: Repository GC:      https://gitee.com/ykwlkj/chat_android/settings#git-gc
remote: Enterprise Edition: https://gitee.com/enterprises#commerces

（github免费用户不清楚有没有这个1G的限制）
如果我按照提示https://gitee.com/help/articles/4232进行改写历史删除二进制文件，我fork的仓库体积是减少了。但是我将https://github.com/wildfirechat/android-chat.git 作为upstream,你们如果有更新，我可以同步合并到我的仓库，而我改写历史后我fork的仓库(有新增修改代码)想和upstream新的更新进行合并就会出现问题，无法合并。
git这块也不是很精通，现在不知道咋搞了。
希望你们官方能尽快解决仓库太大的问题

**Comment by imndx** [comment]
这个issue先关了，集中到 #429 下讨论。
