### ISSUE TITLE
找不到R2 包

### ISSUE THREAD

**Issue by RongWen0316** [wildfirechat/android-chat#436]
将项目移到自己的项目中  报错   提示找不到R2包
![0 0 00 0](https://user-images.githubusercontent.com/20226798/92551541-d7ebf900-f290-11ea-8e08-5b8bdcb9e7fa.png)
![1 1 1 1](https://user-images.githubusercontent.com/20226798/92551571-e63a1500-f290-11ea-8a2d-109ac430258f.png)

**Comment by imndx** [comment]
R2是编译的时候自动生成的，应当是其他编译错误导致的。
