### ISSUE TITLE
安卓模块地下的文档没改还是什么情况？为啥3.5的gradle说的是不支持替换到这个版本，但是在代码中，又超越了3.5的版本

### ISSUE THREAD

**Issue by RookieBro** [wildfirechat/android-chat#439]
安卓模块地下的文档没改还是什么情况？为啥3.5的gradle说的是不支持替换到这个版本，但是在代码中，又超越了3.5的版本

**Comment by imndx** [comment]
3.5版本的gradle，可能会导致音视频通话出问题。其他更新或者更旧的版本，都没有问题。
