### ISSUE TITLE
Project with path ':client' could not be found.

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#442]
1.2. 源码集成
下载android-chat项目
Android Studio -> File -> New -> Import Module... 选择android-chat/uikit
修改cn.wildfire.chat.kit.Config.java完成配置
参考demo，demo相当于是把uikit集成到了chat，遇到注释，请仔细阅读

按照文档集成

到 Android Studio -> File -> New -> Import Module... 选择android-chat/uikit这步的时候提示

Project with path ':client' could not be found.
单独导入每个包也都不行

**Comment by imndx** [comment]
```:client``` 是表示相对路径，请看下你项目下是否有这个目录。
Android studio Import Module的时候，正常会将这个目录从android-chat目录下拷贝到当前目录。

另外，我用最新的Android Studio导入测试了一下，没问题。

**Comment by mankind-evolve** [comment]
已解决。默认导入的时候是在下面生成几行代码

需要把下面的导入代码放到最上面去
