### ISSUE TITLE
Class content provided for type descriptor cn.wildfirechat.avenginekit.C actually defines class cn.wildfirechat.avenginekit.c   导入我的老工程的时候，一安装运行就报错，编译没事  

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#443]
void cn.wildfirechat.avenginekit.PeerConnectionClient$b.onDataChannel(org.webrtc.DataChannel), Class content provided for type descriptor cn.wildfirechat.avenginekit.C actually defines class cn.wildfirechat.avenginekit.c

实在不明白是哪儿的问题

**Comment by imndx** [comment]
系统版本是多少？

有对比过demo吗？

能否提供更多日志。

PS: 以后请按模板提issue哈。

**Comment by imndx** [comment]
no responnse.
