### ISSUE TITLE
语音视频通话安卓和安卓接不了，和苹果可以正常通话这是为什么？

### ISSUE THREAD

**Issue by Tgakes** [wildfirechat/android-chat#445]
只要是安卓和安卓通话就是不行，点击接听的图标接不了，但是和苹果却可以接听，能否解答一下@官方

**Comment by imndx** [comment]
请更新到最新代码测试一下，确保```Config.java```里面```ICE_SERVERS```只有一个元素。

**Comment by Tgakes** [comment]
这个一直都是一个元素，是没错的，然后ios那边测试了如果也是ios和ios通话也不行，我们turn服务后台自己架设好的，用文档里面的turn服务测试是正常的，现在就是两端一样客户端通话就是不行，请问这个能否查出问题？

**Comment by imndx** [comment]
用我们的turn服务测试正常，那可能是你们的turn服务没有部署好了。

请参考[这儿](https://docs.wildfirechat.cn/webrtc/)，确保turn服务部署成功。

**Comment by Tgakes** [comment]
那我能否用demo提供的turn服务来测试下，是否正常，只要能排除到底是不是我们自己的turn没有部署好？还有就是我们的IM地址也都更换自己的了就是该换的我们都换成自己的了，如果用demo里面turn服务能否可以正常测试？

**Comment by Tgakes** [comment]
我刚用demo测试是可以接通，但是接通后说话为什么会有回音？请问如何解决@官方

**Comment by imndx** [comment]
> 我刚用demo测试是可以接通，但是接通后说话为什么会有回音？请问如何解决@官方

通话双方如果离的太近的话，会有回声。

**Comment by Tgakes** [comment]
我离得远也会有，这个你们测试的时候有发现吗？这个能解决吗

**Comment by imndx** [comment]
> 我离得远也会有，这个你们测试的时候有发现吗？这个能解决吗

我们没有发现，请对比一下，我们发布的demo

**Comment by imndx** [comment]
no response.
