### ISSUE TITLE
怎么做才能保证同个账号只能单个设备登录？

### ISSUE THREAD

**Issue by Tgakes** [wildfirechat/android-chat#446]
就是后者登录后能把前面的账号进行踢除，这个是需要需要后端来处理还是前端处理？麻烦给回复一下谢谢了@官方

**Comment by imndx** [comment]
请参考[多端登录处理](https://docs.wildfirechat.cn/blogs/%E5%A4%9A%E7%AB%AF%E7%99%BB%E5%BD%95%E7%9A%84%E5%A4%84%E7%90%86.html?h=%E5%A4%9A%E7%AB%AF)
