### ISSUE TITLE
一定要获取设备的电话权限吗？ 包括设备通话状态和识别码

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#448]
官方demo刚开始的时候要获取电话权限和储存权限

如果拒绝电话权限是不让用的

我是做国外应用的。国外用户对电话权限比较敏感，请问可不可以去掉电话的权限，对整个系统有什么重大的影响了吗？

**Comment by imndx** [comment]
可以去掉测试一下，影响不大。
