### ISSUE TITLE
getMessages获取消息列表，没有更多消息，hasMore仍然返回true

### ISSUE THREAD

**Issue by pipicoming** [wildfirechat/android-chat#449]
getMessages获取消息列表，没有更多消息，hasMore仍然返回true，再次请求getMessages，hasMore才会变为false，消息列表为空。

请求参数：

chat manager method call :{"arguments":{"before":true,"count":8,"fromIndex":5,"target":"SVShShss"},"method":"getMessages"}

响应：

{success: true, hasMore: true, messages: [{messageUid: 184400495956230145, sender: SVShShss, messageId: 2, serverTime: 1602665008463, content: {mentionedTargets: [], mentionedType: 0, messageContentType: 1, extra: , persistFlag: Persist_And_Count, content: 哈哈}, conversation: {line: 0, type: Single, target: SVShShss}, direction: Receive, status: Unread}, {messageUid: 184400565317435393, sender: SVShShss, messageId: 3, serverTime: 1602665041537, content: {mentionedTargets: [], mentionedType: 0, messageContentType: 1, extra: , persistFlag: Persist_And_Count, content: 嗯嗯}, conversation: {line: 0, type: Single, target: SVShShss}, direction: Receive, status: Unread}]}

**Comment by imndx** [comment]
已解决，请更新到最新代码。
