### ISSUE TITLE
接通华为后杀掉进程收不到华为的推送通知

### ISSUE THREAD

**Issue by Tgakes** [wildfirechat/android-chat#452]
项目推送接入个人版华为推送后服务端appSecret和appId也已经配置并且测试推送是通的，安卓这边配置也已经接入，可是安卓客户端就是无法收到华为的推送，通知栏始终没办法出现推送的消息，这个需要怎么排查定位?求救急@官方

**Comment by imndx** [comment]
0. 确认是否正确修改```push/build.gradle```下面的相关key
1. 确认是否正常调用了```ChatManager#setDeviceToken```
2. 确认是否正确修改```push server```推送相关配置
3. 查看```push server```日志，确认```im server```是否有调用推送服务

**Comment by Tgakes** [comment]
你好，安卓客户端我用华为平台上面的推送功能是可以正常推送过来的，但是服务端推送的就是不可以，这是不是华为平台上我们需要去配置什么服务端推送才能正常送达到客户端？

**Comment by imndx** [comment]
确认华为开发者平台和push server 是用同一个token进行推送的吗？

**Comment by Tgakes** [comment]
我对比了下token是没问题的，同样token我用华为平台推送就可以,那这样请问这个该怎么排查呢？

**Comment by Tgakes** [comment]
不过我这边小米是可以收到推送的

**Comment by imndx** [comment]
> 我对比了下token是没问题的，同样token我用华为平台推送就可以,那这样请问这个该怎么排查呢？

可以联系华为排查一下，看日志推送成功的，可能是那么的问题。

**Comment by Tgakes** [comment]
你好，请问透传推送和通知栏推送是在哪设置的？服务端还是客户端？若是再客户端是再哪个文件里面设置的？

**Comment by imndx** [comment]
> 你好，请问透传推送和通知栏推送是在哪设置的？服务端还是客户端？若是再客户端是再哪个文件里面设置的？

服务端。

可以参考这个[PR](https://github.com/wildfirechat/push_server/pull/11)

**Comment by Tgakes** [comment]
你好，那服务端具体是在哪个位置哪个文件上修改？

**Comment by Tgakes** [comment]
你好，若是方便麻烦您能尽快恢复一下，谢谢了！

**Comment by imndx** [comment]
> > 你好，请问透传推送和通知栏推送是在哪设置的？服务端还是客户端？若是再客户端是再哪个文件里面设置的？
> 
> 服务端。
> 
> 可以参考这个[PR](https://github.com/wildfirechat/push_server/pull/11)

你好，请参考上面提到PR，然后去修改。

**Comment by Tgakes** [comment]
你好，不是说在服务器修改吗？那这个PR上面似乎是在客户端修改的，麻烦你给确认一下。

**Comment by imndx** [comment]
确定的，你那就是push  server。
