### ISSUE TITLE
退出界面后，之前的聊天记录没有了

### ISSUE THREAD

**Issue by RongWen0316** [wildfirechat/android-chat#453]
[marsservice.log.txt](https://github.com/wildfirechat/android-chat/files/5407804/marsservice.log.txt)
你好，我想问下。
别人给我发的信息退出界面后再进来还在，
我给别人发的信息退出界面后再进来就没有了

**Comment by heavyrain2012** [comment]
消息是预制的消息，还是自定义消息？用demo对比过吗

**Comment by imndx** [comment]
问题原因已找到。

每次退出页面的时候，都调用了```ChatManager#disconnect(true, true)```。```disconnect```方法的第二个参数表示是否清除session，传true时，会清除数据。

另外，没必要每次进入、退出页面，都调用```connect```和```disconnect```。
