### ISSUE TITLE
调用账号密码登陆方法返回code=13,msg=没有登陆

### ISSUE THREAD

**Issue by yanjwgit** [wildfirechat/android-chat#454]

**Comment by imndx** [comment]
目前支持手机号 + 验证码登录

**Comment by yanjwgit** [comment]
好的，知道了，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/android-chat"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 下午2:08
收件人:&nbsp;"wildfirechat/android-chat"<android-chat@noreply.github.com&gt;;
抄送:&nbsp;"暖若安阳、"<874807039@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wildfirechat/android-chat] 调用账号密码登陆方法返回code=13,msg=没有登陆 (#454)





 
目前支持手机号 + 验证码登录
