### ISSUE TITLE
运行demo后。打不开app

### ISSUE THREAD

**Issue by motouRen** [wildfirechat/android-chat#455]
No pending exception expected: java.lang.NoClassDefFoundError: cn.wildfire.chat.kit.contact.-$$Lambda$ContactListFragment$JWlKBK0pEkYQJrSjIs9yCYNYa8A
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, java.lang.Object) (DexFile.java:-2)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, java.lang.Object, java.util.List) (DexFile.java:226)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:350)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at void cn.wildfire.chat.app.main.MainActivity.initView() (MainActivity.java:265)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at void cn.wildfire.chat.app.main.MainActivity.init() (MainActivity.java:156)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at void cn.wildfire.chat.app.main.MainActivity.lambda$new$0$MainActivity(java.lang.Boolean) (MainActivity.java:103)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at void cn.wildfire.chat.app.main.-$$Lambda$MainActivity$OM2mF15oiJbHOAt6DB2DtD9M0sU.onChanged(java.lang.Object) (lambda:-1)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at void androidx.lifecycle.LiveData.considerNotify(androidx.lifecycle.LiveData$ObserverWrapper) (LiveData.java:131)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at void androidx.lifecycle.LiveData.dispatchingValue(androidx.lifecycle.LiveData$ObserverWrapper) (LiveData.java:144)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at void androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(boolean) (LiveData.java:443)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at void androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(androidx.lifecycle.LifecycleOwner, androidx.lifecycle.Lifecycle$Event) (LiveData.java:395)
10-27 10:05:14.872 1507-1507/cn.wildfirechat.chat A/art: art/runtime/thread.cc:1341]   at void androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(androidx.lifecycle.LifecycleOwner, androidx.lifecycle.Lifecycle$Event) (LifecycleRegistry.java:361)

**Comment by motouRen** [comment]
Android 6.0.1

**Comment by imndx** [comment]
请问做过什么修改吗？

**Comment by motouRen** [comment]
> 请问做过什么修改吗？

没有修改过，打包安装apk可以，直接运行的app进去报错

**Comment by motouRen** [comment]
> 请问做过什么修改吗？
在MainActivity去除ContactListFragment的初始化只是才可以app运行之后才能使用

**Comment by Wenlong0913** [comment]
请问这个问题后来怎么解决呢，在红米4手机上可以稳定复现。但是不是所有手机都能复现，新一些的华为手机就不会出现这个问题。
