### ISSUE TITLE
没有64位的原生代码  上架不了googleplay

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#456]
我是做国外应用的， 我在我的APP的上集成了野火的IM

在发布到GOOGLEPLAY的时候，被提示 

以下 APK 或 App Bundle 面向 64 位设备，但只有 32 位原生代码：[22]

请问这个问题怎么解决

**Comment by imndx** [comment]
你好，我们库支持64位，应当是你们应用层的问题，请确认。
