### ISSUE TITLE
删除联系人， 通讯录列表不更新  我已经通知livedata.setpost了 如下

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#46]
![image](https://user-images.githubusercontent.com/7382234/60382941-1dae0e80-9a9d-11e9-8c20-f9244a11215e.png)

![image](https://user-images.githubusercontent.com/7382234/60382948-34ecfc00-9a9d-11e9-9664-0e9c277514ff.png)

**Comment by imndx** [comment]
请用最新代码测试

**Comment by yuzhongrong** [comment]
问题已经解决
