### ISSUE TITLE
群消息撤回问题

### ISSUE THREAD

**Issue by android-xiao-jun** [wildfirechat/android-chat#464]
问题描述：群消息撤回（群主撤回成员发送的消息），发送的撤回通知messageId和旧的消息id不一致导致出现两条撤回通知

希望修改：ConversationMessageAdapter这个类方法
private boolean contains(UiMessage message) {
        for (UiMessage msg : messages) {
            // 消息发送成功之前，messageUid都是0
            if (message.message.messageId > 0) {
                if (msg.message.messageId == message.message.messageId) {
                    return true;
                }
               //TODO  添加这一句
                if (msg.message.messageUid == message.message.messageUid) {
                    return true;
                }
              //
                // 聊天室里面，由于消息不存储，messageId都是0
            } else if (message.message.messageUid > 0) {
                if (msg.message.messageUid == message.message.messageUid) {
                    return true;
                }
            }
        }
        return false;
    }

**Comment by imndx** [comment]
PR已合并，谢谢。
