### ISSUE TITLE
最新版本的不支持 IP地址配置了？

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#466]
下了最新的包，配好IP地址后 显示配置错误。
现在不让IP配置了？
社区版本？

**Comment by mankind-evolve** [comment]
屏蔽了检查配置代码，用supercode登录的时候又显示得HTTP 或者HTTPS才行

**Comment by imndx** [comment]
支持ip配置，应当是你配置错了，请根据提示和各项配置处的注释说明，仔细确认。
