### ISSUE TITLE
图片上传失败返回状态码-1

### ISSUE THREAD

**Issue by liuzgAs** [wildfirechat/android-chat#469]
经过测试安卓SDK上传图片的时候payload.binaryContent的length大于25000左右就会发送失败返回状态码-1；这方面是否有做什么限制

**Comment by heavyrain2012** [comment]
消息体的大小对性能影响很大，服务器会缓存大量消息，如果消息体太大会造成大量内存，而且在与客户端同步时也会消耗更多的资源也更容易导致消息同步耗时较长，所以我们建议一定要控制消息体的大小，建议消息体大小不要超过15K。
