### ISSUE TITLE
A和B是好友，  A删除B后  AB还能够互通消息

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#47]
应该是 A删除B后   B给A发消息失败 最起码！！！

**Comment by imndx** [comment]
可以拉黑，不然知道id就能发消息

**Comment by yuzhongrong** [comment]
拉黑后还是可以接收到地方信息

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/60409594-d9cf1c80-9bf6-11e9-900a-e1be1fff2160.png)

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/60409625-f8cdae80-9bf6-11e9-9fe2-6908b867f976.png)

**Comment by yuzhongrong** [comment]
我已经实现了这个功能了 谢谢 修改服务器代码的 源头掐死
