### ISSUE TITLE
发图片和断网发消息的问题

### ISSUE THREAD

**Issue by wapalxj** [wildfirechat/android-chat#476]
1.demo中相册连续选中3张图片，发出去了，但是聊天界面只显示2张，退出聊天界面再进来就有了
2.demo中手机断网，给别人发消息，只能发出第1条消息到聊天界面，再发的话聊天界面不会更新，退出聊天界面再进来就有了

**Comment by imndx** [comment]
已解决，请更新最新代码测试。
