### ISSUE TITLE
消息Content如何查看接收到的原始数据？

### ISSUE THREAD

**Issue by AFAP** [wildfirechat/android-chat#477]
因为现有消息和自定义消息都是Parcel，这个东西想要查看它的全部属性不知道怎么查，现有的一些类型都是按顺序读，按顺序写的，但是现在自定义了一个新的类型，安卓端收到后怎么都取不到具体的内容。

有没有办法能把接收到的原始信息打出来？

**Comment by imndx** [comment]
我觉得你排查的方向不太对，应当写的顺序和读的顺序，应当在实现```Parcelable```接口的时候，就定义好了。请参考```TextMessageContent```进行自定义消息。

**Comment by AFAP** [comment]
> 写的顺序和读的顺序，应当在实现`Parcelable`接口的时候，就定义好了。
> 请参考`TextMessageContent`进行自定义消息。

现在是自定义的消息也没问题，比如名片啥的，互发没问题。现在有一个消息是邮件提醒，由后台服务器直接发出，取不到消息，是不是后台需要encode

**Comment by imndx** [comment]
通过server api发送的消息的格式是```MessagePayload```,  里面的有个```type```字段，端上需要自定义一个类型相同的自定义消息，并根据```MessagePayload```正确```decode```成该自定义消息。
