### ISSUE TITLE
咨询下：客户端可以发送只有发送方自己能收到的Notification消息么？对方不需要看到

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#478]
咨询下：客户端可以发送只有发送方自己能收到的Notification消息么？对方不需要看到

**Comment by imndx** [comment]
目前没有这种机制，请问什么场景下有这种需求？

**Comment by imndx** [comment]
如果不要求自己的所有客户端都同步这条消息的话，可以使用```ChatManager.insertMessage```方法，本地插入一条消息。
