### ISSUE TITLE
使用了最新的imserver appserver  无法获取用户信息

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#482]
在登录的时候 用接口写入用户的信息，然后登录，   在私聊页面无法拿到用户的用户信息，返回为Null

**Comment by imndx** [comment]
如果用户信息，本地不存在时，会返回NullUserInfo，等拿到用户信息之后，会有用户信息更新通知。

**Comment by mankind-evolve** [comment]
可是等了很久一直是NullUserInfo

**Comment by imndx** [comment]
通过这个带回调的方法，能获取到不？
```public void getUserInfo(String userId, boolean refresh, GetUserInfoCallback callback)```

**Comment by mankind-evolve** [comment]
重新登录了一下，可以获取了。
