### ISSUE TITLE
离线显示未读消息数量与实际未读消息数量不符

### ISSUE THREAD

**Issue by hihxh** [wildfirechat/android-chat#483]
我们测试当前版本proto未读离线消息数量与实际未读数量不符，测试发送离线消息80多，实际显示未读红点只有30多条。然后Conversation的lastMessage也不是最新的一条，进入Conversation里面显示正常。消息数量和lastMessage都正常。
测试Android和IOS都有同样的问题。

**Comment by heavyrain2012** [comment]
您好，请按照issue模版给我们提供信息。未读红点30多是那个界面？还有conversation的lastmessage不正确也请提供截图或者录像
