### ISSUE TITLE
demo怎么弹广告了？ 

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#485]
从android readme下载的官方demo    弹棋牌类广告了

**Comment by mankind-evolve** [comment]
是故意放的？还是有bug？

**Comment by mankind-evolve** [comment]
机器人功能崩  聊天室进不去

**Comment by imndx** [comment]
> 是故意放的？还是有bug？

我们查下一下，不是我们故意放的。

**Comment by imndx** [comment]
> 从android readme下载的官方demo 弹棋牌类广告了

你好，请问你是从什么地方下载的？请把下载链接贴一下

**Comment by mankind-evolve** [comment]
android项目的  readme 里面的demo 扫描下载的

**Comment by imndx** [comment]
> android项目的 readme 里面的demo 扫描下载的

我下载测试了下，没有发现广告呀；会不会是你的网络被劫持了？请你切换到4g网络或者wifi网络试下。

**Comment by mankind-evolve** [comment]
我这里4G wifi都有 389棋牌的一个广告

**Comment by imndx** [comment]
> 我这里4G wifi都有 389棋牌的一个广告

请你截个图看下

**Comment by heavyrain2012** [comment]
是不是其它应用弹的，我们除了JNI的代码没有开放外，其它都开源了，用的都是正常的组件，不可能弹广告的

**Comment by mankind-evolve** [comment]
现在不弹了
