### ISSUE TITLE
图片消息如何获取到图片的宽高，可以使图片加载前占好位

### ISSUE THREAD

**Issue by jeryfer** [wildfirechat/android-chat#486]
图片消息如何获取到图片的宽高，可以使图片加载前占好位

**Comment by jeryfer** [comment]
目前获取到的宽高都是0 好像

**Comment by imndx** [comment]
```ImageMessageContent```里面有```imageWidth```和```imageHeight```，是这两个字段的值一直为0吗？

**Comment by jeryfer** [comment]
我用iOS发的图片，iOS上反正一直是0，然后Android上接收到的时候也是一直0

**Comment by imndx** [comment]
> 我用iOS发的图片，iOS上反正一直是0，然后Android上接收到的时候也是一直0

Android 之间互相发呢？

iOS端发的时候，如果都是0，那就是iOS的问题，请到对应仓库提issue。

**Comment by ThirdPrince** [comment]
宽高 要自己在消息体 带过去就可以
