### ISSUE TITLE
切换手机后消息丢失以及本地sqlite库查看

### ISSUE THREAD

**Issue by bumblebee1024** [wildfirechat/android-chat#492]
在用2部手机测试消息发送时有消息丢失现象。

具体表现为，用A手机登录用户1发了几条消息和接收几条消息后，再用B手机登录用户1，这个时候A手机上的登录会被挤掉线，
然后再次用A手机登录用户1，去消息列表里面会看到用户1发出去的消息丢失了，仅能看到其它用户发给用户1的消息，推测是切换手机登录之后，原A手机上的用户1的旧消息的sqlite库丢失或者在新登录后不读取用户1的旧消息sqlite库了，并且能看到的旧消息是从服务器同步的“最近消息”，不包括自己发出的。

已经确定没有做任何清除类的操作，并且disconnect的cleanSession值一直是false。

我用的开发手机是root过的，所以我把对应用户1的sqlite库文件“data” copy到我自己开发电脑win10上。
然后使用navicat打开，并且从t_user_session表中找到了对应用户1在这个手机上的_db_secret。
navicat报错 “26 - file is encrypted or is not  a database”
不清楚是_db_secret错误还是需要进行转换。
希望能告知使用_db_secret打开库进行数据比较的方法

**Comment by heavyrain2012** [comment]
被踢出后，应用会调用disconnect，需要确保clearSession为false
