### ISSUE TITLE
安卓端-登录后报错

### ISSUE THREAD

**Issue by 14780001553** [wildfirechat/android-chat#494]
java.lang.NullPointerException
Attempt to read from field 'cn.wildfirechat.message.MessageContent cn.wildfirechat.message.Message.content' on a null object reference

偶尔会遇到这个报错，可能是什么引起的呢？

**Comment by imndx** [comment]
请描述下大概是什么情况下会出现，另外请贴出完整错误日志。

**Comment by imndx** [comment]
no response.
