### ISSUE TITLE
目前是否支持消息的导入和导出备份功能

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#497]
目前是否支持消息的导入和导出备份功能？若目前未支持，是否可以通过二次开发实现，以及实现的具体思路是什么

**Comment by imndx** [comment]
请参考[消息备份](https://docs.wildfirechat.cn/blogs/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95%E7%9A%84%E5%A4%87%E4%BB%BD%E4%B8%8E%E6%81%A2%E5%A4%8D.html)
