### ISSUE TITLE
不同版本之间的未知消息类型

### ISSUE THREAD

**Issue by wapalxj** [wildfirechat/android-chat#498]
新版本添加了一种新消息类型，向旧版本发送这个类型的消息，旧版本显示未知类型消息
但是退出聊天页面再进入的时候，这条消息消失了

**Comment by wapalxj** [comment]
是旧版本的 未知类型消息消失了

**Comment by imndx** [comment]
应当已经修复了，请更新到最新代码测试。

**Comment by heavyrain2012** [comment]
之前版本确实是对未知消息处理有问题，最新版本解决了，如果是未知消息，协议栈会根据远端的存储标志位来决定是否存储。UI需要显示messageId不等于0的未知消息。

**Comment by wapalxj** [comment]
感谢，新版本这个问题OK了

**Comment by heavyrain2012** [comment]
直接版本还有些小问题，建议更新到今天或之后的版本
