### ISSUE TITLE
关于一点小建议

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#500]
最近看android端的代码，发现充斥着这样的代码

  if (!allowPrivateChat) {
                Toast.makeText(getActivity(), "禁止群成员私聊", Toast.LENGTH_SHORT).show();
                return;
            }

case TypingMessageContent.TYPING_TEXT:
                typingDesc = "对方正在输入";
                break;
            case TypingMessageContent.TYPING_VOICE:
                typingDesc = "对方正在录音";
                break;
            case TypingMessageContent.TYPING_CAMERA:
                typingDesc = "对方正在拍照";
                break;
            case TypingMessageContent.TYPING_FILE:
                typingDesc = "对方正在发送文件";
                break;
            case TypingMessageContent.TYPING_LOCATION:
                typingDesc = "对方正在发送位置";
                break;

提示的信息没有放入xml文件啊，这十分不利于国际化的翻译啊。求更正

**Comment by imndx** [comment]
你好，感谢你的建议，现在代码里面有一些```hard code```，后续我们会规范一下。

欢迎提交PR。
