### ISSUE TITLE
用android studio4.1.1 gradle6.5 编译本最新源码时报错，但是百度也搜索了一下，没找到合适的解决方案，主要是不知道错在哪了

### ISSUE THREAD

**Issue by 0230826** [wildfirechat/android-chat#501]
以下是报错的错误代码。
**### Could not get unknown property 'manifestOutputDirectory' for task ':chat:processDebugManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.**

**Comment by 0230826** [comment]
已经解决了这个问题了，经过百度查到的外网上的解决方案就是华为的依赖版本低了，升级一下就可以了。项目下的build.gradle

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        **classpath 'com.huawei.agconnect:agcp:1.4.1.300'**
        classpath 'com.jakewharton:butterknife-gradle-plugin:10.2.1'

    }

**Comment by zyzsixsixsix** [comment]
您好，最近在学习这个项目，想问下您下载的版本还有运行的环境可以吗 我这咋样都通过不了编译，谢谢
