### ISSUE TITLE
消息回执问题

### ISSUE THREAD

**Issue by 787408837** [wildfirechat/android-chat#504]
ChatManager.Instance().isReceiptEnabled() 这个一直返回false  服务器已经确认是开启了，所以导致消息已读和未读一直有问题，是专业版的

**Comment by heavyrain2012** [comment]
iOS客户端什么情况，换个手机换个用户是什么情况？

**Comment by 787408837** [comment]
ios客户端没有试  我们试了你们的安卓demo 没有问题 ，我直接在安卓demo上连接我们的imservice服务器也是返回 false 换手机换用户也是一样

**Comment by heavyrain2012** [comment]
服务器有配置回执的开关，需要打开并重新启动，请检查这个。另外你们专业版是什么时候发布的

**Comment by imndx** [comment]
no response
