### ISSUE TITLE
添加朋友后通讯录不更新

### ISSUE THREAD

**Issue by zhanshen1373** [wildfirechat/android-chat#505]
退出重新登陆后，通讯录会更新。
两次调的是同样的方法呀
List<UserInfo> userInfos = ChatManager.Instance().getMyFriendListInfo(false)

**Comment by imndx** [comment]
```ChatManager.Instance().getMyFriendListInfo(true)```，之后会有好友列表更新的通知。

请对比一下我们demo

**Comment by zhanshen1373** [comment]
> `ChatManager.Instance().getMyFriendListInfo(true)`，之后会有好友列表更新的通知。
> 
> 请对比一下我们demo

你们现在代码也是 false，昨天我试了true可以刷新。底层代码是判断了重新登陆后，即使false也更新通讯录吗？

**Comment by imndx** [comment]
```false```时，如果本地还没有去刷新过，也会去拉的。
