### ISSUE TITLE
修改群公告报 -1没有登录

### ISSUE THREAD

**Issue by meihaiwei** [wildfirechat/android-chat#509]
修改群公告报 -1没有登录

**Comment by heavyrain2012** [comment]
应用服务有个配置 wfc.all_client_support_ssl。 如果应用服务支持https，把这个开关打开，然后客户端使用https的应用服务地址。如果应用服务不支持https，把这个开关关掉，然后使用http的地址。测试一下看看，如果还不行，请debug一下应用服务和客户端的认证

**Comment by meihaiwei** [comment]
这个配置在什么位置，我们服务端没有找到

**Comment by meihaiwei** [comment]
wfc.all_client_support_ssl已经关闭了，false，还是不行，还有其他原因吗？

**Comment by imndx** [comment]
no response.
