### ISSUE TITLE
通过时间戳获取消息的方法

### ISSUE THREAD

**Issue by wapalxj** [wildfirechat/android-chat#511]
![image](https://user-images.githubusercontent.com/16435434/104442056-800f2700-55cf-11eb-9d69-6bf92f61daa6.png)

通过这个方法，无论时间戳传什么值都获取不到数据，

另外这个方法是获取本地是数据还是远程数据？

**Comment by imndx** [comment]
获取本地的。

```timestamp```和```before```这两个参数是一起起作用的，请确认一下

**Comment by wapalxj** [comment]
经过多次调试发现，我的对话类型是Single的，传Single没有数据
Arrays.asList(Conversation.ConversationType.Single.getValue()) 获取不到数据

传Single和Group就有数据
Arrays.asList(Conversation.ConversationType.Single.getValue(), Conversation.ConversationType.Group.getValue()),

**Comment by wapalxj** [comment]
并且目前只能获取到文本消息，自定义消息获取不到

**Comment by imndx** [comment]
```withUser```你传的是什么？这个参数表示是和谁之间的会话消息。

**Comment by imndx** [comment]
方法的定义如下，第二个参数是想获取的消息类型列表，不会会话类型列表。
``` 
/**
     * 按照时间戳获取会话消息
     *
     * @param conversation 会话
     * @param contentTypes 消息类型列表
     * @param timestamp    时间戳
     * @param before       true, 获取fromIndex之前的消息，即更旧的消息；false，获取fromIndex之后的消息，即更新的消息。都不包含fromIndex对应的消息
     * @param count        获取消息条数
     * @param withUser     只有会话类型为{@link cn.wildfirechat.model.Conversation.ConversationType#Channel}时生效, channel主用来查询和某个用户的所有消息
     * @param callback     消息回调，当消息比较多，或者消息体比较大时，可能会回调多次
     */
    public void getMessagesByTimestamp(Conversation conversation, List<Integer> contentTypes, long timestamp, boolean before, int count, String withUser, GetMessageCallback callback) 

```

**Comment by wapalxj** [comment]
感谢，是contentTypes 参数我传错了
