### ISSUE TITLE
长时间登录一个账号，退出登录，用另外一个账号登录，偶尔会出现，还是登录之前账号的信息

### ISSUE THREAD

**Issue by meihaiwei** [wildfirechat/android-chat#512]
长时间登录一个账号，退出登录，用另外一个账号登录，偶尔会出现，还是登录之前账号的信息
退出登录的时候我已经这样设置了
 ChatManagerHolder.gChatManager.disconnect(true, false);
        SharedPreferences sp = getSharedPreferences("config", Context.MODE_PRIVATE);
        sp.edit().clear().apply();
        sp = getSharedPreferences("moment", Context.MODE_PRIVATE);
        sp.edit().clear().apply();
        sp = getSharedPreferences("wildfirechat.config", Context.MODE_PRIVATE);
        sp.edit().clear().apply();
        OKHttpHelper.clearCookies();

**Comment by heavyrain2012** [comment]
协议栈内是通过用户id来建立数据库的，理论上不太可能用不同用户登录用的是同一个数据库，目前也没有接到过类似的问题，可能你们那边问题可能性更大一些。请在connect连接之前加上日志（可以在client层调用connect之前打日志），判断一下是否是用新的用户进行登录的。如果能够复现，请转日志给我们分析

**Comment by meihaiwei** [comment]
ChatManagerHolder.gChatManager.connect(   id, token);    返回false，是连接失败吗？但是正常连接了

**Comment by imndx** [comment]
不是，请看注释。
```
    /**
     * 连接服务器
     * userId和token都不允许为空
     * 需要注意token跟clientId是强依赖的，一定要调用getClientId获取到clientId，然后用这个clientId获取token，这样connect才能成功，如果随便使用一个clientId获取到的token将无法链接成功。
     * 另外不能多次connect，如果需要切换用户请先disconnect，然后3秒钟之后再connect（如果是用户手动登录可以不用等，因为用户操作很难3秒完成，如果程序自动切换请等3秒）
     *
     * @param userId
     * @param token
     * @return 是否是新用户。新用户需要同步信息，耗时较长，可以增加等待提示。
     */
    public boolean connect(String userId, String token) 

```
