### ISSUE TITLE
ChatManager中SERVER_HOST能否动态修改

### ISSUE THREAD

**Issue by wapalxj** [wildfirechat/android-chat#514]
由于业务需要，APP会通过接口拿到动态的SERVER_HOST
查看ChatManager并没有提供修改SERVER_HOST的API，
目前只能在Init的时候设置SERVER_HOST，而不能在init完成以后动态修改
能否提供一个修改的API

**Comment by wapalxj** [comment]
另外发现Config.IM_SERVER_HOST的更改会导致connect不成功

首先Config.IM_SERVER_HOST设置为IP1，运行connect(),成功了，
然后更改Config.IM_SERVER_HOST为IP2，运行connect(),一直不成功
需要卸载APP再安装才会成功.

**Comment by heavyrain2012** [comment]
能简单讲一下业务是什么样的，怎么会有这么奇怪的需求？另外更换地址是有多个IM服务吗？当前用户在每个服务器上的ID是同一个吗，还是隔离的？

**Comment by wapalxj** [comment]
因为我们服务的IP地址是会有变化的情况，不能写死一个IP
当前用户在服务器上的ID是同一个，不是个隔离

会在启动APP的时候通过接口获取当前服务的IP，再用这个IP去连接IM，所以需要可以动态设置

**Comment by wapalxj** [comment]
> 能简单讲一下业务是什么样的，怎么会有这么奇怪的需求？另外更换地址是有多个IM服务吗？当前用户在每个服务器上的ID是同一个吗，还是隔离的？

因为我们服务的IP地址是会有变化的情况，不能写死一个IP
当前用户在服务器上的ID是同一个，不是个隔离

会在启动APP的时候通过接口获取当前服务的IP，再用这个IP去连接IM，所以需要可以动态设置

**Comment by wapalxj** [comment]
> 能简单讲一下业务是什么样的，怎么会有这么奇怪的需求？另外更换地址是有多个IM服务吗？当前用户在每个服务器上的ID是同一个吗，还是隔离的？

因为我们服务的IP地址是会有变化的情况，不能写死一个IP
当前用户在服务器上的ID是同一个，不是隔离的

会在启动APP的时候通过接口获取当前服务的IP，再用这个IP去连接IM，所以需要可以动态设置

**Comment by wapalxj** [comment]
> 能简单讲一下业务是什么样的，怎么会有这么奇怪的需求？另外更换地址是有多个IM服务吗？当前用户在每个服务器上的ID是同一个吗，还是隔离的？

因为我们服务的IP地址是会有变化的情况，不能写死一个IP
当前用户在服务器上的ID是同一个，不是隔离的

会在启动APP的时候通过接口获取当前服务的IP，再用这个IP去连接IM,
并且在使用过程中是可以切换账户的，切换账户也需要重写获取新的IM对应的IP
所以需要可以动态设置

**Comment by heavyrain2012** [comment]
是只有两个固定ip吗，还是有无限多个ip的可能

**Comment by wapalxj** [comment]
IP是动态变化的，有无限多个ip的可能

**Comment by wapalxj** [comment]
> 是只有两个固定ip吗，还是有无限多个ip的可能

IP是动态变化的，有无限多个ip的可能

**Comment by wapalxj** [comment]
也会因为地域的变化，连接就近的服务器地址，导致IP地址是动态变化

**Comment by charlesbabyxu** [comment]
你好  这个issue可以被解决吗或有其他方案吗  最近也是被这个问题困扰过  切换IP后连接不稳定 一只以为是自己这边处理问题  现在存在这样需要切换IP的情况

**Comment by heavyrain2012** [comment]
可以用域名，这样的话可以在不同的区域解析成不同的ip

**Comment by charlesbabyxu** [comment]
用户跨地域登录这种情况呢  域名解析最终还是会解析成IP mars缓存 域名并不能解决用户跨地域登录的问题

**Comment by heavyrain2012** [comment]
请加微信 wildfirechat 我们想咨询一下技术细节 这个问题应该能够有办法解决

**Comment by heavyrain2012** [comment]
server.ip 也可以设置为域名，然后这个域名按照地域来解析

**Comment by charlesbabyxu** [comment]
我的理解域名按照地域解析需要dns服务商提供类似的功能，如果地域是国内国外的切换呢，域名按地域解析方案是存在一定难度的。 另关注：后续sdk本身会修改兼容ip切换

**Comment by wapalxj** [comment]
还有另外一个问题
使用ip地址1成功连接了，在代码里修改SERVER_HOST为ip2，运行connect(),没有连接上,但是onConnectionStatusChange()方法也没有任何回调，此时应该要回调一个连接失败的结果吧，因为线上也可能遇到ip失效的情况

**Comment by heavyrain2012** [comment]
因为协议栈有些限制，无法做到实时更改地址。目前推荐的做法就是，客户端设置地址和IM服务配置文件里的server.ip都使用域名，然后根据地域来解析成不同的ip，这样就可以做到不同区域访问不同的地址。

**Comment by charlesbabyxu520** [comment]
使用域名 域名aws是可以的

**Comment by wapalxj** [comment]
这个问题是不是可以解决一下？



> 还有另外一个问题
> 使用ip地址1成功连接了，在代码里修改SERVER_HOST为ip2，运行connect(),没有连接上,但是onConnectionStatusChange()方法也没有任何回调，此时应该要回调一个连接失败的结果吧，因为线上也可能遇到ip失效的情况
