### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by ckelsel** [wildfirechat/android-chat#517]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。
gradle 
Starting a Gradle Daemon, 3 incompatible Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android-chat'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:4.0.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:4.0.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.0.2/gradle-4.0.2.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.0.2/gradle-4.0.2.pom'.
               > Read timed out
   > Could not resolve com.huawei.agconnect:agcp:1.2.1.301.
     Required by:
         project :
      > Could not resolve com.huawei.agconnect:agcp:1.2.1.301.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/huawei/agconnect/agcp/1.2.1.301/agcp-1.2.1.301.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/huawei/agconnect/agcp/1.2.1.301/agcp-1.2.1.301.pom'.
               > Read timed out
   > Could not resolve com.jakewharton:butterknife-gradle-plugin:10.2.1.
     Required by:
         project :
      > Could not resolve com.jakewharton:butterknife-gradle-plugin:10.2.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/10.2.1/butterknife-gradle-plugin-10.2.1.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/10.2.1/butterknife-gradle-plugin-10.2.1.pom'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

#### 预期结果
你认为正确的表现应该是什么样的。

上面的几个链接已经404

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
```Read timed out```

可能是你网络的问题，请确保网络通畅

**Comment by ckelsel** [comment]
https://dl.google.com/dl/android/maven2/com/jakewharton/butterknife-gradle-plugin/10.2.1/butterknife-gradle-plugin-10.2.1.pom，链接已经404，更换下仓库地址
