### ISSUE TITLE
安卓SDK群搜索匹配类型返回有误

### ISSUE THREAD

**Issue by silentpride** [wildfirechat/android-chat#518]
![image](https://user-images.githubusercontent.com/21210520/110902805-66752c00-8341-11eb-81f9-5eac1b838219.png)

群搜索匹配类型有问题。
如截图，matchType返回2，说明是群名和成员皆命中。
搜索关键词是【好】，debug可以看到，群名并不符合搜索条件。

**Comment by heavyrain2012** [comment]
客户端SDK是什么时候的版本，是不是太旧了，我用最新的版本没有测试出来

**Comment by silentpride** [comment]
> 客户端SDK是什么时候的版本，是不是太旧了，我用最新的版本没有测试出来

用的这个3.1提交版本的SDK。
![image](https://user-images.githubusercontent.com/21210520/111247055-52337680-8642-11eb-94cd-49ff1ac5e99d.png)

**Comment by heavyrain2012** [comment]
你在我们demo上测试一下，如果能够测试成功，请在demo上添加 wildfirechat（添加好友，输入wildfirechat，输入完才可以搜索出来） ，然后把我拉进群里，我来测试一下

**Comment by imndx** [comment]
no response.
