### ISSUE TITLE
提示音量太小 与 传送文件档名错误 

### ISSUE THREAD

**Issue by Wei-Lin-77** [wildfirechat/android-chat#519]
＃提示音量太小
收到 信息 与 来电 时所提示的音效太小声

#视频通话麦克风无声音
android 11 测试 

＃传送文件档名错误
android 11测试
档案后缀名PDF，系统无法识别
![69008](https://user-images.githubusercontent.com/42226449/111113117-3bd2df80-859c-11eb-9a95-34cba7c911e0.jpg)

**Comment by imndx** [comment]
提示音量太小
视频通话麦克风无声音
---------
无法复现
