### ISSUE TITLE
删除聊天记录后，再次进入，会话列表的lastMessage获取不到

### ISSUE THREAD

**Issue by wapalxj** [wildfirechat/android-chat#520]
清空或者删除聊天记录后，再进入聊天，这时候会拉取历史聊天记录，但是回到会话列表后，lastMessage获取不到

![image](https://user-images.githubusercontent.com/16435434/111245952-6f674580-8640-11eb-858b-6a7f85169e99.png)

![image](https://user-images.githubusercontent.com/16435434/111246272-e7ce0680-8640-11eb-9268-b4b0acdc19fa.png)

**Comment by heavyrain2012** [comment]
这个是我们这两天引入的一个bug，刚刚修正了，请更新最新的协议栈试一下
