### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by shunFSKi** [wildfirechat/android-chat#521]
![13fe15195f314ec33d18dca45c2a55f](https://user-images.githubusercontent.com/15389700/111273037-49589a00-866e-11eb-810b-79668b7e0a28.png)
在flutter项目中集成sdk，按照文档导入，运行时爆出这个错误，请问是集成的问题吗？

**Comment by heavyrain2012** [comment]
我们有个flutter的sdk，您可以参考一下 https://github.com/wildfirechat/flutter_imclient。建议使用这个，如果可以的话

**Comment by shunFSKi** [comment]
主要是需要音视频通话的功能。。。
