### ISSUE TITLE
服务端调用 subscribe方法报错

### ISSUE THREAD

**Issue by Acier** [wildfirechat/android-chat#523]
报405异常,请修复谢谢.
cn.wildfirechat.sdk.ChannelServiceApi.subscribe 方法报错!

**Comment by heavyrain2012** [comment]
server 最新版本已经添加了频道api的接口，你们可以更新测试一下。
更新需要注意几个地方
1. 你们版本太旧了，直接更新太危险，需要先在测试服务验证过再升级
2. 升级前备份，以便出了问题能够及时回滚
3. 升级时检查升级兼容说明，有群组的说明还有修复sql的语句需要执行
4. 频道的权限问题，以前频道没有权限限制，现在有显示，详情参考 https://docs.wildfirechat.net/base_knowledge/channel.html。可能需要对现有频道的权限进行手动修改
