### ISSUE TITLE
链接状态与server的错误码对应关系

### ISSUE THREAD

**Issue by wapalxj** [wildfirechat/android-chat#526]
请问下前后端的这个连接code的有对应关系吗

server端code: 
   CONNECTION_ACCEPTED((byte) 0x00),
    CONNECTION_REFUSED_UNACCEPTABLE_PROTOCOL_VERSION((byte) 0X01),
    CONNECTION_REFUSED_IDENTIFIER_REJECTED((byte) 0x02),
    CONNECTION_REFUSED_SERVER_UNAVAILABLE((byte) 0x03),
    CONNECTION_REFUSED_BAD_USER_NAME_OR_PASSWORD((byte) 0x04),
    CONNECTION_REFUSED_NOT_AUTHORIZED((byte) 0x05),
    CONNECTION_REFUSED_UNEXPECT_NODE((byte) 0X06),
    CONNECTION_REFUSED_SESSION_NOT_EXIST((byte) 0x07);

android端code:
public interface ConnectionStatus {
    int ConnectionStatusSecretKeyMismatch = -6;
    int ConnectionStatusTokenIncorrect = -5;
    int ConnectionStatusServerDown = -4;
    int ConnectionStatusRejected = -3;
    int ConnectionStatusLogout = -2;
    int ConnectionStatusUnconnected = -1;
    int ConnectionStatusConnecting = 0;
    int ConnectionStatusConnected = 1;
    int ConnectionStatusReceiveing = 2;
}

**Comment by heavyrain2012** [comment]
没有对应关系
