### ISSUE TITLE
群聊获取不到自己的消息

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#532]
正常聊天的时候没有问题

一退出程序重新进来，从服务器拉取消息以后，就获取不到自己的消息了

请问应该从哪些方面进行排查，请指点一下

**Comment by mankind-evolve** [comment]
以前的老版本发的群聊可以拉取自己的消息    更新了最新的版本就不行了。

**Comment by heavyrain2012** [comment]
服务器版本换到最新版本试试

**Comment by mankind-evolve** [comment]
我也注意到可能是这个问题。 不知道怎么升到最新的版本
