### ISSUE TITLE
调用移除群成员函数removeGroupMembers()可否回调 赋值List<GroupMember> members？

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#534]
// IRemoteClient   
 mClient.setOnGroupMembersUpdateListener(new IOnGroupMembersUpdateListener.Stub() {
                    @Override
                    public void onGroupMembersUpdated(String groupId, List<GroupMember> members) throws RemoteException {
                        ChatManager.this.onGroupMembersUpdate(groupId, members);
                    }
  });
添加群成员addGroupMembers()，回调onGroupMembersUpdated(String groupId, List<GroupMember> members)函数中members 已经赋值，请在调用removeGroupMembers()，一系列回调函数中中赋值  List<GroupMember> members 参数，谢谢。

**Comment by heavyrain2012** [comment]
刚刚更新的协议栈解决了这个问题，请更新代码验证
