### ISSUE TITLE
好友申请拒绝无响应？需要调用二次才会修改FriendRequest 中 status 属性

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#536]
调用 ChatManager.Instance().handleFriendRequest(String friendId,boolean accept)函数，传入 accept = false ，返回onSuccess() 后，当前申请 FriendRequest 对应状态值 （status  = 0 ），再次点击 传入 false 才会更新 FriendRequest   对应状态值 （status  = 2 ），麻烦帮忙看一下？

**Comment by heavyrain2012** [comment]
刚刚更新的协议栈解决了这个问题，请更新代码验证
