### ISSUE TITLE
多次发送好友申请一直失败sendFriendRequest()

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#537]
调用 ChatManager.Instance().sendFriendRequesttargetUid, message, )申请添加好友函数后，不管对方有没有处理这个申请请求，再次发送都会返回失败状态，可否调整为对方拒绝、或者之前申请请求过期再次调用添加好友申请返回成功状态，麻烦帮忙看一下？

**Comment by heavyrain2012** [comment]
请查看 https://docs.wildfirechat.cn/faq/general.html 问题3
