### ISSUE TITLE
请问野火的音视频拨打、接听、挂断分别执行了那些逻辑呢。

### ISSUE THREAD

**Issue by xfjxfj** [wildfirechat/android-chat#538]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
1、我在自己的项目中调用  WfcUIKit.singleCall(context1, userid, isAudioOnly) 这个方法就可以实现拨打电话和视频的功能，然后再WfcUIKit这个类中的startActivity这个方法里面把Intent main = new Intent(context.getPackageName() + ".main");替换成Intent main = new Intent(context,SingleCallActivity.class);。这样就可以接听视频了  如果不改这个方法则无法弹出接听页面。
2、现在出现的问题如下
      a  被拨打方 点击接听视频，拨打方显示已经“对方已取消”
     b  被拨打方 点击接听、点击挂断无反应
     c  拨打视频电话，被拨打方点击切换到语音通话后  点击接听和点击挂断无反应
    d  拨打视频电话  拨打方点击挂断后，被拨打方无反应  依旧在等待接听界面
    e   刚刚点击登录  然后给其拨打电话无反应   等待几分钟后 打视频  对方可以跳出界面 并且可以接听视频电话
    f	第二次拨打电话   被拨打方接听电话  页面直接闪退
#### 表现现象
现象现在就是基本音视频电话没有办法使用。

#### 预期结果
预期的效果我以为是 双方可以互打电话互发视频

#### 补充条件
在被拨打方  如果是第一次进入  则可以接听视频。但是偶尔也接听不到。项目服务器使我们自己公司部署的。我也把贵公司的项目中的服务器地址替换成我们自己公司服务器地址。功能是完好的。所以是我本地出的问题

#### demo对比结果
demo中使用我们自己公司部署的服务器是正常的。

**Comment by imndx** [comment]
1. 不能弹出接听界面，可能是AndroidManifest.xml里面```SingleCallActivity```的```intent-filter```不对
2. ```Config.java```里面的```ICE_SERVERS```保持demo的原有配置测试一下。

**Comment by xfjxfj** [comment]
服务器配置应该是没问题的  我们公司还有其他项目在用贵公司的sdk  现在flutter已经跑通了，拨打电话没有我这个问题，就很奇怪

**Comment by imndx** [comment]
> 谢谢 看到了 不过音视频通话现在还是有问题。具体表现在：A设备登录过后 立刻B设备给A设备打视频打不通，等几分钟过后可以打通，还有就是A设备挂断后，感觉页面是强制退出的，然后B设备给A设备打电话打不通，等几分钟可以弹出接听界面，但是点击接听按钮第一次无反应，第二次直接退出 我想请问下这后面的server是在那里去调用的

-----------
这个和im server没关系。
请测试一下你们的turn服务，是否正常。[turn 服务测试](https://docs.wildfirechat.cn/webrtc/trickle-ice/)

如果正常的话，请将拨打方和接听方的日志，都附上，我们分析一下

**Comment by imndx** [comment]
请将拨打方和接听方的日志，都附上，我们分析一下

**Comment by heavyrain2012** [comment]
> > 谢谢 看到了 不过音视频通话现在还是有问题。具体表现在：A设备登录过后 立刻B设备给A设备打视频打不通，等几分钟过后可以打通，还有就是A设备挂断后，感觉页面是强制退出的，然后B设备给A设备打电话打不通，等几分钟可以弹出接听界面，但是点击接听按钮第一次无反应，第二次直接退出 我想请问下这后面的server是在那里去调用的
> 
> 这个和im server没关系。
> 请测试一下你们的turn服务，是否正常。[turn 服务测试](https://docs.wildfirechat.cn/webrtc/trickle-ice/)
> 
> 如果正常的话，请将拨打方和接听方的日志，都附上，我们分析一下

测试一下turn服务状态，然后再换成我们的turn服务测试一下

**Comment by heavyrain2012** [comment]
这个查出来了，是我们SDK的问题，更新一下avenginekit.aar就好了

**Comment by xfjxfj** [comment]
更新了  我这边再看下  非常感谢
