### ISSUE TITLE
群聊天发送消息后会收到SettingUpdateListener事件

### ISSUE THREAD

**Issue by wapalxj** [wildfirechat/android-chat#543]
群内一个用户每发送一条消息后，其他用户会收到SettingUpdateListener事件
这里发送消息应该和SettingUpdateListener无关吧？

**Comment by heavyrain2012** [comment]
IM服务问题，请下载最新代码编译验证，修改请参考 https://github.com/wildfirechat/server/commit/40e9d108ad1a5d52115d6538ed353da4cca3922f

**Comment by imndx** [comment]
no response.
