### ISSUE TITLE
uikit打成ARR报错

### ISSUE THREAD

**Issue by scsfwgy** [wildfirechat/android-chat#546]
因为野火安卓源码很多，并且底层不需要修改，所以我的想法是把 module：uikit打成arr,直接引入到项目。但是引入后提示缺少文件。

![image](https://user-images.githubusercontent.com/16045179/118928496-e0471880-b975-11eb-89b7-ce486fe54e78.png)

ikit引用的库，比如：avenginekit 代码都没有。

![image](https://user-images.githubusercontent.com/16045179/118928515-e806bd00-b975-11eb-867c-f857449590f5.png)

**Comment by imndx** [comment]
1. ```avenginekit```是闭源的。
2. ```UIKit```部分目前不支持打包成aar
