### ISSUE TITLE
你好我想参考一下 avenginekit 的代码，请问在哪里可以找到？

### ISSUE THREAD

**Issue by licoba** [wildfirechat/android-chat#547]
#### 操作说明
我下载了Android-chat的源码在本地运行

#### 表现现象
看到代码
```
AVEngineKit.Instance().startCall(conversation, Collections.singletonList(targetId), isAudioOnly, null);
```
的时候，发现在AVEngineKit的库里面，这个库是加了混淆的。

#### 预期结果
期望AVEngineKit也能够开源，做到真正的开源

#### 补充条件
谢谢！

**Comment by heavyrain2012** [comment]
这个库是我们购买的使用权，无法用来开源，但您可以免费使用这个库，用在商业用途也没有关系。我们是一家商业公司，有员工薪水和公司运转的资金压力，所以就需要有部分闭源和收费，这样也能够确保我们能够长期坚持把项目做下去，请您理解。

**Comment by licoba** [comment]
好的！知道了
