### ISSUE TITLE
安装新用户，或者切换新用户登录第一次获取用户信息返回name = "用户"(NullUserInfo)

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#548]
ChatManager.Instance().getUserInfos(ids, groupId);
返回 NullUserInfo 对象
请帮忙看看此问题，谢谢。

**Comment by imndx** [comment]
```getUserInfos```会先从本地获取用户信息，当本地不存在时，会直接返回```NullUserInfo```，然后去服务端拉取，当拉取成功之后，通过```UserInfosUpdate```进行通知。

另外，获取用户信息，也有回调版本的API，通过回调返回用户信息。
```    public void getUserInfo(String userId, boolean refresh, GetUserInfoCallback callback) ```
