### ISSUE TITLE
群引用消息，引用消息不显示（必现）

### ISSUE THREAD

**Issue by scsfwgy** [wildfirechat/android-chat#549]
群消息
安卓客户端发引用消息:另外安卓和iOS客户端都可以看到引用消息。
iOS客户端发引用消息:另外安卓引用消息不显示，但是iOS引用消息显示正常。
必现的，请看一下。

**Comment by heavyrain2012** [comment]
iOS端的问题，已经修正 https://github.com/wildfirechat/ios-chat/commit/f1cfafa75354aa268fdfa14037f5a44d3bee397d 请更新iOS代码验证

**Comment by scsfwgy** [comment]
好的
