### ISSUE TITLE
安卓5.1系统，无法调节音量

### ISSUE THREAD

**Issue by beyond1008** [wildfirechat/android-chat#551]
音量大小无法调节，调用的是语音通话类型？
以下是设置音量的代码，帮忙分析下是哪里有问题，谢谢。

        int callMaxVolume;
        AudioManager  audioaManager = (AudioManager) MyApp.getContext().getSystemService(Context.AUDIO_SERVICE);
        audioaManager .setMode(AudioManager.MODE_IN_CALL);
        callMaxVolume = audioaManager .getStreamMaxVolume(AudioManager.STREAM_VOICE_CALL);//最大值为5
        int volume = audioaManager .getStreamVolume(AudioManager.STREAM_VOICE_CALL);
        volume++;
        if (volume >= callMaxVolume) {
            volume = callMaxVolume;
        }
        Log.i(TAG, "当前音量 " + volume +" 最大音量 " + callMaxVolume);
        audioaManager .setStreamVolume(AudioManager.STREAM_VOICE_CALL, volume, 0);

**Comment by imndx** [comment]
你好，现在不用在上层控制```mode```，请更新测试。
