### ISSUE TITLE
群成员更新回调

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#553]
// 设置群成员改变的监听
 mClient.setOnGroupMembersUpdateListener(new IOnGroupMembersUpdateListener.Stub() {
           @Override
            public void onGroupMembersUpdated(String groupId, List<GroupMember> members) throws RemoteException {
                        ChatManager.this.onGroupMembersUpdate(groupId, members);
            }
 });
OnGroupMembersUpdateListener会持续调用（频率很高），返回参数 List<GroupMember> groupMembers，能否修改为
添加群成员、移除群成员 赋值，其它情况 groupMembers 不赋值，方便对接者在此监听处理距离业务逻辑，目前好像群成员未发生改变时 groupMembers 参数返回固定值，因为监听频繁调用导致处理业务逻辑卡顿，谢谢。

**Comment by heavyrain2012** [comment]
请抓日志给我们分析一下，抓协议栈日志，抓日志的方法文档常见问题里有，从启动开始抓，发送到邮箱support@wildfirechat.cn 谢谢
