### ISSUE TITLE
如果先加入黑名单后删除好友，再次申请添加好友一直失败

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#554]
/**
     * 发送好友请求
     *
     * @param userId
     * @param reason
     * @param callback
     */
    public void sendFriendRequest(String userId, String reason, String extra, final GeneralCallback callback) {
        if (!checkRemoteService()) {
            if (callback != null){
                callback.onFail(ErrorCode.SERVICE_DIED);
            }
            return;
        }

        try {
            mClient.sendFriendRequest(userId, reason, extra, new cn.wildfirechat.client.IGeneralCallback.Stub() {
                @Override
                public void onSuccess() throws RemoteException {
                    if (callback != null) {
                        mMainHandler.post(new Runnable() {
                            @Override
                            public void run() {
                                callback.onSuccess();
                            }
                        });
                    }
                }

                @Override
                public void onFailure(final int errorCode) throws RemoteException {
                    if (callback != null) {
                        mMainHandler.post(new Runnable() {
                            @Override
                            public void run() {
                                callback.onFail(errorCode);
                            }
                        });
                    }
                }
            });
        } catch (RemoteException e) {
            e.printStackTrace();
            if (callback != null){
                mMainHandler.post(() -> callback.onFail(ErrorCode.SERVICE_EXCEPTION));
            }
        }
    }

测试过如果先从黑名单里面移除，再调用添加好友可以成功，
先判断是否属于黑名单用户，如果已添加至黑名单，先移除黑名单，然后我们在调用添加好友？
还是SDK层调整一下，谢谢。

**Comment by heavyrain2012** [comment]
对的，应该先移出黑名单，再添加好友
