### ISSUE TITLE
可否配置不存储消息至客户端DB

### ISSUE THREAD

**Issue by RadiumCao** [wildfirechat/android-chat#556]
安卓客户端可否配置只拉取远程消息，不使用手机DB存储消息，退出app后本地不存留。

**Comment by imndx** [comment]
什么场景下有这种需求？

可以这样尝试下：

每种类型的消息定义的时候，都有一个```flag```标识，配置为```No_Persist```时，将不会存储。

**Comment by heavyrain2012** [comment]
> 什么场景下有这种需求？
> 
> 可以这样尝试下：
> 
> 每种类型的消息定义的时候，都有一个`flag`标识，配置为`No_Persist`时，将不会存储。

如果本地不存储消息，则数据库不会维护会话了，需要自己来维护会话
