### ISSUE TITLE
表情包的国际化

### ISSUE THREAD

**Issue by scsfwgy** [wildfirechat/android-chat#558]
现在的表情实现是assets下读取sticker。能否像drawable的国际化玩法一样，默认读取sticker，英文读取sticker-en?
或者有什么好的思路实现表情包的国际化？

**Comment by heavyrain2012** [comment]
可以的，打包多套环境，启动时检查语言然后拷贝对应的资源，这样本地是什么语言，发出去的表情就是什么语言。

但这样也有个问题，接收方可能语言不匹配，比如发送方是英语，接收方是中文收到的也是英语表情。如果要想改变这种情况，可能就需要重构目前的实现方式了

**Comment by scsfwgy** [comment]
能实现第一点就行了。这个也是产品提的需求，产品有国外用户。
我感觉这个是个伪需求，本身聊天就是双方交互的，国际化这一块很难做的完美。微信这么大的产品，切换到英文，还随处可见中文的。
