### ISSUE TITLE
Fox:退出群后没有及时刷新conversationlistdata

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#56]
![image](https://user-images.githubusercontent.com/7382234/60606050-35fb9180-9ded-11e9-8fce-a2ae7c1aa376.png)

**Comment by yuzhongrong** [comment]
需要杀死app后重新进入方可 去掉coversation

**Comment by yuzhongrong** [comment]
嗯

**Comment by imndx** [comment]
解决，等待服务端上线。

**Comment by yuzhongrong** [comment]
好的 服务器上线了 那就可以关闭了
