### ISSUE TITLE
demo 登录后闪退到登录界面

### ISSUE THREAD

**Issue by Adgeros** [wildfirechat/android-chat#560]
是自己部署的服务器，ip访问的（我们的地址会闪退，官方的不会，是我们部署的不对吗）
模拟器 android 11
登录后就闪退
编译后装手机上也闪退到登录界面

**Comment by Adgeros** [comment]
找到问题，是配置问题，有两个地方需要配置域名

**Comment by imndx** [comment]
请关注日志输出。

当配置错误时，会进行提示，并退出应用。
