### ISSUE TITLE
将demo集成到应用app之后，出现用iOS demo来语音呼叫Android，Android内部无法自动弹出等待接听页面

### ISSUE THREAD

**Issue by CHparis** [wildfirechat/android-chat#561]
#### 操作说明
将demo代码集成到我们的业务app中，登录、发消息这些显示正常，但是当我用iOS demo客户端语音呼叫Android用户的时候，消息可以收到，无法弹出Android等待接听的界面。

#### 表现现象
iOS demo呼叫Android客户端，无法在app内自动弹出等待接听的页面。IM消息的接收是正常的，Android app呼叫iOS demo双方也是正常的。

#### 预期结果
能够正常弹出等待接听的页面。由于代码量比较庞大，希望能告知这个弹出页面的控制代码是在哪里的，我好自己去进行排查问题。

#### 补充条件
是毕现的。

#### demo对比结果
demo是一切正常的。

**Comment by imndx** [comment]
请先看下[Android常见问题](https://docs.wildfirechat.cn/faq/android.html)第5、6个问题

**Comment by CHparis** [comment]
根据5、6问题检查了一下，看起是没有问题的，
我的场景是这样的，我先运行了一下demo，demo可以正常的运行起来，对方语音呼叫我，也是正常的可以弹出被呼叫的页面，
但是当我把一系列的module集成到我们自己的应用之后，其他的IM功能是正常的，就这个被呼叫的时候，无法弹出这个被呼叫的等待页面。

**Comment by imndx** [comment]
可以从```WfcUIKit.onReceiveCall```开始查，这是收到音视频通话邀请在UI层的入口。

采用```intent-filter```方式启动```Activity```，请确认下这儿的```action```和```AndroidManifest.xml```里面定义的是否一致。
