### ISSUE TITLE
音视频问题咨询

### ISSUE THREAD

**Issue by shunFSKi** [wildfirechat/android-chat#562]
您好
我在集成音视频的过程中有些问题咨询，请有空时给我提供一些解决思路和方向：
1、安卓端在我自己的工程中集成音视频最近出现了接通后接收方依然会有铃声直到挂断，或者过了几十秒后自动断开，没有什么明显错误log，我自己猜测是没有连接成功
2、我在遇到上述问题后，去github下载了最新版本的代码测试，互相拨打的时候接收方通话页面一闪而过（用的是野火的服务，没有改任何代码），iOS和安卓端拨打也是接通自动挂断
最后感谢野火的开源服务，希望能给我提供任何可能的思路指导我解决上述问题，祝工作生活顺利。

**Comment by imndx** [comment]
#378 
我怀疑和这个issue类似，请你给我们提供一份完整的日志分析下

**Comment by shunFSKi** [comment]
[main.log](https://github.com/wildfirechat/android-chat/files/6800436/main.log)
[marsservice.log](https://github.com/wildfirechat/android-chat/files/6800438/marsservice.log)

**Comment by imndx** [comment]
你好，上面的日志不太完整。

请你微信添加一下：wfchat ，他来看下这问题吧

**Comment by ChandlerZeng** [comment]
问题解决了吗，我也遇到这个问题了，方便说下怎么解决的吗？
