### ISSUE TITLE
三星手机F52，安卓11,点击通知跳转到聊天页面，crash

### ISSUE THREAD

**Issue by msn465780** [wildfirechat/android-chat#564]
三星手机F52，安卓11,点击通知跳转到聊天页面，crash, 提示是聊天界面获取不到conversation对象，空指针
WfcNotificationManager.java

Intent mainIntent = new Intent(context.getPackageName() + ".main");
            Intent conversationIntent = new Intent(context, ConversationActivity.class);
            conversationIntent.putExtra("conversation", message.conversation);
            PendingIntent pendingIntent = PendingIntent.getActivities(context, notificationId(message.conversation), new Intent[]{mainIntent, conversationIntent}, PendingIntent.FLAG_UPDATE_CURRENT);
            String tag = "wfc notification tag";
            showNotification(context, tag, notificationId(message.conversation), title, pushContent, pendingIntent);

ConversationActivity.java
private void init() {
        Intent intent = getIntent();
        conversation = intent.getParcelableExtra("conversation");
        // conversation是空对象
        String conversationTitle = intent.getStringExtra("conversationTitle");
        long initialFocusedMessageId = intent.getLongExtra("toFocusMessageId", -1);
        if (conversation == null) {
            finish();
        }
        conversationFragment.setupConversation(conversation, conversationTitle, initialFocusedMessageId, null);
    }

**Comment by imndx** [comment]
能必现吗？可以加点日志调试下

**Comment by 511430890** [comment]
我有三星S11，点击通知栏的消息也会闪退。  是因为点击通知栏时候，通过PendingIntent 传值到 ConversationActivity 传不过去。
   Intent conversationIntent = new Intent(context, ConversationActivity.class);
            conversationIntent.putExtra("conversation", message.conversation);
            conversationIntent.putExtra("conversationTitle", "conversationTitle");

在 ConversationActivity中 获取下面的值都是空的。
           conversation = intent.getParcelableExtra("conversation");
        String conversationTitle = intent.getStringExtra("conversationTitle");

**Comment by 511430890** [comment]
> 能必现吗？可以加点日志调试下

我有三星S11，点击通知栏的消息也会闪退。 是因为点击通知栏时候，通过PendingIntent 传值到 ConversationActivity 传不过去。
Intent conversationIntent = new Intent(context, ConversationActivity.class);
conversationIntent.putExtra("conversation", message.conversation);
conversationIntent.putExtra("conversationTitle", "conversationTitle");

在 ConversationActivity中 获取下面的值都是空的。
conversation = intent.getParcelableExtra("conversation");
String conversationTitle = intent.getStringExtra("conversationTitle");
