### ISSUE TITLE
会议缩小后会显示白色小方块

### ISSUE THREAD

**Issue by wenxuancheung** [wildfirechat/android-chat#567]
Redmi K20 Pro Android 10 

会议缩小后会显示白色小方块
![6c90b6972cca73489a06a4c0ad8a75d](https://user-images.githubusercontent.com/34408245/126585679-2e75c838-1548-4a89-9e7f-4486481c59a5.jpg)

**Comment by heavyrain2012** [comment]
跟手机有关系吗，换其他手机是什么情况

**Comment by wenxuancheung** [comment]
> 跟手机有关系吗，换其他手机是什么情况

和手机无关，安卓都有这种情况

**Comment by imndx** [comment]
请更新最新代码测试一下
