### ISSUE TITLE
发起会议后会议发起者APP闪退

### ISSUE THREAD

**Issue by 1wum2ing2** [wildfirechat/android-chat#568]
安卓会议发布者发起会议之后窗口悬浮，参与者（多人）参与会议之后也悬浮窗口，会议发起者APP会闪退
[wfc.log](https://github.com/wildfirechat/android-chat/files/6860619/wfc.log)

**Comment by imndx** [comment]
请更新最新代码测试

**Comment by imndx** [comment]
no response.
