### ISSUE TITLE
群公告功能bug

### ISSUE THREAD

**Issue by weilaishangweizhi** [wildfirechat/android-chat#569]
获取群公告
接口(/get_group_announcement)报错，返回值 code:13,mes:没有登录
public void getGroupAnnouncement(String groupId, AppServiceProvider.GetGroupAnnouncementCallback callback)

修改群公告
接口（/put_group_announcement）报错，返回值 code:13,mes:没有登录
public void updateGroupAnnouncement(String groupId, String announcement, AppServiceProvider.UpdateGroupAnnouncementCallback callback)

调用方法中并未看到有传递用户信息或者token的参数

**Comment by imndx** [comment]
请将android代码和app server都更新到最新

**Comment by imndx** [comment]
no response.
