### ISSUE TITLE
使用SM4加密方式，token解密失败

### ISSUE THREAD

**Issue by Janseon** [wildfirechat/android-chat#571]
操作说明：
Android 端调用SDK的useSM4()后，使用后端返回的sm4加密的token，调用setAuthInfo和connect后，连接不上，返回连接状态为-5，表示token不正确。

我们后端为开源版的。
请问后端如何对token进行sm4的加密才能保证app端能够解密成功？例如：使用哪种加密模式、是否使用iv参数、密钥是什么？
或者能否说明一下sdk的使用sm4的解密需要的参数和流程？

**Comment by heavyrain2012** [comment]
国密只有在专业版上才支持，如果想用国密加密，请购买或者试用专业版。另外野火不建议自己修改社区版代码，如果修改社区版代码，我们将不在提供任何的技术支持了，因为修改了就跟我们版本分裂，对我们只有坏处没有好处，另外改了什么样我们也不知道，两眼一抹黑的情况下是没有办法做技术支持的。

多说一句，我们是商业化的公司，有员工需要养、公司也需要花钱的，是有资金压力的。所以需要在免费和收费之间平衡。一方面在普适性的功能方面尽可能的免费使用，现在绝大用户都使用手机，所以手机方面也免费，来满足大部分人的需求；另外一方面我们只在一些小的边缘的点上收点费用，用于员工和公司的支出，毕竟再美好的愿望也要先吃饭吧，而且我们的产品绝对是良心价了，价格只是市场上同等质量下产品的几十分之一，如果我们公司无法继续下去将会是大家的损失，所以请在力所能及范围内帮助我们一些。

多说了几句，还请见谅，感谢一直以来对我们的支持！
