### ISSUE TITLE
Android 添加群成员调用addgroupMembers方法中传入extra，但消息中没有带过来extra，还是为空

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#572]
添加群成员时addgroupMembers方法中传入extra，但消息中没有带过来extra，还是为空

**Comment by heavyrain2012** [comment]
添加群组成员的方式是public void addGroupMembers(String groupId, List<String> memberIds, String memberExtra, List<Integer> lines, MessageContent notifyMsg, final GeneralCallback callback)。

其中memberExtra为gropmember的extra，如果要在通知消息中加extra，请使用notifyMsg中的extra，请注意notifyMsg需要使用AddGroupMemberNotificationContent
