### ISSUE TITLE
视频通话音频无法传输

### ISSUE THREAD

**Issue by Re1nnman** [wildfirechat/android-chat#577]
#### 操作说明
视频通话

#### 表现现象
画面正常，A设备音频无法正常传到B设备，B设备音频可以传到A设备

#### 预期结果
音频可以正常传输

#### 补充条件
问题设备Android8.1，网络环境为WiFi，问题必现，版本为2021/08/16最新版

#### demo对比结果
问题就是在demo上产生的
[marsserviver.log](https://github.com/wildfirechat/android-chat/files/6991561/marsserviver.log)
[main.log](https://github.com/wildfirechat/android-chat/files/6991562/main.log)

**Comment by imndx** [comment]
请用最新代码测试。
