### ISSUE TITLE
后台群主解散群操作

### ISSUE THREAD

**Issue by liuzgAs** [wildfirechat/android-chat#578]
后台调用群解散功能，并设置不删除会话，解散后web端和ios端会话列表还存在，安卓端会话列表被删除。

**Comment by heavyrain2012** [comment]
IM服务的版本发布日期和客户端从github上取下来的日期分别是多少

**Comment by heavyrain2012** [comment]
专业版IM服务在2021.1.4号之后才支持的，请确认im服务日志

**Comment by liuzgAs** [comment]
使用的最新版本

**Comment by heavyrain2012** [comment]
IM服务的版本是多少

**Comment by liuzgAs** [comment]
> IM服务的版本是多少

{
 "tags":"null",
 "branch":"fe1795bfa33286b05474c864725c73f28a8f03e4",
 "dirty":"null",
 "remoteOriginUrl":"https://github.com/heavyrain2012/server_commercial.git",
 "commitId":"fe1795bfa33286b05474c864725c73f28a8f03e4",
 "commitIdAbbrev":"fe1795b",
 "describe":"v0.20-1002-gfe1795b-dirty",
 "describeShort":"null",
 "commitUserName":"heavyrain2012",
 "commitUserEmail":"heavyrain.lee@gmail.com",
 "commitMessageFull":"解决server api创建群组有部分参数无效问题\n",
 "commitMessageShort":"解决server api创建群组有部分参数无效问题",
 "commitTime":"20210701150045",
 "nodeIds":"1 ",
 "closestTagName":"null",
 "closestTagCommitCount":"null",
 "buildUserName":"imndx",
 "buildUserEmail":"imndxx@gmail.com",
 "buildTime":"20210701152633",
 "buildHost":"null",
 "buildVersion":"null",
 "verified":true
}

**Comment by heavyrain2012** [comment]
经确认是Android端的问题，在Android客户端过滤了找不到群信息的会话，最新版本已经修改
