### ISSUE TITLE
android 首次安装点击联系人- 新的朋友 100%崩溃，app重启后正常

### ISSUE THREAD

**Issue by morning-sir** [wildfirechat/android-chat#58]
手机：redmi 6
安卓版本：8.1
MIUI版本: 10.3.2

android 首次安装点击联系人- 新的朋友 100%崩溃，app重启后正常
初步怀疑是某个缓存值没有初始化

**Comment by yuzhongrong** [comment]
我们不会华为 小米都不会 你排查下 什么原因

**Comment by imndx** [comment]
未能复现，能否提供日志？

**Comment by wangsanpiao** [comment]
我又把这个问题报了个issue。。。。，空指针，adpater为Null
