### ISSUE TITLE
最新AS版本 4.2 打开野火安卓demo无法运行 报错

### ISSUE THREAD

**Issue by JohnConstine** [wildfirechat/android-chat#583]
已经添加过了android.useAndroidX=true；android.enableJetifier=true；
还是会报错This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.versionedparcelable:versionedparcelable:1.1.0, androidx.fragment:fragment:1.2.0, com.google.android.material:material:1.3.0-alpha01, androidx
![image](https://user-images.githubusercontent.com/33423607/132443532-f5ffce76-61a4-4269-9fe8-2628ed4b88a5.png)

![image](https://user-images.githubusercontent.com/33423607/132443544-cda09f86-c354-4a92-9944-10c67cbd3ba4.png)

**Comment by imndx** [comment]
请在```gradle.properties```里面，加入下面两行测试一下：
```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by JohnConstine** [comment]
你好 我已经加入了 还是出了问题










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/android-chat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wildfirechat/android-chat] 最新AS版本 4.2 打开野火安卓demo无法运行 报错 (#583)





 
请在gradle.properties里面，加入下面两行测试一下：
 android.useAndroidX=true android.enableJetifier=true  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JohnConstine** [comment]
刚刚我同事使用AS4.0.1打开无误 所以我使用这个版本吧

**Comment by imndx** [comment]
OK
