### ISSUE TITLE
关于android使用gradle4.0以上版本打包冲突的问题

### ISSUE THREAD

**Issue by xiaolongzhangloveLol** [wildfirechat/android-chat#585]
因为我们的工程使用的是gradle4.1，将咱们的mars库的aar合入之后，会导致出现以下问题：
![6281631678243_ pic](https://user-images.githubusercontent.com/4065903/133379607-a531c379-fe4d-4b50-8458-3e6de625cbaf.jpg)

我们查了一下官方问题，是这么说明的：
https://developer.android.com/studio/releases/gradle-plugin#cmake-imported-targets

更明确的解决方案有：
https://blog.csdn.net/guiying712/article/details/109600490

主要是要去掉外部so库的指定path，在4.0以上不用再配置了 

还麻烦尽快处理下，这个影响到我们对外正式打包，非常感谢

**Comment by imndx** [comment]
你好，我们使用的版本信息如下：

```com.android.tools.build:gradle:4.0.2```

```Gradle 6.1.1```
