### ISSUE TITLE
寻求类似抖音的聊天系统的实现思路

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#594]
抖音im的系统  是随便都可以发信息，但是呢。如果对方不回信的话，只能发三条。只要对方回信就可以随便发了。    我想用现成的野火实现这个功能

这个思路要怎么实现呢？ 

我也思考了一些方案，就是用serverapi检查对方不是好友，

如果不是好友，就看一下给对方发了几条信息，如果三条了就不让再发了。

如果对方发消息，就自动用serverapi添加好友，然后就一切正常了

这个思路关键的一条是现成的IM系统里有没有查询对方发了几条信息的功能   如果再用另外的系统去记录就有点太乱了

**Comment by mankind-evolve** [comment]
还有没有更好的实现思路，请大佬指点一下

**Comment by imndx** [comment]
是不是可以通过```getRemoteMessages``` 获取远程历史消息来判断

**Comment by heavyrain2012** [comment]
这个记录一下很简单的，比如在应用服务记录，用户发一条就增1。用户每次发之前先检查是不是好友，如果是好友就正常流程，如果不是好友就去应用服务获取发了几条，如果超过规定条数就提示不能发，如果没有超过就发送发送成功后在调用应用服务接口加一。回复也很容易，检查是不是好友，如果不是好友且是回复，调用用用服务，应用服务调用添加好友

**Comment by mankind-evolve** [comment]
是不是可以通过getRemoteMessages 获取远程历史消息来判断

我觉得这个方案会比较简单，而且不用另外侵入应用服务器的逻辑。 我试一下。
