### ISSUE TITLE
华为推送app接收不到推送

### ISSUE THREAD

**Issue by wl532882877** [wildfirechat/android-chat#595]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***
服务器配置了推送appID,和密钥 获取了华为token
#### 操作说明
在app端向另一台手机发送消息 （处在后台），确定允许通知，在状态栏显示，横幅，允许打扰和允许自启动、运行后台活动都已打开的情况下
#### 表现现象
在华为开发者平台上测试通知，app 端能收到通知，如果在app端像另一台手机发消息，没有收到通知

#### 预期结果
app在后台的情况下，会收到横幅通知

#### 补充条件
是最新版的野火im  huawei P9  android 8.0

#### demo对比结果
demo 也是没有收到推送

**Comment by imndx** [comment]
1. 确认调用华为推送初始成功，并成功调用```ChatManager.setDeviceToken```，初始化相关代码在```PushService```
2. ```push server```上查看日志，看是否向华为推送，有没有什么错误提示
2. 华为手机上，采用透传方式，需要在 手机管家 里面设置，允许自启动等

**Comment by imndx** [comment]
no response.
