### ISSUE TITLE
第一次进入没有问题,第二次进入后一直重连失败,因为也没有具体的报错原因,有没有什么排错的方法

### ISSUE THREAD

**Issue by clbDream** [wildfirechat/android-chat#60]

**Comment by imndx** [comment]
需要日志，才能更快定位问题。

**Comment by clbDream** [comment]
他这个也没有报错日志,就是第二次进入APP之后开始初始化,在走到connection的时候 连接状态就成连接失败了,我打断点看了IM账号和token都存在,是这个token再次进入的时候需要从新请求吗,还是用第一次登陆的就可以,,第一次进入APP登陆之后所有的功能都是正常的,点击返回键退出应用再次进入APP也是正常的,只有完全杀死进程,然后再次进入APP就会一直连不上

**Comment by clbDream** [comment]
而且,如果这个时候再执行一次退出重新登录并重新连接的话,可以连接成功,可以监听到新消息的到来,但是会话列表是空的,getConversationList获取到的列表是空的,需要看哪部分代码,我可以截图
![image](https://user-images.githubusercontent.com/28987014/60754509-96b8e300-a014-11e9-9fde-9227999d08a9.png)

**Comment by clbDream** [comment]
初始化代码
![image](https://user-images.githubusercontent.com/28987014/60754524-d4b60700-a014-11e9-99e4-8af58972d79c.png)
![image](https://user-images.githubusercontent.com/28987014/60754526-dbdd1500-a014-11e9-903c-20472cc8bba3.png)
登录成功后执行连接IM的操作
![image](https://user-images.githubusercontent.com/28987014/60754540-07f89600-a015-11e9-84c2-2bdde18aa566.png)
退出登录
![image](https://user-images.githubusercontent.com/28987014/60754543-13e45800-a015-11e9-974a-f68b0dd843b2.png)

**Comment by imndx** [comment]
我看不出有什么错误。

第一次和第二次调用```connect(String userId, String token)```确定参数是一样的吗？

**Comment by clbDream** [comment]
是一样的,第一次登陆之后,我就用SP保存了,然后第二次启动时,从SP中取出来进行的connect

**Comment by clbDream** [comment]
我找到了一小部分原因,就是杀死进程之后,重新进入,在连接的时候mClient是null,所以没有连接成功,我找到这个mClient的初始化是在绑定服务的时候,但是绑定的时候,没有绑定成功,所以造成了连接失败,


![Uploading image.png…]()

**Comment by clbDream** [comment]
但是这个服务绑定一直不成功一般会是什么原因造成的

**Comment by skpy5272** [comment]
打印下sp的取值  应该是空的

**Comment by clbDream** [comment]
账号和Token我看了,重新进入的时候并不是空的
![image](https://user-images.githubusercontent.com/28987014/61118854-31f60080-a4cc-11e9-8870-200e67dbca0b.png)

**Comment by clbDream** [comment]
主要是调用这个connect的时候mClient并未有初始化完成,直到connect结束后才初始化完,而这个时候已经不调用connect了,但是不知道为什么进入APP之后 自动重连一直显示连接失败

**Comment by imndx** [comment]
connect的时候，会把userId和token给保存下来，如果此时mClient为空，会等服务bing绑定之后，再次调用connect

**Comment by clbDream** [comment]
问题就出在这里,等到服务bing成功后,mClient确实初始化了,但是通过打断点发现,并没有再次调用connect,是还需要在哪里做什么操作吗

**Comment by clbDream** [comment]
而且我手动调用connect的时候也没有连接状态的回调

**Comment by skpy5272** [comment]
我也遇见过 把SP存取 使用他提供的 就好了

**Comment by clbDream** [comment]
我改成了他的还是不行

**Comment by clbDream** [comment]
主要是连接状态报-6,不知道该从哪下手

**Comment by clbDream** [comment]
我用DEMO连我部署的IM服务,都正常,应该是客户端的问题,但是就是找不到问题在哪

**Comment by imndx** [comment]
检查的token和clientId是否匹配

**Comment by clbDream** [comment]
clientId每次杀死进程重新进入APP,都会发生改变,这个地方需要做什么处理吗,是需要把这个值在本地保存还是需要进程保活?看了一下源码,还是不太懂clientId的生成机制

**Comment by imndx** [comment]
无法复现。
