### ISSUE TITLE
两台android 手机 登录相同账户连接回调状态问题

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#604]
两台android 手机 登录相同账户， onConnectionStatusChange(int status) 函数 监听回调 返回状态 码 0 和 1 ；
之前还会调用 -2;  （ int ConnectionStatusLogout = -2;  连接状态 注销），今天替换了client  + mars-core-release 就初夏这个问题了，
请帮忙看看此问题，谢谢。

**Comment by heavyrain2012** [comment]
同一个账户两个android端登陆会互踢才对，默认情况下一个用户只能在一个移动客户端登陆。IM服务的配置文件中有是否允许多端登陆，建议保持现在的状态，除非特殊需求
