### ISSUE TITLE
扫描群二维码加群页面，会loading很久的问题

### ISSUE THREAD

**Issue by KingOfHui** [wildfirechat/android-chat#605]
#### 操作说明

扫描群二维码，然后回跳转到群信息页面(GroupInfoActivity)，此时偶尔会出现loading很久的情况。这个页面的代码就是原始的demo里的代码，没有任何的改动。

#### 表现现象

这个页面会loading很久
![image](https://user-images.githubusercontent.com/30006239/145156875-70944080-b23a-4c2b-90d6-2a828631ab50.png)

#### 预期结果

预期：像正常情况一样扫码之后获取到正确的群成员信息。

#### 补充条件

这是一个偶现的问题，或者说还没找到有什么规律，在正常的手机设备上出现的。安卓代码使用的版本为v0.9.0版本

**Comment by imndx** [comment]
最终，loading对话框会消失，并显示出操作按钮来不？

**Comment by KingOfHui** [comment]
> 最终，loading对话框会消失，并显示出操作按钮来不？

最终loading不会消失，一直在loading。

**Comment by imndx** [comment]
有一种可能是加载群成员信息失败，但我们也复现不了。

可以加个超时控制，如果加载超时了，给个提示，让用户重新扫码。
