### ISSUE TITLE
多端登录撤回消息，lastMessag的问题

### ISSUE THREAD

**Issue by wapalxj** [wildfirechat/android-chat#608]
配置了多端登录，IOS和android 同时登录一个账号，其中一端把倒数第二条消息撤回了，
另外一端会话列表的lastMessage会变成消息已撤回
![fffffff](https://user-images.githubusercontent.com/16435434/146307858-4803ceb4-f29c-4173-8f2c-b1f286f810e6.png)

**Comment by imndx** [comment]
杀进程，重启之后，会恢复正常吗？

**Comment by wapalxj** [comment]
> 杀进程，重启之后，会恢复正常吗？

杀进程，重启，重新安装APP都不会恢复

**Comment by heavyrain2012** [comment]
已经解决，请更新最新版本验证
