### ISSUE TITLE
关于android的自定义消息原始信息

### ISSUE THREAD

**Issue by AFAP** [wildfirechat/android-chat#609]
你好，自定义消息是继承与MessageContent的，也定义了消息类型是大于1000的数字，也有无参构造器，目前遇到的问题就是Parcel这个类型无法看到里面具体的信息，有没有什么办法能够查看收到的原始信息呢。

其实对于服务器来说消息都是一样的，仅作传递，现在就是想如何在android中调试查看未区分类型前的原始信息。

**Comment by imndx** [comment]
1. 自定义消息需要实现```Parcelable```接口，实现过程可以通过```Android Parcelable Code Generator```生成相关代码，具体可以参考 ```TextMessageContent```。
2. 如果仅仅是想看原始信息，可以在```ClientService#onReceiveMessage```打断点或者加调试信息查看
