### ISSUE TITLE
avenginekit.aar中缺少getSelectedAudioDevice

### ISSUE THREAD

**Issue by fanershuai** [wildfirechat/android-chat#613]
## 编译问题
编译之后，真机运行，avenginekit.aar中缺少getSelectedAudioDevice
![1640250453094](https://user-images.githubusercontent.com/17716872/147217583-e5292154-1f26-4241-9a6c-1446f6381059.jpg)

**Comment by heavyrain2012** [comment]
请更新到最新代码测试
