### ISSUE TITLE
魅族的push包出现问题了  

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#614]
发布googleplay的时候提示一下的错误。 我看了下魅族的包更新到了4.1了。改动还挺大

您的应用中存在不安全的解压缩模式，可能会导致路径遍历安全漏洞。请参阅这篇 Google 帮助中心文章，了解如何解决此问题。  com.meizu.cloud.pushsdk.notification.util.ZipExtractTask.unzip

**Comment by mankind-evolve** [comment]
https://support.google.com/faqs/answer/9294009

**Comment by imndx** [comment]
你可以先把魅族推送相关的移除了。

考虑到魅族市场占有率越来越低，我们可能会将其移除，你们自行对接。
