### ISSUE TITLE
Execution failed for task ':chat:processDebugManifest'.

### ISSUE THREAD

**Issue by hu-lielie** [wildfirechat/android-chat#615]
> Could not get unknown property 'manifestOutputDirectory' for task ':chat:processDebugManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by hu-lielie** [comment]
安卓编译的时候一直报这个错误，不知道是哪里的问题。我用的是最新的Android studio

**Comment by imndx** [comment]
需要更多信息，大概率是环境问题。

可以在命令行下，执行：```./gradlew clean aR```试下
