### ISSUE TITLE
a1

### ISSUE THREAD

**Issue by SakuraLuLua** [wildfirechat/android-chat#617]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by SakuraLuLua** [comment]
#操作说明
群聊多人视频
#表现现象
如果多人音视频通话用户一直未接通 
用户1超时自动挂断 
用户2一直连接中
#预期结果
超过一定时间未接通，用户自动挂断

**Comment by imndx** [comment]
使用的是自行部署的的 turn 服务，还是我们提供的？
