### ISSUE TITLE
Fox:群聊头像没有显示多个人，只显示一个人

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#62]
![image](https://user-images.githubusercontent.com/7382234/60763620-c1557b00-a0aa-11e9-8f7a-33658d0bd84d.png)

**Comment by yuzhongrong** [comment]
之前是可以的 现在 修改什么东西不行了 ，搞的我都不敢更新了

**Comment by imndx** [comment]
最新代码上面，没复现
