### ISSUE TITLE
频道聊天记录远程会话无法删除

### ISSUE THREAD

**Issue by lxwlxw111** [wildfirechat/android-chat#621]
#### 操作说明
频道->会话详情->清除聊天记录->清除远程会话
#### 表现现象
删除远程会话后，退出频道聊天，再打开依旧存在聊天记录。
#### 预期结果
清空远程会话后，退出频道聊天，再打开聊天记录不存在。
#### 补充条件
必现

**Comment by heavyrain2012** [comment]
频道信息是没有办法清除远程消息的，所以频道这个清除远程消息功能应该删除掉 @imndx
