### ISSUE TITLE
搜索结果里头像正确，但会话列表和单个会话中，显示头像错误

### ISSUE THREAD

**Issue by qdhaiqiang** [wildfirechat/android-chat#622]
#### 操作说明
后台修改了机器人(type=1)用户头像，在app搜索结果里头像是对的.
但是在会话列表和单个会话中，不显示头像。

#### 表现现象
在搜索结果里头像是对的，但是在会话列表和单个会话中，不显示头像。

#### 预期结果
都显示正确的头像

#### 补充条件
服务端版本：0.55
安卓客户端打log，发现头像是https://avatars.io/gravatar/+_uid的值，实际上数据库已经修改了。

 #### 截图

**Comment by qdhaiqiang** [comment]
服务重启过，没有管用。

**Comment by heavyrain2012** [comment]
忘记说了，修改数据时，_dt要加1，这个是版本号，根据这个来同步到客户端的

**Comment by qdhaiqiang** [comment]
了解了，这样就没有问题了。

以后尽量还是用api来操作数据。

谢谢。

**Comment by qdhaiqiang** [comment]
了解了，这样就没有问题了。

以后尽量还是用api来操作数据。

谢谢。
