### ISSUE TITLE
UpdateRemoteMessageContent is returning error in Android 

### ISSUE THREAD

**Issue by LuckyBuyAsif** [wildfirechat/android-chat#627]
**Issues**
UpdateRemoteMessageContent(Function) in ChatManager(Class) is returning errorCode=248 (Android)

**Instructions.**
When I call:-
ChatManager.Instance().updateRemoteMessageContent(messageUid,messageContent,distribute(true),updateLocal(true)) // From ChatManager class...
**Returns:-**
errorCode =248 //correct parameters and content   

(ChatManager line no 4605)
**Expected Results;**
This method should work and also reflect changes to other end both in single and group chat 	

**Supplementary Conditions**
this is happending all the time.

**P.S:**
we are using professional version

**Comment by heavyrain2012** [comment]
请检查此函数的说明：
```
    /**
     * 更新远程消息消息内容，只有专业版支持。客户端仅能更新自己发送的消息，更新的消息类型不能变，更新的消息类型是服务配置允许更新的内容。Server API更新则没有限制。
     *
     * @param messageUid     消息的UID
     * @param messageContent 消息内容
     * @param distribute     是否分发给其他客户端
     * @param updateLocal    是否更新本地消息内容
     * @param callback       操作结果回调
     */
```
客户端更新需要满足3个条件：
1，自己发送的消息
2，消息类型不能变更
3，IM服务配置中添加允许客户端更新消息类型。

使用server api更新消息则没有任何限制

**Comment by LuckyBuyAsif** [comment]
3，IM服务配置中添加允许客户端更新消息类型。
Where is I'm service configuration.? Is this is on the server I did not find on the client.

**Comment by LuckyBuyAsif** [comment]
Thanks we got the solution
