### ISSUE TITLE
怎么更改android默认的http接口的80　端口呢

### ISSUE THREAD

**Issue by clywm520** [wildfirechat/android-chat#629]

**Comment by imndx** [comment]
端口必须用80，因为IM是一个比较有风险的软件，需要备案使用，确保处于监管之下。

如果是政企等可信单位，因安全等原因，确实不能使用 80 端口，请邮件联系我们。

**Comment by toxmc** [comment]
意思是最底层native c那层写死端口了是吗？

**Comment by imndx** [comment]
> 意思是最底层native c那层写死端口了是吗？

是的
