### ISSUE TITLE
想问一下，app本地的表结构在哪可以看到！

### ISSUE THREAD

**Issue by zombiu** [wildfirechat/android-chat#63]
公司用的是websocket，不能使用mars去连接处理。

**Comment by imndx** [comment]
协议栈部分加密了，看不了。

基于websocket的js SDK开发中

**Comment by zombiu** [comment]
感谢回复！

**Comment by zombiu** [comment]
@imndx  大佬 我想问一下，表结构这类的信息是开源的吗，如果可以的话，再哪可以看到！
