### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by dyjAndroid** [wildfirechat/android-chat#632]
权限问题
<uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS" />
sdk中包含此权限，导致华为审核无法通过，请修改
![11](https://user-images.githubusercontent.com/20662698/157350020-42482063-b14a-4497-9742-ebe94de39552.jpg)

**Comment by heavyrain2012** [comment]
因为野火有音视频通话功能，需要处理跟电话的冲突，所以就有这个权限。是不是可以跟商店解释一下。
我们稍后会把这段处理冲突的代码从音视频库中移动到kit中，这样如果无法通过商店的解释，可以自行去掉这个权限
