### ISSUE TITLE
铃声问题

### ISSUE THREAD

**Issue by dyjAndroid** [wildfirechat/android-chat#633]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
测试机：小米12，Android版本 Android 12
收到视频或者语音请求，没有声音
拨打视频或者语音电话，没有声音

#### 表现现象
没有声音

#### 预期结果
应该播放来电铃声或者去电铃声

#### 补充条件
必现

#### demo对比结果
就是用Demo测试的 0.9.3版本

**Comment by imndx** [comment]
我手上没有有 Android 12 的设备，用模拟器测试一下，发现响铃正常的。

响铃相关方法是```WfcUIKit#shouldStartRing```，你们可以调试一下。

**Comment by imndx** [comment]
可以用最新代码，或者最新的 demo 测试一下

**Comment by dyjAndroid** [comment]
好的
