### ISSUE TITLE
密信搜索，会搜到已不存在的群聊（包括已经退出、列表已删除的群）

### ISSUE THREAD

**Issue by daiyyyyyyy** [wildfirechat/android-chat#635]
在密信搜索框中，输入搜索内容，会展示出已不应该存在的群聊。
比如：已经退出的群聊，在此处搜索群内某成员昵称，依旧能搜到该群，并能打开该群。

**Comment by heavyrain2012** [comment]
在野火客户端的数据库中，消息和会话表是分开的，当搜索消息时，没有考虑会话情况。所以如果需要不能搜索不存在的会话，需要：
1. 在客户端删除会话时，同时清空此会话的消息。默认是只删除会话，改成清空消息。
2. 在群解散或者退出群时，需要也同时删除消息，IM服务相关配置，是否在被踢或者解散时删除消息。

这样只能解决以后的群组消息搜索，以前的没有办法处理了。
