### ISSUE TITLE
插入消息问题

### ISSUE THREAD

**Issue by liuzgAs** [wildfirechat/android-chat#636]
安卓最新SDK，先insertMessage插入一条消息，再调用sendSavedMessage发送该消息，会话的lastMessage还是上一条消息没有改变

**Comment by heavyrain2012** [comment]
“会话的lastMessage”中的会话是内存中的会话，还是重新从数据库读取出来的会话？插入消息应该数据库中的会话的最后一条消息已经更新了，但UI上需要一个通知来让UI层从新从数据库中加载

**Comment by liuzgAs** [comment]
调用getConversationList刷新会话列表，现在情况是insertMessage插入一条消息，再调用sendSavedMessage发送该消息，调用getConversationList会话的lastMessage没有改变，该会话也没有到最顶部，getMessages有这条消息

**Comment by heavyrain2012** [comment]
我提交了测试代码在 issue636分支，我们测试都是正常的，你们检查一下测试代码。另外sendSavedMessage也更新了一些通知状态。

**Comment by liuzgAs** [comment]
> 我提交了测试代码在 issue636分支，我们测试都是正常的，你们检查一下测试代码。另外sendSavedMessage也更新了一些通知状态。

解决了，服务器时间问题，我获取的服务器时间，传0成功了
