### ISSUE TITLE
使用官方的野火IM，版本号demo 41 0.9.4 通话时候闪一下就中断

### ISSUE THREAD

**Issue by gitxiaohua** [wildfirechat/android-chat#638]
**下载官方的野火IM，版本号demo 41 0.9.4 ，使用小米，华为，手机相互呼叫对方视频通话正常，后台挂超过20秒使用oppo手机呼叫后闪一下白色自动进入到app内，我拍的有视频，请看附件

https://user-images.githubusercontent.com/60765479/158110164-6d43b971-e85a-4539-af28-db6bfeb384c8.mp4

**Comment by heavyrain2012** [comment]
我们手上没有这个型号的手机，请帮我们抓一下日志吧

**Comment by gitxiaohua** [comment]
> 我们手上没有这个型号的手机，请帮我们抓一下日志吧

好的谢谢，那个手机占时不在
