### ISSUE TITLE
野火IM能不能修改被呼叫时候的提示铃声

### ISSUE THREAD

**Issue by gitxiaohua** [wildfirechat/android-chat#639]
1.野火IM官方版本能不能修改被呼叫时候的提示铃声

2.我这边也有之前购买过版本，如何修改被呼叫时候的提示铃声
如果可以修改那么，能不能预设多个声音可以选择

**Comment by gitxiaohua** [comment]
> 你说的是呼出的铃声还是来电的铃声？在WfcUIKit.java中有个处理播放的函数shouldStartRing(boolean isIncoming)，另外如果有通知栏推送，还需要处理一下推送的提示音

我这边呼出的铃声和来电的铃声都想修改

**Comment by imndx** [comment]
铃声文件在：```uikit/src/res/raw```目录下，可以替换一下。

**Comment by gitxiaohua** [comment]
> 铃声文件在：`uikit/src/res/raw`目录下，可以替换一下。

好的谢谢
