### ISSUE TITLE
0.93相比0.94修改了哪些功能？

### ISSUE THREAD

**Issue by gitxiaohua** [wildfirechat/android-chat#640]
我这边用过源码进行编译过视频通话不稳定，最近测试0.94版本发现比0.93版本视频通话相对比之前稳定很多，想了解下修改了哪些内容

**Comment by imndx** [comment]
下面是 0.9.3 到 0.9.4的提交日志。
```
更新用户在线状态 imndx Today 4:14 下午
not sign when release heavyrian2012 2022/3/13, 9:57 下午
会议界面，不应当显示观众 imndx 2022/3/12, 4:59 下午
更新音会议相关提示信息 imndx 2022/3/12, 11:20 上午
update version imndx 2022/3/11, 3:20 下午
将电话相关权限移到上层 fix #632 imndx 2022/3/11, 2:18 下午
fix https://github.com/wildfirechat/android-chat/issues/634  https://github.com/wildfirechat/android-chat/issues/631 heavyrian2012 2022/3/11, 10:21 上午
fix https://github.com/wildfirechat/android-chat/issues/636 heavyrian2012 2022/3/11, 10:20 上午
修复连接状态回到可能错误问题 imndx 2022/3/10, 8:28 下午
更新会议 UI imndx 2022/3/10, 8:28 下午
update avengine imndx 2022/3/3, 3:27 下午
fix PendingIntent issue imndx 2022/3/3, 2:45 下午
用户在线状态 imndx 2022/3/2, 3:33 下午
fix imageMessageContent issue imndx 2022/3/2, 11:22 上午
修复屏幕共享ui 问题 imndx 2022/2/21, 10:35 下午
屏幕共享支持单独的 pc imndx 2022/2/17, 6:24 下午
在mars进程bind成功之前，跨进程调用不可用 heavyrian2012 2022/3/2, 11:14 上午
update proto heavyrian2012 2022/2/24, 12:44 下午
撤回消息显示错误. fix #626 imndx 2022/2/18, 11:12 上午
fix #621 imndx 2022/2/12, 10:30 下午
注释 heavyrian2012 2022/2/11, 11:06 上午
注释 heavyrian2012 2022/2/10, 10:06 上午
update dependency imndx 2022/1/27, 8:52 下午
异步获取会话列表 imndx 2022/1/25, 3:12 下午
update avengine imndx 2022/1/25, 9:46 上午
fix async getMessages issue imndx 2022/1/20, 11:32 上午
fix async getMessages issue imndx 2022/1/19, 8:48 下午
解决消息过大时，多次回调消息处理错误问题 heavyrian2012 2022/1/19, 8:15 下午
fix 兼容 java7 imndx 2022/1/19, 10:42 上午
```

**Comment by gitxiaohua** [comment]
> 下面是0.9.3到0.9.4的提交日志。
> 
> ```
> 更新用户在线状态 imndx Today 4:14 下午
> not sign when release heavyrian2012 2022/3/13, 9:57 下午
> 会议界面，不应当显示观众 imndx 2022/3/12, 4:59 下午
> 更新音会议相关提示信息 imndx 2022/3/12, 11:20 上午
> update version imndx 2022/3/11, 3:20 下午
> 将电话相关权限移到上层 fix #632 imndx 2022/3/11, 2:18 下午
> fix https://github.com/wildfirechat/android-chat/issues/634  https://github.com/wildfirechat/android-chat/issues/631 heavyrian2012 2022/3/11, 10:21 上午
> fix https://github.com/wildfirechat/android-chat/issues/636 heavyrian2012 2022/3/11, 10:20 上午
> 修复连接状态回到可能错误问题 imndx 2022/3/10, 8:28 下午
> 更新会议 UI imndx 2022/3/10, 8:28 下午
> update avengine imndx 2022/3/3, 3:27 下午
> fix PendingIntent issue imndx 2022/3/3, 2:45 下午
> 用户在线状态 imndx 2022/3/2, 3:33 下午
> fix imageMessageContent issue imndx 2022/3/2, 11:22 上午
> 修复屏幕共享ui 问题 imndx 2022/2/21, 10:35 下午
> 屏幕共享支持单独的 pc imndx 2022/2/17, 6:24 下午
> 在mars进程bind成功之前，跨进程调用不可用 heavyrian2012 2022/3/2, 11:14 上午
> update proto heavyrian2012 2022/2/24, 12:44 下午
> 撤回消息显示错误. fix #626 imndx 2022/2/18, 11:12 上午
> fix #621 imndx 2022/2/12, 10:30 下午
> 注释 heavyrian2012 2022/2/11, 11:06 上午
> 注释 heavyrian2012 2022/2/10, 10:06 上午
> update dependency imndx 2022/1/27, 8:52 下午
> 异步获取会话列表 imndx 2022/1/25, 3:12 下午
> update avengine imndx 2022/1/25, 9:46 上午
> fix async getMessages issue imndx 2022/1/20, 11:32 上午
> fix async getMessages issue imndx 2022/1/19, 8:48 下午
> 解决消息过大时，多次回调消息处理错误问题 heavyrian2012 2022/1/19, 8:15 下午
> fix 兼容 java7 imndx 2022/1/19, 10:42 上午
> ```

好的谢谢，不好意思我还想了解下 0.93更新日志，我还想了解下这个能不能在哪里看到更新的日志
