### ISSUE TITLE
updateMessage更新消息问题

### ISSUE THREAD

**Issue by liuzgAs** [wildfirechat/android-chat#641]
从Sending状态更新到Sent正常，更新到Send_Failure的时候回调的onMessageUpdate里面消息状态没有更新

**Comment by heavyrain2012** [comment]
没有明白什么意思？能详细描述一下操作和状态吗

**Comment by liuzgAs** [comment]
> 没有明白什么意思？能详细描述一下操作和状态吗

ChatManager.Instance().updateMessage(message.messageId, MessageStatus.Send_Failure);调用这个方法的时候回调的onMessageUpdate里面消息状态没有更新；ChatManager.Instance().updateMessage(message.messageId, MessageStatus.Sent);正常
