### ISSUE TITLE
三星手机，息屏语音通话crash

### ISSUE THREAD

**Issue by dyjAndroid** [wildfirechat/android-chat#643]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
三星Galaxy Note9， 启动应用，回到主界面，打开最近任务列表，清空所有，锁屏，向这台手机发起语音通话，主进程crash

#### 预期结果
可以正常收到通话

必现

#### demo对比结果
本次测试使用Demo 0.9.4版本
[野火bug.txt](https://github.com/wildfirechat/android-chat/files/8346737/bug.txt)

**Comment by imndx** [comment]
你好，请查下手机是不是有什么日志级别相关设置，感觉日志不完整，看不出什么有用信息。

另外，抓取日志的时候，建议使用: ```adb logcat > test.log```进行抓取。

**Comment by dyjAndroid** [comment]
[log3.txt](https://github.com/wildfirechat/android-chat/files/8347638/log3.txt)
重新抓了下，麻烦看下

**Comment by imndx** [comment]
[6724e81](https://github.com/wildfirechat/android-chat/commit/6724e819535311eb381829f8ec767cbd0baa15d5)

请更新到最新代码测试一下

**Comment by imndx** [comment]
应当解决了，如果测试还有问题，请重新打开此 issue
