### ISSUE TITLE
关于getUserInfos 频繁调用报错问题

### ISSUE THREAD

**Issue by hzbx** [wildfirechat/android-chat#644]
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/16591739/162356850-5828544c-2589-4da0-b06e-e95d09b5a78b.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/16591739/162356889-d1763e3f-0c45-4e33-91dc-1bcae238ab49.png">

**Comment by hzbx** [comment]
200人的群，批量获取所有用户数据，就会容易报错

**Comment by imndx** [comment]
> 200人的群，批量获取所有用户数据，就会容易报错

你说的批量调用，是怎调用？

调用 ```getUserInfos```方法，一次就能获取到了。

**Comment by VincentJ1989** [comment]
场景：查看消息已读未读人数列表，短时间多次进入这个列表页面(会调用getUserInfos，一次性获取200人),就会报错

**Comment by VincentJ1989** [comment]
> > 200人的群，批量获取所有用户数据，就会容易报错
> 
> 你说的批量调用，是怎调用？
> 
> 调用 `getUserInfos`方法，一次就能获取到了。

场景：查看消息已读未读人数列表，短时间多次进入这个列表页面(会调用getUserInfos，一次性获取200人),就会报错
