### ISSUE TITLE
音视频功能问题反馈

### ISSUE THREAD

**Issue by Neroliuxx** [wildfirechat/android-chat#651]
官方DEMO，两台华为机型互相拨通，收听方都显示没有应用可执行此操作。且拨打Android12手机后，将会直接闪退。

**Comment by imndx** [comment]
你好。

是用我们编译好的 apk 测试的，还是自己编译的？

其他手机上什么情况呢？

**Comment by Neroliuxx** [comment]
自己编译的 同样ios的官方demo也拨不通，ios手机点击通话后自动结束，已经测试过安卓和ios通话和两台ios手机通话了。

**Comment by Neroliuxx** [comment]
ios最新代码编译出来的可以和安卓和ios通话，appstore上的demo不可以。

**Comment by Neroliuxx** [comment]
目前测试 Android手机接听都显示
![Screenshot_20220425-111621](https://user-images.githubusercontent.com/35095175/165015999-b8f502e4-d847-4ed3-b6d7-11d2dbbc79a8.jpg)
