### ISSUE TITLE
请问弱网情况上传图片

### ISSUE THREAD

**Issue by heli-boop** [wildfirechat/android-chat#658]
你好 我们的网络环境走专网 只有10kb/s的样子（相当于gsm网络）。所以在上传图片的时候，想自己做切片上传（目前社区版图片是传不上去的） ，不知道是否可行。如果可行的话，从哪里入手呢，能否给个解决方案或者建议

**Comment by heavyrain2012** [comment]
10kb/s的带宽太低了，是不是可以考虑不要用图片和头像等所有消耗流量的功能了。如果要是想发图片就不能依赖协议栈发送，可以在上层上传，上传成功后，把远程地址写入消息体，最后发送。详细流程如下：
1，用户点击上传，不要调用协议栈的发送接口，先保存消息，消息的状态是发送中。
2，这时用你们自己的方法上传图片，需要你们自己部署文件服务，把文件上传，注意上传进度作为发送消息进度。
3，上传成功后，得到文件链接，调用接口修改消息内容，把链接写入到messagepayload的remoteUrl中。
4，调用sendSavedMessage方法发送消息

**Comment by heli-boop** [comment]
> 

你好 我现在先insertMessage  ,让后调用自己的上传接口，上传之后设置remoteUrl，再调用sendSavedMessage；这个流程对吗？但是sendSavedMessage的调用 ，回调函数不响应
