### ISSUE TITLE
自定义消息扩充

### ISSUE THREAD

**Issue by liuhuanbo** [wildfirechat/android-chat#660]
期望可以基于野火实现类似钉钉审批消息提醒的消息功能，请问下社区版或者专业版支持吗，支持的话，如何扩充，不支持的话，能否二开扩展？另附上图
![WechatIMG118](https://user-images.githubusercontent.com/9410051/170165720-0c10005a-29de-4630-92b2-c6f04a9ee7e7.jpeg)

**Comment by heavyrain2012** [comment]
目前有个RichNotificationContent消息与这个UI比较接近，可以参考这个消息进行自定义消息
