### ISSUE TITLE
官方demo  杀死app后接收不到推送消息

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#663]
发现这个bug是因为我正常用的app杀死后，接收不到推送消息了，push后端《推送版本0.1.2》的控制台显示已经推送成功了，就是收不到。  走的FMS通道，两个手机都是一加9R    都已经科学上网   。

然后试了一下官方的DEMO，在杀死的状态下都没有收到，是后台没有开放FMS通道还是代码里面有什么问题？

**Comment by imndx** [comment]
> 后台没有开放FMS通道还是代码里面有什么问题？
-------------
后台没有任何限制，相关代码，你们都是能够看到的，可以自行调试下。

另外：
默认 oppo 手机会走 oppo 推送，这个是在```PushService.java```设置的
