### ISSUE TITLE
如图所示，内容扩充

### ISSUE THREAD

**Issue by liuhuanbo** [wildfirechat/android-chat#664]
下面名片后面想扩充功能，社区版本代码不支持修改，专业版可以扩充吗？如果均不可能如何处理
![WechatIMG127](https://user-images.githubusercontent.com/9410051/171079424-84d52d46-01bf-4106-a7e7-b2ea3e314cc2.jpeg)
？

**Comment by imndx** [comment]
首先，只有 [im-server](https://github.com/wildfirechat/im-server) 有社区版和专业版之分。

这个问题和 im-server 没关系，是客户端的功能，相关代码都是开源的，支持自行扩充扩展功能的，具体请参考```UserCardExt.java```的实现。
