### ISSUE TITLE
自建应用如何和原生APP交互。

### ISSUE THREAD

**Issue by liuhuanbo** [wildfirechat/android-chat#665]
如图所示，自建应用和原生应用有交互，参数传递这些如何处理，自建应用和原生如何交互，自建应用如何调用原生应用现有的功能，比如回话里面的发送名片，位置等。
![WechatIMG142](https://user-images.githubusercontent.com/9410051/171366243-a40720c2-18e7-4b89-b618-3ad83cfcc43d.jpeg)

**Comment by liuhuanbo** [comment]
目前需求也是出于调研阶段，暂时还不完整，那现在有个低一点的方式处理，就是在点击上图中的测试功能，能否不需要二次登录，意思就是点击测试功能拿到APP本身登录的的用户信息。

**Comment by imndx** [comment]
可以的，日报那个 demo，就实现了免密登录

**Comment by liuhuanbo** [comment]
那个有没有移动端demo，初步看了下是web端的示例。

**Comment by imndx** [comment]
> 那个有没有移动端demo，初步看了下是web端的示例。

日报那个 demo，是个 web 应用，是用来演示野火开放平台能力的，可以用在移动端和 pc 端，里面有免密登录流程。

**Comment by liuhuanbo** [comment]
好的，谢谢
