### ISSUE TITLE
点击自建应用无法无响应

### ISSUE THREAD

**Issue by liuhuanbo** [wildfirechat/android-chat#668]
日报服务已启动，开放平台里已经配置了应用，移动端工作台也显示出来了，点击创建的应用无响应，如图所示，目前定位不到问题出现在哪块，请求协助处理下。
![WechatIMG159](https://user-images.githubusercontent.com/9410051/172576757-b9d5472f-f9b4-4fc7-8068-ecfcdfb03bad.jpeg)
![WechatIMG161](https://user-images.githubusercontent.com/9410051/172576772-d7b1b3a1-8448-479c-b7e8-929b650c2f0d.jpeg)

**Comment by imndx** [comment]
> 点击创建的应用无响应

是开放平台吗？看下控制台日志

**Comment by liuhuanbo** [comment]
不是，是在移动端点击无响应。 移动端控制台没有输出日志

**Comment by liuhuanbo** [comment]
是看IM server的日志，还是移动端控制台日志 还是那个项目的日志呢？

**Comment by imndx** [comment]
> 不是，是在移动端点击无响应。 移动端控制台没有输出日志

移动端，“我的” 那个栏目，只显示你在开放平台创建的非全局应用，请先确认开放平台是否创建了非全局应用。

**Comment by liuhuanbo** [comment]
创建了非全局应用，移动端“我的“里面也显示出来了,但是点击响应。

**Comment by liuhuanbo** [comment]
创建了非全局应用，移动端“我的“里面也显示出来了,但是点击无响应。

**Comment by imndx** [comment]
1. 可以在Android 端```JsApi#openUrl```打个断点

**Comment by imndx** [comment]
1. Android Studio 模拟器允许 Android 端应用
2. ```Chrome```浏览器访问 ```chrome://inspect```，然后选择```Devices```选项卡
3. ```inspect```相关页面，请参考下图：

![image](https://user-images.githubusercontent.com/34434072/172974515-d19e21af-504e-4b15-b65f-dc77932d9f31.png)

**Comment by liuhuanbo** [comment]
用真机可以不？还是只能用模拟器？

**Comment by liuhuanbo** [comment]
👌

**Comment by liuhuanbo** [comment]
我在管理后台配置的应用，真机有显示出来，模拟器显示没有
<img width="300" alt="image" src="https://user-images.githubusercontent.com/9410051/173012119-7e3da7ff-a5c6-4d71-aa55-8cd5e6a3f757.png">

**Comment by imndx** [comment]
也可以按上面说的方法，用 Chrome 看下日志

**Comment by liuhuanbo** [comment]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/9410051/173025330-56a571db-73b9-474a-bdaf-546565844c42.png">
device里面没有那个下面那些信息
