### ISSUE TITLE
自定义消息问题

### ISSUE THREAD

**Issue by liuhuanbo** [wildfirechat/android-chat#670]
<img width="639" alt="WechatIMG1" src="https://user-images.githubusercontent.com/9410051/172978830-a2ce4bc3-2dbc-4447-a648-76aa3ffa9540.png">
如图所示，自定义消息中@MessageContentType 注解中两个类，是不是就是发送和接收方的MessageContent，两者顺序是如何的？

**Comment by imndx** [comment]
不是，```MessageContentType```注解是用来将消息本身和该消息对应的 UI 进行绑定。

上面的截图中中的意思是：```TextMessageContent```和```PTextMessageContent```两种消息，对应的 UI 都是```TextMessageContentViewHolder```

**Comment by liuhuanbo** [comment]
好的，那如果发送和接收方UI不一致，那是否就是如图所示，需要注册两次，发送和接收UI调换一下位置？需求是当前消息页面，发送和接收者消息UI不一致，这种情况该如何处理。
<img width="973" alt="image" src="https://user-images.githubusercontent.com/9410051/173262304-760f9147-1be5-492a-ac38-163b4cc8ac13.png">

**Comment by imndx** [comment]
只用注册一次，```registerMessageViewHolder```的第二、三个参数，对应的是发送方、接受方的消息布局样式

**Comment by liuhuanbo** [comment]
好的，那如何出发自定义消息，有没有相关示例。

**Comment by imndx** [comment]
你参考发送位置消息吧，```LocationExt.java```里面。

**Comment by liuhuanbo** [comment]
👌
