### ISSUE TITLE
群人数过多，进入群设置或者群成员列表卡顿

### ISSUE THREAD

**Issue by lebulang** [wildfirechat/android-chat#671]
#### 操作说明
建个人数多的群，进入群设置或者群成员列表页面
#### 表现现象
页面卡顿，无法及时响应，UI刷新过于频繁

#### 预期结果
不卡顿，且群成员信息都不是NullUserInfo格式

#### 补充条件
未拉取用户数据之前必现

**Comment by imndx** [comment]
请录制个视频看一下

**Comment by lebulang** [comment]
这个现在先提前更新了所有用户信息，如果不提前更新，上述两个页面的用户信息更新回调会频繁被调用，频道的刷新页面ui，导致卡顿



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月30日 09:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wildfirechat/android-chat] 群人数过多，进入群设置或者群成员列表卡顿 (Issue #671) |

请录制个视频看一下

**Comment by imndx** [comment]
群成员有多少？

**Comment by lebulang** [comment]
大概100左右，用户信息本地没有，进去群设置开始拉取就卡住了，好几百人的群也试过，更卡



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月30日 09:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wildfirechat/android-chat] 群人数过多，进入群设置或者群成员列表卡顿 (Issue #671) |

群成员有多少？

**Comment by imndx** [comment]
已解决
