### ISSUE TITLE
收不到对方的好友请求

### ISSUE THREAD

**Issue by heli-boop** [wildfirechat/android-chat#673]
#### 操作说明
登录A账号，然后添加b为好友，好友请求发送成功；退出账号，登录b账号，在新的朋友列表页面看不到好友请求

#### 表现现象
ChatManager.Instance().getFriendRequest(true)拉不到数据，好友请求列表数据如下
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/3947213/174213721-5222066a-1b31-48a0-8513-1ad7b3a0aa78.png">

#### 预期结果
b账号登录后，在好友请求 页面应该能看到A的好友请求吧

**Comment by heli-boop** [comment]
后面试了下两个账号同时在线，C向D发送了好有请求，客户端返回邀请成功。然后D还是收不到请求，并且去新的朋友列表页搜索不到

**Comment by heavyrain2012** [comment]
我用最新的IM服务和android客户端代码测试，都是正常的啊。你这样再测试一下吧：A、B两个客户端在线，A发送好友请求给B，如果B没有好友请求，把B的协议栈日志和im服务日志一起发邮件给support@wildfirechat.cn ，我们分析一下日志
