### ISSUE TITLE
getGoupMembers希望可以提供一个参数，用于控制获取多少个群成员。

### ISSUE THREAD

**Issue by gnmmdk** [wildfirechat/android-chat#676]
public java.util.List<cn.wildfirechat.model.GroupMember> getGroupMembers(java.lang.String groupId, boolean forceUpdate) throws android.os.RemoteException;
希望可以提供一个参数，用于控制获取多少个群成员。
好处：会话列表做拼接群头像的时候，需要获取前九个群成员拼接群头像。目前只能使用getGroupMemebers获取所有成员。
这样就会导致如果群成员有500个，就会返回500个GroupMemeber。如果会话有n个，就会获取n*500个群成员。android这里又是跨进程通讯，容易引起跨进程通讯数据量太大的问题。

**Comment by heavyrain2012** [comment]
已添加，请检查 https://github.com/wildfirechat/android-chat/commit/8b7abd77bfec23519f96fe7d0c3fd29a160da170

**Comment by heavyrain2012** [comment]
不好意思，确认有个地方没有考虑到，我们有重新更新了协议栈，请更新最新协议栈验证
