### ISSUE TITLE
如何关闭自带的日志？

### ISSUE THREAD

**Issue by AFAP** [wildfirechat/android-chat#678]
控制台疯狂输出日志，示例为：I/mars::stn: [shortlink.cc, ~ShortLink, 133]:-> ~ShortLink taskid:247, cgi:/im, @0x752528DB90这样的。
如何设置不输出im自带的日志。

**Comment by imndx** [comment]
先找下调用```ChatManager#startLog```的地方，注释了看看。

后台我们在设置里面，添加一个开关日志的开关。

**Comment by imndx** [comment]
no response.
