### ISSUE TITLE
在报错之前，疑似被释放，导致无法查看报错信息

### ISSUE THREAD

**Issue by CyAndroid** [wildfirechat/android-chat#681]
在二开的过程中对界面进行了部分修改，但是在启动页出现后疑似被释放，Android Studio中也没有相关的报错信息，比较影响开发效率，由于开发阶段不想使用bugly，更希望能在AS中直观的看到报错信息，请问有什么办法解决吗

**Comment by imndx** [comment]
可以用 ``` adb logcat ``` 抓取错误日志
