### ISSUE TITLE
野火的隐私政策是哪个

### ISSUE THREAD

**Issue by gnmmdk** [wildfirechat/android-chat#684]
目前上架到应用宝，检测到野火sdk又搜集用户的信息，因为需要在隐私政策的第三方SDK列表中，加入贵公司的隐私政策。
![image](https://user-images.githubusercontent.com/18391426/187367652-321cf5b3-4e84-4235-941f-f0ac2ae2f770.png)

请问贵公司的隐私政策的链接是哪个？
在android-chat工程有看到隐私政策，链接是：https://wildfirechat.cn/firechat_user_privacy.html。
遗憾的是web页面返回404。

**Comment by gnmmdk** [comment]
收集个人信息类型或权限除了AndroidID，还有哪些？

**Comment by imndx** [comment]
> 收集个人信息类型或权限除了AndroidID，还有哪些？

没有了，并且已将 AndroidID移除

**Comment by imndx** [comment]
> > 收集个人信息类型或权限除了AndroidID，还有哪些？
> 
> 没有了，并且已将 AndroidID移除

隐私政策链接错了：https://wildfirechat.net/firechat_user_privacy.html
