### ISSUE TITLE
多人音视频的主动加入功能

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#685]
看文档里面Demo 里面 实现了此功能，git 上面 下载你们最新的代码，运行之后发现没有此功能，请问在哪里可以看到实现代码,谢谢。

**Comment by heavyrain2012** [comment]
Android的config.java文件里有个开关，
```
// 允许主动加入多人音视频通话
    public static boolean ENABLE_MULTI_CALL_AUTO_JOIN = false;
```
打开就可以了，iOS在appdeleget.m中找到注掉的
```
    //多人音视频通话时，是否在会话中现在正在通话让其他人主动加入。
    //[WFCUConfigManager globalManager].enableMultiCallAutoJoin = YES;
```
打开注释。

关于自动加入实现方法，可以参考 https://docs.wildfirechat.cn/blogs/多人音视频的主动加入功能.html 自动加入都是UI层实现的，你们也好自己来维护
