### ISSUE TITLE
android 4.4.4 libmarsstn.so 加载失败

### ISSUE THREAD

**Issue by x836724926** [wildfirechat/android-chat#686]
0.9.5版本
android 6.0.1上跑起来正常，android 4.4.4 系统上报错。
dlopen("/data/app-lib/cn.wildfirechat.chat-1/libmarsstn.so") failed: dlopen failed: cannot locate symbol "signal" referenced by "libmarsstn.so"...

I/MultiDex: install done
W/dalvikvm: VFY: unable to resolve static field 257 (SUPPORTED_ABIS) in Landroid/os/Build;
D/dalvikvm: VFY: replacing opcode 0x62 at 0x0009
W/dalvikvm: VFY: unable to resolve static method 2438: Landroid/os/Process;.is64Bit ()Z
D/dalvikvm: VFY: replacing opcode 0x71 at 0x0007
    DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_64_BIT_ABIS
W/dalvikvm: VFY: unable to resolve static field 256 (SUPPORTED_64_BIT_ABIS) in Landroid/os/Build;
D/dalvikvm: VFY: replacing opcode 0x62 at 0x0014
W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/cn.wildfirechat.chat/files
E/ContextImpl: getExternalCacheDirs null getPackageName=cn.wildfirechat.chat
W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/cn.wildfirechat.chat/cache
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0031
W/dalvikvm: VFY: unable to resolve virtual method 695: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
D/dalvikvm: VFY: replacing opcode 0x6e at 0x001a
D/dalvikvm: Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libgnustl_shared.so 0x418e8c50
    Added shared lib /data/app-lib/cn.wildfirechat.chat-1/libgnustl_shared.so 0x418e8c50
    No JNI_OnLoad found in /data/app-lib/cn.wildfirechat.chat-1/libgnustl_shared.so 0x418e8c50, skipping init
    DexOpt: couldn't find field Landroid/content/pm/PackageInfo;.signingInfo
W/dalvikvm: VFY: unable to resolve instance field 61
D/dalvikvm: VFY: replacing opcode 0x54 at 0x0015
    DexOpt: couldn't find field Landroid/content/pm/PackageInfo;.signingInfo
D/dalvikvm: DexOpt: couldn't find field Landroid/content/pm/PackageInfo;.signingInfo
E/PermissionCheck: The authManager is: null; the authCallback is: null; the mContext is: null
W/CuidBuddyInfoManager: galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
    galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
    galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
E/PermissionCheck: permission check result is: 601
D/dalvikvm: DexOpt: couldn't find field Landroid/content/pm/PackageInfo;.signingInfo
W/dalvikvm: VFY: unable to resolve instance field 61
D/dalvikvm: VFY: replacing opcode 0x54 at 0x0015
D/dalvikvm: DexOpt: couldn't find field Landroid/content/pm/PackageInfo;.signingInfo
W/dalvikvm: VFY: unable to resolve instance field 61
D/dalvikvm: VFY: replacing opcode 0x54 at 0x0016
    DexOpt: couldn't find field Landroid/content/pm/PackageInfo;.signingInfo
W/dalvikvm: VFY: unable to resolve static field 257 (SUPPORTED_ABIS) in Landroid/os/Build;
D/dalvikvm: Note: class Lcn/wildfirechat/client/IRemoteClient$Stub; has 192 unimplemented (abstract) methods
I/dalvikvm: Could not find method android.os.LocaleList.getDefault, referenced from method cn.wildfirechat.client.ClientService.getDeviceType
W/dalvikvm: VFY: unable to resolve static method 2293: Landroid/os/LocaleList;.getDefault ()Landroid/os/LocaleList;
D/dalvikvm: VFY: replacing opcode 0x71 at 0x002d
D/dalvikvm: Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libc++_shared.so 0x418e8c50
D/dalvikvm: Added shared lib /data/app-lib/cn.wildfirechat.chat-1/libc++_shared.so 0x418e8c50
    No JNI_OnLoad found in /data/app-lib/cn.wildfirechat.chat-1/libc++_shared.so 0x418e8c50, skipping init
    Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libmarsxlog.so 0x418e8c50
    Added shared lib /data/app-lib/cn.wildfirechat.chat-1/libmarsxlog.so 0x418e8c50
    Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libmarsstn.so 0x418e8c50
E/dalvikvm: dlopen("/data/app-lib/cn.wildfirechat.chat-1/libmarsstn.so") failed: dlopen failed: cannot locate symbol "signal" referenced by "libmarsstn.so"...
D/dalvikvm: Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libc++_shared.so 0x418e8c50
    Shared lib '/data/app-lib/cn.wildfirechat.chat-1/libc++_shared.so' already loaded in same CL 0x418e8c50
    Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libmarsxlog.so 0x418e8c50
    Shared lib '/data/app-lib/cn.wildfirechat.chat-1/libmarsxlog.so' already loaded in same CL 0x418e8c50
    Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libmarsstn.so 0x418e8c50
E/dalvikvm: dlopen("/data/app-lib/cn.wildfirechat.chat-1/libmarsstn.so") failed: dlopen failed: cannot locate symbol "signal" referenced by "libmarsstn.so"...
D/TelephonyMSMSConfig: MSMS_CONFIG_STANDBY_COUNT = 1
D/ClientService: onnCreate
D/dalvikvm: DexOpt: couldn't find field Landroid/content/pm/PackageInfo;.signingInfo
W/dalvikvm: VFY: unable to resolve instance field 61
D/dalvikvm: VFY: replacing opcode 0x54 at 0x0011
    DexOpt: couldn't find field Landroid/content/pm/PackageInfo;.signingInfo
D/dalvikvm: DexOpt: couldn't find field Landroid/content/pm/PackageInfo;.signingInfo
D/dalvikvm: Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libc++_shared.so 0x418e8c50
    Shared lib '/data/app-lib/cn.wildfirechat.chat-1/libc++_shared.so' already loaded in same CL 0x418e8c50
    Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libmarsxlog.so 0x418e8c50
    Shared lib '/data/app-lib/cn.wildfirechat.chat-1/libmarsxlog.so' already loaded in same CL 0x418e8c50
    Trying to load lib /data/app-lib/cn.wildfirechat.chat-1/libmarsstn.so 0x418e8c50
E/dalvikvm: dlopen("/data/app-lib/cn.wildfirechat.chat-1/libmarsstn.so") failed: dlopen failed: cannot locate symbol "signal" referenced by "libmarsstn.so"...
W/dalvikvm: No implementation found for native Lcom/tencent/mars/proto/ProtoLogic;.setBackupAddressStrategy:(I)V
E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.UnsatisfiedLinkError: Native method not found: com.tencent.mars.proto.ProtoLogic.setBackupAddressStrategy:(I)V
        at com.tencent.mars.proto.ProtoLogic.setBackupAddressStrategy(Native Method)
        at cn.wildfirechat.client.ClientService$ClientServiceStub.setBackupAddressStrategy(ClientService.java:342)
        at cn.wildfirechat.client.IRemoteClient$Stub.onTransact(IRemoteClient.java:759)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)
W/dalvikvm: threadid=10: thread exiting with uncaught exception (group=0x41634bd8)
E/AndroidRuntime: FATAL EXCEPTION: Binder_2
    Process: cn.wildfirechat.chat:marsservice, PID: 15088
    java.lang.UnsatisfiedLinkError: Native method not found: com.tencent.mars.proto.ProtoLogic.setBackupAddressStrategy:(I)V
        at com.tencent.mars.proto.ProtoLogic.setBackupAddressStrategy(Native Method)
        at cn.wildfirechat.client.ClientService$ClientServiceStub.setBackupAddressStrategy(ClientService.java:342)
        at cn.wildfirechat.client.IRemoteClient$Stub.onTransact(IRemoteClient.java:759)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)

请帮忙看下，谢谢！

**Comment by imndx** [comment]
请问下，```4.4.4```的系统比较老了，请问下什么地方还有```4.4.4```的系统？

**Comment by x836724926** [comment]
测试机用的，请问是不支持android 4.4.4么？试了很多个代码包版本都是这样的错
