### ISSUE TITLE
对接华为离线推送，返回token值并且ChatManager调用setDeviceToken，但是没有收到离线消息

### ISSUE THREAD

**Issue by zhijiehuanga** [wildfirechat/android-chat#696]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by heavyrain2012** [comment]
您好，推送服务说明上有排查说明，请按照说明检查问题。如果还是无法解决问题，请把检查结果贴到这里

**Comment by zhijiehuanga** [comment]
![A24O16(R`S1R8PDK9{Q(~9](https://user-images.githubusercontent.com/114142122/191716372-6b16703d-491f-49cd-b511-8f2db7db2c9e.png)
前面五点确认没有问题，第六点：我是发送文字信息的 日志要在哪里查看呢，    我使用华为后台直接推送离线消息，是可以接收到的离线消息的

**Comment by heavyrain2012** [comment]
第六步的这几步确认情况如何？还有推送服务是否收到了IM服务发过来的推送请求？

**Comment by heavyrain2012** [comment]
如果推送服务收到IM服务的请求，那后面就是推送服务与推送厂商的工作了，可以检查一下推送服务里面关于推送的代码然后对比厂商的说明来调试

**Comment by zhijiehuanga** [comment]
第六步 第三点具体需要如何确认 安卓代码中没有找到t_user_session这个关键字。 厂商没有看到推送信息

**Comment by imndx** [comment]
> 第六步 第三点具体需要如何确认 安卓代码中没有找到t_user_session这个关键字。 厂商没有看到推送信息

```t_user_session```是 im-server 数据库里面的一张表

**Comment by heavyrain2012** [comment]
> 第六步 第三点具体需要如何确认 安卓代码中没有找到t_user_session这个关键字。 厂商没有看到推送信息

我的问题是：推送服务是否收到了IM服务发过来的推送请求？没有说厂商，推送服务是需要你们自己维护，所以一定要弄明白整个推送的流程，知道每一部分是谁负责，如果出了问题，也能够准确地找出那一步出了问题并准确描述问题，至少到目前为止我们还不知道哪里出了问题。

**Comment by zhijiehuanga** [comment]
“推送服务是否收到了IM服务发过来的推送请求“”  这个具体要怎么确认   查看日志吗是哪个关键字呢 还是其他做法

**Comment by zhijiehuanga** [comment]
> > 第六步 第三点具体需要如何确认 安卓代码中没有找到t_user_session这个关键字。 厂商没有看到推送信息
> 
> 我的问题是：推送服务是否收到了IM服务发过来的推送请求？没有说厂商，推送服务是需要你们自己维护，所以一定要弄明白整个推送的流程，知道每一部分是谁负责，如果出了问题，也能够准确地找出那一步出了问题并准确描述问题，至少到目前为止我们还不知道哪里出了问题。

我的问题是：现在可以返回token值，并且调用了ChatManager的setDeviceToken，把token值传到你们，有这个token不就可以去调用华为的推送吗，我是否还需要设置其他东西

**Comment by imndx** [comment]
https://github.com/wildfirechat/push_server

这个服务部署了吗？

**Comment by zhijiehuanga** [comment]
> https://github.com/wildfirechat/push_server
> 
> 这个服务部署了吗？

这个需要后端部署是吧

**Comment by zhijiehuanga** [comment]
> > https://github.com/wildfirechat/push_server
> > 这个服务部署了吗？
> 
> 这个需要后端部署是吧

应该后端部署问题，那暂时没问题了   辛苦了 感谢

**Comment by imndx** [comment]
> > https://github.com/wildfirechat/push_server
> > 这个服务部署了吗？
> 
> 这个需要后端部署是吧

是的，没有部署这个就不可能推送，上说的第7部检查日志，也是检查这个服务的日志

强烈建议仔细看下文档，特别是系统架构部分
https://docs.wildfirechat.cn/architecture/

**Comment by zhijiehuanga** [comment]
> > > https://github.com/wildfirechat/push_server
> > > 这个服务部署了吗？
> > 
> > 
> > 这个需要后端部署是吧
> 
> 是的，没有部署这个就不可能推送，上说的第7部检查日志，也是检查这个服务的日志
> 
> 强烈建议仔细看下文档，特别是系统架构部分 https://docs.wildfirechat.cn/architecture/

好的  谢谢

**Comment by michaelPual** [comment]
您好，我部署后端推送服务了，服务日志显示推送成功，但是手机端收不到离线推送。

**Comment by michaelPual** [comment]
第6步检查也没有问题。
