### ISSUE TITLE
自定义信息怎么修改状态呢?

### ISSUE THREAD

**Issue by jueduiyheng** [wildfirechat/android-chat#699]
比如有条红包或者优惠券的自定义信息,我第一次点进去领了,那么我下次在点进去的时候我怎么知道我之前是领的呢,第一次进的时候有方法修改这条信息吗?

**Comment by heavyrain2012** [comment]
有几种办法，一种是本地记录，如果打开过，就记录下这个红包的状态，下次显示时再读取状态。另外一种是放到服务器去，显示时去服务器读，这样可能会有延迟，最好跟第一种办法结合，如果有记录就用本地记录，如果没有就去服务器更新，这样就能解决更换手机拉取的历史消息的问题。还有一种办法是使用专业版IM服务，可以服务器端改消息内容。

**Comment by jueduiyheng** [comment]
00  明白了  谢谢
