### ISSUE TITLE
app在后台或者关闭时推送问题

### ISSUE THREAD

**Issue by BillWang0408** [wildfirechat/android-chat#700]
安卓推送的问题：
给离线用户（杀死进程或长时间挂在后台）拨打语音视频通话，用户未收到离线通知
给离线用户（杀死进程）发送文字消息，用户未收到离线推送
软件长时间挂在后台，无法接收到消息推送

**Comment by imndx** [comment]
请先仔细看[push-server](https://github.com/wildfirechat/push_server)的 readme
