### ISSUE TITLE
Android Push Notifications not working

### ISSUE THREAD

**Issue by mhamidg** [wildfirechat/android-chat#701]
Unable to receive call or message:

When app is not kill, we receive message and calls normally. 

When I kill the app, and then try to call and message I am unable to receive it. 

Tried on:
Samsung Galaxy S20Plus, android 12
Samsung M31, android 12 as well.

**Comment by imndx** [comment]
需要部署并调通[推送服务](https://github.com/wildfirechat/push_server)

**Comment by mankind-evolve** [comment]
看样子这个人是个老外，估计用的FMC  我的FMC也出现了问题    下载官方代码    push初始化的屏蔽所有的渠道，只用FMC的时候，也是收不到消息。   我自己的代码中，拿到token,我直接从FMC后台推送测试信息,也是收不到
