### ISSUE TITLE
会话中，图片不能保存到本地

### ISSUE THREAD

**Issue by yinhonlong** [wildfirechat/android-chat#703]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by yinhonlong** [comment]
会话中，提示保存图片成功，实际并未保存到系统相册

**Comment by imndx** [comment]
用最新代码测试了吗？这问题最近应当解决了

**Comment by yinhonlong** [comment]
好的，我试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月17日(星期一) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wildfirechat/android-chat] 会话中，图片不能保存到本地 (Issue #703)





 
用最新代码测试了吗？这问题最近应当解决了
