### ISSUE TITLE
多个应用服务该如何配置?

### ISSUE THREAD

**Issue by cfmj** [wildfirechat/android-chat#707]
比如正常业务通过APP_SERVER 1
设置头像等 要上传到自有的对象存储服务 需要通过APP_SERVER 2

**Comment by imndx** [comment]
没有直接的配置方法。

可以这么做，在应用层自行处理媒体上传，然后在设置头像等；如果需要发送上传到自有存储的上的媒体问题，可以将上传得到的 ```remoteUrl```设置到媒体文件里面，然后进行发送
