### ISSUE TITLE
app端收到一条后台推送的消息，app端可以修改该条消息在服务端的状态变为已读吗？有提供这种接口吗？

### ISSUE THREAD

**Issue by zhengjiaai2008** [wildfirechat/android-chat#708]
#### 操作说明
一台app端收到一条后台推送的消息，这个时候另外一台手机的同一个账号登录后还是能收到同样的推送消息，而且消息还是未读状态

#### 表现现象
app端收到一条后台推送的消息，app端可以修改该条消息在服务端的状态变为已读吗？有提供这种接口吗？

#### 预期结果
一台app端可以修改该条消息在服务端的状态变为已读，另外一台手机的同一个账号登录后能收到同样的推送消息时，希望消息可以是已读状态

**Comment by imndx** [comment]
你好，专业版 im-server 支持消息回执，如果真读了的话，其他端也会标识为已读的。
