### ISSUE TITLE
聊天列表，加载聊天列表一直处于加载中 ...

### ISSUE THREAD

**Issue by hubangmao** [wildfirechat/android-chat#716]
![image](https://user-images.githubusercontent.com/20508257/199772635-3a3d64c4-cd24-461f-ac5a-b8713fc485b0.png)

链接成功，可以发送消息，就是聊天列表卡住的。

链接初始化都是成功的。
ChatManager.Instance().connect(info.getImUserId(), info.getFireToken())

**加载聊天列表一直在加载中，不回调成功，也不回调失败，但是发送消息又可以正常发送。**

**Comment by imndx** [comment]
请到```marsservice```进程打端口看下，是否有加载到消息。

<img width="660" alt="image" src="https://user-images.githubusercontent.com/34434072/199911971-ed40bcbb-d854-4aae-a039-cff13c9c64e3.png">

**Comment by hubangmao** [comment]
> 请到`marsservice`进程打端口看下，是否有加载到消息。
> 
> <img alt="image" width="660" src="https://user-images.githubusercontent.com/34434072/199911971-ed40bcbb-d854-4aae-a039-cff13c9c64e3.png">

谢谢，我发现是我用的aar依赖包不是最新的导致的。

**Comment by hubangmao** [comment]
> > 请到`marsservice`进程打端口看下，是否有加载到消息。
> > <img alt="image" width="660" src="https://user-images.githubusercontent.com/34434072/199911971-ed40bcbb-d854-4aae-a039-cff13c9c64e3.png">
> 
> 谢谢，我发现是我用的aar依赖包不是最新的导致的。
