### ISSUE TITLE
我们公司买的是专业版IM, 一台app端收到一条后台推送的消息，这个时候另外一台手机的同一个账号登录后还是能收到同样的推送消息，而且消息还是未读状态

### ISSUE THREAD

**Issue by zhengjiaai2008** [wildfirechat/android-chat#717]
#### 操作说明
我们公司买的是专业版IM, 一台app端收到一条后台推送的消息，这个时候另外一台手机的同一个账号登录后还是能收到同样的推送消息，而且消息还是未读状态

表现现象
专业版IM,app端收到一条后台推送的消息，app端可以修改该条消息在服务端的状态变为已读吗？有提供这种接口吗？

预期结果
专业版IM, 一台app端可以修改该条消息在服务端的状态变为已读，另外一台手机的同一个账号登录后能收到同样的推送消息时，希望消息可以是已读状态

**Comment by imndx** [comment]
先收到消息的那个app端，读了该消息了吗？

另外，你说的推送是指应用被杀之后，通过厂商推送通道收到的？还是应用活着，通过应用消息连接通道收到的？

**Comment by zhengjiaai2008** [comment]
账号1在A手机登录，然后全部消息已读。这时候使用B手机登录账号1，这时候ChatManager.Instance().addOnReceiveMessageListener 回调里面显示消息都是未读状态，而打开会话列表获取历史会话又全是已读状态，需求是ChatManager.Instance().addOnReceiveMessageListener这个回调要获取到真是的状态

**Comment by imndx** [comment]
服务端没有维护具体的消息的状态，但维护了会话的已读情况，可以通过```getConversationRead```获取会话的已读情况，就能算出消息是否被读了

**Comment by imndx** [comment]
no response
