### ISSUE TITLE
未读数的问题

### ISSUE THREAD

**Issue by wapalxj** [wildfirechat/android-chat#718]
版本：发帖时的最新版，android会出现，ios不会出现
现象：已经全部阅读完会话列表的消息
清除app数据后首次连接，前几次拉会话列表，某一次会出现：拉到一些其中一些好友有1条未读，再拉1次又没有了

已经反复测试过多次,同一个账号每次清除数据后重新连接都会出现

使用api    ChatManager.Instance().getUnreadCountEx() 会出现未读数
以及api    ConversationInfo.unreadCount.unread   单个会话出现1条未读数

**Comment by imndx** [comment]
请问 demo 上可以复现吗？

**Comment by wapalxj** [comment]
demo 暂时没有复现




vnix
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/android-chat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 晚上8:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wildfirechat/android-chat] 未读数的问题 (Issue #718)





 
请问 demo 上可以复现吗？

**Comment by wapalxj** [comment]
> 请问 demo 上可以复现吗？


> demo 暂时没有复现 vnix ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wildfirechat/android-chat" ***@***.***&gt;; 发送时间:&nbsp;2022年11月8日(星期二) 晚上8:04 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wildfirechat/android-chat] 未读数的问题 (Issue #718) 请问 demo 上可以复现吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


同时会触发onReceiveMessage()回调

**Comment by wapalxj** [comment]
demo清掉数据重新登录也会触发onReceiveMessage()包含很多条数据，并且也是又未读的，但是demo后续会接着推送一条系统消息来刷新了，就看不出来未读数了

**Comment by charlesbabyxu** [comment]
安卓客户端sdk客户端拉取消息和会话设置后，最终计算结果没有返回回调，而是返回了中途计算结果，导致计算出的会话每一个都会有未读，实际上最终计算结果是没有未读的。
demo版本因为系统系统消息自动发送，恰好触发sdk再次拉取消息计算，能放回正确未读计算。
测试复现方法，排除掉业务处理服务一些自动发送影响，可以复现。

**Comment by charlesbabyxu** [comment]
> demo清掉数据重新登录也会触发onReceiveMessage()包含很多条数据，并且也是又未读的，但是demo后续会接着推送一条系统消息来刷新了，就看不出来未读数了

从服务端日志看，多次安卓客户端多次退出登录，中间无消息新增，但是MP均返回了消息，疑似最后MP的最新版本未能准确保存到客户端sdk中记录

**Comment by heavyrain2012** [comment]
协议栈的工作机制是这样的：在首次连接上以后，把连接状态设置为接收中，然后拉取消息，消息拉取保存在本地都是未读的，拉取成功以后，再拉取设置，其中设置中有阅读状态，把本地消息的状态修改正确，把连接状态设置为已连接。

所以应用在首次连接成功还没有进入到已连接时，未读消息状态可能是错误的，可以在首次已连接或则用户设置变更时再刷新一下UI。

**Comment by wapalxj** [comment]
> 协议栈的工作机制是这样的：在首次连接上以后，把连接状态设置为接收中，然后拉取消息，消息拉取保存在本地都是未读的，拉取成功以后，再拉取设置，其中设置中有阅读状态，把本地消息的状态修改正确，把连接状态设置为已连接。
> 
> 所以应用在首次连接成功还没有进入到已连接时，未读消息状态可能是错误的，可以在首次已连接或则用户设置变更时再刷新一下UI。

首次连接成功后连续多次拉取都有未读数，只有在延迟几秒后拉取才会正常
