### ISSUE TITLE
插入本地消息问题：

### ISSUE THREAD

**Issue by clg0118** [wildfirechat/android-chat#728]
插入本地消息问题：
1、插入后messageUid为0
2、插入数据有没有去重的方法
3、插入的direction也无法控制

**Comment by heavyrain2012** [comment]
android的sdk中有2个插入接口，有一个带messageUid的参数的，用那个方法。messageUid带唯一索引的，如果messageUid带上会排重的。direction是根据消息状态来决定，比如已发送状态那就是发送，已读就是接收
