### ISSUE TITLE
群管理员退群

### ISSUE THREAD

**Issue by Anlycal** [wildfirechat/android-chat#73]
群管理员已成功，但重新获取群成员数据列表还存在该管理员，只有普通成员才能退群。

**Comment by imndx** [comment]
群主，还是管理员？群主只能解散群，或者把群转让给别人

**Comment by Anlycal** [comment]
群管理员退群成功，但群成员里面没有把该管理员移除

**Comment by imndx** [comment]
移除的群成员，会还在列表里面，但type会变成Removed
