### ISSUE TITLE
重复jar的问题

### ISSUE THREAD

**Issue by niushicha1** [wildfirechat/android-chat#733]
#### 操作说明
 app的moudle里面用的zxing功能的库是 'com.github.yuzhiqiang1993:zxing:2.2.8'，而你们的uikit的moudle里面用的是com.king.zxing:zxing-lite:1.1.1，当我项目把你们的uikit引入到app的module里面的时候，编译运行的时候出现的问题：

Duplicate class com.google.zxing.qrcode.encoder.BlockPair found in modules jetified-core-3.3 (core-3.3.3.jar) and jetified-zxing-2.2.8-runtime (com.github.yuzhiqiang1993:zxing:2.2.8)
Duplicate class com.google.zxing.qrcode.encoder.ByteMatrix found in modules jetified-core-3.3 (core-3.3.3.jar) and jetified-zxing-2.2.8-runtime (com.github.yuzhiqiang1993:zxing:2.2.8)
Duplicate class com.google.zxing.qrcode.encoder.Encoder found in modules jetified-core-3.3 (core-3.3.3.jar) and jetified-zxing-2.2.8-runtime (com.github.yuzhiqiang1993:zxing:2.2.8)
Duplicate class com.google.zxing.qrcode.encoder.Encoder$1 found in modules jetified-core-3.3 (core-3.3.3.jar) and jetified-zxing-2.2.8-runtime (com.github.yuzhiqiang1993:zxing:2.2.8)
Duplicate class com.google.zxing.qrcode.encoder.MaskUtil found in modules jetified-core-3.3 (core-3.3.3.jar) and jetified-zxing-2.2.8-runtime (com.github.yuzhiqiang1993:zxing:2.2.8)
Duplicate class com.google.zxing.qrcode.encoder.MatrixUtil found in modules jetified-core-3.3 (core-3.3.3.jar) and jetified-zxing-2.2.8-runtime (com.github.yuzhiqiang1993:zxing:2.2.8)
Duplicate class com.google.zxing.qrcode.encoder.QRCode found in modules jetified-core-3.3 (core-3.3.3.jar) and jetified-zxing-2.2.8-runtime (com.github.yuzhiqiang1993:zxing:2.2.8)

Go to the documentation to learn how to Fix dependency resolution errors.

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
项目根目录的```build.gradle```里面，可以配置```resolutionStrategy```，你可以这儿配置，把```com.google.zxing.qrcode```固定到你们依赖的那个版本
