### ISSUE TITLE
为什么所有的UI界面都是白色的，修改xml为其他的颜色，都是无效的。

### ISSUE THREAD

**Issue by niushicha1** [wildfirechat/android-chat#734]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
不可能呀，你调试下，应当是什么地方没修改对

**Comment by niushicha1** [comment]
> 不可能呀，你调试下，应当是什么地方没修改对

你不信可以试一下你们的ConversationListFragment的recyclerview的item为黑色。

**Comment by imndx** [comment]
由于需要特殊处理置顶等，演示是通过代码动态设置的。
https://github.com/wildfirechat/android-chat/blob/bcae1bbe8e5b5bd2a1c086ea63ba35b75fa5272c/uikit/src/main/java/cn/wildfire/chat/kit/conversationlist/viewholder/ConversationViewHolder.java#L109

**Comment by niushicha1** [comment]
> 由于需要特殊处理置顶等，背景颜色是通过代码动态设置的。
> 
> https://github.com/wildfirechat/android-chat/blob/bcae1bbe8e5b5bd2a1c086ea63ba35b75fa5272c/uikit/src/main/java/cn/wildfire/chat/kit/conversationlist/viewholder/ConversationViewHolder.java#L109

好的，可以了，非常感谢

**Comment by imndx** [comment]
> > 由于需要特殊处理置顶等，背景颜色是通过代码动态设置的。
> > https://github.com/wildfirechat/android-chat/blob/bcae1bbe8e5b5bd2a1c086ea63ba35b75fa5272c/uikit/src/main/java/cn/wildfire/chat/kit/conversationlist/viewholder/ConversationViewHolder.java#L109
> 
> 好的，可以了，非常感谢

不客气，客气就给个 star 😄
