### ISSUE TITLE
清空所有会话并删除会话内所有聊天记录，结果聊天记录还在

### ISSUE THREAD

**Issue by zwnetwork** [wildfirechat/android-chat#739]
#### 操作说明
 ChatManager.Instance().clearAllMessages(false);
调用该方法想删除所有会话以及会话内聊天数据

#### 表现现象
结果只是清空会话列表展示的数据，并未删除会话内所有聊天记录，再次点击会话进入聊天页面，聊天内容还在。

#### 预期结果
应该删除会话内所有聊天数据

#### 补充条件
必现的
#### demo对比结果
目前就是运行的demo

**Comment by imndx** [comment]
这个方法只删除本地的消息，远端的消息还在，进入会话时，会从服务端拉取历史消息。
```im-server``` 配置文件里面的```message.remote_history_message```可以关闭历史消息功能。

另外，如果想删除远端的历史消息，需要调用 ```clearRemoteConversationMessage``` 方法。

**Comment by zwnetwork** [comment]
好的谢谢
