### ISSUE TITLE
退出群后 应该直接在会话列表删除这个群，并且在通讯录列表也删除这个群 

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#74]

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/61166925-dfb6ed00-a568-11e9-9f90-086e57ea5f5a.png)

**Comment by imndx** [comment]
请用我们最新代码测试，这问题应当解决了的。

**Comment by yuzhongrong** [comment]
最新代码还是存在的

**Comment by yuzhongrong** [comment]
出现概率大概是50%

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/61287317-333e6a80-a7f7-11e9-8c9a-ac37b2f231d3.png)

**Comment by imndx** [comment]
refer to: wildfirechat/server#47
