### ISSUE TITLE
release打包apk 登录时connect方法异常闪退

### ISSUE THREAD

**Issue by niyongsheng** [wildfirechat/android-chat#740]
#### 登录后的success回调中userId和token没有获取到导致的，debug模式没有这个问题；
![image](https://user-images.githubusercontent.com/28373699/215938033-e538289a-d288-47a7-b02d-e9c785db803f.png)

**Comment by heavyrain2012** [comment]
登录返回userId和token是应用服务的功能，应用服务是开源的，你们可以自己debug看看为什么有问题

**Comment by heavyrain2012** [comment]
是不是代码有混淆，如果model混淆了，反序列化可能就会出问题

**Comment by imndx** [comment]
混淆问题，请参考```chat/proguard-rules.pro```
