### ISSUE TITLE
master分支上的代码有报错不能编译

### ISSUE THREAD

**Issue by hhahali** [wildfirechat/android-chat#741]
master分支上的代码有报错不能编译

**Comment by li-ld** [comment]
使用了专业版的sdk和音视频sdk

**Comment by hhahali** [comment]
G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\client\ClientService.java:1899: 错误: 无法将类 ProtoLogic中的方法 searchMessageEx应用到给定类型;
                protoMessages = ProtoLogic.searchMessageEx(0, "", 0, keyword, desc, limit, offset, withUser);
                                          ^
  需要: int,String,int,String,boolean,int,int
  找到: int,String,int,String,boolean,int,int,String
  原因: 实际参数列表和形式参数列表长度不同
G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\client\ClientService.java:1901: 错误: 无法将类 ProtoLogic中的方法 searchMessageEx应用到给定类型;
                protoMessages = ProtoLogic.searchMessageEx(conversation.type.getValue(), conversation.target, conversation.line, keyword, desc, limit, offset, withUser);
                                          ^
  需要: int,String,int,String,boolean,int,int
  找到: int,String,int,String,boolean,int,int,String
  原因: 实际参数列表和形式参数列表长度不同
G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\client\ClientService.java:1921: 错误: 无法将类 ProtoLogic中的方法 searchMessageByTypes应用到给定类型;
                protoMessages = ProtoLogic.searchMessageByTypes(0, "", 0, keyword, contentTypes, desc, limit, offset, withUser);
                                          ^
  需要: int,String,int,String,int[],boolean,int,int
  找到: int,String,int,String,int[],boolean,int,int,String
  原因: 实际参数列表和形式参数列表长度不同
G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\client\ClientService.java:1923: 错误: 无法将类 ProtoLogic中的方法 searchMessageByTypes应用到给定类型;
                protoMessages = ProtoLogic.searchMessageByTypes(conversation.type.getValue(), conversation.target, conversation.line, keyword, contentTypes, desc, limit, offset, withUser);
                                          ^
  需要: int,String,int,String,int[],boolean,int,int
  找到: int,String,int,String,int[],boolean,int,int,String
  原因: 实际参数列表和形式参数列表长度不同
G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\client\ClientService.java:1952: 错误: 无法将类 ProtoLogic中的方法 searchMessageByTypesAndTimes应用到给定类型;
            protoMessages = ProtoLogic.searchMessageByTypesAndTimes(convType, target, line, keyword, contentTypes, startTime, endTime, desc, limit, offset, withUser);
                                      ^
  需要: int,String,int,String,int[],long,long,boolean,int,int
  找到: int,String,int,String,int[],long,long,boolean,int,int,String
  原因: 实际参数列表和形式参数列表长度不同
G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\client\ClientService.java:1969: 错误: 无法将类 ProtoLogic中的方法 searchMessageEx2应用到给定类型;
            ProtoMessage[] protoMessages = ProtoLogic.searchMessageEx2(conversationTypes, lines, contentTypes, keyword, fromIndex, before, count, withUser);
                                                     ^
  需要: int[],int[],int[],String,long,boolean,int
  找到: int[],int[],int[],String,long,boolean,int,String
  原因: 实际参数列表和形式参数列表长度不同
G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\client\ClientService.java:2990: 错误: 不兼容的类型: void无法转换为boolean
            return ProtoLogic.commitTransaction();
                                               ^
G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\client\ClientService.java:2995: 错误: 找不到符号
            return ProtoLogic.rollbackTransaction();
                             ^
  符号:   方法 rollbackTransaction()
  位置: 类 ProtoLogic
G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\client\ClientService.java:3049: 错误: 找不到符号
            ProtoLogic.checkSignature();
                      ^
  符号:   方法 checkSignature()
  位置: 类 ProtoLogic
注: G:\javaProject\android-chat\client\src\main\java\cn\wildfirechat\remote\ChatManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
9 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':client:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
55 actionable tasks: 48 executed, 7 up-to-date

**Comment by hhahali** [comment]
执行 gradle clean build 后控制台输出错误信息如上

**Comment by imndx** [comment]
> 使用了专业版的sdk和音视频sdk

你说的专业版 sdk 是什么东西？

这个问题，可能是用了最新的代码，但协议栈文件```mars-core-release.aar```是旧版的

**Comment by hhahali** [comment]
协议栈是去年11月的。我需要拉取哪个分支？

**Comment by hhahali** [comment]
专业版是说，imserver使用的是专业版。是你们发过来的sdk。

**Comment by imndx** [comment]
> 协议栈是去年11月的。我需要拉取哪个分支？

如果没有使用最定义的端口，直接用 master 分支的对应文件就可以；如果修改过默认端口，请邮件联系我们，需要重新给你们打包自定义端口的协议栈文件
