### ISSUE TITLE
音视频会议中，三星手机切换前置或后置摄像头，有时候要点2次才能切换

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/android-chat#746]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
音视频会议中，三星手机切换前置或后置摄像头，有时候要点2次才能切换

#### 表现现象
音视频会议中，三星手机切换前置或后置摄像头，有时候要点2次才能切换

#### 预期结果
点击一次切换

#### 补充条件
demo必现。

#### demo对比结果
demo必现。

**Comment by imndx** [comment]
是最新代码吗？这个问题，在最新代码上，应当修复了。

**Comment by guodonghuang** [comment]
> 是最新代码吗？这个问题，在最新代码上，应当修复了。

最新的代码是哪个分支，我们用的是conf_enginesdk，是这个分支吗

**Comment by imndx** [comment]
`master`分支

**Comment by guodonghuang** [comment]
> 

master分支的会议功能现在被隐藏掉了，没有音视频会议功能了

**Comment by imndx** [comment]
请你微信添加下: `wfchat`
