### ISSUE TITLE
web端与安卓端接听音视频时,无法互踢.

### ISSUE THREAD

**Issue by cfmj** [wildfirechat/android-chat#749]
web端与安卓端同时登录,
其中一端接听音视频,另一端无法自动关闭待接听界面

1.web使用多人版音视频sdk
2.野火demo上无法复现

**Comment by imndx** [comment]
demo 上无法复现，那你把 web 端`wfc`目录更新到最新，android 端也更新到最新测试下呢

**Comment by cfmj** [comment]
已更到最新,可否请测试下是否只在多人版上有这个问题?

**Comment by imndx** [comment]
已处理了，是最近新增单聊定向消息功能引起的一个问题，请更新 im 服务端，然后测试。
