### ISSUE TITLE
视频通话挂断后，视频流没关闭

### ISSUE THREAD

**Issue by Anlycal** [wildfirechat/android-chat#75]
视频通话挂断后，视频流没有关闭，还能听到声音

**Comment by imndx** [comment]
请问，怎么复现这个问题？

**Comment by Anlycal** [comment]
视频通话结束后，退出视频通话页面，相机录制视频没有关闭，还能发送视频流，另一个用户还能收到视频图像和声音

**Comment by imndx** [comment]
视频通话结束后，退出视频通话页面

是挂断，还是点home键去后台？

**Comment by Anlycal** [comment]
是直接挂断

**Comment by Anlycal** [comment]
问下哪些配置的改动可能导致视频语音不能挂断？一直在后台运行。
