### ISSUE TITLE
VoipCallService内经常会出现RemoteServiceException异常

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#756]
android.app.RemoteServiceException

Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ba26749 u0 com.tongfudun.dtcmessenger/cn.wildfire.chat.kit.voip.VoipCallService}

**Comment by imndx** [comment]
这个问题，是不是在特定版本的 Android 系统上才能复现？
