### ISSUE TITLE
第一次链接im服务器的链接不上是为什么？ 关闭app再打开就能连接上，附 日志

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/android-chat#759]
第一次打开app需要走个注册的流程，注册流程客户端不牵涉Im的逻辑，第一次就链接不上。找到了ChatManager的日志

![image](https://user-images.githubusercontent.com/10117769/236464547-d8525884-e875-46d3-945d-bee101f7b1fc.png)

第二次打开的时候链接正常，也找到了ChatManager的日志，发现两者有点不同， 没有正常连接的逻辑好像是少点东西，找到了问题想问问可能是什么原因造成的呢？
![image](https://user-images.githubusercontent.com/10117769/236465026-47d9848d-f86a-4f9e-977b-e6101e493eaf.png)

**Comment by heavyrain2012** [comment]
图上的日志是主进程的日志，协议栈情况需要看mars进程的日志，你可以把两种情况下mars进程的日志发给support@wildfirechat.cn 我们分析一下原因

**Comment by mankind-evolve** [comment]
找到原因了。im服务器地址有问题。马虎了
