### ISSUE TITLE
关于updateMessage 方法问题

### ISSUE THREAD

**Issue by hzbx** [wildfirechat/android-chat#760]
<img width="807" alt="image" src="https://github.com/wildfirechat/android-chat/assets/16591739/83491644-eaad-4204-90f1-0cf1bd9bbaac">
该方法在更新UnknownMessageContent 消息后，里面的原数据MessagePayload.type会强制修改为0
<img width="623" alt="image" src="https://github.com/wildfirechat/android-chat/assets/16591739/2c67bea5-a0ab-4cda-922f-c33488086df4">

导致 在旧版本在升级新版本（新注册的消息），不能展示新的ui逻辑，一直展示未知消息类型

**Comment by hzbx** [comment]
根据我们的业务，我能确定：
获取消息UnknownMessageContent的 orignalPayload.type=4014;
后面进行了updateMessage方法，下次获取该消息后orignalPayload.type变成了0

**Comment by heavyrain2012** [comment]
您好，请提供详细的信息，我们需要在demo上来复现这个问题才能解决这个问题

**Comment by imndx** [comment]
no response
