### ISSUE TITLE
会议中开启屏幕共享，播放视频的时候接收方没有声音

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#761]
会议中开启屏幕共享如果当前手机播放其它视频，接收方只是收到的画面没有声音？

可以增加 投屏的 时候 增加开启 或者 关闭 声音 的功能吗 ？

**Comment by imndx** [comment]
测试了下，如果没有静音的的话，设备播放出的声音，能通过麦克风录入，对方能听到的。

是期望自己静音，然后屏幕共享时，对方能听到设备播放出的声音？

**Comment by imndx** [comment]
@chenlin4653 请确认下

> 测试了下，如果没有静音的的话，设备播放出的声音，能通过麦克风录入，对方能听到的。
> 
> 是期望自己静音，然后屏幕共享时，对方能听到设备播放出的声音？

**Comment by chenlin4653** [comment]
是的，自己静音的情况下，设备播放出的声音，对方能听到

**Comment by imndx** [comment]
> 是的，自己静音的情况下，设备播放出的声音，对方能听到

OK，理解问题了，我们研究下

**Comment by imndx** [comment]
这个需求，我们评估了下，觉得意义不太大，先关闭
