### ISSUE TITLE
会议开启屏幕共享,希望api层增加同时开启人数的配置

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#763]
会议开启屏幕共享，AVEngineKit 增加同时开启人数的配置，
例如： 允许 一人开启屏幕共享， 2人不是 同时开启 ，客户端 自己可以控制 ，若 2人 同时点击屏幕共享，客户端 控制不了，需要api  层控制 ，返回的 boolean 状态，客户端自行处理

**Comment by imndx** [comment]
如果只允许一个人开启屏幕共享的话，可以用`requireLock`和`releaseLock`方法实现，`lockId`就用会议 id

**Comment by chenlin4653** [comment]
看了 ChatManger 提供了 requireLock  和  releaseLock  的 方法， demo  没有示例 不清楚具体的使用情况，不知道能不能解决问题， 如果两个人同时点击屏幕共享的操作，最先开启的 触发锁定，后面触发 屏幕共享的 返回 什么呢 ？

**Comment by imndx** [comment]
会走 `onFail`回调，错误码是`25`
