### ISSUE TITLE
进入会话详情，列表错乱

### ISSUE THREAD

**Issue by wangbo666** [wildfirechat/android-chat#764]
## 提issue小提示
为了尽快定位问题，需要我提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
点击会话进入详情，点击右上角未读消息（21条消息），进入第一条未读消息，下拉加载更多，消息是倒序排列的，再下拉 消息重复了。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。
#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
demo也是这样，视频太大传不上来

**Comment by imndx** [comment]
已解决 [86ecd8e](https://github.com/wildfirechat/android-chat/commit/86ecd8ee4691d4fbc52ce52571db199a58d28468)
