### ISSUE TITLE
android 13手机无法打开应用

### ISSUE THREAD

**Issue by believe777** [wildfirechat/android-chat#765]
请问下是否没有做android 13的存储权限适配，现在启动应用无法获取存储权限导致一直finish

**Comment by imndx** [comment]
适配了的。有没有相关日志？怎么复现？

**Comment by imndx** [comment]
demo 上能复现吗？

**Comment by believe777** [comment]
![微信图片_20230602103921](https://github.com/wildfirechat/android-chat/assets/33677634/87274ddf-01df-4bc2-8b67-823537828e37)
android13没有弹出存储权限的授权框，重启应用后就一直finish

**Comment by imndx** [comment]
是不是首次启动的时候，不给权限，还禁止弹出授权请求框了？

**Comment by believe777** [comment]
就弹了2个权限框，没有存储权限框弹出来，去应用详情里面查看权限也没有存储权限
![微信图片_20230602105802](https://github.com/wildfirechat/android-chat/assets/33677634/0d1c5548-dc9c-41c2-b1bb-742a2df8af6c)

**Comment by imndx** [comment]
我们将对动态权限进行重构，可关注`dev-permission`分支。

**Comment by imndx** [comment]
请用最新代码进行测试
