### ISSUE TITLE
熄屏状态下OnReceiveMessageListener接收不到服务

### ISSUE THREAD

**Issue by haiyang886** [wildfirechat/android-chat#766]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
息屏之后，应用是否还活着？
如果被杀了的话，会走推送通道，需要对接[推送](https://github.com/wildfirechat/push_server)

**Comment by haiyang886** [comment]
我用的官方提供的apk测试，息屏但是应用没有被杀次  也呼叫不过来，  熄屏端账号显示  android 不久前在线

**Comment by imndx** [comment]
呼叫不过来 什么意思？音视频通话？

音视频通话的话，是系统限制，小米和华为支持透传推送，能拉活应用，然后弹出音视频通话页面。

**Comment by haiyang886** [comment]
对  就是音视频通话，当被呼叫这处于息屏但是进程在的情况下。呼叫对面，对面接收不到被呼叫的通知

**Comment by imndx** [comment]
> 对 就是音视频通话，当被呼叫这处于息屏但是进程在的情况下。呼叫对面，对面接收不到被呼叫的通知

是收不音视频通话邀请消息，还是能收到音视频通话邀请消息，但是弹不出音视频通话页面？

另外，确定进程还在吗？能否收到普通消息？

**Comment by imndx** [comment]
no response
