### ISSUE TITLE
 群主调用 muteGroupMember 禁言群管理员，返回 248  没有权限的问题 

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#772]
问题汇总
1： 群主调用 muteGroupMember 禁言群管理员，返回 248  没有权限的问题 ？
2： 群可见性  setGroupSearchType（群不可以被查找 、群可以被查找） ，设置  群不可以被查找  还是可以正常搜索？
3 :   好友申请记录能不能增加删除功能，目前删除好友也不会清除好友申请的记录？
4： 同意或者拒绝好友申请  触发 onFriendRequestUpdate   回调 getUnreadFriendRequestCount 未同步更新 好友申请数量？
5： 好友申请拒绝之后 会回调通知申请人吗，申请过期的天数在后端哪里配置，  请问下面三种情况在什么场景下触发？  
   //user error
    public static final int FRIEND_ALREADY_REQUEST = 16;  //"already send request");
    public static final int FRIEND_REQUEST_BLOCKED = 18;  //"friend request blocked");
    public static final int FRIEND_REQUEST_EXPIRED = 19;  //"friend request expired");
6： 群组搜索结果 GroupSearchResult ，搜索中发现群名称和群成员名称 都包含 返回的 1 群成员包含？
    //0 march group name, 1 march group member name, 2 both
    // 0 组名称，1组成员名称，2两者
    // 匹配类型
    public int          marchedType;

**Comment by heavyrain2012** [comment]
问题汇总
1： 群主调用 muteGroupMember 禁言群管理员，返回 248 没有权限的问题 ？
只有专业版IM服务才有禁言单个成功的功能，社区版不支持
2： 群可见性 setGroupSearchType（群不可以被查找 、群可以被查找） ，设置 群不可以被查找 还是可以正常搜索？
IM服务没有群搜索功能，群搜索功能需要你们自己在业务服务上实现，不要在IM服务上做开发
3 : 好友申请记录能不能增加删除功能，目前删除好友也不会清除好友申请的记录？
这个我们稍后会添加删除接口
4： 同意或者拒绝好友申请 触发 onFriendRequestUpdate 回调 getUnreadFriendRequestCount 未同步更新 好友申请数量？
通消息一样，好友申请是有阅读状态的，之后调用clearUnreadFriendRequestStatus才会清除
5： 好友申请拒绝之后 会回调通知申请人吗，申请过期的天数在后端哪里配置， 请问下面三种情况在什么场景下触发？
//user error
public static final int FRIEND_ALREADY_REQUEST = 16; //"already send request");
public static final int FRIEND_REQUEST_BLOCKED = 18; //"friend request blocked");
public static final int FRIEND_REQUEST_EXPIRED = 19; //"friend request expired");
在客户端有个接口，一个是获取发出去的好友申请，一个是获取收到的好友申请。当自己发出去的好友申请被拒绝后，状态会同步到本地，通知是好友请求状态变更。当已经给一个用户发送过好友邀请后，再次发送会有16的错误码。如果被这个用户拉黑，会提示18；当一个人收到好友请求时，没有处理，等待超时时间（IM服务配置）后，再点击接受，会19的错误码
6： 群组搜索结果 GroupSearchResult ，搜索中发现群名称和群成员名称 都包含 返回的 1 群成员包含？
//0 march group name, 1 march group member name, 2 both
// 0 组名称，1组成员名称，2两者
// 匹配类型
public int marchedType;
这个最新SDK有变化，请参考一下最新代码的注释

**Comment by heavyrain2012** [comment]
3 : 好友申请记录能不能增加删除功能，目前删除好友也不会清除好友申请的记录？
这个我们稍后会添加删除接口

这个接口已经添加
