### ISSUE TITLE
申请好友，对方有红点提示，但是点击新的朋友没有数据

### ISSUE THREAD

**Issue by zbalabala** [wildfirechat/android-chat#773]
申请好友，对方有红点提示，但是点击新的朋友没有数据

**Comment by imndx** [comment]
demo 上能复现吗？

**Comment by heavyrain2012** [comment]
demo上只显示了收到的邀请，没有显示发出去的邀请，有获取发出去邀请的接口，你们可以自己来实现，或者你们把产品设计给出来我们在demo上实现也行

**Comment by heavyrain2012** [comment]
这个问题是我们最近协议栈引入的问题，已经更新协议栈解决了这个问题
