### ISSUE TITLE
日志收集中奔溃日志：Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference  cn.wildfirechat.avenginekit.PeerConnectionClient

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#779]
1
cn.wildfirechat.avenginekit.PeerConnectionClient$thcs.nf(PeerConnectionClient.java:10)
2
cn.wildfirechat.avenginekit.PeerConnectionClient$thcs.$r8$lambda$-EvG1RHInMDrlHoqLlDQkmR9AyE(Unknown Source:0)
3
cn.wildfirechat.avenginekit.PeerConnectionClient$thcs$$ExternalSyntheticLambda2.run(Unknown Source:4)
4
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
5
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
6
java.lang.Thread.run(Thread.java:1012)

**Comment by imndx** [comment]
已解决
