### ISSUE TITLE
视频语音挂断调用endCall()方法无效

### ISSUE THREAD

**Issue by Anlycal** [wildfirechat/android-chat#78]
挂断时调用endCall()方法无效

AVEngineKit.CallSession session = gEngineKit.getCurrentSession();
        if (session != null) {
            session.endCall();
        } else {
            getActivity().finish();
        }

**Comment by imndx** [comment]
你是最新代码吗？之前有个版本，出现过不能接通、挂断的bug。

**Comment by Anlycal** [comment]
是基于之前的代码开发的，后面更新过协议栈，挂断功能就不能用了，问下最新代码改动的地方在哪？

**Comment by imndx** [comment]
改动了不少，你升级下代码吧，或者测试下我们demo

**Comment by Anlycal** [comment]
语音视频与最新的代码比较了一下，这部分没什么改动，问题是视频接通了之后一直处于Connecting的状态，不能监听到Connected和Idle的状态，问下这个问题是怎么造成的？

**Comment by imndx** [comment]
ChatManager#updateMessage方法，你的代码和最新的是否一致？这个可能有关系

**Comment by Anlycal** [comment]
问题解决了，多谢。
