### ISSUE TITLE
日志收集中有关webrtc的奔溃日志：SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#780]
1	#00 pc 000cc950 /vendor/lib/egl/libGLESv2_mtk.so [armeabi-v8::34ed5df2075eeb41cbc04b3113ec2bda]
2	#01 pc 00096b2f /vendor/lib/egl/libGLESv2_mtk.so [armeabi-v8::34ed5df2075eeb41cbc04b3113ec2bda]
3	#02 pc 00069569 /vendor/lib/egl/libGLESv2_mtk.so [armeabi-v8::34ed5df2075eeb41cbc04b3113ec2bda]
4	#03 pc 000271bf /vendor/lib/egl/libGLESv2_mtk.so [armeabi-v8::34ed5df2075eeb41cbc04b3113ec2bda]
5	#04 pc 0002687d /vendor/lib/egl/libGLESv2_mtk.so [armeabi-v8::34ed5df2075eeb41cbc04b3113ec2bda]
6	#05 pc 0000bdcb /vendor/lib/libIMGegl.so [armeabi-v8::371891638abe6c30816cd11ab5761699]
7	#06 pc 00010bb9 /vendor/lib/libIMGegl.so (IMGeglDestroyContext+464) [armeabi-v8::371891638abe6c30816cd11ab5761699]
8	#07 pc 0001c591 /vendor/lib/egl/libGLES_meow.so [armeabi-v8::6d6caf55643460f2db471f5c3405e207]
9	#08 pc 00015b41 /system/lib/libEGL.so [armeabi-v8::ba8fdea35c7f0366c4bc3b056057dc3a]
10	#09 pc 0008faa1 /system/lib/libandroid_runtime.so [armeabi-v8::ab0a96415073b1a840cb12bf2e86fe67]
11	#10 pc 00973da3 /system/framework/arm/boot-framework.oat [armeabi::135cf4cd96e2dfadc15682f2d50b3461]
12	java:
13	org.webrtc.EglBase14Impl.release(EglBase14Impl.java:160)
14	org.webrtc.HardwareVideoEncoder.release(HardwareVideoEncoder.java:328)

**Comment by imndx** [comment]
已解决，请更新到最新代码测试
