### ISSUE TITLE
日志收集中有关webrtc的奔溃日志：SIGSEGV(SEGV_MAPERR)，收集工具中此问题出现频率很高

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#781]
出错堆栈

1	#00 pc 001e02c8 /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
2	#01 pc 001e020f /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
3	#02 pc 001e01c9 /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
4	#03 pc 004e42bd /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
5	#04 pc 004d18b5 /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
6	#05 pc 0048e355 /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
7	#06 pc 0048f1e1 /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
8	#07 pc 0048e71b /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
9	#08 pc 0023bcb1 /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
10	#09 pc 0023bc27 /data/app/com.tongfudun.dtcmessenger-ZpMY6GYAf_kSU1wptFLOjA==/lib/arm/libjingle_peerconnection_so.so [armeabi-v7a::3aed9f052c0d3a0c0000000000000000]
11	#10 pc 000a6293 /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20) [armeabi-v8::af31ec96b35fedca378e07659b30896c]
12	#11 pc 00060803 /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) [armeabi-v8::af31ec96b35fedca378e07659b30896c]
13	java:
14	[Failed to get Java stack]

**Comment by imndx** [comment]
已解决
