### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#784]
Error during updateTexImage (see logcat for details)
android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)

1	android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
2	android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
3	org.webrtc.SurfaceTextureHelper.updateTexImage(SurfaceTextureHelper.java:334)
4	org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:354)
5	org.webrtc.SurfaceTextureHelper.lambda$new$0$org-webrtc-SurfaceTextureHelper(SurfaceTextureHelper.java:207)
6	org.webrtc.SurfaceTextureHelper$$ExternalSyntheticLambda0.onFrameAvailable(Unknown Source:2)
7	android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:211)
8	android.os.Handler.dispatchMessage(Handler.java:106)
9	android.os.Looper.loop(Looper.java:236)
10	android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by imndx** [comment]
[webrtc issue](https://bugs.chromium.org/p/webrtc/issues/detail?id=9683)
