### ISSUE TITLE
需要解决的问题

### ISSUE THREAD

**Issue by ceshi8899** [wildfirechat/android-chat#785]
1、安卓手机--我的--账号与安全中，无法查看自己的手机号，也无法修改，苹果手机正常显示号码
2、点开好友用户信息，点击有角...，显示设置“取消星标好友”，操作后实际操作为设置星标好友，提示语错误，相反，取消星标好友的提示语为“设置星标好友”，显示错误
3、删除好友后，联系人列表不显示该用户，对话列表仍显示，可以向对方发送信息，对方也能收到，点击头像查看信息显示可添加对方好友
4、安卓/苹果收藏视频后，在收藏中无法打开查看
5、手机、电脑保存群聊，两边通讯录不同步，手机保存的电脑不显示，电脑保存的，手机不显示

**Comment by imndx** [comment]
2. 提示的是`设置成功`，你们如果想设置为其他的可以自行修改
3. 最新`demo`上无法复现，删好友成功之后，删一下对应的会话，如果在`demo`复现，请录屏看一下
4. 最新代码已支持
5. 最新`demo`上无法复现，如果在`demo`复现，请录屏看一下

**Comment by ceshi8899** [comment]
4、安卓/苹果收藏视频后，在中无法打开查看

**Comment by imndx** [comment]
以上两个问题，最新代码都已修复
