### ISSUE TITLE
Make sure to call FirebaseApp.initializeApp(Context) first.

### ISSUE THREAD

**Issue by captain-miao** [wildfirechat/android-chat#794]
#### 操作说明
谷歌服务的手机

#### 表现现象
Default FirebaseApp is not initialized in this process com.heavysword.chuanshu:marsservice. Make sure to call FirebaseApp.initializeApp(Context) first.

com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)

应用闪退

#### 修复
``` java
    private void initFCM(Context context) {
        FirebaseApp.initializeApp(context); // 增加这一行
        FirebaseMessaging.getInstance().setAutoInitEnabled(true);
        ...
    }
```

**Comment by imndx** [comment]
谢谢反馈
