### ISSUE TITLE
关于修改系统时间后聊天消息发送失败，实际成功问题

### ISSUE THREAD

**Issue by xiaoeli** [wildfirechat/android-chat#795]
复现步骤：
把系统时间改成手动设置，年份设置未来几年后，聊天发文本消息 sendMessage 接口返回 errorCode： -100001，Send_Failure，但是对方能成功收到这条消息

必现，iOS 也有此问题，demo 必现。

期望：表现与结果一致

**Comment by heavyrain2012** [comment]
IM服务的问题，只检查了单向的时间间隔，最新代码已经解决，请更新最新代码验证
