### ISSUE TITLE
音视频通话聊天存在问题

### ISSUE THREAD

**Issue by hbliucl** [wildfirechat/android-chat#8]
1. 视频聊天, 聊天界面正常, 但是双方说话没有声音
2. 音频聊天, 第一次安卓给ios打, 双方都有声音, 挂断, 安卓再给ios打, 能接通但是说话没有声音, 反过来ios给安卓打, 接通说话还是没有声音

希望能修复, 辛苦各位!

**Comment by heavyrain2012** [comment]
手机是什么型号，所有需要的权限都开了吗，当时的网络是移动网络还是wifi，android和android打有没有问题，ios和ios打有没有问题

**Comment by imndx** [comment]
没有进一步回应。
