### ISSUE TITLE
清空消息后，消息内容还在

### ISSUE THREAD

**Issue by FredericYan** [wildfirechat/android-chat#80]
清空会话消息后，消息内容还在，并没有真正清空

**Comment by imndx** [comment]
本地清空了，然后又从服务器加载了远程历史消息

**Comment by FredericYan** [comment]
那这种情况如何清除消息呢？本地消息删除后，会发请求给服务器删除服务器消息或修改此条消息在服务器的状态么？

**Comment by imndx** [comment]
我能想到两个方案吧。

## 方案1
简单粗暴。直接把拉远程历史消息的函数注释了。

## 方案2
0. ```UserSettingScope```添加一种类型```ClearConversation```
1. ```UserSetting#UserSettingScope```里面存储每个会话最旧一条消息的```messageUid```，默认是0，当清会话时，更新为该会话最新一条消息的```messageUid```。
2. 会话里面不显示```messageUid```小于该会话最旧```messgeUid```的消息
3. 多端收到```UserSetting#UserSettingScope```更新通知时，执行本地批量删除消息的操作。
4. 协议栈需要新增```deleteMessages(type, target, line, beforeMessageUid)```接口，但这步其实是可选的。

**Comment by yuzhongrong** [comment]
@FredericYan 这个你实现了吗 我写了后 发现错误挺多的

**Comment by yuzhongrong** [comment]
就撤回去了

**Comment by imndx** [comment]
这问题可以通过server端关闭消息漫游功能解决。

[消息漫游](https://github.com/wildfirechat/server/blob/512d797d4d9ac4e2b3572bf20d7ee3e76c627eba/broker/config/wildfirechat.conf#L46)

**Comment by imndx** [comment]
请看这儿[消息无法删除问题](http://docs.wildfirechat.cn/faq/general.html#%E6%B6%88%E6%81%AF%E6%97%A0%E6%B3%95%E5%88%A0%E9%99%A4%E9%97%AE%E9%A2%98)
