### ISSUE TITLE
Xlog如何存储在不同的文件夹，并且设置不同的文件名称

### ISSUE THREAD

**Issue by gnmmdk** [wildfirechat/android-chat#804]
想使用Xlog进行日志写入，发现野火已经集成了，如何在野火集成的基础上，设置日志保存在不同的文件夹，并且设置不同的文件名。

**Comment by gnmmdk** [comment]
另外Xlog日志删除时间是什么时候？保存的时间是多久？

**Comment by gnmmdk** [comment]
另外Xlog日志删除时机是什么时候？保存的时间是多久？

**Comment by imndx** [comment]
`Xlog`的使用方法等，和`mars`官方的完全一致。

**Comment by heavyrain2012** [comment]
到clientservice.java文件中找到startLog方法，看那个就行

**Comment by gnmmdk** [comment]
野火现在是设置log作为文件夹，设置多个文件夹，例如野火还是放在log，其他日志放到/otherLog 文件夹

**Comment by gnmmdk** [comment]
野火现在是设置log作为文件夹，我想要的是设置多个文件夹，例如野火还是放在log文件夹下面，其他日志放到/otherLog 文件夹

**Comment by heavyrain2012** [comment]
xlog应该是不支持这样吧
