### ISSUE TITLE
希望提供会议修改主持人的 api 同时增加会议 主持人改变的回调方法

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#805]
希望提供  会议修改主持人的  api 同时增加会议 主持人改变的回调方法，AVEngineKit类 调用加入会议之后，如果中途转让主持人，AVEngineKit.CallSession 获取的主持人还是之前，请帮忙协助解决，谢谢。。。

**Comment by heavyrain2012** [comment]
在会议中其实所有成员的权限都是平等的，包括“主持人”和普通成员。所以这个主持人是没有意义的，可以忽略callsession中的“主持人”然后在其他数据中记录主持人
