### ISSUE TITLE
文件消息第一次点击提示“找不到能打开此文件的应用”

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/android-chat#807]
#### 操作说明
会话里收到文件
点击文件消息气泡

#### 表现现象
提示“找不到能打开此文件的应用”，同一个消息气泡要再点击一次才会弹出调用外部app打开的询问弹窗
miui13

#### 预期结果
第一次点击就能弹起调用外部app打开的面板

（我们发现是第一次点击时还未下载完成，所以打开不了文件）

第一次点击
![03c73fe61c01df577ea6ed5c3532d29](https://github.com/wildfirechat/android-chat/assets/11338629/22fb4003-a4fd-444b-b272-26b69970d904)

第二次点击
![5d2f0bc8653d9687d28eda7ce70f174](https://github.com/wildfirechat/android-chat/assets/11338629/8412d885-c80b-4a82-8498-3db1124950f4)

**Comment by zenggong965** [comment]
应该是网页版发文件content type问题，更新了最新的web sdk就好了

**Comment by imndx** [comment]
这个可能是发送端`content-type`的问题，我们这边复现不了了，请问还能复现吗？

**Comment by zenggong965** [comment]
@imndx 可以复现，用网页版的文件传输助手发文件到手机端
![image](https://github.com/wildfirechat/android-chat/assets/11338629/39bb7c07-0fc1-4c66-b177-10eea65a02e0)

**Comment by imndx** [comment]
我们用 demo 怎么怎么复现不了呢？:cry:

**Comment by zenggong965** [comment]
@imndx 用office三件套的文件试一下
[xls表格.xls](https://github.com/wildfirechat/android-chat/files/12463671/xls.xls)
[docx文件.docx](https://github.com/wildfirechat/android-chat/files/12463677/docx.docx)
[pptx文件.pptx](https://github.com/wildfirechat/android-chat/files/12463678/pptx.pptx)
