### ISSUE TITLE
已发送的信息是否可以改变其中某个状态值

### ISSUE THREAD

**Issue by gukezfc** [wildfirechat/android-chat#808]
野火已发送出去的消息中的某个状态字段可以改动吗，比如说发送了一条红包信息，未领取状态0与已领取状态1，领取之后把这个未领取状态0怎么修改变成1，

**Comment by heavyrain2012** [comment]
客户端SDK有更新本地消息的接口，可以更新本地的消息内容。如果要想同步更新所有端，专业版支持更新远程消息的功能

**Comment by gukezfc** [comment]
本地更新的接口名字与专业版更新远程消息的api名字是什么

**Comment by imndx** [comment]
`updateMessage`和`updateRemoteMessageContent`
