### ISSUE TITLE
部分手机暗黑模式下看不清消息气泡里的文字

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/android-chat#809]
测试机型，一加7
建议暗黑模式时，对方发的消息用白色文字，己方发的消息还是保持黑色文字
![image](https://github.com/wildfirechat/android-chat/assets/11338629/e3a257ed-f565-409c-a65e-55023ca90657)

**Comment by zenggong965** [comment]
@imndx 这已经影响到可用性了，年纪大的用户看不清消息完全没法用

**Comment by imndx** [comment]
@zenggong965 demo 本身并没有做暗黑模式，这是系统强制改的。
