### ISSUE TITLE
内存溢出的问题

### ISSUE THREAD

**Issue by gukezfc** [wildfirechat/android-chat#812]
有一个用户，今天突然自己无法打开聊天列表，也无法发送信息，其他用户只要打开与此账号的聊天框闪退，报错信息如下Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 2932344992 byte allocation with 21220277 free bytes and 235MB until OOM, target footprint 42473325, growth limit 268435456

**Comment by imndx** [comment]
有无更多信息？是不是该账号有什么特殊消息触发的？

**Comment by gukezfc** [comment]
特殊消息？什么情况下的特殊消息会导致内存溢出

**Comment by imndx** [comment]
不知道，我们没遇到过，之前也没人反馈过
要有更多信息，我们才能确定问题

**Comment by imndx** [comment]
no response
