### ISSUE TITLE
删除有未读消息的会话，消息状态变成已读问题

### ISSUE THREAD

**Issue by xiaoeli** [wildfirechat/android-chat#816]
#### 操作说明
A收到B新消息（未读），A 删除会话，B的消息状态显示为：A 已读。

#### 预期结果
消息状态为：未读

#### 补充条件
必现

#### demo对比结果
最新 demo 必现

**Comment by heavyrain2012** [comment]
这个应该是正确的吧，已经处理了，应该就是已读
