### ISSUE TITLE
加好友后消息显示不了

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/android-chat#820]
### 操作说明
两个用户都是安卓
B在本机新安装App后，用验证码注册，设置密码，进入app会话
B设置自己的昵称
A扫B的二维码发起加好友
B回到通讯录里>新的朋友里面通过加好友请求
B在会话里查看A的消息

### 表现现象
B手机显示不了加好友消息，A再发消息，B也显示不了。B把app杀进程重启就能正常显示了。
非必现

A手机是小米11，miui13
B手机是realme v30t，realme ui 3.0

这个现象在设置了用户退群消息只群主/群管理可见以后，变的多了起来
![c09b65b4370703411a30bfa90b7837f](https://github.com/wildfirechat/android-chat/assets/11338629/dd9dec76-a8da-497c-a3d8-2a7c5922c18d)

### 预期结果
消息能够正常显示

**Comment by imndx** [comment]
demo 上能复现能复现这问题吗？

**Comment by zenggong965** [comment]
目前没找到稳定复现路径，在demo也复现不了。因为app杀进程重启能正常显示，想问下可能是哪个环节出问题？

**Comment by imndx** [comment]
B手机显示不了加好友消息，A再发消息，B也显示不了。B把app杀进程重启就能正常显示了。

-----

A 再发消息，B 也显示不了；那反过来，B 给 A 发消息，两边显示正常吗？


另外，回落到`unknown`消息的时候，日志上会显示回落的原因，看下日志。

**Comment by imndx** [comment]
no response
