### ISSUE TITLE
修改保存超出字数限制的群公告，提示“失败500”，但群内已发布了群公告消息。

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/android-chat#825]
####操作说明及现象：
群-修改群公告，
当长度超过一定值（试了下似乎是英文255和中文249），点击确定提示保存失败“500”
查看群公告栏保存失败，但是群内还是发布了消息
“@ 所有人 xxxx”。

概率：100%

####预期结果：
提示保存失败正确说明，群内不应该发布显示未保存的群公告。

**Comment by heavyrain2012** [comment]
原因是appserver那边没有设置文本内容的宽度，这样默认就是255。https://github.com/wildfirechat/app-server/commit/7c6f3bea4adc85b726c23a3998b513f3958c51c0 这个修改已经改成2048，我们认为这个数字是比较合适的，如果你们要是觉得不合适，可以改成其他数字或者不限制长度的文本。
