### ISSUE TITLE
初次进入修改群公告，提示“获取群公告失败”

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/android-chat#826]
#### 操作说明
新建群，进入会话详情，点击“群公告”

#### 表现现象
提示“获取群公告失败”（只要不修改，反复进入群公告都会提示）

#### 预期结果
不应该提示这条信息

#### 补充条件
必现

**Comment by imndx** [comment]
由于没有设置群公告，获取群公告就会失败。

可以下面这个提示给注释了，或者根据`code`和`msg`字段，显示更明确的提示
https://github.com/wildfirechat/android-chat/blob/a157a504e0c2b360886ff9ba28671093fa67cefa/uikit/src/main/java/cn/wildfire/chat/kit/group/SetGroupAnnouncementActivity.java#L70
