### ISSUE TITLE
Android 调用 clearAllUnreadStatus 无效

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#828]
android端调用 clearAllUnreadStatus方法，没有清除未读消息，手动杀死应用重新打开未读消息依然存在，demo （android-chat-8ab3042804486d03fd4d8c2305a7b861ac2a22cf） 试过也是同样的问题，请帮忙排查 clearAllUnreadStatus（）

**Comment by imndx** [comment]
[cdc90ee](https://github.com/wildfirechat/android-chat/commit/cdc90ee2658f6119cbd8cd8df831fdd7608a649b)
