### ISSUE TITLE
android clearAllUnreadStatus() 和 clearUnreadStatusEx()  函数的问题

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#831]
android 端 

调用 clearAllUnreadStatus()函数清除本地未读消息，未同步清除远程未读消息状态，卸载重新安装发现之前清除的未读消息依然存在；

调用 clearUnreadStatusEx(List<Conversation.ConversationType> conversationTypes, List<Integer> lines)() 方法  返回 false ， 没有任何效果，iOS这边 使用此方法 可以正常清除未读消息，且同步远程未读消息状态， 卸载重新安装，一切正常；

**Comment by imndx** [comment]
已修复，请用最新代码测试
