### ISSUE TITLE
Android 13版本。

### ISSUE THREAD

**Issue by 871263000** [wildfirechat/android-chat#836]
红米 手机Android 13系统。文字消息。不显示，有的显示不全

**Comment by imndx** [comment]
是不是你们改出来的什么问题？demo 上能复现吗？

**Comment by 871263000** [comment]
textView  好像没有给textColor。   是别人的手机，  我这边手机都没有问题。

**Comment by 871263000** [comment]
系统给了默认的白色。  好像没有显示

**Comment by imndx** [comment]
可以自行调整下配色
