### ISSUE TITLE
clearMessageUnreadStatusBefore 频繁调用 在android11之后会阻塞ui

### ISSUE THREAD

**Issue by z876335662** [wildfirechat/android-chat#839]
clearUnreadStatusBeforeMessage:::startTime::::1698921069422
clearUnreadStatusBeforeMessage:::endTime::::3
 clearUnreadStatusBeforeMessage:::startTime::::1698921069439
clearUnreadStatusBeforeMessage:::endTime::::2
android 10  小米频繁 调用不会卡顿

clearUnreadStatusBeforeMessage:::startTime::::1698921522830
clearUnreadStatusBeforeMessage:::endTime::::155
 clearUnreadStatusBeforeMessage:::startTime::::1698921522986
clearUnreadStatusBeforeMessage:::endTime::::121
clearUnreadStatusBeforeMessage:::startTime::::1698921523124                   
 clearUnreadStatusBeforeMessage:::endTime::::266
android 13 oppo 手机频繁调用就非常卡顿
运行过程中log提示   Already have a pending vsync event.  There should only be one at a time

**Comment by imndx** [comment]
可以采用异步的方式调用`clearUnreadStatusBeforeMessage`
