### ISSUE TITLE
群聊人数过多，点选右上方人头「会话详情」，卡顿或崩溃

### ISSUE THREAD

**Issue by yichenlo01** [wildfirechat/android-chat#84]
我这边群组有五百人。
点选群组右上方人头察看详情时
会稍微停顿，应该是在Loading。
但是手机比较不好的就会崩溃闪退

**Comment by yichenlo01** [comment]
载了最新版的客端，虽然不会闪退。
但是会显示野火IM已停止运作，而且人头都不见了

**Comment by imndx** [comment]
停止工作，应当是出了什么错误，能否提供一下日志？
