### ISSUE TITLE
发送消息在 onFail 回调里面收到 10091

### ISSUE THREAD

**Issue by LeonShannon** [wildfirechat/android-chat#842]
<img width="350" alt="image" src="https://github.com/wildfirechat/android-chat/assets/24221796/efc1fb71-0a48-4c7c-848b-e8c8c2cd3bf2">
<img width="772" alt="image" src="https://github.com/wildfirechat/android-chat/assets/24221796/23583abc-890c-4c77-9be0-df9a3004ff4d">
 用户可以收到消息，但是无法发送消息，卸载重装都试过了也不行

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
这个可能是网络相关错误，请附上`adb logcat > log.log`抓取的完整日志。

**Comment by imndx** [comment]
试试这个命令：

给任意人发送`*#marslog#`，如果没有屏蔽这个命令的话，会把日志发送到当前会话中。

**Comment by imndx** [comment]
> 我们先测试了一下，没有 log，需要怎么查看是否屏蔽.

默认是内置这个调试命令的，发送这几个字符`*#marslog#`就会把日志发到当前聊天会话。

另外，demo 的话，设置页是有上传日志功能，不知道，你们去了没有。

和 soc 没关系，细节会被操作系统屏蔽的，请想办法提供日志，我们需要日志才能分析。

**Comment by imndx** [comment]
我们就内置两种办法，现在可能都被你们屏蔽了，我们没其他办法，需要你们想其他办法了。

**Comment by imndx** [comment]
> 问了下服务端，他们并没有说有过类似操作。我们应该如何排查解除屏蔽`*#marslog#`命令呢

这是客户端的一个功能，请参考：

https://github.com/wildfirechat/android-chat/blob/c93a5a77f0d794027e4bdb2aa63ca59f69e4d318/uikit/src/main/java/cn/wildfire/chat/kit/WfcUIKit.java#L156-L156

**Comment by imndx** [comment]
调用`ChatManager#startLog`打开日志功能了吗？

https://github.com/wildfirechat/android-chat/blob/c93a5a77f0d794027e4bdb2aa63ca59f69e4d318/uikit/src/main/java/cn/wildfire/chat/kit/WfcUIKit.java#L155

**Comment by adams-github** [comment]
@LeonShannon 你好，想问下你这个问题怎么解决的，我这边也遇到了
