### ISSUE TITLE
重复发送好友请求问题

### ISSUE THREAD

**Issue by hfz336** [wildfirechat/android-chat#846]
#### 操作说明
申请添加好友时可以重复发送两次好友请求，等第三次才会提示失败。

#### 预期结果
在重复周期内应该只能发送一次

请问这种需要如何调整修改？

#### 补充条件
必现现象

**Comment by heavyrain2012** [comment]
最近添加一个功能，发送好友请求在5分钟内可以再发送一次，一般用来发送请求时填错信息，可以再次发送来补救。请测试超过5分钟后还能不能发送，如果超过5分钟不能发送就可以认为功能正确
