### ISSUE TITLE
发起群聊搜索联系人分组显示问题

### ISSUE THREAD

**Issue by xiaoeli** [wildfirechat/android-chat#847]
操作说明
首页发起群聊----创建会话，联系人列表搜索字母分组的第一人，如 x 组第一位 小火，搜索结果列表点击 小火

表现现象
点击后，联系人列表 "x" 变成了 “搜索结果”，Demo 必现

预期结果
点击后 "x" 不变

**Comment by imndx** [comment]
你好，不太理解问题，请截图示例下

**Comment by xiaoeli** [comment]
> 示

![1706760453316-402704397886292097](https://github.com/wildfirechat/android-chat/assets/26917553/0b22d879-0214-4434-9a5e-14e413ca65e6)
