### ISSUE TITLE
申请好友+群管理 + 群禁言 问题 

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#848]
协议栈 版本20231225;
1: 申请添加好友，申请方发起好友申请请求，接口方调用 getUnreadFriendRequestStatus() 返回数量 0 ，实际 调用 getFriendRequest(true) 返回有正确的好友申请列表，此问题之前没有，换 20231225 打包的协议栈后出现， iOS 也有同样的问题 ；

2： 微信维护群反馈的问题：
(1) : 客户端 操作 群人数 (3000+) 調用 setGroupManager()设置群管理员，客户端 返回失败( 失败返回错误码 4 )，服务端查询实际成功了，客户端二次进入发现上次操作失败的其实是成功的，群人数 (1500+) 調用 setGroupManager()设置群管理员 成功 ，此问题 微信im维护群 回复  这个问题可能更新版本就好了（请问服务端 和  客户端 同时更新版本吗 ？）

(2) :调用   muteGroupMember() 设置 禁言群成员 ，群主角色禁言群管理员身份  返回 错误码 248 （没有权限操作）, 群主 角色 禁言 群成员身份 返回错误码 4 (服务器出现未知错误)；

**Comment by heavyrain2012** [comment]
1，这个问题我们测试一下。
2，我们最新版本已经优化了，更新最新版本IM服务应该就能解决问题，客户端不用更新
3，禁言时，必须先取消管理员，再禁言这个群成员，不能直接禁言管理员

**Comment by chenlin4653** [comment]
谢谢
反馈2的问题 等我们服务端升级之后再看看；
反馈 3的问题 测试 群主禁言 普通群成员 成功， 群管理 禁言 普通群成员 也 成功。

**Comment by imndx** [comment]
第1 个问题， demo 上无法复现，请用 demo 测试一下

**Comment by imndx** [comment]
no response.
