### ISSUE TITLE
请问clientId都有什么情况下会改变,我打开APP 获取了一下clientId,杀死进程重新进入APP在获取clientId 发现已经改变了

### ISSUE THREAD

**Issue by clbDream** [wildfirechat/android-chat#85]

**Comment by clbDream** [comment]
在DEMO中没有发现保存呀,你说的应该是IM的用户id和token需要通过sp保存吧
![image](https://user-images.githubusercontent.com/28987014/61364093-b626fa00-a8b7-11e9-8b01-a032387d4b75.png)

**Comment by imndx** [comment]
clientService那个类里面保存的

**Comment by clbDream** [comment]
通过打日志我发现,用SP保存ClientId这个字段的时候返回保存成功了,但是SP文件里面并没有这个记录,我看获取的SP文件名是默认的,因为我修改了DEMO的包名为我的包名,所以我尝试换个SP文件名来保存,神奇的是这次正常了,而且之前的所有问题都没有了,而我一旦换成默认的SP文件名,问题就出现了,下面是我的两个SP文件
![image](https://user-images.githubusercontent.com/28987014/61506505-e59f4900-aa14-11e9-8428-bf21e59d59a9.png)
![image](https://user-images.githubusercontent.com/28987014/61506514-ecc65700-aa14-11e9-99d9-5f42a61275ce.png)
![image](https://user-images.githubusercontent.com/28987014/61506574-17181480-aa15-11e9-9a5f-cb5c3694a419.png)

**Comment by clbDream** [comment]
修改SP的文件名两天了,暂时没有发现之前遇到的情况,按理说我直接使用DEMO开发的,应该除了修改项目的包名和一些第三方的Key还有IP地址,其他的应该不需要修改

**Comment by imndx** [comment]
这有点神奇啊

**Comment by Godsbox** [comment]
我的会这个问题， 最好你们源码改下
