### ISSUE TITLE
如何获取聊天记录的大小，包括全部的和各个会话的大小

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/android-chat#850]
我们想做个聊天记录备份和恢复的功能，如何获取聊天记录的大小，包括全部的和各个会话的聊天记录大小

**Comment by imndx** [comment]
请参考这篇文章来实现相关功能，如果有问题的话，请在这个 issue 下继续讨论
[如何实现聊天记录的备份与恢复](https://docs.wildfirechat.cn/blogs/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95%E7%9A%84%E5%A4%87%E4%BB%BD%E4%B8%8E%E6%81%A2%E5%A4%8D.html)

**Comment by imndx** [comment]
no response
