### ISSUE TITLE
USE_EXACT_ALARM  google play 提审被拒

### ISSUE THREAD

**Issue by Hopkin2016** [wildfirechat/android-chat#851]
## google play 提审被拒

![04DD6299-058D-42B2-AE5E-36CE3FA1930C](https://github.com/wildfirechat/android-chat/assets/19381002/a5412b20-af13-4086-b384-24bc534400f7)

“精确闹钟权限”政策：对该权限的使用与您应用的核心用途没有直接关系。
详细信息
我们发现您的应用不符合使用 [USE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission#USE_EXACT_ALARM) 权限的相关要求。具体而言，对该权限的使用与实现应用的核心用途并没有直接关系。

**Comment by imndx** [comment]
这个可以进行申诉一下，即时通讯相关 app，需要通过心跳机制和服务端端保持连接。

**Comment by Hopkin2016** [comment]
![04DD6299-058D-42B2-AE5E-36CE3FA1930C](https://github.com/wildfirechat/android-chat/assets/19381002/9d214631-5f41-4199-8a98-a9bad024aaba)
