### ISSUE TITLE
使用音视频服务时，release包点击语音通话、视频通话，没有弹出拨打界面，对方直接收到未接通消息，debug包正常。是使用im服务端代码自己部署的

### ISSUE THREAD

**Issue by leef2464** [wildfirechat/android-chat#853]
#### 表现现象
使用音视频服务时，release包点击语音通话、视频通话，没有弹出拨打界面，对方直接收到未接通消息，debug包正常。是使用im服务端代码自己部署的。我看日志是因为AVEngineKit.Instance().startCall方法返回的AVEngineKit.CallSession对象为null。请问这是什么原因呢

#### 预期结果
正常使用

#### 补充条件
必现，最新的库

**Comment by imndx** [comment]
是不是混淆的问题？

**Comment by imndx** [comment]
no response
