### ISSUE TITLE
为什么在 android-chat 项目里面没有配置 tencent_sms.properties ，不就没有办法更换信息服务功能吗？

### ISSUE THREAD

**Issue by wondenful** [wildfirechat/android-chat#855]
为什么在 android-chat 项目里面没有配置 tencent_sms.properties ，不就没有办法更换信息服务功能吗？

**Comment by imndx** [comment]
短信验证码相关和`android-chat`没有关系，这个功能是在[app-server](https://github.com/wildfirechat/app-server)的，需要在`app-server`修改配置
