### ISSUE TITLE
android 14精准闹钟权限导致信息无法发送

### ISSUE THREAD

**Issue by z876335662** [wildfirechat/android-chat#857]
java.lang.SecurityException: Caller com.xxxx needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
03-18 10:29:12.233 18445 19966 W System.err:    at android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
03-18 10:29:12.233 18445 19966 W System.err:    at android.os.Parcel.createException(Parcel.java:3071)
03-18 10:29:12.233 18445 19966 W System.err:    at android.os.Parcel.readException(Parcel.java:3054)
03-18 10:29:12.234 18445 19966 W System.err:    at android.os.Parcel.readException(Parcel.java:2996)
03-18 10:29:12.234 18445 19966 W System.err:    at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:329)
03-18 10:29:12.234 18445 19966 W System.err:    at android.app.AlarmManager.setImpl(AlarmManager.java:1097)
03-18 10:29:12.234 18445 19966 W System.err:    at android.app.AlarmManager.setImpl(AlarmManager.java:1057)
03-18 10:29:12.234 18445 19966 W System.err:    at android.app.AlarmManager.setExact(AlarmManager.java:821)
03-18 10:29:12.235 18445 19966 W System.err:    at com.tencent.mars.comm.Alarm.setAlarmMgr(Alarm.java:164)
03-18 10:29:12.235 18445 19966 W System.err:    at com.tencent.mars.comm.Alarm.start(Alarm.java:98)
03-18 10:29:12.235 18445 19966 W System.err:    at com.tencent.mars.comm.PlatformComm$C2Java.startAlarm(PlatformComm.java:193)
03-18 10:29:12.235 18445 19966 E mars::comm: [alarm.cc, Start, 56]:startAlarm error, id:12970367469222658528, after:240000, seq:243
03-18 10:29:12.235 18445 19966 W mars::stn: [longlink_task_manager.cc, __OnResponse, 568]:task error, taskid:0, cmdid:0, error_type:4, error_code:-10091

**Comment by imndx** [comment]
```
   <uses-permission
        android:name="android.permission.SCHEDULE_EXACT_ALARM"
        android:maxSdkVersion="32" />
    <uses-permission android:name="android.permission.USE_EXACT_ALARM" />


```
