### ISSUE TITLE
插入消息所在的群已退出了，插入后群头像和名称不正确

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/android-chat#858]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
我们做了个备份和恢复消息的功能，
有一种场景：
1，备份消息的时候在群内；
2，退群了；
3，恢复并插入消息；
问题：这个退的群的消息所在的群头像和信息不正确；
分析：在插入消息的时候，无法获取已退出群的信息，但是消息仍然插入了。

#### 预期结果
希望已退的群的消息就不再插入操作了，直接跳过该消息；

**Comment by heavyrain2012** [comment]
需要服务器端做支持

**Comment by heavyrain2012** [comment]
我们最近添加了群组标记删除功能。在插入消息，或者显示会话列表时，如果发现群组是被删除的，删除会话和消息可以实现你的需求
