### ISSUE TITLE
关闭「消息撤回」的提醒消息，不生效。

### ISSUE THREAD

**Issue by PaulYan233** [wildfirechat/android-chat#860]
## 提issue小提示
希望实现，发生撤回消息的动作后，不显示“消息已撤回”的消息提醒。
但是配置了也还是会有这个提示消息。

#### 操作说明
// 改成 PersistFlag.No_Persist 没作用

@ContentTag(type = ContentType_Recall, flag = PersistFlag.No_Persist)
public class RecallMessageContent extends NotificationMessageContent {

}

#### 预期结果
撤回消息之后，不显示“消息已撤回”的消息提醒或者不产生这个提醒。

**Comment by imndx** [comment]
已更新，需要配合 im-server 更新
