### ISSUE TITLE
清空本地会话 功能模糊

### ISSUE THREAD

**Issue by Dong200003** [wildfirechat/android-chat#865]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明

在聊天会话中，进行清空聊天记录，选择【清空本地会话】。

#### 表现现象
清空后返回到“消息”列表，再次进入该聊天会话时，消息又恢复了。

#### 预期结果
清空本地聊天记录的时候，可以记录下，再进入会话时，不再加载远程历史消息

#### 补充条件
必现的

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
比如这种情况，你们期望是什么样子？

清空会话的本地消息，之后，会话里面又收发了有很多消息，查看消息时，不断下拉查看之前的消息，那清空本地消息操作节点之前的消息，还应当加载吗？
