### ISSUE TITLE
NetworkSignalUtil.InitNetworkSignalUtil

### ISSUE THREAD

**Issue by Hopkin2016** [wildfirechat/android-chat#872]
## 提issue小提示
NetworkSignalUtil.InitNetworkSignalUtil

Unable to create service cn.wildfirechat.client.ClientService: java.lang.IllegalStateException: Pid 11299 has exceeded the number of permissible registered listeners. Ignoring request to add.

firebase 后台收集的奔溃日志

android.os.Parcel.createExceptionOrNull (Parcel.java:3095)
android.os.Parcel.createException (Parcel.java:3071)
android.os.Parcel.readException (Parcel.java:3054)
android.os.Parcel.readException (Parcel.java:2996)
com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList (ITelephonyRegistry.java:1182)
android.telephony.TelephonyRegistryManager.listenFromListener (TelephonyRegistryManager.java:301)
android.telephony.TelephonyManager.listen (TelephonyManager.java:6612)
com.tencent.mars.comm.NetworkSignalUtil.InitNetworkSignalUtil (NetworkSignalUtil.java:18)
com.tencent.mars.comm.PlatformComm.init (PlatformComm.java:69)
com.tencent.mars.Mars.init (Mars.java:37)
cn.wildfirechat.client.ClientService.onCreate (ClientService.java:3910)
android.app.ActivityThread.handleCreateService (ActivityThread.java:4928)
android.app.ActivityThread.-$$Nest$mhandleCreateService
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2456)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:257)
android.os.Looper.loop (Looper.java:368)
android.app.ActivityThread.main (ActivityThread.java:8839)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:572)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1049)

**Comment by imndx** [comment]
https://github.com/Tencent/mars/issues/829

**Comment by imndx** [comment]
这个问题，出现的频率高吗？
系统版本分布是什么情况？

**Comment by Hopkin2016** [comment]
再我们项目的crash 排第一 
![image](https://github.com/user-attachments/assets/0c29bff5-f85d-4eb2-a550-9628a2ecdeaa)
![image](https://github.com/user-attachments/assets/5de62f87-a797-44ee-9e4d-6eee040f8e78)
![image](https://github.com/user-attachments/assets/9886738d-ef68-4322-9936-b2a637390053)
