### ISSUE TITLE
添加好友时不要列出现有用户吧，很容易被不法份子利用骚扰

### ISSUE THREAD

**Issue by zbm2024** [wildfirechat/android-chat#883]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
安卓用户在添加好友时，输入1，会把所有包含1的用户都显示出来，这样即使我打开了不允许用账号找到我，别人还是能添加我

#### 预期结果
应该按照微信样式，用户输入什么都不检索信息，只当他点了搜索后，才按照完全匹配显示用户，这是给骗子创造机会

#### 补充条件
发现

#### demo对比结果
一样的问题

**Comment by heavyrain2012** [comment]
检查一下搜索用户接口，有个参考可以控制如何搜索用户，修改那个参数就可以满足你们的需求

**Comment by captain-miao** [comment]
关闭昵称搜索

**Comment by imndx** [comment]
https://github.com/wildfirechat/android-chat/blob/eb74dcc7f15fdd48169dfb178f64ea764e041416/client/src/main/java/cn/wildfirechat/remote/ChatManager.java#L291-L309

**Comment by zbm2024** [comment]
嗯，这个我们处理好了
&nbsp;


海草集万事通
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月10日(星期四) 上午9:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wildfirechat/android-chat] 添加好友时不要列出现有用户吧，很容易被不法份子利用骚扰 (Issue #883)














 
https://github.com/wildfirechat/android-chat/blob/eb74dcc7f15fdd48169dfb178f64ea764e041416/client/src/main/java/cn/wildfirechat/remote/ChatManager.java#L291-L309
