### ISSUE TITLE
超级群 已加载未加载到的信息 notloaded都是0

### ISSUE THREAD

**Issue by z876335662** [wildfirechat/android-chat#889]
![微信图片_20241126141608](https://github.com/user-attachments/assets/4a4a7a24-fc13-45ce-a95e-88754fce92ea)

**Comment by imndx** [comment]
请先更新这个提交测试下 https://github.com/wildfirechat/android-chat/commit/a74a7aed456e8f5cf85ad81a7d97afe04f55a4d7

**Comment by imndx** [comment]
no response
