### ISSUE TITLE
群公告位置偏上

### ISSUE THREAD

**Issue by wangsanpiao** [wildfirechat/android-chat#89]
![2019-07-22-10-54-54](https://user-images.githubusercontent.com/17610744/61603308-ae78a400-ac6f-11e9-8fab-65ad00bc606e.png)

群公告这个位置是设计就是偏上的呢还是一个bug？

**Comment by LeonDevLifeLog** [comment]
群公告功能暂未完成开发,不是bug,底下的空间是放公告内容的

**Comment by wangsanpiao** [comment]
明白了，谢谢解答
