### ISSUE TITLE
问题1.聊天页面 时间显示不对。问题2.会话列表页面发出消息刷出的时间对 ，接收数据刷的时间不对

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/android-chat#96]
![image](https://user-images.githubusercontent.com/7382234/61744029-f101c400-adc8-11e9-943a-58ecae57e14d.png)

**Comment by yuzhongrong** [comment]
总结一点 接收的消息多加了8个小时

**Comment by imndx** [comment]
请测试最新代码
