### ISSUE TITLE
群管理移除管理员功能依然不正常，详情见下图

### ISSUE THREAD

**Issue by wangsanpiao** [wildfirechat/android-chat#97]
![gifhome_320x746_15s](https://user-images.githubusercontent.com/17610744/61759481-2a532780-adfb-11e9-82f6-546d7b31cafc.gif)

点击移除群管理后，依然不起作用

**Comment by wangsanpiao** [comment]
bug好像没修复完全，ui上没做出响应，管理员列表中依然有被移除的那个管理员

**Comment by LeonDevLifeLog** [comment]
等下看看
