### ISSUE TITLE
建议：添加群成员在群内禁言功能，如截图

### ISSUE THREAD

**Issue by handy001** [wildfirechat/android-chat#98]
![image](https://user-images.githubusercontent.com/15883260/61759685-9f266180-adfb-11e9-8388-696b3485c9e1.png)

![image](https://user-images.githubusercontent.com/15883260/61759674-99308080-adfb-11e9-88ad-f9745ab91f03.png)

**Comment by imndx** [comment]
已新增群成员禁言功能，请更新到最新代码测试。
